import 'package:flutter/material.dart';
import '../models/screen_metadata.dart';
import '../models/governance_types.dart';
import '../models/platform_geometry.dart';

/// [PlatformScreenRegistry] - Centralized single source of truth for all platform screens.
/// This registry serves both the UI implementation (primecare_ui) and 
/// the governance monitoring (primecare_governance).
class PlatformScreenRegistry {
  static final Map<String, ScreenMetadata> screens = {
    'CONTROL_CENTER': const ScreenMetadata(
      id: 'CONTROL_CENTER',
      featureName: 'Control Center',
      title: 'Enterprise Control Center',
      route: '/governance/control-center',
      icon: Icons.hub_outlined,
      roles: ['ADMIN', 'GOVERNANCE_OFFICER'],
      lifecycleStatus: LifecycleStatus.design,
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      isVirtual: true,
    ),
    'VERIFICATION_CENTER': const ScreenMetadata(
      id: 'VERIFICATION_CENTER',
      featureName: 'Verification Center',
      title: 'Verification Center',
      route: '/verification',
      icon: Icons.verified_user_outlined,
      roles: ['ADMIN', 'GOVERNANCE_OFFICER'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      testPassRate: 100.0,
      isPhiCompliant: true,
      isLocalizationReady: true,
      isDesktopVerified: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      accessibilityScore: 100.0,
      performanceScore: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'VERIF_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/core/ui/dynamic_screen_view.dart',
      isDataBindingVerified: true,
      isSecurityVerified: true,
      isTelemetryVerified: true,
      isNavigationVerified: true,
      hasEmptyState: true,
      completionPercent: 100.0,
    ),
    'AUDIT_LOG': const ScreenMetadata(
      id: 'AUDIT_LOG',
      featureName: 'Audit Log',
      title: 'Audit Log Viewer',
      route: '/governance/audit',
      icon: Icons.history_edu_rounded,
      roles: ['ADMIN', 'GOVERNANCE_OFFICER'],
      lifecycleStatus: LifecycleStatus.design,
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/core/governance/registries/core_governance_registry.dart',
      isVirtual: true,
    ),
    'DATA_ENTRY': const ScreenMetadata(
      id: 'DATA_ENTRY',
      featureName: 'Data Entry',
      title: 'Governance Data Entry',
      route: '/governance/data-entry',
      icon: Icons.edit_note_rounded,
      roles: ['ADMIN', 'GOVERNANCE_OFFICER'],
      lifecycleStatus: LifecycleStatus.design,
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/core/governance/registries/core_governance_registry.dart',
      isVirtual: true,
    ),
    'MONITORING': const ScreenMetadata(
      id: 'MONITORING',
      featureName: 'Monitoring',
      title: 'System Monitoring',
      route: '/governance/monitoring',
      icon: Icons.monitor_heart_rounded,
      roles: ['ADMIN', 'GOVERNANCE_OFFICER'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      testPassRate: 100.0,
      isPhiCompliant: true,
      isLocalizationReady: true,
      isDesktopVerified: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      accessibilityScore: 100.0,
      performanceScore: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'MONITOR_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/core/ui/dynamic_screen_view.dart',
      isDataBindingVerified: true,
      isSecurityVerified: true,
      isTelemetryVerified: true,
      isNavigationVerified: true,
      hasEmptyState: true,
      completionPercent: 100.0,
    ),
    'DEVICE_SECURITY': const ScreenMetadata(
      id: 'DEVICE_SECURITY',
      featureName: 'Security & Device Governance',
      title: 'Device Security Hub',
      route: '/governance/device-security',
      icon: Icons.security_outlined,
      roles: ['ADMIN', 'GOVERNANCE_OFFICER'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      testPassRate: 100.0,
      isPhiCompliant: true,
      isLocalizationReady: true,
      isDesktopVerified: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      accessibilityScore: 100.0,
      performanceScore: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'DEV_SEC_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/core/ui/dynamic_screen_view.dart',
      completionPercent: 100.0,
    ),
    'SECURITY_SENTINEL': const ScreenMetadata(
      id: 'SECURITY_SENTINEL',
      featureName: 'Security Sentinel',
      title: 'Security Sentinel & Compliance',
      route: '/governance/security',
      icon: Icons.security_rounded,
      roles: ['ADMIN', 'GOVERNANCE_OFF_OFFICER'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      testPassRate: 100.0,
      isPhiCompliant: true,
      isLocalizationReady: true,
      isDesktopVerified: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      accessibilityScore: 100.0,
      performanceScore: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'SEC_SENT_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/core/ui/dynamic_screen_view.dart',
      completionPercent: 100.0,
    ),
    'TICKET_CENTER': const ScreenMetadata(
      id: 'TICKET_CENTER',
      featureName: 'Ticket Center',
      title: 'Correction Ticket Center',
      route: '/governance/tickets',
      icon: Icons.confirmation_number_outlined,
      roles: ['ADMIN', 'GOVERNANCE_OFFICER'],
      lifecycleStatus: LifecycleStatus.design,
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/features/tickets/correction_ticket_controller.dart',
    ),
    'GOVERNANCE_HUD': const ScreenMetadata(
      id: 'GOVERNANCE_HUD',
      featureName: 'Governance HUD',
      title: 'Aura Intelligence HUD',
      route: '/governance/hud',
      icon: Icons.radar_outlined,
      roles: ['ADMIN', 'GOVERNANCE_OFFICER'],
      lifecycleStatus: LifecycleStatus.design,
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/core/ui/dynamic_screen_view.dart',
    ),
    'SCREEN_STATUS_DASHBOARD': const ScreenMetadata(
      id: 'SCREEN_STATUS_DASHBOARD',
      featureName: 'Screen Status',
      title: 'Screen Status Dashboard',
      route: '/governance/screen-status',
      icon: Icons.checklist_rtl_outlined,
      roles: ['ADMIN', 'GOVERNANCE_OFFICER'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      testPassRate: 100.0,
      isPhiCompliant: true,
      isLocalizationReady: true,
      isDesktopVerified: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      accessibilityScore: 100.0,
      performanceScore: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'STAT_DASH_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/core/ui/dynamic_screen_view.dart',
      completionPercent: 100.0,
    ),
    'SYSTEM_GOVERNANCE_DASHBOARD': const ScreenMetadata(
      id: 'SYSTEM_GOVERNANCE_DASHBOARD',
      featureName: 'System Governance',
      title: 'Governance Dashboard',
      route: '/governance/dashboard',
      icon: Icons.dashboard_outlined,
      roles: ['ADMIN', 'GOVERNANCE_OFFICER'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      testPassRate: 100.0,
      isPhiCompliant: true,
      isLocalizationReady: true,
      isDesktopVerified: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      accessibilityScore: 100.0,
      performanceScore: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'SYS_GOV_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/core/ui/dynamic_screen_view.dart',
      completionPercent: 100.0,
    ),
    'SIDEBAR_MAPPING': const ScreenMetadata(
      id: 'SIDEBAR_MAPPING',
      featureName: 'Sidebar Mapping',
      title: 'Role & Office Sidebar Mapping',
      route: '/governance/sidebar-mapping',
      icon: Icons.account_tree_outlined,
      roles: ['ADMIN', 'GOVERNANCE_OFFICER'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      testPassRate: 100.0,
      isPhiCompliant: true,
      isLocalizationReady: true,
      isDesktopVerified: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      accessibilityScore: 100.0,
      performanceScore: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'SIDE_MAP_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/core/ui/dynamic_screen_view.dart',
      completionPercent: 100.0,
    ),
    'CLINICAL_REFERENCE': const ScreenMetadata(
      id: 'CLINICAL_REFERENCE',
      featureName: 'Clinical Reference',
      title: 'Precision Clinical Education',
      route: '/governance/clinical-reference',
      icon: Icons.library_books_outlined,
      roles: ['ADMIN', 'GOVERNANCE_OFFICER'],
      lifecycleStatus: LifecycleStatus.design,
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/features/clinical_reference/clinical_reference_view.dart',
    ),
    'PROPOSALS': const ScreenMetadata(
      id: 'PROPOSALS',
      featureName: 'Proposals',
      title: 'Proposal Inbox',
      route: '/proposals',
      icon: Icons.inbox_outlined,
      roles: ['ADMIN', 'GOVERNANCE_OFFICER'],
      lifecycleStatus: LifecycleStatus.design,
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/core/governance/registries/core_governance_registry.dart',
      isVirtual: true,
    ),
    'PROPOSAL_NEW': const ScreenMetadata(
      id: 'PROPOSAL_NEW',
      featureName: 'New Proposal',
      title: 'New Feature Request',
      route: '/proposals/new',
      icon: Icons.add_to_photos_outlined,
      roles: ['ADMIN', 'GOVERNANCE_OFFICER'],
      lifecycleStatus: LifecycleStatus.design,
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/core/governance/registries/core_governance_registry.dart',
      isVirtual: true,
    ),
    'DEBUG_THEME': const ScreenMetadata(
      id: 'DEBUG_THEME',
      featureName: 'Theme Center',
      title: 'Theme Center',
      route: '/debug/theme-center',
      icon: Icons.palette_outlined,
      roles: ['ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      testPassRate: 100.0,
      isPhiCompliant: true,
      isLocalizationReady: true,
      isDesktopVerified: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      accessibilityScore: 100.0,
      performanceScore: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'DEBUG_THM_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/core/ui/dynamic_screen_view.dart',
      completionPercent: 100.0,
    ),
    'DEBUG_KITCHEN_SINK': const ScreenMetadata(
      id: 'DEBUG_KITCHEN_SINK',
      featureName: 'Kitchen Sink',
      title: 'Kitchen Sink',
      route: '/debug/kitchen-sink',
      icon: Icons.widgets_outlined,
      roles: ['ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      testPassRate: 100.0,
      isPhiCompliant: true,
      isLocalizationReady: true,
      isDesktopVerified: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      accessibilityScore: 100.0,
      performanceScore: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'KITCH_SNK_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/core/ui/dynamic_screen_view.dart',
      completionPercent: 100.0,
    ),
    'LOGIN': const ScreenMetadata(
      id: 'LOGIN',
      featureName: 'Authentication',
      title: 'Login',
      route: '/login',
      icon: Icons.login_outlined,
      roles: ['ADMIN', 'GOVERNANCE_OFFICER', 'guest'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      testPassRate: 100.0,
      isPhiCompliant: true,
      isLocalizationReady: true,
      isDesktopVerified: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      accessibilityScore: 100.0,
      performanceScore: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'AUTH_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'apps/primecare_governance/lib/features/auth/login_view.dart',
      isDataBindingVerified: true,
      isSecurityVerified: true,
      isTelemetryVerified: true,
      isNavigationVerified: true,
      completionPercent: 100.0,
    ),

    // --- HYDRATED DECENTRALIZED SCREENS ---

    // Clinical Role: Clinical Director
    'SCREEN_CLINICAL_DIRECTOR_DASHBOARD': const ScreenMetadata(
      id: 'SCREEN_CLINICAL_DIRECTOR_DASHBOARD',
      featureName: 'Clinical Oversight',
      title: 'Clinical Director Dashboard',
      route: '/clinical/director/dashboard',
      icon: Icons.medical_services_outlined,
      roles: ['CLINICAL_DIRECTOR', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'CLIN_DIR_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
      office: 'Clinical Governance',
    ),
    'SCREEN_CLINICAL_DIRECTOR_REPORTS': const ScreenMetadata(
      id: 'SCREEN_CLINICAL_DIRECTOR_REPORTS',
      featureName: 'Clinical Analytics',
      title: 'Clinical Director Reports',
      route: '/clinical/director/reports',
      icon: Icons.analytics_outlined,
      roles: ['CLINICAL_DIRECTOR', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'CLIN_REP_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
      office: 'Clinical Analytics',
    ),

    // Corporate Role: CEO
    'SCREEN_CEO_DASHBOARD': const ScreenMetadata(
      id: 'SCREEN_CEO_DASHBOARD',
      featureName: 'Enterprise Strategy',
      title: 'CEO Dashboard',
      route: '/corporate/ceo/dashboard',
      icon: Icons.business_center_outlined,
      roles: ['CEO', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'CEO_DASH_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
      office: 'Executive Office',
    ),

    // Clinical Role: PSW
    'SCREEN_PSW_DASHBOARD': const ScreenMetadata(
      id: 'SCREEN_PSW_DASHBOARD',
      featureName: 'Clinical Operations',
      title: 'PSW Dashboard',
      route: '/clinical/psw/dashboard',
      icon: Icons.dashboard_customize_outlined,
      roles: ['PSW', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'PSW_DASH_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
      office: 'Frontline Operations',
    ),
    'SCREEN_PSW_SHIFT_TRACKER': const ScreenMetadata(
      id: 'SCREEN_PSW_SHIFT_TRACKER',
      featureName: 'Clinical Operations',
      title: 'PSW Shift Tracker',
      route: '/clinical/psw/shift-tracker',
      icon: Icons.timer_outlined,
      roles: ['PSW', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'PSW_SHIFT_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),
    'SCREEN_PSW_TASKS': const ScreenMetadata(
      id: 'SCREEN_PSW_TASKS',
      featureName: 'Clinical Operations',
      title: 'PSW Task List',
      route: '/clinical/psw/tasks',
      icon: Icons.checklist_outlined,
      roles: ['PSW', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'PSW_TASK_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),
    'SCREEN_PSW_SCHEDULE': const ScreenMetadata(
      id: 'SCREEN_PSW_SCHEDULE',
      featureName: 'Clinical Operations',
      title: 'PSW Schedule',
      route: '/clinical/psw/schedule',
      icon: Icons.calendar_today_outlined,
      roles: ['PSW', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'PSW_SCHED_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),
    'SCREEN_PSW_VISIT_NOTES': const ScreenMetadata(
      id: 'SCREEN_PSW_VISIT_NOTES',
      featureName: 'Clinical Operations',
      title: 'PSW Visit Notes',
      route: '/clinical/psw/notes',
      icon: Icons.note_alt_outlined,
      roles: ['PSW', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'PSW_NOTE_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),
    'SCREEN_PSW_CLIENTS': const ScreenMetadata(
      id: 'SCREEN_PSW_CLIENTS',
      featureName: 'Clinical Operations',
      title: 'PSW Client List',
      route: '/clinical/psw/clients',
      icon: Icons.people_outline,
      roles: ['PSW', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'PSW_CLNT_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),

    // Clinical Role: Intake
    'SCREEN_INTAKE_PATIENT_INTAKE_FORM': const ScreenMetadata(
      id: 'SCREEN_INTAKE_PATIENT_INTAKE_FORM',
      featureName: 'Patient Onboarding',
      title: 'Patient Intake Form',
      route: '/clinical/intake/patient-intake',
      icon: Icons.assignment_ind_outlined,
      roles: ['INTAKE_COORDINATOR', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'INTAKE_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
      office: 'Admissions',
    ),

    // Coordinator Role
    'SCREEN_COORDINATOR_HUB': const ScreenMetadata(
      id: 'SCREEN_COORDINATOR_HUB',
      featureName: 'Logistics',
      title: 'Coordinator Hub',
      route: '/logistics/coordinator/hub',
      icon: Icons.hub_outlined,
      roles: ['COORDINATOR', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'COORD_HUB_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),
    'SCREEN_COORDINATOR_DISPATCH_MAP': const ScreenMetadata(
      id: 'SCREEN_COORDINATOR_DISPATCH_MAP',
      featureName: 'Logistics',
      title: 'Dispatch Map',
      route: '/logistics/coordinator/dispatch',
      icon: Icons.map_outlined,
      roles: ['COORDINATOR', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'COORD_MAP_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),
    'SCREEN_COORDINATOR_SOS': const ScreenMetadata(
      id: 'SCREEN_COORDINATOR_SOS',
      featureName: 'Logistics',
      title: 'SOS Response',
      route: '/logistics/coordinator/sos',
      icon: Icons.emergency_outlined,
      roles: ['COORDINATOR', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'COORD_SOS_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),
    'SCREEN_COORDINATOR_WAITLIST': const ScreenMetadata(
      id: 'SCREEN_COORDINATOR_WAITLIST',
      featureName: 'Logistics',
      title: 'Waitlist Management',
      route: '/logistics/coordinator/waitlist',
      icon: Icons.hourglass_empty_outlined,
      roles: ['COORDINATOR', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'COORD_WAIT_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),

    // RN Role
    'SCREEN_RN_DASHBOARD': const ScreenMetadata(
      id: 'SCREEN_RN_DASHBOARD',
      featureName: 'Clinical Operations',
      title: 'RN Dashboard',
      route: '/clinical/rn/dashboard',
      icon: Icons.dashboard_outlined,
      roles: ['RN', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'RN_DASH_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),
    'SCREEN_RN_ASSESSMENTS': const ScreenMetadata(
      id: 'SCREEN_RN_ASSESSMENTS',
      featureName: 'Clinical Operations',
      title: 'RN Assessments',
      route: '/clinical/rn/assessments',
      icon: Icons.assessment_outlined,
      roles: ['RN', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'RN_ASSESS_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),
    'SCREEN_RN_CARE_PLANS': const ScreenMetadata(
      id: 'SCREEN_RN_CARE_PLANS',
      featureName: 'Clinical Operations',
      title: 'RN Care Plans',
      route: '/clinical/rn/care-plans',
      icon: Icons.assignment_outlined,
      roles: ['RN', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'RN_CARE_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),

    // RPN Role
    'SCREEN_RPN_DASHBOARD': const ScreenMetadata(
      id: 'SCREEN_RPN_DASHBOARD',
      featureName: 'Clinical Operations',
      title: 'RPN Dashboard',
      route: '/clinical/rpn/dashboard',
      icon: Icons.dashboard_outlined,
      roles: ['RPN', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'RPN_DASH_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),

    // Allied Health
    'SCREEN_PT_DASHBOARD': const ScreenMetadata(
      id: 'SCREEN_PT_DASHBOARD',
      featureName: 'Clinical Operations',
      title: 'PT Dashboard',
      route: '/clinical/pt/dashboard',
      icon: Icons.dashboard_outlined,
      roles: ['PT', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'PT_DASH_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),
    'SCREEN_RMT_DASHBOARD': const ScreenMetadata(
      id: 'SCREEN_RMT_DASHBOARD',
      featureName: 'Clinical Operations',
      title: 'RMT Dashboard',
      route: '/clinical/rmt/dashboard',
      icon: Icons.dashboard_outlined,
      roles: ['RMT', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'RMT_DASH_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),
    'SCREEN_SW_DASHBOARD': const ScreenMetadata(
      id: 'SCREEN_SW_DASHBOARD',
      featureName: 'Clinical Operations',
      title: 'SW Dashboard',
      route: '/clinical/sw/dashboard',
      icon: Icons.dashboard_outlined,
      roles: ['SW', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'SW_DASH_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),
    'SCREEN_CHIRO_DASHBOARD': const ScreenMetadata(
      id: 'SCREEN_CHIRO_DASHBOARD',
      featureName: 'Clinical Operations',
      title: 'Chiro Dashboard',
      route: '/clinical/chiro/dashboard',
      icon: Icons.dashboard_outlined,
      roles: ['CHIRO', 'ADMIN'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      isAccessibilityVerified: true,
      isPerformanceVerified: true,
      isLocalizationReady: true,
      isPhiCompliant: true,
      isDesktopVerified: true,
      isMobileVerified: true,
      testPassRate: 100.0,
      uatApprover: 'Shaikh Rais',
      lastVerificationHash: 'CHIRO_DASH_V1_HASH',
      designSize: PlatformSize(3840, 2160),
      sourcePath: 'packages/primecare_ui/lib/src/registry/screen_registry.dart',
      completionPercent: 100.0,
    ),
  };

  static List<ScreenMetadata> get allScreens => screens.values.toList();

  static ScreenMetadata? getById(String id) => screens[id];

  static void registerScreens(List<ScreenMetadata> newScreens) {
    for (final screen in newScreens) {
      screens[screen.id] = screen;
    }
  }

  static void clearRegistry() {
    screens.clear();
  }

  static List<ScreenMetadata> getAllScreens() => screens.values.toList();
}
