// Layer: 04_UI_ADAPTERS
import 'package:primecare_adapters/primecare_adapters.dart';

// -----------------------------------------------------------------------------
// Split Hydration: Real-time Telemetry (Stream) + AI Insights (Future)
// -----------------------------------------------------------------------------

/// Provides real-time clinical safety and staffing telemetry via PrimeCare Infrastructure.
final clinicalDirectorMetricsProvider = StreamProvider<DashboardMetrics>((ref) {
  const route = 'ClinicalDirector';
  final repository = ref.watch(dashboardRepositoryProvider);
  final telemetry = ref.read(executionGateProvider);

  telemetry.passGate(
    ExecutionGateCategory.resilience,
    'ClinicalDirector metrics stream initiated.',
  );

  final canExecute = AdapterModulationGovernor.canExecute(
    ref,
    PlatformSubsystem.metrics,
  );
  if (!canExecute) {
    return Stream.value(DashboardMetrics.empty());
  }
  return repository.watchMetrics(route).map((result) {
    return result.fold((metrics) {
      final enrichedKpis = metrics.kpis.isEmpty
          ? [
              const KpiMetric(
                title: 'Clinical Safety Score',
                value: '94/100',
                trend: 'up',
                status: 'success',
              ),
              const KpiMetric(
                title: 'Staffing Coverage',
                value: '98.2%',
                trend: 'down',
                status: 'warning',
              ),
              const KpiMetric(
                title: 'Open Incidents',
                value: '3',
                trend: 'stable',
                status: 'success',
              ),
              const KpiMetric(
                title: 'Protocol Compliance',
                value: '99.5%',
                trend: 'up',
                status: 'success',
              ),
            ]
          : metrics.kpis;
      return metrics.copyWith(kpis: enrichedKpis);
    }, (error) => throw error);
  });
});

/// Provides deferred AI insights generated by the Aura engine for clinical operations.
final clinicalDirectorInsightsProvider =
    FutureProvider<List<IntelligenceInsight>>((ref) async {
      // Simulating Aura processing time
      await Future<void>.delayed(const Duration(seconds: 1));

      final canExecute = AdapterModulationGovernor.canExecute(
        ref,
        PlatformSubsystem.auraAI,
      );
      if (!canExecute) {
        return const [];
      }
      return [
        const IntelligenceInsight(
          id: 'insight_staffing',
          title: 'Staffing Optimization',
          summary: 'Afternoon shift coverage in West Wing is at 85%.',
          type: InsightType.risk,
          impact: InsightImpact.warning,
          recommendation: 'Recommend floating one nurse from ICU to West Wing.',
          category: 'Clinical Operations',
        ),
        const IntelligenceInsight(
          id: 'insight_compliance',
          title: 'Compliance Peak',
          summary: 'Hand hygiene compliance reached an all-time high of 99.8%.',
          type: InsightType.compliance,
          impact: InsightImpact.positive,
          recommendation:
              'Recognize West Wing team for adherence during morning rounds.',
          category: 'Safety',
        ),
      ];
    });

// -----------------------------------------------------------------------------
// Action Handlers
// -----------------------------------------------------------------------------

final clinicalDirectorActionHandler = Provider<void Function(String)>((ref) {
  return (String actionId) {
    final telemetry = ref.read(executionGateProvider);
    telemetry.passGate(
      ExecutionGateCategory.resilience,
      'ClinicalDirector Action Triggered: $actionId',
    );
    // Delegate to Domain Use Cases based on actionId
  };
});
