import 'package:flutter/material.dart';
import '../shared/widgets/page_template.dart';
import '../shared/widgets/kpi_card.dart';

// Hits PATCH /v1/manager/incidents/:id natively

class ManagerIncidentsScreen extends StatelessWidget {
  const ManagerIncidentsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return PageTemplate(
      title: 'Incident Escalations',
      subtitle: 'Review and resolve frontline SOS alerts',
      icon: Icons.warning_amber_rounded,
      headerGradientColors: const [Colors.redAccent, Colors.red],
      kpiCards: const [
        UnifiedKpiCard(
          title: 'Active Alerts',
          value: '3 Critical',
          icon: Icons.notifications_active,
          color: Colors.red,
        ),
        UnifiedKpiCard(
          title: 'Resolved (7d)',
          value: '14 Tickets',
          icon: Icons.check_circle,
          color: Colors.green,
        ),
      ],
      children: [
        Card(
          margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
          elevation: 3,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text('Urgent Action Required', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.red)),
                const SizedBox(height: 16),
                _buildIncidentTile(
                  context,
                  'INC-8092',
                  'Client slipped and fell. Requires lift assist.',
                  'PSW: Jane Smith',
                  isCritical: true,
                ),
                const Divider(),
                _buildIncidentTile(
                  context,
                  'INC-8091',
                  'Call-in / No Show tracking generated by Coordinator.',
                  'PSW: Unknown',
                  isCritical: false,
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildIncidentTile(BuildContext context, String code, String desc, String pswStr, {bool isCritical = false}) {
    return ListTile(
      leading: CircleAvatar(
        backgroundColor: isCritical ? Colors.red.withOpacity(0.1) : Colors.orange.withOpacity(0.1),
        child: Icon(isCritical ? Icons.emergency : Icons.warning, color: isCritical ? Colors.red : Colors.orange),
      ),
      title: Text('$code: $desc'),
      subtitle: Text(pswStr),
      trailing: ElevatedButton.icon(
        onPressed: () {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Incident $code marked as RESOLVED.')),
          );
        },
        icon: const Icon(Icons.done_all, size: 18),
        label: const Text('Resolve'),
        style: ElevatedButton.styleFrom(
          backgroundColor: Colors.green,
          foregroundColor: Colors.white,
        ),
      ),
    );
  }
}
