export 'screen_metadata.dart';
import 'screen_metadata.dart';

// Domain Registries
import 'registries/clinical_registry.dart';
import 'registries/corporate_registry.dart';
import 'registries/operational_registry.dart';
import 'registries/franchise_registry.dart';
import 'registries/business_development_registry.dart';
import 'registries/marketing_registry.dart';
import 'registries/admin_infrastructure_registry.dart';
import 'registries/workflows_forms_registry.dart';
import 'registries/support_registry.dart';
import 'registries/client_portal_registry.dart';
import 'registries/regional_finance_registry.dart';

class ScreenRegistry {
  // Common Screen Constants
  static const String dashboard = 'SCREEN_DASHBOARD';
  static const String clinical = 'SCREEN_CLINICAL';
  static const String billing = 'SCREEN_BILLING';
  
  // Registry Aggregator
  static final Map<String, ScreenMetadata> screens = {
    ...CorporateRegistryRegistry.screens,
    ...OperationalRegistryRegistry.screens,
    ...ClinicalRegistryRegistry.screens,
    ...FranchiseRegistryRegistry.screens,
    ...BusinessDevelopmentRegistryRegistry.screens,
    ...MarketingRegistryRegistry.screens,
    ...AdminInfrastructureRegistryRegistry.screens,
    ...WorkflowsFormsRegistryRegistry.screens,
    ...ClientPortalRegistryRegistry.screens,
    ...SupportRegistryRegistry.screens,
    ...RegionalFinanceRegistry.screens,
      'RECOVERED_OFFICES_CLINICAL_ROLES_PSW_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_CLINICAL_ROLES_PSW_DASHBOARD',
      featureName: 'Recovered OFFICES_CLINICAL_ROLES_PSW_DASHBOARD',
      routePath: '/offices/clinical/roles/psw/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_CLINICAL_ROLES_PSW_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OFFICES_CLINICAL_ROLES_RMT_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_CLINICAL_ROLES_RMT_DASHBOARD',
      featureName: 'Recovered OFFICES_CLINICAL_ROLES_RMT_DASHBOARD',
      routePath: '/offices/clinical/roles/rmt/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_CLINICAL_ROLES_RMT_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OFFICES_CLINICAL_ROLES_RN_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_CLINICAL_ROLES_RN_DASHBOARD',
      featureName: 'Recovered OFFICES_CLINICAL_ROLES_RN_DASHBOARD',
      routePath: '/offices/clinical/roles/rn/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_CLINICAL_ROLES_RN_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OFFICES_CORPORATE_ROLES_BILLING_ADMIN_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_CORPORATE_ROLES_BILLING_ADMIN_DASHBOARD',
      featureName: 'Recovered OFFICES_CORPORATE_ROLES_BILLING_ADMIN_DASHBOARD',
      routePath: '/offices/corporate/roles/billing_admin/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_CORPORATE_ROLES_BILLING_ADMIN_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OFFICES_CORPORATE_ROLES_COMPLIANCE_MANAGER_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_CORPORATE_ROLES_COMPLIANCE_MANAGER_DASHBOARD',
      featureName: 'Recovered OFFICES_CORPORATE_ROLES_COMPLIANCE_MANAGER_DASHBOARD',
      routePath: '/offices/corporate/roles/compliance_manager/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_CORPORATE_ROLES_COMPLIANCE_MANAGER_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OFFICES_CORPORATE_ROLES_CEO_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_CORPORATE_ROLES_CEO_DASHBOARD',
      featureName: 'Recovered OFFICES_CORPORATE_ROLES_CEO_DASHBOARD',
      routePath: '/offices/corporate/roles/ceo/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_CORPORATE_ROLES_CEO_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OFFICES_CORPORATE_ROLES_CTO_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_CORPORATE_ROLES_CTO_DASHBOARD',
      featureName: 'Recovered OFFICES_CORPORATE_ROLES_CTO_DASHBOARD',
      routePath: '/offices/corporate/roles/cto/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_CORPORATE_ROLES_CTO_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OFFICES_CORPORATE_ROLES_CFO_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_CORPORATE_ROLES_CFO_DASHBOARD',
      featureName: 'Recovered OFFICES_CORPORATE_ROLES_CFO_DASHBOARD',
      routePath: '/offices/corporate/roles/cfo/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_CORPORATE_ROLES_CFO_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OFFICES_CORPORATE_ROLES_FINANCE_DIRECTOR_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_CORPORATE_ROLES_FINANCE_DIRECTOR_DASHBOARD',
      featureName: 'Recovered OFFICES_CORPORATE_ROLES_FINANCE_DIRECTOR_DASHBOARD',
      routePath: '/offices/corporate/roles/finance_director/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_CORPORATE_ROLES_FINANCE_DIRECTOR_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OFFICES_CORPORATE_ROLES_TRAINING_DIRECTOR_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_CORPORATE_ROLES_TRAINING_DIRECTOR_DASHBOARD',
      featureName: 'Recovered OFFICES_CORPORATE_ROLES_TRAINING_DIRECTOR_DASHBOARD',
      routePath: '/offices/corporate/roles/training_director/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_CORPORATE_ROLES_TRAINING_DIRECTOR_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OFFICES_CLINICAL_ROLES_CLINICAL_DIRECTOR_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_CLINICAL_ROLES_CLINICAL_DIRECTOR_DASHBOARD',
      featureName: 'Recovered OFFICES_CLINICAL_ROLES_CLINICAL_DIRECTOR_DASHBOARD',
      routePath: '/offices/clinical/roles/clinical_director/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_CLINICAL_ROLES_CLINICAL_DIRECTOR_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OFFICES_CORPORATE_ROLES_HR_HIRING_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_CORPORATE_ROLES_HR_HIRING_DASHBOARD',
      featureName: 'Recovered OFFICES_CORPORATE_ROLES_HR_HIRING_DASHBOARD',
      routePath: '/offices/corporate/roles/hr_hiring/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_CORPORATE_ROLES_HR_HIRING_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OFFICES_ROLES_HR_HIRING_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_ROLES_HR_HIRING_DASHBOARD',
      featureName: 'Recovered OFFICES_ROLES_HR_HIRING_DASHBOARD',
      routePath: '/offices/roles/hr_hiring/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_ROLES_HR_HIRING_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OFFICES_CORPORATE_ROLES_HEAD_OF_MARKETING_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_CORPORATE_ROLES_HEAD_OF_MARKETING_DASHBOARD',
      featureName: 'Recovered OFFICES_CORPORATE_ROLES_HEAD_OF_MARKETING_DASHBOARD',
      routePath: '/offices/corporate/roles/head_of_marketing/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_CORPORATE_ROLES_HEAD_OF_MARKETING_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OFFICES_ROLES_RECEPTIONIST_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_ROLES_RECEPTIONIST_DASHBOARD',
      featureName: 'Recovered OFFICES_ROLES_RECEPTIONIST_DASHBOARD',
      routePath: '/offices/roles/receptionist/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_ROLES_RECEPTIONIST_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_INFRASTRUCTURE_GOVERNANCE_MONITOR': const ScreenMetadata(
      id: 'RECOVERED_INFRASTRUCTURE_GOVERNANCE_MONITOR',
      featureName: 'Recovered INFRASTRUCTURE_GOVERNANCE_MONITOR',
      routePath: '/infrastructure/governance/monitor',
      allowedRoles: ['Admin'],
      title: 'Recovered INFRASTRUCTURE_GOVERNANCE_MONITOR',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OFFICES_CORPORATE_ROLES_COO_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_CORPORATE_ROLES_COO_DASHBOARD',
      featureName: 'Recovered OFFICES_CORPORATE_ROLES_COO_DASHBOARD',
      routePath: '/offices/corporate/roles/coo/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_CORPORATE_ROLES_COO_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OFFICES_CLINICAL_ROLES_QUALITY_METRICS_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_OFFICES_CLINICAL_ROLES_QUALITY_METRICS_DASHBOARD',
      featureName: 'Recovered OFFICES_CLINICAL_ROLES_QUALITY_METRICS_DASHBOARD',
      routePath: '/offices/clinical/roles/quality_metrics/dashboard',
      allowedRoles: ['Admin'],
      title: 'Recovered OFFICES_CLINICAL_ROLES_QUALITY_METRICS_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_DYNAMIC_ROLE_DASHBOARD': const ScreenMetadata(
      id: 'RECOVERED_DYNAMIC_ROLE_DASHBOARD',
      featureName: 'Recovered DYNAMIC_ROLE_DASHBOARD',
      routePath: 'DYNAMIC_ROLE_DASHBOARD',
      allowedRoles: ['Admin'],
      title: 'Recovered DYNAMIC_ROLE_DASHBOARD',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OPERATIONAL_STAFFING_DIRECTOR': const ScreenMetadata(
      id: 'RECOVERED_OPERATIONAL_STAFFING_DIRECTOR',
      featureName: 'Recovered OPERATIONAL_STAFFING_DIRECTOR',
      routePath: '/operational/staffing-director',
      allowedRoles: ['Admin'],
      title: 'Recovered OPERATIONAL_STAFFING_DIRECTOR',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_OPERATIONAL_REGIONAL_MANAGER': const ScreenMetadata(
      id: 'RECOVERED_OPERATIONAL_REGIONAL_MANAGER',
      featureName: 'Recovered OPERATIONAL_REGIONAL_MANAGER',
      routePath: '/operational/regional-manager',
      allowedRoles: ['Admin'],
      title: 'Recovered OPERATIONAL_REGIONAL_MANAGER',
      pendingComponents: [],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_ONTARIO_FINANCE_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_ONTARIO_FINANCE_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_ONTARIO_FINANCE_REGIONAL_VIEW',
      routePath: '/business-development/ontario-finance-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_ONTARIO_FINANCE_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_ONTARIO_CLINICAL_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_ONTARIO_CLINICAL_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_ONTARIO_CLINICAL_REGIONAL_VIEW',
      routePath: '/business-development/ontario-clinical-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_ONTARIO_CLINICAL_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_ONTARIO_OPERATIONS_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_ONTARIO_OPERATIONS_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_ONTARIO_OPERATIONS_REGIONAL_VIEW',
      routePath: '/business-development/ontario-operations-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_ONTARIO_OPERATIONS_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_ONTARIO_HR_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_ONTARIO_HR_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_ONTARIO_HR_REGIONAL_VIEW',
      routePath: '/business-development/ontario-hr-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_ONTARIO_HR_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_ONTARIO_MARKETING_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_ONTARIO_MARKETING_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_ONTARIO_MARKETING_REGIONAL_VIEW',
      routePath: '/business-development/ontario-marketing-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_ONTARIO_MARKETING_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_ONTARIO_COMPLIANCE_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_ONTARIO_COMPLIANCE_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_ONTARIO_COMPLIANCE_REGIONAL_VIEW',
      routePath: '/business-development/ontario-compliance-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_ONTARIO_COMPLIANCE_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_USA_FINANCE_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_USA_FINANCE_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_USA_FINANCE_REGIONAL_VIEW',
      routePath: '/business-development/usa-finance-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_USA_FINANCE_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_USA_CLINICAL_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_USA_CLINICAL_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_USA_CLINICAL_REGIONAL_VIEW',
      routePath: '/business-development/usa-clinical-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_USA_CLINICAL_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_USA_OPERATIONS_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_USA_OPERATIONS_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_USA_OPERATIONS_REGIONAL_VIEW',
      routePath: '/business-development/usa-operations-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_USA_OPERATIONS_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_USA_HR_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_USA_HR_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_USA_HR_REGIONAL_VIEW',
      routePath: '/business-development/usa-hr-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_USA_HR_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_USA_MARKETING_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_USA_MARKETING_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_USA_MARKETING_REGIONAL_VIEW',
      routePath: '/business-development/usa-marketing-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_USA_MARKETING_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_USA_COMPLIANCE_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_USA_COMPLIANCE_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_USA_COMPLIANCE_REGIONAL_VIEW',
      routePath: '/business-development/usa-compliance-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_USA_COMPLIANCE_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_QUEBEC_FINANCE_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_QUEBEC_FINANCE_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_QUEBEC_FINANCE_REGIONAL_VIEW',
      routePath: '/business-development/quebec-finance-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_QUEBEC_FINANCE_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_QUEBEC_CLINICAL_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_QUEBEC_CLINICAL_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_QUEBEC_CLINICAL_REGIONAL_VIEW',
      routePath: '/business-development/quebec-clinical-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_QUEBEC_CLINICAL_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_QUEBEC_OPERATIONS_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_QUEBEC_OPERATIONS_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_QUEBEC_OPERATIONS_REGIONAL_VIEW',
      routePath: '/business-development/quebec-operations-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_QUEBEC_OPERATIONS_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_QUEBEC_HR_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_QUEBEC_HR_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_QUEBEC_HR_REGIONAL_VIEW',
      routePath: '/business-development/quebec-hr-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_QUEBEC_HR_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_QUEBEC_MARKETING_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_QUEBEC_MARKETING_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_QUEBEC_MARKETING_REGIONAL_VIEW',
      routePath: '/business-development/quebec-marketing-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_QUEBEC_MARKETING_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_QUEBEC_COMPLIANCE_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_QUEBEC_COMPLIANCE_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_QUEBEC_COMPLIANCE_REGIONAL_VIEW',
      routePath: '/business-development/quebec-compliance-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_QUEBEC_COMPLIANCE_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_BC_FINANCE_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_BC_FINANCE_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_BC_FINANCE_REGIONAL_VIEW',
      routePath: '/business-development/bc-finance-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_BC_FINANCE_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_BC_CLINICAL_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_BC_CLINICAL_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_BC_CLINICAL_REGIONAL_VIEW',
      routePath: '/business-development/bc-clinical-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_BC_CLINICAL_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_BC_OPERATIONS_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_BC_OPERATIONS_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_BC_OPERATIONS_REGIONAL_VIEW',
      routePath: '/business-development/bc-operations-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_BC_OPERATIONS_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_BC_HR_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_BC_HR_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_BC_HR_REGIONAL_VIEW',
      routePath: '/business-development/bc-hr-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_BC_HR_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_BC_MARKETING_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_BC_MARKETING_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_BC_MARKETING_REGIONAL_VIEW',
      routePath: '/business-development/bc-marketing-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_BC_MARKETING_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_BC_COMPLIANCE_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_BC_COMPLIANCE_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_BC_COMPLIANCE_REGIONAL_VIEW',
      routePath: '/business-development/bc-compliance-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_BC_COMPLIANCE_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_ALBERTA_FINANCE_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_ALBERTA_FINANCE_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_ALBERTA_FINANCE_REGIONAL_VIEW',
      routePath: '/business-development/alberta-finance-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_ALBERTA_FINANCE_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_ALBERTA_CLINICAL_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_ALBERTA_CLINICAL_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_ALBERTA_CLINICAL_REGIONAL_VIEW',
      routePath: '/business-development/alberta-clinical-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_ALBERTA_CLINICAL_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_ALBERTA_OPERATIONS_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_ALBERTA_OPERATIONS_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_ALBERTA_OPERATIONS_REGIONAL_VIEW',
      routePath: '/business-development/alberta-operations-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_ALBERTA_OPERATIONS_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_ALBERTA_HR_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_ALBERTA_HR_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_ALBERTA_HR_REGIONAL_VIEW',
      routePath: '/business-development/alberta-hr-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_ALBERTA_HR_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_ALBERTA_MARKETING_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_ALBERTA_MARKETING_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_ALBERTA_MARKETING_REGIONAL_VIEW',
      routePath: '/business-development/alberta-marketing-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_ALBERTA_MARKETING_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_ALBERTA_COMPLIANCE_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_ALBERTA_COMPLIANCE_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_ALBERTA_COMPLIANCE_REGIONAL_VIEW',
      routePath: '/business-development/alberta-compliance-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_ALBERTA_COMPLIANCE_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_MARITIMES_FINANCE_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_MARITIMES_FINANCE_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_MARITIMES_FINANCE_REGIONAL_VIEW',
      routePath: '/business-development/maritimes-finance-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_MARITIMES_FINANCE_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_MARITIMES_CLINICAL_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_MARITIMES_CLINICAL_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_MARITIMES_CLINICAL_REGIONAL_VIEW',
      routePath: '/business-development/maritimes-clinical-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_MARITIMES_CLINICAL_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_MARITIMES_OPERATIONS_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_MARITIMES_OPERATIONS_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_MARITIMES_OPERATIONS_REGIONAL_VIEW',
      routePath: '/business-development/maritimes-operations-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_MARITIMES_OPERATIONS_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_MARITIMES_HR_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_MARITIMES_HR_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_MARITIMES_HR_REGIONAL_VIEW',
      routePath: '/business-development/maritimes-hr-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_MARITIMES_HR_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_MARITIMES_MARKETING_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_MARITIMES_MARKETING_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_MARITIMES_MARKETING_REGIONAL_VIEW',
      routePath: '/business-development/maritimes-marketing-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_MARITIMES_MARKETING_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
    'RECOVERED_BUSINESS_DEVELOPMENT_MARITIMES_COMPLIANCE_REGIONAL_VIEW': const ScreenMetadata(
      id: 'RECOVERED_BUSINESS_DEVELOPMENT_MARITIMES_COMPLIANCE_REGIONAL_VIEW',
      featureName: 'Recovered BUSINESS_DEVELOPMENT_MARITIMES_COMPLIANCE_REGIONAL_VIEW',
      routePath: '/business-development/maritimes-compliance-regional-view',
      allowedRoles: ['Admin'],
      title: 'Recovered BUSINESS_DEVELOPMENT_MARITIMES_COMPLIANCE_REGIONAL_VIEW',
      pendingComponents: ['Aura HUD', 'Regional Heatmap', 'Site Compliance Grid', 'Territory KPI HUD'],
      lifecycleStatus: LifecycleStatus.backlog,
    ),
};

  // Helper to find screen by ID
  static ScreenMetadata? getById(String id) => screens[id];

  // Helper to find screen by route
  static ScreenMetadata? getByRoute(String route) {
    try {
      return screens.values.firstWhere((s) => s.routePath == route);
    } catch (_) {
      return null;
    }
  }

  // Helper to get all registered screens
  static List<ScreenMetadata> getAllScreens() => screens.values.toList();
}
