/**
 * Bookings Route Definitions + Handlers
 * Extracted from bookings.routes.ts
 */
import { createRoute, z } from '@hono/zod-openapi';
import { ROUTE_METADATA } from '@primecare/infrastructure';
import { requirePermission, requireAnyPermission } from '@primecare/security';
import { logAudit } from '@primecare/infrastructure';

const BookingSchema = z.object({ serviceId: z.string().uuid().optional(), serviceType: z.string(), requestedStartAt: z.string().datetime(), durationMinutes: z.number().min(30), priority: z.enum(['normal', 'urgent']).default('normal'), notes: z.string().optional(), recurrenceRule: z.any().optional() });
const BookingParamsSchema = z.object({ id: z.string().openapi({ param: { name: 'id', in: 'path' } }) });

export const listBookingsRoute = createRoute({ ...ROUTE_METADATA.CLIENT.LIST_BOOKINGS, method: 'get', path: '/', summary: 'List Bookings', tags: ['Client', 'Bookings'], middleware: [requireAnyPermission(['request_booking', 'manage_schedule', 'clinical_oversight'])], responses: { 200: { content: { 'application/json': { schema: z.array(z.any()) } }, description: 'List of bookings' }, 404: { description: 'Profile not found' },
    '400': { description: 'Bad Request', content: { 'application/json': { schema: z.object({ error: z.string() }) } } }
} });
export const createBookingRoute = createRoute({ ...ROUTE_METADATA.CLIENT.CREATE_BOOKING, method: 'post', path: '/', summary: 'Create Booking', tags: ['Client', 'Bookings'], middleware: [requirePermission('request_booking')], request: { body: { content: { 'application/json': { schema: BookingSchema } } } }, responses: { 201: { content: { 'application/json': { schema: z.any() } }, description: 'Booking created successfully' }, 404: { description: 'Profile not found' },
    '400': { description: 'Bad Request', content: { 'application/json': { schema: z.object({ error: z.string() }) } } }
} });
export const updateBookingRoute = createRoute({ ...ROUTE_METADATA.CLIENT.UPDATE_BOOKING, method: 'patch', path: '/{id}', summary: 'Update Booking', tags: ['Client', 'Bookings'], middleware: [requireAnyPermission(['request_booking', 'manage_schedule'])], request: { params: BookingParamsSchema, body: { content: { 'application/json': { schema: BookingSchema.partial() } } } }, responses: { 200: { content: { 'application/json': { schema: z.any() } }, description: 'Booking updated successfully' },
    '400': { description: 'Bad Request', content: { 'application/json': { schema: z.object({ error: z.string() }) } } },
    '404': { description: 'Not Found', content: { 'application/json': { schema: z.object({ error: z.string() }) } } }
} });
export const createBookingRequestRoute = createRoute({ ...ROUTE_METADATA.CLIENT.BOOKING_REQUESTS, method: 'post', path: '/requests', summary: 'Create Booking Request', tags: ['Client', 'Bookings'], middleware: [requirePermission('request_booking')], request: { body: { content: { 'application/json': { schema: z.object({ serviceType: z.string(), preferredDate: z.string().datetime(), preferredTime: z.string().optional(), notes: z.string().optional() }) } } } }, responses: { 201: { content: { 'application/json': { schema: z.any() } }, description: 'Booking request submitted' }, 404: { description: 'Profile not found' },
    '400': { description: 'Bad Request', content: { 'application/json': { schema: z.object({ error: z.string() }) } } }
} });

export async function handleListBookings(c: any) { const prisma = c.get('prisma'); const userId = c.get('jwtPayload').sub; const profile = await prisma.clientProfile.findUnique({ where: { userId } }); if (!profile) return c.json({ error: 'Profile not found' }, 404); return c.json(await prisma.booking.findMany({ where: { clientId: profile.id }, orderBy: { startAt: 'desc' }, include: { visits: { include: { service: true, psw: { select: { fullName: true } } } } } }), 200); }
export async function handleCreateBooking(c: any) { const prisma = c.get('prisma'); const userId = c.get('jwtPayload').sub; const data = c.req.valid('json'); const tenantId = c.get('jwtPayload').tenantId; const profile = await prisma.clientProfile.findUnique({ where: { userId } }); if (!profile) return c.json({ error: 'Profile not found' }, 404); const booking = await prisma.booking.create({ data: { clientId: profile.id, startAt: new Date(data.requestedStartAt), endAt: new Date(new Date(data.requestedStartAt).getTime() + data.durationMinutes * 60000), serviceType: data.serviceType, priority: data.priority, notes: data.notes, recurrenceRule: data.recurrenceRule, tenantId } }); if (!data.recurrenceRule) { await prisma.visit.create({ data: { bookingId: booking.id, clientId: profile.id, serviceId: data.serviceId || '', requestedStartAt: new Date(data.requestedStartAt), durationMinutes: data.durationMinutes, status: 'requested', clientNotes: data.notes, priority: data.priority, tenantId } }); } await logAudit(prisma, userId, 'BOOK_SERVICE', 'BOOKING', booking.id, { serviceType: data.serviceType }); return c.json(booking, 201); }
export async function handleUpdateBooking(c: any) { const prisma = c.get('prisma'); const { id } = c.req.valid('param'); const data = c.req.valid('json'); const userId = c.get('jwtPayload').sub; const booking = await prisma.booking.update({ where: { id }, data: { ...data, startAt: data.requestedStartAt ? new Date(data.requestedStartAt) : undefined } }); await logAudit(prisma, userId, 'UPDATE_BOOKING', 'BOOKING', id, data); return c.json(booking, 200); }
export async function handleCreateBookingRequest(c: any) { const prisma = c.get('prisma'); const userId = c.get('jwtPayload').sub; const data = c.req.valid('json'); const tenantId = c.get('jwtPayload').tenantId; const profile = await prisma.clientProfile.findUnique({ where: { userId } }); if (!profile) return c.json({ error: 'Profile not found' }, 404); const request = await prisma.bookingRequest.create({ data: { clientId: profile.id, tenantId, serviceType: data.serviceType, preferredDate: new Date(data.preferredDate), preferredTime: data.preferredTime, notes: data.notes } }); await logAudit(prisma, userId, 'REQUEST_SERVICE', 'BOOKING_REQUEST', request.id, { serviceType: data.serviceType }); return c.json(request, 201); }
