import type { FormEntry } from '../FormRegistry';

export const ADMIN_FORMS: FormEntry[] = [
    {
        id: 'admin.user-invite',
        label: 'Invite User',
        route: '/platform/admin/users',
        apiEndpoint: '/v1/admin/users',
        method: 'POST',
        dataCyPrefix: 'user-invite',
        category: 'admin',
        fields: [
            { name: 'email', label: 'Email', type: 'email', required: true },
            { name: 'firstName', label: 'First Name', type: 'text', required: true },
            { name: 'lastName', label: 'Last Name', type: 'text', required: true },
            { name: 'role', label: 'Role', type: 'select', required: true },
            { name: 'phone', label: 'Phone', type: 'tel', required: false },
        ],
    },
    {
        id: 'admin.user-entry',
        label: 'Create / Edit User',
        route: '/platform/admin/users/new',
        apiEndpoint: '/v1/admin/users',
        fetchEndpoint: '/v1/admin/users',
        method: 'POST',
        dataCyPrefix: 'user-entry',
        category: 'admin',
        fields: [
            { name: 'firstName', label: 'First Name', type: 'text', required: true },
            { name: 'lastName', label: 'Last Name', type: 'text', required: true },
            { name: 'email', label: 'Email', type: 'email', required: true },
            { name: 'password', label: 'Temporary Password', type: 'password', required: true },
            { name: 'role', label: 'Role', type: 'select', required: true },
            { name: 'phone', label: 'Phone Number', type: 'tel', required: false },
            { name: 'address', label: 'Address', type: 'text', required: false },
        ],
    },
    {
        id: 'admin.service-modal',
        label: 'Create / Edit Service',
        route: '/platform/admin/services',
        apiEndpoint: '/v1/admin/services',
        fetchEndpoint: '/v1/admin/services',
        method: 'POST',
        dataCyPrefix: 'service',
        category: 'admin',
        fields: [
            { name: 'name', label: 'Service Name', type: 'text', required: true },
            { name: 'description', label: 'Description', type: 'textarea', required: false },
            { name: 'rate', label: 'Hourly Rate ($)', type: 'number', required: true },
            { name: 'category', label: 'Category', type: 'select', required: true },
            { name: 'isActive', label: 'Active', type: 'checkbox', required: false },
        ],
    },
    {
        id: 'admin.lead-entry',
        label: 'Create / Edit Lead',
        route: '/platform/admin/leads/new',
        apiEndpoint: '/v1/admin/leads',
        fetchEndpoint: '/v1/admin/leads',
        method: 'POST',
        dataCyPrefix: 'lead',
        category: 'admin',
        fields: [
            { name: 'firstName', label: 'First Name', type: 'text', required: true },
            { name: 'lastName', label: 'Last Name', type: 'text', required: true },
            { name: 'email', label: 'Email', type: 'email', required: true },
            { name: 'phone', label: 'Phone', type: 'tel', required: true },
            { name: 'source', label: 'Lead Source', type: 'select', required: true },
            { name: 'notes', label: 'Notes', type: 'textarea', required: false },
            { name: 'serviceInterest', label: 'Service Interest', type: 'select', required: false, fetchOptionsFrom: '/v1/admin/services' },
        ],
        dependencies: [
            { field: 'serviceInterest', entityType: 'serviceType', inlineCreateEndpoint: '/v1/admin/services', fetchEndpoint: '/v1/admin/services', inlineCreateLabel: '+ New Service Type' },
        ],
    },
    {
        id: 'admin.incident-entry',
        label: 'Create / Edit Incident',
        route: '/platform/admin/incidents/new',
        apiEndpoint: '/v1/admin/incidents',
        fetchEndpoint: '/v1/admin/incidents',
        method: 'POST',
        dataCyPrefix: 'incident',
        category: 'admin',
        fields: [
            { name: 'title', label: 'Incident Title', type: 'text', required: true },
            { name: 'clientId', label: 'Client', type: 'select', required: true, fetchOptionsFrom: '/v1/admin/clients' },
            { name: 'pswId', label: 'PSW Involved', type: 'select', required: false, fetchOptionsFrom: '/v1/admin/users?role=psw' },
            { name: 'severity', label: 'Severity', type: 'select', required: true },
            { name: 'description', label: 'Description', type: 'textarea', required: true },
            { name: 'dateOccurred', label: 'Date Occurred', type: 'date', required: true },
        ],
        dependencies: [
            { field: 'clientId', entityType: 'client', inlineCreateEndpoint: '/v1/admin/clients', fetchEndpoint: '/v1/admin/clients', inlineCreateLabel: '+ New Client' },
            { field: 'pswId', entityType: 'psw', inlineCreateEndpoint: '/v1/admin/users', fetchEndpoint: '/v1/admin/users?role=psw', inlineCreateLabel: '+ New PSW' },
        ],
    },
];
