/**
 * Auto-generated Owner Coverage Tests: allied
 * Ensures all 3 pages owned by "allied" are importable.
 * Generated by scripts/generate-tests.mjs
 */
import { describe, it, expect } from 'vitest';

describe('Owner Coverage: allied (3 pages)', () => {
    it('should have at least 1 page', () => {
        expect(3).toBeGreaterThan(0);
    });

    it('D18: Allied Health is importable and owned by allied', async () => {
        const mod: any = await import('@/app/routes/tenancy/allied-health');
        const component = mod.default || Object.values(mod)[0];
        expect(component).toBeDefined();
        expect('allied').toBe('allied');
    });

    it('L21: Treatment List is importable and owned by allied', async () => {
        const mod: any = await import('../app/routes/tenancy/allied-health');
        const component = mod.default || Object.values(mod)[0];
        expect(component).toBeDefined();
        expect('allied').toBe('allied');
    });

    it('T42: Sign Off is importable and owned by allied', async () => {
        const mod: any = await import('../app/routes/tenancy/allied-health');
        const component = mod.default || Object.values(mod)[0];
        expect(component).toBeDefined();
        expect('allied').toBe('allied');
    });
});
