/**
 * Auto-generated Registry Cross-Reference Tests
 * Validates PageRegistry, HomeRegistry, ListRegistry, etc. are internally consistent.
 * Generated by scripts/generate-tests.mjs
 */
import { describe, it, expect } from 'vitest';
import {
    PageRegistry, HomeRegistry, ListRegistry, HubRegistry,
    WizardRegistry, ReportRegistry, ToolRegistry,
    MASTER_REGISTRY, MASTER_REGISTRY_COUNT, PAGE_REGISTRY_COUNT,
    getPageById, getPagesByType, getPagesByOwner,
    FILE_IDENTITY_MAP, FILE_ASSOCIATE_MAP,
} from 'prime-care-shared';

describe('Registry Cross-Reference', () => {
    // ── Counts ──
    it('MASTER_REGISTRY should have at least 168 entries', () => {
        expect(MASTER_REGISTRY_COUNT).toBeGreaterThanOrEqual(168);
    });

    it('PageRegistry and MASTER_REGISTRY should be consistent', () => {
        expect(MASTER_REGISTRY_COUNT).toBeGreaterThanOrEqual(168);
    });

    // ── Sub-registry consistency ──
    it('HomeRegistry should have entries', () => {
        expect(HomeRegistry.length).toBeGreaterThan(3);
    });

    it('ListRegistry should have entries', () => {
        expect(ListRegistry.length).toBeGreaterThan(3);
    });

    it('HubRegistry should have entries', () => {
        expect(HubRegistry.length).toBeGreaterThan(3);
    });

    // ── FILE_IDENTITY_MAP ──
    it('FILE_IDENTITY_MAP should have entries', () => {
        expect(Object.keys(FILE_IDENTITY_MAP).length).toBeGreaterThan(0);
    });

    // ── Type distribution ──
    it('should have home pages', () => {
        expect(getPagesByType('home').length).toBeGreaterThan(0);
    });

    it('should have form pages', () => {
        expect(getPagesByType('form').length).toBeGreaterThan(0);
    });

    it('should have list pages', () => {
        expect(getPagesByType('list').length).toBeGreaterThan(0);
    });

    it('should have hub pages', () => {
        expect(getPagesByType('hub').length).toBeGreaterThan(0);
    });

    it('should have tool pages', () => {
        expect(getPagesByType('tool').length).toBeGreaterThan(0);
    });

    it('should have wizard pages', () => {
        expect(getPagesByType('wizard').length).toBeGreaterThan(0);
    });

    it('should have report pages', () => {
        expect(getPagesByType('report').length).toBeGreaterThan(0);
    });

    // ── Owner distribution ──
    it('should have pages owned by admin', () => {
        expect(getPagesByOwner('admin' as any).length).toBeGreaterThan(0);
    });

    it('should have pages owned by psw', () => {
        expect(getPagesByOwner('psw' as any).length).toBeGreaterThan(0);
    });

    it('should have pages owned by rn', () => {
        expect(getPagesByOwner('rn' as any).length).toBeGreaterThan(0);
    });

    it('should have pages owned by client', () => {
        expect(getPagesByOwner('client' as any).length).toBeGreaterThan(0);
    });

    it('should have pages owned by coordinator', () => {
        expect(getPagesByOwner('coordinator' as any).length).toBeGreaterThan(0);
    });

    it('should have pages owned by manager', () => {
        expect(getPagesByOwner('manager' as any).length).toBeGreaterThan(0);
    });

    // ── Lookup helpers ──
    it('getPageById returns first page', () => {
        const first = PageRegistry[0];
        expect(getPageById(first.id)).toBeDefined();
    });

    it('getPageById returns undefined for garbage', () => {
        expect(getPageById('zzz-nonexistent')).toBeUndefined();
    });
});
