name = "primecare-verification-service"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[vars]
ENVIRONMENT = "development"

[triggers]
crons = ["*/15 * * * *"] # Every 15 minutes trigger verification
