name = "primecare-verification-service"
main = "src/index.ts"
compatibility_date = "2024-02-22"
compatibility_flags = [ "nodejs_compat" ]

[vars]
ENVIRONMENT = "development"
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=dummy_mock_key"
INTERNAL_API_KEY = "dummy"

[triggers]
crons = ["*/15 * * * *"] # Every 15 minutes trigger verification
