name: primecare_adapters
description: "A standalone package dedicated to centralized UI data binding logic and adapters for the PrimeCare platform."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.11.3

dependencies:
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  shared_preferences: ^2.5.5
  equatable: ^2.0.7
  intl: ^0.20.2
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
