export const PLATFORM_ROUTES = {
    ADMIN: {
        DASHBOARD: '/platform/admin',
        SUMMARY_DASHBOARD: '/platform/admin/summary-dashboard',
        CUSTOMERS: '/platform/admin/customers',
        USERS: '/platform/admin/users',
        USERS_NEW: '/platform/admin/users/new',
        USERS_EDIT: (id: string) => `/platform/admin/users/${id}/edit`,
        SCHEDULE: '/platform/admin/schedule',
        EARNINGS: '/platform/admin/earnings',
        INCIDENTS: '/platform/admin/incidents',
        INCIDENTS_NEW: '/platform/admin/incidents/new',
        INCIDENTS_EDIT: (id: string) => `/platform/admin/incidents/${id}/edit`,
        LEADS: '/platform/admin/leads',
        LEADS_NEW: '/platform/admin/leads/new',
        LEADS_EDIT: (id: string) => `/platform/admin/leads/${id}/edit`,
        LEADS_CONVERT: (id: string) => `/platform/admin/leads/${id}/convert`,
        INVOICES_NEW: '/platform/admin/invoices/new',
        INVOICES_EDIT: (id: string) => `/platform/admin/invoices/${id}/edit`,
        TIMESHEETS: '/platform/admin/timesheets',
        TIMESHEET_ADJUST: '/platform/admin/timesheets/adjust',
        REPORTS: '/platform/admin/reports',
        REPORT_EXPORT: '/platform/admin/reports/export',
        SEARCH: '/platform/admin/search',
        SERVICES: '/platform/admin/services',
        SETTINGS: '/platform/admin/settings',
        CONTENT: '/platform/admin/content',
        AUDITS: '/platform/admin/audits',
        ADMISSION: '/platform/admin/admission',
        ONBOARDING: '/platform/admin/onboarding',
        LOCATIONS: '/platform/admin/locations',
        SETUP_WIZARD: '/platform/admin/setup-wizard',
        WIZARD_HUB: '/platform/admin/wizard-hub',
        STAFF_ONBOARDING: '/platform/admin/wizards/staff-onboarding',
        CARE_PLAN_WIZARD: '/platform/admin/wizards/care-plan',
        REVENUE_WIZARD: '/platform/admin/wizards/revenue',
        BUSINESS_MODEL_WIZARD: '/platform/admin/wizards/business-strategy',
        BUSINESS_STATUS: '/platform/admin/business-status',
        KNOWLEDGE_BASE: '/platform/admin/knowledge-base',
        KNOWLEDGE_BASE_ARTICLE: (slug: string) => `/platform/admin/knowledge-base/${slug}`,
        AI_INSIGHTS: '/platform/admin/insights',
        CLINICAL_ASSISTANT: '/platform/admin/clinical-assistant',
        AUTOPILOT: '/platform/admin/automation/clinical-autopilot',
        INTEROP: '/platform/admin/interop',
        SOVEREIGN: '/platform/admin/sovereign',
        TEMPLATE_EDITOR: '/platform/admin/template-editor',
        ROLE_EDITOR: '/platform/admin/role-editor',
        PRIVATE_MARKETPLACE: '/platform/admin/private-marketplace',
        AI: {
            DASHBOARD: '/platform/admin/ai',
            PREDICTIVE_ANALYTICS: '/platform/admin/ai/predictive',
            CHURN_RISK: '/platform/admin/ai/churn-risk',
            VISIT_OPTIMIZATION: '/platform/admin/ai/visit-optimization',
            SENTIMENT_ANALYSIS: '/platform/admin/ai/sentiment',
        },
        SECURITY: {
            DASHBOARD: '/platform/admin/security',
            PERMISSION_GRID: '/platform/admin/security/permissions',
            AUDIT_DETAIL: (id: string) => `/platform/admin/security/audits/${id}`,
            SESSION_MONITOR: '/platform/admin/security/sessions',
            THREAT_DETECTION: '/platform/admin/security/threats',
            GOVERNANCE: '/platform/admin/security/governance',
            DEVICE_REGISTRY: '/platform/admin/security/devices',
            FORENSIC_TRAILS: '/platform/admin/security/forensic',
            CORS_SETTINGS: '/platform/admin/security/cors',
            INTEGRITY_SCAN: '/platform/admin/security/integrity',
            FINANCIAL_LEDGER: '/platform/admin/security/ledger',
            TAX_HUB: '/platform/admin/security/tax-hub',
        },
        OPERATIONS: {
            CENTER: '/platform/admin/ops/center',
            REALTIME_CAPACITY: '/platform/admin/ops/capacity',
            REGION_MAPPING: '/platform/admin/ops/regions',
            SUPPLY_DEMAND: '/platform/admin/ops/supply-demand',
            LOGISTICS_HUB: '/platform/admin/ops/logistics',
        },
        ERP: {
            INVENTORY: '/platform/admin/erp/inventory',
            PROCUREMENT: '/platform/admin/erp/procurement',
        },
        TELEHEALTH: {
            CENTER: '/platform/admin/telehealth/center',
            ALERTS: '/platform/admin/telehealth/alerts',
        },
        RCM: {
            CLAIMS: '/platform/admin/rcm/claims',
            REVENUE: '/platform/admin/rcm/revenue',
        },
        PHARMACY: {
            HUB: '/platform/admin/pharmacy/hub',
            MAR: '/platform/admin/pharmacy/mar',
        },
        FINANCE: {
            DASHBOARD: '/platform/admin/finance/dashboard',
            TRADING_ACCOUNT: '/platform/admin/finance/trading',
            PROFIT_LOSS: '/platform/admin/finance/p-and-l',
            BALANCE_SHEET: '/platform/admin/finance/balance-sheet',
            RECONCILIATION: '/platform/admin/finance/reconciliation',
        },
        EVV: {
            DASHBOARD: '/platform/admin/evv',
            EXCEPTIONS: '/platform/admin/evv/exceptions',
            EXPORT: '/platform/admin/evv/export',
        },
        AUTHORIZATIONS: {
            LIST: '/platform/admin/authorizations',
            ALERTS: '/platform/admin/authorizations/alerts',
            UTILIZATION: (clientId: string) => `/platform/admin/authorizations/utilization/${clientId}`,
        },
        CONSENT: {
            LIST: '/platform/admin/consent',
            TEMPLATES: '/platform/admin/consent/templates',
            EXPIRING: '/platform/admin/consent/expiring',
        },
        REFERRALS: {
            LIST: '/platform/admin/referrals',
            ANALYTICS: '/platform/admin/referrals/analytics',
            CONVERT: (id: string) => `/platform/admin/referrals/${id}/convert`,
        },
        CLAIMS: {
            LIST: '/platform/admin/claims',
            ERA: '/platform/admin/claims/era',
        },
        WEBHOOKS: {
            LIST: '/platform/admin/webhooks',
            DELIVERIES: '/platform/admin/webhooks/deliveries',
        },
        AUDIT_EXPORT: {
            DOWNLOAD: '/platform/admin/audit-export',
            COMPLIANCE: '/platform/admin/audit-export/compliance',
            REGULATORY: '/platform/admin/audit-export/regulatory',
        },
        NOTIFICATIONS_HUB: '/platform/admin/notifications',
        DOCUMENT_CENTER: '/platform/admin/documents',
        PAYROLL_HUB: '/platform/admin/payroll',
        BOOKING_REQUESTS: '/platform/admin/booking-requests',
        REFERENCE_DATA: '/platform/admin/reference-data',
        CRON_DASHBOARD: '/platform/admin/cron-dashboard',
        FORM_REGISTRY: '/platform/admin/form-registry',
        PAGE_REGISTRY: '/platform/admin/page-registry',
    },
    SUPERUSER: {
        DASHBOARD: '/platform',
        TENANTS: '/platform/tenants',
        AUDIT_LOGS: '/platform/audit-logs',
        SLA: '/platform/sla',
        RISK_SURVEILLANCE: '/platform/risk-surveillance',
        GOVERNANCE_HUB: '/platform/governance',
        SYSTEM_POLICIES: '/platform/policies',
    },
    SCRUM_MASTER: {
        DASHBOARD: '/platform/scrum-master',
        API_ENDPOINTS: '/platform/scrum-master/api-endpoints',
        PAGES: '/platform/scrum-master/pages',
        COMPONENTS: '/platform/scrum-master/components',
        ROLE_FLOWS: '/platform/scrum-master/role-flows',
        MONITORING: '/platform/scrum-master/monitoring',
        ENV_AUDIT: '/platform/scrum-master/env-audit',
        REGISTRY_CHECK: '/platform/scrum-master/registry-check',
        DATABASE_SCHEMA: '/platform/scrum-master/database-schema',
        THEME_CENTER: '/platform/scrum-master/theme-center',
        DEVELOPER: '/platform/scrum-master/developer',
        DEV_KB: '/platform/scrum-master/dev-kb',
        PERFORMANCE: '/platform/scrum-master/performance',
        BUILD_HEALTH: '/platform/scrum-master/builds',
        SECURITY_SCANS: '/platform/scrum-master/security-scans',
        LOCALIZATION: '/platform/scrum-master/locales',
        INTERACTION_AUDIT: '/platform/scrum-master/interaction-audit',
        AUTO_FIX: '/platform/scrum-master/auto-fix',
        IMPERSONATE: '/platform/scrum-master/impersonate',
        RESPONSE_BOT: '/platform/scrum-master/response-bot',
    },
} as const;
