export const theme = {
    name: 'PrimeCare Clinical',
    colors: {
        surface: '#f7f9fb',
        surfaceDim: '#d8dadc',
        surfaceBright: '#f7f9fb',
        surfaceContainerLowest: '#ffffff',
        surfaceContainerLow: '#f2f4f6',
        surfaceContainer: '#eceef0',
        surfaceContainerHigh: '#e6e8ea',
        surfaceContainerHighest: '#e0e3e5',
        onSurface: '#191c1e',
        onSurfaceVariant: '#434655',
        inverseSurface: '#2d3133',
        inverseOnSurface: '#eff1f3',
        outline: '#737686',
        outlineVariant: '#c3c6d7',
        surfaceTint: '#0053db',
        primary: '#004ac6',
        onPrimary: '#ffffff',
        primaryContainer: '#2563eb',
        onPrimaryContainer: '#eeefff',
        inversePrimary: '#b4c5ff',
        secondary: '#4059aa',
        onSecondary: '#ffffff',
        secondaryContainer: '#8fa7fe',
        onSecondaryContainer: '#1d3989',
        tertiary: '#943700',
        onTertiary: '#ffffff',
        tertiaryContainer: '#bc4800',
        onTertiaryContainer: '#ffede6',
        error: '#ba1a1a',
        onError: '#ffffff',
        errorContainer: '#ffdad6',
        onErrorContainer: '#93000a',
        primaryFixed: '#dbe1ff',
        primaryFixedDim: '#b4c5ff',
        onPrimaryFixed: '#00174b',
        onPrimaryFixedVariant: '#003ea8',
        secondaryFixed: '#dce1ff',
        secondaryFixedDim: '#b6c4ff',
        onSecondaryFixed: '#00164e',
        onSecondaryFixedVariant: '#264191',
        tertiaryFixed: '#ffdbcd',
        tertiaryFixedDim: '#ffb596',
        onTertiaryFixed: '#360f00',
        onTertiaryFixedVariant: '#7d2d00',
        background: '#f7f9fb',
        onBackground: '#191c1e',
        surfaceVariant: '#e0e3e5',
    },
    typography: {
        h1: {
            fontFamily: 'Manrope',
            fontSize: '30px',
            fontWeight: '700',
            lineHeight: '38px',
            letterSpacing: '-0.02em',
        },
        h2: {
            fontFamily: 'Manrope',
            fontSize: '24px',
            fontWeight: '600',
            lineHeight: '32px',
            letterSpacing: '-0.01em',
        },
        h3: {
            fontFamily: 'Manrope',
            fontSize: '20px',
            fontWeight: '600',
            lineHeight: '28px',
        },
        bodyLg: {
            fontFamily: 'Inter',
            fontSize: '16px',
            fontWeight: '400',
            lineHeight: '24px',
        },
        bodyMd: {
            fontFamily: 'Inter',
            fontSize: '14px',
            fontWeight: '400',
            lineHeight: '20px',
        },
        bodySm: {
            fontFamily: 'Inter',
            fontSize: '13px',
            fontWeight: '400',
            lineHeight: '18px',
        },
        labelBold: {
            fontFamily: 'Inter',
            fontSize: '12px',
            fontWeight: '600',
            lineHeight: '16px',
            letterSpacing: '0.05em',
        },
        labelMd: {
            fontFamily: 'Inter',
            fontSize: '12px',
            fontWeight: '500',
            lineHeight: '16px',
        },
    },
    borderRadius: {
        sm: '0.25rem',
        default: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
    },
    spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        containerPadding: '24px',
        cardGap: '16px',
    },
};

