// Layer: 01_INFRASTRUCTURE
// DYNAMIC ADAPTER RESOLVER
// Auto-generated by PrimeCare UI Architectural Normalize Pipeline

import 'package:primecare_ui/src/shared/primecare_adapters.dart';
import 'package:flutter_core/flutter_core.dart';
import 'package:primecare_ui/primecare_ui.dart';

/// Global Registry dynamically mapping screen routing IDs to their Hydration Adapters
final Map<String, dynamic> globalAdapterRegistry = {
  //   'addFranchiseLeadForm': addFranchiseLeadFormAdapterProvider,
  //   'approveExpenseReimbursementForm': approveExpenseReimbursementFormAdapterProvider,
  //   'approveFranchiseDisclosureForm': approveFranchiseDisclosureFormAdapterProvider,
  //   'approveLeaveRequestForm': approveLeaveRequestFormAdapterProvider,
  //   'approveMedicationRefillForm': approveMedicationRefillFormAdapterProvider,
  //   'approvePayrollRunForm': approvePayrollRunFormAdapterProvider,
  'architecturePlanning': architecturePlanningMetricsProvider,
  //   'assignLeadForm': assignLeadFormAdapterProvider,
  //   'assignTrainingModuleForm': assignTrainingModuleFormAdapterProvider,
  //   'auditPayrollDiscrepancyForm': auditPayrollDiscrepancyFormAdapterProvider,
  'billingAdminDashboard': billingAdminMetricsProvider,
  'ceoDashboard': ceoMetricsProvider,
  'cfoDashboard': cfoMetricsProvider,
  'clientDashboard': clientDashboardAdapterProvider,
  'clinicDashboard': clinicDashboardAdapterProvider,
  'communityOutreachDashboard': communityOutreachDashboardAdapterProvider,
  'complianceManagerDashboard': complianceManagerDashboardAdapterProvider,
  'cooDashboard': cooMetricsProvider,
  'courseArchitect': courseArchitectAdapterProvider,
  //   'createAdPlacementForm': createAdPlacementFormAdapterProvider,
  'ctoDashboard': ctoMetricsProvider,
  'customerSupportDashboard': customerSupportMetricsProvider,
  'cxDirectorDashboard': cxDirectorMetricsProvider,
  //   'dailyVitalsCardForm': dailyVitalsCardFormAdapterProvider,
  //   'disciplineLogForm': disciplineLogFormAdapterProvider,
  'dynamicScreen': dynamicAdapterProvider(PrimeCareForm.genericDashboard),
  'familyDashboard': familyDashboardAdapterProvider,
  'financeDirectorDashboard': financeDirectorMetricsProvider,
  //   'franchiseOnboardingChecklistForm': franchiseOnboardingChecklistFormAdapterProvider,
  'franchiseOwner': franchiseOwnerMetricsProvider,
  'franchiseSalesManagerDashboard':
      franchiseSalesManagerDashboardAdapterProvider,
  'generalManagerDashboard': generalManagerMetricsProvider,
  'guestDashboard': guestDashboardAdapterProvider,
  'headOfBusDevDashboard': busDevMetricsProvider,
  'headOfMarketingDashboard': marketingMetricsProvider,
  'hrDirectorDashboard': hrDirectorMetricsProvider,
  'hrHiringDashboard': hrMetricsProvider,
  'intakeDashboard': intakeMetricsProvider,
  //   'leaveRequestForm': leaveRequestFormAdapterProvider,
  'localMarketingManagerDashboard':
      localMarketingManagerDashboardAdapterProvider,
  //   'logEmployeeGrievanceForm': logEmployeeGrievanceFormAdapterProvider,
  //   'logFranchiseeVettingCallForm': logFranchiseeVettingCallFormAdapterProvider,
  //   'newEmployeeOnboardingForm': newEmployeeOnboardingFormAdapterProvider,
  //   'nurtureLocalizedLeadForm': nurtureLocalizedLeadFormAdapterProvider,
  'operationsManagerDashboard': operationsMetricsProvider,
  'ownerDashboard': ownerMetricsProvider,
  'partnershipManagerDashboard': partnershipManagerDashboardAdapterProvider,
  'patientDashboard': patientDashboardAdapterProvider,
  //   'patientIntakeForm': patientIntakeFormAdapterProvider,
  'qaDashboard': qaMetricsProvider,
  'regionalBdmDashboard': regionalBdmDashboardAdapterProvider,
  'regionalManagerOntarioDashboard': regionalManagerOntarioMetricsProvider,
  'regionalManagerUsaDashboard': regionalManagerUsaDashboardAdapterProvider,
  //   'requestShiftAdjustmentForm': requestShiftAdjustmentFormAdapterProvider,
  //   'reviewLeadConversionForm': reviewLeadConversionFormAdapterProvider,
  //   'reviewMarketShareForm': reviewMarketShareFormAdapterProvider,
  //   'reviewOnboardingStatusForm': reviewOnboardingStatusFormAdapterProvider,
  //   'reviewPeerPerformanceForm': reviewPeerPerformanceFormAdapterProvider,
  //   'scheduleInterviewForm': scheduleInterviewFormAdapterProvider,
  //   'scheduleOpenHouseForm': scheduleOpenHouseFormAdapterProvider,
  'schedulerDashboard': schedulerMetricsProvider,
  'scrumMasterDashboard': scrumMasterMetricsProvider,
  //   'singleInputForm': singleInputFormAdapterProvider,
  //   'submitExitInterviewForm': submitExitInterviewFormAdapterProvider,
  //   'submitMarketingBudgetForm': submitMarketingBudgetFormAdapterProvider,
  'supportDashboard': supportMetricsProvider,
  'systemVerification': systemVerificationMetricsProvider,
  'territoryExpansionManagerDashboard': territoryExpansionMetricsProvider,
  'territorySalesManagerDashboard': territorySalesMetricsProvider,
  'trainingCoordinatorDashboard': trainingCoordMetricsProvider,
  'trainingDirectorCertificate': trainingDirectorCertMetricsProvider,
  'trainingDirectorDashboard': trainingMetricsProvider,
  'trainingHub': trainingHubMetricsProvider,
  'volunteerCoordinatorDashboard': volunteerMetricsProvider,
};

/// Resolver utility to dynamically fetch any ViewModel provider by string ref
dynamic resolveAdapterByName(String name) {
  return globalAdapterRegistry[name];
}
