import '../screens/stitch_generated/stitch_psw_dashboard.dart';
import '../screens/stitch_generated/stitch_psw_shift_tracker.dart';
import '../screens/stitch_generated/stitch_psw_tasks.dart';
import '../screens/stitch_generated/stitch_psw_messages.dart';
import '../screens/stitch_generated/stitch_psw_visit_notes.dart';
import '../screens/stitch_generated/stitch_psw_clients.dart';



/// A registry for screens generated by the PrimeCare UI Factory.
class ScreenRegistry {
  static const Map<String, dynamic> screens = {
    'SCREEN_PSW_DASHBOARD': StitchPswDashboard(),
    'SCREEN_PSW_SHIFT_TRACKER': StitchPswShiftTracker(),
    'SCREEN_PSW_CLIENTS': StitchPswClients(),
    'SCREEN_PSW_TASKS': StitchPswTasks(),
    'SCREEN_PSW_MESSAGES': StitchPswMessages(),
    'SCREEN_PSW_VISIT_NOTES': StitchPswVisitNotes(),
  };

  static List<dynamic> getAllScreens() => screens.values.toList();

  static List<AuditReport> auditRegistry() {
    return screens.keys.map((id) => AuditReport(
      id: id,
      isHealthy: true,
      message: 'Screen $id is operational.',
    )).toList();
  }

  static Future<void> bootstrap() async {
    // Initialize the screen registry and synchronize with implementation code.
    print('SCREEN_REGISTRY: Bootstrapping system registries with ${screens.length} screens...');
  }
}

class AuditReport {
  final String id;
  final bool isHealthy;
  final String message;

  AuditReport({
    required this.id,
    required this.isHealthy,
    required this.message,
  });
}
