// Governance - Category: service | Purpose: ── Admin Operations Forms (admission, onboarding, locations, timesheet, reseller, resolution) ──
import type { FormEntry } from '../form_registry';

// ── Admin Operations Forms (admission, onboarding, locations, timesheet, reseller, resolution) ──

export const ADMIN_OPS_FORMS: FormEntry[] = [
    {
        id: 'admin.admission',
        label: 'Client Admission',
        route: '/platform/admin/admission',
        apiEndpoint: '/v1/admin/clients',
        method: 'POST',
        dataCyPrefix: 'admission',
        category: 'admin',
        fields: [
            { name: 'firstName', label: 'First Name', type: 'text', required: true },
            { name: 'lastName', label: 'Last Name', type: 'text', required: true },
            { name: 'email', label: 'Email', type: 'email', required: true },
            { name: 'phone', label: 'Phone', type: 'tel', required: true },
            { name: 'dateOfBirth', label: 'Date of Birth', type: 'date', required: true },
            { name: 'address', label: 'Address', type: 'text', required: true },
            { name: 'serviceTypeId', label: 'Service Type', type: 'select', required: true, fetchOptionsFrom: '/v1/admin/services' },
            { name: 'assignedPswId', label: 'Assigned PSW', type: 'select', required: false, fetchOptionsFrom: '/v1/admin/users?role=psw' },
            { name: 'emergencyContact', label: 'Emergency Contact', type: 'text', required: true },
            { name: 'notes', label: 'Admission Notes', type: 'textarea', required: false },
        ],
        dependencies: [
            { field: 'serviceTypeId', entityType: 'serviceType', inlineCreateEndpoint: '/v1/admin/services', fetchEndpoint: '/v1/admin/services', inlineCreateLabel: '+ New Service Type' },
            { field: 'assignedPswId', entityType: 'psw', inlineCreateEndpoint: '/v1/admin/users', fetchEndpoint: '/v1/admin/users?role=psw', inlineCreateLabel: '+ New PSW' },
        ],
    },
    {
        id: 'admin.onboarding',
        label: 'Staff Onboarding',
        route: '/platform/admin/onboarding',
        apiEndpoint: '/v1/admin/users',
        method: 'POST',
        dataCyPrefix: 'onboarding',
        category: 'admin',
        fields: [
            { name: 'firstName', label: 'First Name', type: 'text', required: true },
            { name: 'lastName', label: 'Last Name', type: 'text', required: true },
            { name: 'email', label: 'Email', type: 'email', required: true },
            { name: 'role', label: 'Role', type: 'select', required: true },
            { name: 'startDate', label: 'Start Date', type: 'date', required: true },
            { name: 'credentials', label: 'Credentials / Certifications', type: 'textarea', required: false },
        ],
    },
    {
        id: 'admin.locations',
        label: 'Create / Edit Location',
        route: '/platform/admin/locations',
        apiEndpoint: '/v1/admin/locations',
        fetchEndpoint: '/v1/admin/locations',
        method: 'POST',
        dataCyPrefix: 'location',
        category: 'admin',
        fields: [
            { name: 'name', label: 'Location Name', type: 'text', required: true },
            { name: 'address', label: 'Address', type: 'text', required: true },
            { name: 'city', label: 'City', type: 'text', required: true },
            { name: 'province', label: 'Province / State', type: 'text', required: true },
            { name: 'postalCode', label: 'Postal Code', type: 'text', required: true },
            { name: 'managerId', label: 'Branch Manager', type: 'select', required: false, fetchOptionsFrom: '/v1/admin/users' },
            { name: 'phone', label: 'Phone', type: 'tel', required: false },
        ],
    },
    {
        id: 'admin.timesheet-adjust',
        label: 'Timesheet Adjustment',
        route: '/platform/admin/timesheets/adjust',
        apiEndpoint: '/v1/admin/timesheets',
        method: 'PUT',
        dataCyPrefix: 'timesheet',
        category: 'admin',
        fields: [
            { name: 'pswId', label: 'PSW', type: 'select', required: true, fetchOptionsFrom: '/v1/admin/users?role=psw' },
            { name: 'visitDate', label: 'Visit Date', type: 'date', required: true },
            { name: 'checkIn', label: 'Check-in Time', type: 'time', required: true },
            { name: 'checkOut', label: 'Check-out Time', type: 'time', required: true },
            { name: 'reason', label: 'Adjustment Reason', type: 'textarea', required: true },
        ],
    },
    {
        id: 'admin.reseller-provision',
        label: 'Provision New Agency',
        route: '/platform/admin/reseller',
        apiEndpoint: '/v1/admin/reseller/provision',
        method: 'POST',
        dataCyPrefix: 'reseller',
        category: 'admin',
        fields: [
            { name: 'name', label: 'Agency Name', type: 'text', required: true },
            { name: 'slug', label: 'Routing Slug', type: 'text', required: true },
            { name: 'adminEmail', label: 'Admin Login Email', type: 'email', required: true },
            { name: 'adminPassword', label: 'Temporary Password', type: 'password', required: true },
        ],
    },
    {
        id: 'admin.incident-resolution',
        label: 'Incident Resolution',
        route: '/platform/admin/incidents',
        apiEndpoint: '/v1/admin/incidents',
        method: 'PUT',
        dataCyPrefix: 'incident-resolution',
        category: 'admin',
        fields: [
            { name: 'resolution', label: 'Resolution Summary', type: 'textarea', required: true },
            { name: 'rootCause', label: 'Root Cause', type: 'select', required: true },
            { name: 'followUpDate', label: 'Follow-up Date', type: 'date', required: false },
        ],
    },
];
