import json
import os
import re

# Paths
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../../"))
PAGE_INVENTORY = os.path.join(ROOT_DIR, ".agents/governance/page_inventory.yaml")
FEATURES_DIR = os.path.join(ROOT_DIR, "packages/factory_system/primecare_ui/lib")
ADAPTERS_DIR = os.path.join(ROOT_DIR, "packages/primecare_adapters/lib")
LOCALE_KEYS_FILE = os.path.join(ROOT_DIR, "packages/primecare_adapters/lib/src/config/00_I_locale_keys.dart")
TRANSLATIONS_DIR = os.path.dirname(os.path.abspath(__file__))

def to_title_case(snake_str):
    return " ".join(x.capitalize() for x in snake_str.replace("_", " ").split())

def to_slug(text):
    return text.lower().strip().replace(" ", "_").replace("&", "and")

def parse_yaml_inventory():
    """Simple regex parser for the page inventory YAML."""
    if not os.path.exists(PAGE_INVENTORY):
        return [], []
    
    with open(PAGE_INVENTORY, 'r') as f:
        content = f.read()
    
    # Split by '- id:' to handle multi-line items
    blocks = content.split("- id:")[1:]
    items = []
    sections = set()

    for block in blocks:
        # Get ID (first word after - id:)
        id_match = re.search(r'^\s*\"?(\w+)\"?', block)
        if not id_match: continue
        mid = id_match.group(1)
        
        # Get Label
        label_match = re.search(r'label:\s*\"?([\w\s&]+)\"?', block)
        mlabel = label_match.group(1).strip() if label_match else to_title_case(mid)
        
        # Get Section
        section_match = re.search(r'section:\s*\"?([\w\s&]+)\"?', block)
        msection = section_match.group(1).strip() if section_match else "Main"
        
        items.append({"id": mid, "label": mlabel, "section": msection})
        sections.add(msection)
    
    return items, sorted(list(sections))

def scan_dashboard_intents():
    """Scans all *intent.dart files for dashboard keys."""
    dashboards = {}
    
    if not os.path.exists(FEATURES_DIR):
        return dashboards

    for root, _, files in os.walk(FEATURES_DIR):
        for file in files:
            if file.endswith("intent.dart"):
                path = os.path.join(root, file)
                with open(path, 'r') as f:
                    content = f.read()
                
                # Extract role/key from title pattern: dashboards.role.title
                title_match = re.search(r"dashboards\.(\w+)\.title", content)
                if title_match:
                    role = title_match.group(1)
                    if role not in dashboards:
                        dashboards[role] = {
                            "title": to_title_case(role) + " Dashboard",
                            "subtitle": "Access metrics.",
                            "labels": {}
                        }
                    
                    # Extract labels
                    label_matches = re.findall(r"dashboards\." + role + r"\.labels\.(\w+)", content)
                    for label_key in label_matches:
                        dashboards[role]["labels"][label_key] = to_title_case(label_key)
    
    return dashboards

def generate_locale_keys(all_keys):
    """Generates the static LocaleKeys Dart class."""
    content = "// Generated by gen_translations.py - DO NOT EDIT MANUALLY\n"
    content += "abstract class LocaleKeys {\n"
    
    def add_keys(data, prefix=""):
        nonlocal content
        # Sort keys for deterministic output
        for k in sorted(data.keys()):
            v = data[k]
            key_path = f"{prefix}.{k}" if prefix else k
            if isinstance(v, dict):
                add_keys(v, key_path)
            else:
                # Create a valid Dart constant name
                const_name = key_path.replace(".", "_").replace("&", "and").replace("-", "_")
                # Remove common prefixes from const name if redundant, but here we keep full for clarity
                content += f"  static const String {const_name} = '{key_path}';\n"

    add_keys(all_keys)
    content += "}\n"
    
    with open(LOCALE_KEYS_FILE, 'w') as f:
        f.write(content)
    print(f"Generated {LOCALE_KEYS_FILE}")

def scan_codebase_for_keys(en_translations):
    """Scans all Dart files in primecare_adapters and primecare_ui for used LocaleKeys to ensure they are generated and translated."""
    processed_keys = set()
    
    # Scan both directories
    scan_dirs = [ADAPTERS_DIR, FEATURES_DIR]
    
    for scan_dir in scan_dirs:
        if not os.path.exists(scan_dir): continue
        
        for root_path, _, files in os.walk(scan_dir):
            for file in files:
                if file.endswith(".dart"):
                    path = os.path.join(root_path, file)
                    with open(path, 'r', encoding='utf-8', errors='ignore') as f:
                        content = f.read()
                    
                    # Match LocaleKeys.some_key_name.tr() with optional whitespace anywhere
                    matches = re.findall(r"LocaleKeys\s*\.\s*(\w+)\s*\.\s*tr\(", content)
                    for full_key in matches:
                        if full_key in processed_keys: continue
                        processed_keys.add(full_key)
                        
                        # Handle dashboard patterns: dashboards_<role>_labels_<key>
                        dash_match = re.match(r"dashboards_(\w+)_labels_(\w+)", full_key)
                        if dash_match:
                            role, label_key = dash_match.groups()
                            if "dashboards" not in en_translations: en_translations["dashboards"] = {}
                            if role not in en_translations["dashboards"]:
                                en_translations["dashboards"][role] = {
                                    "title": to_title_case(role) + " Dashboard",
                                    "subtitle": "Access metrics.",
                                    "labels": {}
                                }
                            if "labels" not in en_translations["dashboards"][role]:
                                en_translations["dashboards"][role]["labels"] = {}
                            
                            if label_key not in en_translations["dashboards"][role]["labels"]:
                                en_translations["dashboards"][role]["labels"][label_key] = to_title_case(label_key)
                            continue
                            
                        # Handle dashboards_<role>_title
                        title_match = re.match(r"dashboards_(\w+)_title", full_key)
                        if title_match:
                            role = title_match.group(1)
                            if "dashboards" not in en_translations: en_translations["dashboards"] = {}
                            if role not in en_translations["dashboards"]:
                                en_translations["dashboards"][role] = {
                                    "title": to_title_case(role) + " Dashboard",
                                    "subtitle": "Access metrics.",
                                    "labels": {}
                                }
                            en_translations["dashboards"][role]["title"] = to_title_case(role) + " Dashboard"
                            continue

                        # Handle other top-level keys
                        if full_key not in en_translations:
                            is_already_present = False
                            for top_key in ["navigation", "dashboards", "common", "auth", "aura"]:
                                if top_key in en_translations and full_key.startswith(top_key + "_"):
                                    is_already_present = True
                                    break
                            
                            if not is_already_present:
                                en_translations[full_key] = to_title_case(full_key.split("_")[-1])

def main():
    print("Starting Smart Translation Sync...")
    
    # 1. Gather Data
    nav_items, nav_sections = parse_yaml_inventory()
    dashboards = scan_dashboard_intents()
    
    # 2. Build Translation Maps
    en_translations = {
        "navigation": {
            "sections": {to_slug(s): s for s in nav_sections},
            "items": {item["id"]: item["label"] for item in nav_items},
            "footer": {"language": "Language"}
        },
        "dashboards": dashboards,
        "common": {
            "app_name": "PrimeCare",
            "loading": "Loading...", "save": "Save", "cancel": "Cancel",
            "language": {"en": "English", "fr": "French", "es": "Spanish"}
        },
        "auth": {
            "title_curator": "Welcome to PrimeCare",
            "curator_subtitle": "Enterprise Access Portal",
            "welcome_back": "Welcome Back",
            "login_instructions": "Sign in to your account",
            "email": "Email Address",
            "email_placeholder": "Enter your email",
            "password": "Password",
            "forgot_password": "Forgot Password?",
            "sign_in": "Sign In",
            "security_notice_long": "This system is restricted to authorized personnel.",
            "authentication_failed": "Authentication failed.",
            "enter_credentials_to_continue": "Please enter credentials."
        },
        "aura": {
            "search_hint": "Search Aura...",
            "sign_out": "Sign Out",
            "intelligence": "Aura Intelligence",
            "daily_briefing": "Daily Briefing: {}",
            "executive_overview": "EXECUTIVE OVERVIEW",
            "operational_summary": "Systems are currently operating within nominal parameters.",
            "critical_insights": "CRITICAL INSIGHTS",
            "staff_retention_alert": "Staff Retention Alert",
            "staff_retention_desc": "Regional turnover in Ontario South has increased by 12% this month.",
            "view_retention_plan": "VIEW RETENTION PLAN",
            "marketing_roi_surge": "Marketing ROI Surge",
            "marketing_roi_desc": "Ad campaign 'CommunityCare' has achieved a 4.2x ROI.",
            "adjust_budget": "ADJUST BUDGET",
            "supply_chain_sync": "Supply Chain Sync",
            "supply_chain_desc": "Inventory levels across 14 franchises synchronized successfully.",
            "see_report": "SEE REPORT",
            "governance_alert": "GOVERNANCE ALERT",
            "real_time_intelligence": "REAL-TIME INTELLIGENCE",
            "view_details": "VIEW DETAILS",
            "synchronizing": "Synchronizing Aura IQ...",
            "offline": "Aura Offline",
            "snoozed": "Aura Alerts Snoozed",
            "resume": "RESUME",
            "auditors_blueprint": "AUDITOR'S BLUEPRINT",
            "structural_contract": "STRUCTURAL CONTRACT",
            "verified_components": "VERIFIED COMPONENTS",
            "full_system_audit": "Full System Audit",
            "events": {
                "stable_title": "System Stable",
                "stable_desc": "Institutional heartbeat is nominal.",
                "critical_occupancy_title": "Critical Occupancy Spike",
                "critical_occupancy_desc": "Facility at 98% capacity.",
                "revenue_variance_title": "Revenue Variance Detected",
                "revenue_variance_desc": "Detected a 12% dip in projected daily billing.",
                "efficiency_opt_title": "Efficiency Optimization",
                "efficiency_opt_desc": "Shift change documentation cycle completed 4 minutes faster.",
                "staffing_gap_title": "Anticipated Staffing Gap",
                "staffing_gap_desc": "Trend analysis predicts a 15% staffing deficit.",
                "budget_overrun_title": "Projected Budget Overrun",
                "budget_overrun_desc": "Current spending velocity suggests a potential budget threshold breach.",
                "architectural_drift_title": "Architectural Drift Detected",
                "architectural_drift_desc": "Screen [{}] has drifted from Auditor Blueprint. Missing: {}"
            }
        }
    }
    
    # 3. Scan codebase for loose keys and handle nesting
    scan_codebase_for_keys(en_translations)
    
    # 4. Create French
    fr_translations = json.loads(json.dumps(en_translations))
    
    # French Sections
    fr_sections = {
        "main": "Principale", "management": "Gestion", "common_tools": "Outils Communs",
        "strategic": "Stratégique", "workflows": "Flux de Travail", "operations": "Opérations",
        "finance": "Finance", "clinical": "Clinique", "growth": "Croissance", "master_directory": "Répertoire Principal"
    }
    fr_translations["navigation"]["sections"].update(fr_sections)
    
    # French Navigation Items
    fr_item_mapping = {
        "dashboard": "Tableau de Bord", "system": "Système", "compliance": "Conformité",
        "hub": "Hub", "settings": "Paramètres", "user": "Utilisateur", "management": "Gestion",
        "enterprise": "Entreprise", "overview": "Aperçu", "strategic": "Stratégique",
        "growth": "Croissance", "pipeline": "Pipeline", "region": "Région", "performance": "Performance",
        "leadership": "Leadership", "reports": "Rapports", "financial": "Financier", "revenue": "Revenu",
        "profitability": "Rentabilité", "tax": "Taxe", "remittance": "Remise", "operations": "Opérations",
        "scheduling": "Planification", "health": "Santé", "api": "API", "monitoring": "Surveillance",
        "usage": "Utilisation", "audit": "Audit", "logs": "Journaux", "policy": "Politique",
        "risk": "Risque", "register": "Registre", "matrix": "Matrice", "staffing": "Effectif",
        "coverage": "Couverture", "variance": "Variance", "protocol": "Protocole", "adherence": "Adhérence",
        "trends": "Tendances", "center": "Centre", "site": "Site", "comparative": "Comparatif",
        "operational": "Opérationnel", "indices": "Indices", "scorecard": "Scorecard",
        "expansion": "Expansion", "territory": "Territoire", "command": "Command", "verification": "Vérification"
    }
    
    def translate_to_fr(text):
        words = text.split()
        translated = []
        for word in words:
            low_word = word.lower()
            if low_word in fr_item_mapping:
                translated.append(fr_item_mapping[low_word].capitalize() if word[0].isupper() else fr_item_mapping[low_word])
            else:
                translated.append(word)
        return " ".join(translated)

    for item_id in fr_translations["navigation"]["items"]:
        fr_translations["navigation"]["items"][item_id] = translate_to_fr(fr_translations["navigation"]["items"][item_id])

    # French Dashboard Titles
    for role in fr_translations["dashboards"]:
        fr_translations["dashboards"][role]["title"] = translate_to_fr(fr_translations["dashboards"][role]["title"])
        fr_translations["dashboards"][role]["subtitle"] = "Accéder aux indicateurs."
        if "labels" in fr_translations["dashboards"][role]:
            for label_key in fr_translations["dashboards"][role]["labels"]:
                fr_translations["dashboards"][role]["labels"][label_key] = translate_to_fr(fr_translations["dashboards"][role]["labels"][label_key])

    # French Common & Auth
    fr_translations["common"].update({
        "loading": "Chargement...", "save": "Enregistrer", "cancel": "Annuler",
        "language": {"en": "Anglais", "fr": "Français", "es": "Espagnol"}
    })
    fr_translations["auth"].update({
        "title_curator": "Bienvenue chez PrimeCare",
        "curator_subtitle": "Portail d'Accès Entreprise",
        "welcome_back": "Bon retour",
        "login_instructions": "Connectez-vous à votre compte",
        "email": "Adresse Courriel",
        "email_placeholder": "Entrez votre courriel",
        "password": "Mot de passe",
        "forgot_password": "Mot de passe oublié?",
        "sign_in": "Se connecter"
    })
    
    # Save Files
    with open(os.path.join(TRANSLATIONS_DIR, "en.json"), 'w', encoding='utf-8') as f:
        json.dump(en_translations, f, indent=2, ensure_ascii=False)
    
    with open(os.path.join(TRANSLATIONS_DIR, "fr.json"), 'w', encoding='utf-8') as f:
        json.dump(fr_translations, f, indent=2, ensure_ascii=False)
    
    # Generate Static Dart Keys
    generate_locale_keys(en_translations)
    
    print("Localization Sync Complete.")

if __name__ == "__main__":
    main()
