import '../screen_metadata.dart';

class AdminInfrastructureRegistryRegistry {
  static const Map<String, ScreenMetadata> screens = {
        'SCREEN_SYSTEM_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_SYSTEM_DASHBOARD',
      title: 'system Dashboard',
      featureName: 'system Dashboard',
      routePath: '/system-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'system_dashboard_view.dart',
      implementedComponents: ["Aura HUD (System Uptime)","Server Uptime Graph","API Latency Monitor","Error Density Heatmap"],
    ),
        'SCREEN_HEALTH_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_HEALTH_DASHBOARD',
      title: 'health Dashboard',
      featureName: 'health Dashboard',
      routePath: '/health-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (System Uptime)","Service Status","Resource Consumption","Log Stream"],
    ),
        'SCREEN_SECURITY_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_SECURITY_DASHBOARD',
      title: 'security Dashboard',
      featureName: 'security Dashboard',
      routePath: '/security-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Threat Detection)","Active Vulnerabilities","Security Audit Logs","Encryption Status"],
    ),
        'SCREEN_SCRUM_MASTER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_SCRUM_MASTER_DASHBOARD',
      title: 'scrum Master Dashboard',
      featureName: 'scrum Master Dashboard',
      routePath: '/scrum-master-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'scrum_master_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Sprint Velocity)","Burn-down Chart","Team Capacity","Blocker Management"],
    ),
        'SCREEN_SYSTEM_VERIFICATION': ScreenMetadata(
      id: 'SCREEN_SYSTEM_VERIFICATION',
      title: 'system Verification',
      featureName: 'system Verification',
      routePath: '/system-verification',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'system_verification_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Validation Integrity)","Test Suite Results","Deployment Health","Checksum Logs"],
    ),
        'SCREEN_INFRASTRUCTURE_GOVERNANCE_MONITOR_': ScreenMetadata(
      id: 'SCREEN_INFRASTRUCTURE_GOVERNANCE_MONITOR_',
      title: '/infrastructure/governance/monitor',
      featureName: '/infrastructure/governance/monitor',
      routePath: '/infrastructure/governance/monitor',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Audit Header","Compliance Summary","DashboardRegistry Audit Report","Remediation Actions"],
    ),
        'SCREEN_INFRASTRUCTURE_AND_ADMIN_SYSTEM_INFRASTRUCTURE_OVERVIEW_': ScreenMetadata(
      id: 'SCREEN_INFRASTRUCTURE_AND_ADMIN_SYSTEM_INFRASTRUCTURE_OVERVIEW_',
      title: '/infrastructure-and-admin/system-infrastructure-overview',
      featureName: '/infrastructure-and-admin/system-infrastructure-overview',
      routePath: '/infrastructure-and-admin/system-infrastructure-overview',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Aura Behavioral Telemetry"],
    ),
        'SCREEN_INFRASTRUCTURE_AND_ADMIN_CONFIGURATOR_HUB_': ScreenMetadata(
      id: 'SCREEN_INFRASTRUCTURE_AND_ADMIN_CONFIGURATOR_HUB_',
      title: '/infrastructure-and-admin/configurator-hub',
      featureName: '/infrastructure-and-admin/configurator-hub',
      routePath: '/infrastructure-and-admin/configurator-hub',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Platform Registry"],
    ),
        'SCREEN_INFRASTRUCTURE_AND_ADMIN_AUXILIARY_PLATFORM_VIEW__I_': ScreenMetadata(
      id: 'SCREEN_INFRASTRUCTURE_AND_ADMIN_AUXILIARY_PLATFORM_VIEW__I_',
      title: '/infrastructure-and-admin/auxiliary-platform-view',
      featureName: '/infrastructure-and-admin/auxiliary-platform-view',
      routePath: '/infrastructure-and-admin/auxiliary-platform-view',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","KPI Stat Grid"],
    ),
        'SCREEN_IT_SECURITY_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_IT_SECURITY_DASHBOARD',
      title: 'IT Security Dashboard',
      featureName: 'IT Security Dashboard',
      routePath: '/it-security-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'it_security_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Threat Intelligence","Access Control Logs","Encryption Status"],
    ),
        'SCREEN_ERROR_401': ScreenMetadata(
      id: 'SCREEN_ERROR_401',
      title: 'Unauthorized (401)',
      featureName: 'System Error',
      routePath: '/error-401',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'error401_page_view.dart',
      implementedComponents: ["Aura HUD (Security Alert)","Access Request Form","Auth Redirect"],
    ),
        'SCREEN_ERROR_404': ScreenMetadata(
      id: 'SCREEN_ERROR_404',
      title: 'Not Found (404)',
      featureName: 'System Error',
      routePath: '/error-404',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'error404_page_view.dart',
      implementedComponents: ["Aura HUD (Drift Detection)","Site Map","Support Link"],
    ),
        'SCREEN_SIGN_IN': ScreenMetadata(
      id: 'SCREEN_SIGN_IN',
      title: 'Sign In',
      featureName: 'Authentication',
      routePath: '/sign-in',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'sign_in_view.dart',
      implementedComponents: ["Aura HUD (Auth Velocity)","Identity Field","Password Field","MFA Module"],
    ),
        'SCREEN_SIGN_OUT': ScreenMetadata(
      id: 'SCREEN_SIGN_OUT',
      title: 'Sign Out',
      featureName: 'Authentication',
      routePath: '/sign-out',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'sign_out_view.dart',
      implementedComponents: ["Aura HUD (Session End)","Logout Confirmation","Telemetry Sync"],
    ),
        'SCREEN_SIGN_UP': ScreenMetadata(
      id: 'SCREEN_SIGN_UP',
      title: 'Sign Up',
      featureName: 'Authentication',
      routePath: '/sign-up',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'sign_up_view.dart',
      implementedComponents: ["Aura HUD (Onboarding)","Registration Form","Identity Verification"],
    ),
        'SCREEN_ARCHITECTURAL_PLANNING': ScreenMetadata(
      id: 'SCREEN_ARCHITECTURAL_PLANNING',
      title: 'Architectural Planning',
      featureName: 'System Architecture',
      routePath: '/architectural-planning',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'architectural_planning_view.dart',
      implementedComponents: ["Aura HUD","Subsystem Blueprints","Component Dependency Graph","State Management Audit"],
    ),
        'SCREEN_COURSE_ARCHITECT_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_COURSE_ARCHITECT_DASHBOARD',
      title: 'Course Architect Dashboard',
      featureName: 'Education Architecture',
      routePath: '/course-architect-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'course_architect_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Curriculum Builder","Resource Mapping","LMS Integration Monitor"],
    ),
        'SCREEN_DYNAMIC_ROLE_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_DYNAMIC_ROLE_DASHBOARD',
      title: 'Dynamic Role Dashboard',
      featureName: 'RBAC Architecture',
      routePath: '/dynamic-role-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'dynamic_role_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Permission Set Builder","Role Inheritance Map","User Role Audit"],
    ),
        'SCREEN_DYNAMIC_SCREEN_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_DYNAMIC_SCREEN_DASHBOARD',
      title: 'Dynamic Screen Dashboard',
      featureName: 'UI Architecture',
      routePath: '/dynamic-screen-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'dynamic_screen_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Widget Factory HUD","Screen Layout Architect","Style Token Monitor"],
    ),
        'SCREEN_FEATURES_EXPLORER': ScreenMetadata(
      id: 'SCREEN_FEATURES_EXPLORER',
      title: 'Features Explorer',
      featureName: 'Product Architecture',
      routePath: '/features-explorer',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'features_view.dart',
      implementedComponents: ["Aura HUD","Feature Flag Dashboard","Beta Component Catalog","Usage Analytics Heatmap"],
    ),
    'SCREEN_CREATE_USER_FORM': ScreenMetadata(
      id: 'SCREEN_CREATE_USER_FORM',
      title: 'CreateUserForm',
      featureName: 'CreateUserForm',
      routePath: '/admin/create-user',
      office: 'Admin',
      role: 'admin_portal',
      allowedRoles: ['admin_portal'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_PASSWORD_RESET_FORM': ScreenMetadata(
      id: 'SCREEN_PASSWORD_RESET_FORM',
      title: 'PasswordResetForm',
      featureName: 'PasswordResetForm',
      routePath: '/admin/reset-password',
      office: 'Admin',
      role: 'admin_portal',
      allowedRoles: ['admin_portal'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_CREATE_SHIFT_FORM': ScreenMetadata(
      id: 'SCREEN_CREATE_SHIFT_FORM',
      title: 'CreateShiftForm',
      featureName: 'CreateShiftForm',
      routePath: '/admin/create-shift',
      office: 'Admin',
      role: 'manager_portal',
      allowedRoles: ['manager_portal'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_USER_MANAGEMENT': ScreenMetadata(
      id: 'SCREEN_USER_MANAGEMENT',
      title: 'UserManagement',
      featureName: 'UserManagement',
      routePath: '/offices/common/roles/admin/user-management',
      office: 'Admin',
      role: 'Admin',
      allowedRoles: ['Admin', 'CEO'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_ADMIN_LAYOUT': ScreenMetadata(
      id: 'SCREEN_ADMIN_LAYOUT',
      title: 'Admin Layout',
      featureName: 'System Layouts',
      routePath: '/layouts/admin',
      office: 'Infrastructure',
      role: 'System',
      allowedRoles: ['Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'admin_layout_screen.dart',
      implementedComponents: ["Navigation Drawer", "Header", "Content Area"],
    ),
    'SCREEN_AUTH_LAYOUT': ScreenMetadata(
      id: 'SCREEN_AUTH_LAYOUT',
      title: 'Auth Layout',
      featureName: 'System Layouts',
      routePath: '/layouts/auth',
      office: 'Infrastructure',
      role: 'System',
      allowedRoles: ['all'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'auth_layout_screen.dart',
      implementedComponents: ["Branding", "Auth Container"],
    ),
    'SCREEN_AUTH_SPLIT_LAYOUT': ScreenMetadata(
      id: 'SCREEN_AUTH_SPLIT_LAYOUT',
      title: 'Auth Split Layout',
      featureName: 'System Layouts',
      routePath: '/layouts/auth-split',
      office: 'Infrastructure',
      role: 'System',
      allowedRoles: ['all'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'auth_split_layout_screen.dart',
      implementedComponents: ["Split View", "Marketing Image", "Auth Form"],
    ),
    'SCREEN_CLIENT_LAYOUT': ScreenMetadata(
      id: 'SCREEN_CLIENT_LAYOUT',
      title: 'Client Layout',
      featureName: 'System Layouts',
      routePath: '/layouts/client',
      office: 'Infrastructure',
      role: 'System',
      allowedRoles: ['Client'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'client_layout_screen.dart',
      implementedComponents: ["Client Header", "Side Navigation"],
    ),
    'SCREEN_DEMO_LAYOUT_FOOTER': ScreenMetadata(
      id: 'SCREEN_DEMO_LAYOUT_FOOTER',
      title: 'Demo Layout Footer',
      featureName: 'System Layouts',
      routePath: '/layouts/demo-footer',
      office: 'Infrastructure',
      role: 'System',
      allowedRoles: ['all'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'demo_layout_footer_content_screen.dart',
      implementedComponents: ["Footer Content"],
    ),
    'SCREEN_FUSE_LAYOUT': ScreenMetadata(
      id: 'SCREEN_FUSE_LAYOUT',
      title: 'Fuse Core Layout',
      featureName: 'System Layouts',
      routePath: '/layouts/fuse-core',
      office: 'Infrastructure',
      role: 'System',
      allowedRoles: ['Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'fuse_layout_screen.dart',
      implementedComponents: ["Dynamic Layout Engine"],
    ),
    'SCREEN_MASTER_LAYOUT': ScreenMetadata(
      id: 'SCREEN_MASTER_LAYOUT',
      title: 'Master Shell Layout',
      featureName: 'System Layouts',
      routePath: '/layouts/master',
      office: 'Infrastructure',
      role: 'System',
      allowedRoles: ['all'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'master_layout_screen.dart',
      implementedComponents: ["Global Shell"],
    ),
    'SCREEN_PROVIDER_LAYOUT': ScreenMetadata(
      id: 'SCREEN_PROVIDER_LAYOUT',
      title: 'Provider Layout',
      featureName: 'System Layouts',
      routePath: '/layouts/provider',
      office: 'Infrastructure',
      role: 'System',
      allowedRoles: ['Staff'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'provider_layout_screen.dart',
      implementedComponents: ["Provider Header", "Staff Navigation"],
    ),
    'SCREEN_NAVBAR_V2': ScreenMetadata(
      id: 'SCREEN_NAVBAR_V2',
      title: 'Navigation Bar V2',
      featureName: 'System Components',
      routePath: '/components/navbar-v2',
      office: 'Infrastructure',
      role: 'System',
      allowedRoles: ['all'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'navbar_layout2_screen.dart',
      implementedComponents: ["Modern Navbar"],
    ),
    'SCREEN_NAVBAR_V3': ScreenMetadata(
      id: 'SCREEN_NAVBAR_V3',
      title: 'Navigation Bar V3',
      featureName: 'System Components',
      routePath: '/components/navbar-v3',
      office: 'Infrastructure',
      role: 'System',
      allowedRoles: ['all'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'navbar_layout3_screen.dart',
      implementedComponents: ["Minimal Navbar"],
    ),
    'SCREEN_TOOLBAR_V1': ScreenMetadata(
      id: 'SCREEN_TOOLBAR_V1',
      title: 'Action Toolbar V1',
      featureName: 'System Components',
      routePath: '/components/toolbar-v1',
      office: 'Infrastructure',
      role: 'System',
      allowedRoles: ['all'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'toolbar_layout1_screen.dart',
      implementedComponents: ["Standard Toolbar"],
    ),
    'SCREEN_TOOLBAR_V2': ScreenMetadata(
      id: 'SCREEN_TOOLBAR_V2',
      title: 'Action Toolbar V2',
      featureName: 'System Components',
      routePath: '/components/toolbar-v2',
      office: 'Infrastructure',
      role: 'System',
      allowedRoles: ['all'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'toolbar_layout2_screen.dart',
      implementedComponents: ["Compact Toolbar"],
    ),
    'SCREEN_SYSTEM_METRICS': ScreenMetadata(
      id: 'SCREEN_SYSTEM_METRICS',
      title: 'System Performance Metrics',
      featureName: 'System Components',
      routePath: '/components/metrics',
      office: 'Infrastructure',
      role: 'System',
      allowedRoles: ['Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Metrics Dashboard"],
    ),
  };
}
