import '../screen_metadata.dart';

class BusinessDevelopmentRegistryRegistry {
  static const Map<String, ScreenMetadata> screens = {
        'SCREEN_TERRITORY_EXPANSION_MANAGER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_TERRITORY_EXPANSION_MANAGER_DASHBOARD',
      title: 'territory Expansion Manager Dashboard',
      featureName: 'territory Expansion Manager Dashboard',
      routePath: '/territory-expansion-manager-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'territory_expansion_manager_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Expansion Roadmap)","Geographic Vetting Map","Site Viability Scorecard","Research Log"],
    ),
        'SCREEN_REGIONAL_MANAGER_ONTARIO_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_REGIONAL_MANAGER_ONTARIO_DASHBOARD',
      title: 'regional Manager Ontario Dashboard',
      featureName: 'regional Manager Ontario Dashboard',
      routePath: '/regional-manager-ontario-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'regional_manager_ontario_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Ontario Revenue Growth)","Regional Revenue Grid","Ontario Market Heatmap","Site Audit Tracker"],
    ),
        'SCREEN_REGIONAL_MANAGER_USA_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_REGIONAL_MANAGER_USA_DASHBOARD',
      title: 'regional Manager Usa Dashboard',
      featureName: 'regional Manager Usa Dashboard',
      routePath: '/regional-manager-usa-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'regional_manager_usa_dashboard_view.dart',
      implementedComponents: ["Aura HUD (US Expansion Velocity)","Multi-state Revenue Grid","USA Expansion Map","Compliance Drift Log"],
    ),
        'SCREEN_FRANCHISE_SALES_MANAGER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_FRANCHISE_SALES_MANAGER_DASHBOARD',
      title: 'franchise Sales Manager Dashboard',
      featureName: 'franchise Sales Manager Dashboard',
      routePath: '/franchise-sales-manager-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'franchise_sales_manager_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Franchise Sales Funnel)","Sales Funnel Visualization","Candidate Lifecycle Map","CD Pipeline Monitor"],
    ),
        'SCREEN_PARTNERSHIP_MANAGER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_PARTNERSHIP_MANAGER_DASHBOARD',
      title: 'partnership Manager Dashboard',
      featureName: 'partnership Manager Dashboard',
      routePath: '/partnership-manager-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'partnership_manager_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Partner Synergy Matrix)","Partner Referral Grid","Affiliate Performance Table","Synergy DashboardMetrics"],
    ),
        'SCREEN_GENERAL_MANAGER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_GENERAL_MANAGER_DASHBOARD',
      title: 'general Manager Dashboard',
      featureName: 'general Manager Dashboard',
      routePath: '/general-manager-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'general_manager_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Occupancy Trend)","Occupancy Heatmap","Facility Revenue Grid","Resource Utilization"],
    ),
        'SCREEN_BUSINESS_DEVELOPMENT_REGION_DOMAIN_REGIONAL_VIEW_': ScreenMetadata(
      id: 'SCREEN_BUSINESS_DEVELOPMENT_REGION_DOMAIN_REGIONAL_VIEW_',
      title: '/business-development/regional-view',
      featureName: '/business-development/regional-view',
      routePath: '/business-development/regional-view',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Regional Heatmap","Site Compliance Grid","Territory KPI HUD"],
    ),
        'SCREEN_REGIONAL_BDM_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_REGIONAL_BDM_DASHBOARD',
      title: 'Regional BDM Dashboard',
      featureName: 'Regional BDM Dashboard',
      routePath: '/regional-bdm-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'regional_bdm_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Territory Performance Heatmap","BDM Activity Log","Conversion Statistics"],
    ),
  };
}
