import '../screen_metadata.dart';

class ClientPortalRegistryRegistry {
  static const Map<String, ScreenMetadata> screens = {
        'SCREEN_CLIENT_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_CLIENT_DASHBOARD',
      title: 'Client Dashboard',
      featureName: 'Client Dashboard',
      routePath: '/client-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'client_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Health Snapshot","Appointment Calendar","Care Team Messaging"],
    ),
        'SCREEN_FAMILY_MEMBER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_FAMILY_MEMBER_DASHBOARD',
      title: 'Family Member Dashboard',
      featureName: 'Family Member Dashboard',
      routePath: '/family-member-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'family_member_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Care Coordination)","Patient Status Card","Care Log Timeline","Wellness Trend Chart"],
    ),
        'SCREEN_FAMILY_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_FAMILY_DASHBOARD',
      title: 'Family Dashboard',
      featureName: 'Family Dashboard',
      routePath: '/family-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'family_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Household Health Overview","Shared Care Calendar","Family Wellness Score"],
    ),
        'SCREEN_PATIENT_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_PATIENT_DASHBOARD',
      title: 'Patient Dashboard',
      featureName: 'Patient Dashboard',
      routePath: '/patient-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'patient_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Personalized Care Plan","Vitals Log","Medication Adherence"],
    ),
        'SCREEN_CLINIC_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_CLINIC_DASHBOARD',
      title: 'Clinic Dashboard',
      featureName: 'Clinic Dashboard',
      routePath: '/clinic-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'clinic_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Clinic Performance KPIs","Daily Patient Flow","Staffing Levels"],
    ),
        'SCREEN_GUEST_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_GUEST_DASHBOARD',
      title: 'Guest Dashboard',
      featureName: 'Guest Dashboard',
      routePath: '/guest-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'guest_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Welcome Module","Service Explorer","Self-Guided Intake"],
    ),
  };
}
