import '../screen_metadata.dart';

class ClinicalRegistryRegistry {
  static const Map<String, ScreenMetadata> screens = {
        'SCREEN_CLINICAL_DIRECTOR_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_CLINICAL_DIRECTOR_DASHBOARD',
      title: 'clinical Director Dashboard',
      featureName: 'clinical Director Dashboard',
      routePath: '/clinical-director-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'clinical_director_dashboard_view.dart',
      implementedComponents: ["Clinical Safety Score","Staffing Heatmap","Protocol Compliance"],
    ),
        'SCREEN_INTAKE_COORDINATOR_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_INTAKE_COORDINATOR_DASHBOARD',
      title: 'intake Coordinator Dashboard',
      featureName: 'intake Coordinator Dashboard',
      routePath: '/intake-coordinator-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'intake_coordinator_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Total Active Intakes)","Intake Funnel Chart","Urgent Referral List","Capacity Availability Grid"],
    ),
        'SCREEN_NURSE_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_NURSE_DASHBOARD',
      title: 'nurse Dashboard',
      featureName: 'nurse Dashboard',
      routePath: '/nurse-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Critical Alerts)","MAR (Medication Record)","Nurse Assessment Grid"],
    ),
    'SCREEN_RN_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_RN_DASHBOARD',
      title: 'RN Clinical Dashboard',
      featureName: 'RN Core Dashboard',
      routePath: '/offices/clinical/roles/rn/dashboard',
      office: 'Clinical',
      role: 'RN',
      allowedRoles: ['RN', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/rn_dashboard_v4',
      generationPrompt: 'PrimeCare V4: RN Clinical Dashboard with patient acuity heatmaps, MAR reconciliation, and supervisor alerts.',
      generateScreen: true,
      implementedComponents: ["Aura HUD","MAR Reconciliation","Clinical Acuity Heatmap","Wound Care Module"],
    ),
    'SCREEN_RN_ASSESSMENTS': ScreenMetadata(
      id: 'SCREEN_RN_ASSESSMENTS',
      title: 'Clinical Assessments',
      featureName: 'RN Assessment Hub',
      routePath: '/offices/clinical/roles/rn/assessments',
      office: 'Clinical',
      role: 'RN',
      allowedRoles: ['RN', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/rn_assessments_v4',
      generationPrompt: 'PrimeCare V4: RN Clinical Assessment Hub for OASIS and interRAI assessments with dynamic scoring.',
      generateScreen: true,
      implementedComponents: ["Bento Assessment Hub","Dynamic Scoring Engine","Validation Summary"],
    ),
    'SCREEN_RN_CARE_PLANS': ScreenMetadata(
      id: 'SCREEN_RN_CARE_PLANS',
      title: 'Care Plan Builder',
      featureName: 'RN Care Planning',
      routePath: '/offices/clinical/roles/rn/care-plans',
      office: 'Clinical',
      role: 'RN',
      allowedRoles: ['RN', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/rn_care_plans_v4',
      generationPrompt: 'PrimeCare V4: RN Care Plan Builder with goal tracking, intervention library, and multi-disciplinary sign-off.',
      generateScreen: true,
      implementedComponents: ["Care Plan Builder","Intervention Library","Goal Status Tracker"],
    ),
        'SCREEN_THERAPIST_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_THERAPIST_DASHBOARD',
      title: 'therapist Dashboard',
      featureName: 'therapist Dashboard',
      routePath: '/therapist-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Treatment Velocity)","Patient Anatomy Map","SOAP Note Builder","Treatment Plan View"],
    ),
        'SCREEN_PSW_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_PSW_DASHBOARD',
      title: 'PSW Dashboard',
      featureName: 'PSW Core Dashboard',
      routePath: '/offices/clinical/roles/psw/dashboard',
      office: 'Clinical',
      role: 'PSW',
      allowedRoles: ['PSW', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/ab4a8ebeee494490a72d07965f220682',
      generationPrompt: 'PrimeCare V4: PSW Dashboard featuring clinical summary, care plan checklist, incident reporting, and real-time operations feed.',
      generateScreen: true,
      implementedComponents: ["Aura HUD","Clinical Summary","Care Plan Checklist","Incident Quick-Report","Interactive Route Logistics"],
    ),
    'SCREEN_PSW_SHIFT_TRACKER': ScreenMetadata(
      id: 'SCREEN_PSW_SHIFT_TRACKER',
      title: 'Shift Tracker',
      featureName: 'PSW Shift Tracking',
      routePath: '/offices/clinical/roles/psw/shift-tracker',
      office: 'Clinical',
      role: 'PSW',
      allowedRoles: ['PSW', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/83307567039943f69482701e8da54a43',
      generationPrompt: 'PrimeCare V4: PSW Shift Tracker with clock-in/out, GPS-verified visit logging, and shift duration analytics.',
      generateScreen: true,
      implementedComponents: ["Time Clock Widget","Visit Log List","GPS Validation Feed","Interactive Route Logistics"],
    ),
    'SCREEN_PSW_CLIENTS': ScreenMetadata(
      id: 'SCREEN_PSW_CLIENTS',
      title: 'Client List',
      featureName: 'PSW Client Management',
      routePath: '/offices/clinical/roles/psw/clients',
      office: 'Clinical',
      role: 'PSW',
      allowedRoles: ['PSW', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/e43940428e214d06a090e8f6e2168340',
      generationPrompt: 'PrimeCare V4: PSW Client List with active patient profiles, care requirements, and quick-access emergency contacts.',
      generateScreen: true,
      implementedComponents: ["Client Directory Card","Risk Status Indicator","Emergency Contact Hub","Interactive Route Logistics"],
    ),
    'SCREEN_PSW_TASKS': ScreenMetadata(
      id: 'SCREEN_PSW_TASKS',
      title: 'Task Checklist',
      featureName: 'PSW Care Plan Tasks',
      routePath: '/offices/clinical/roles/psw/tasks',
      office: 'Clinical',
      role: 'PSW',
      allowedRoles: ['PSW', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/b00192e2126f43e5a593368297762694',
      generationPrompt: 'PrimeCare V4: PSW Daily Task Checklist with medication alerts, meal prep tracking, and task completion metrics.',
      generateScreen: true,
      implementedComponents: ["Medication Task Group","Meal Prep Log","ADL Completion Status"],
    ),
    'SCREEN_PSW_MESSAGES': ScreenMetadata(
      id: 'SCREEN_PSW_MESSAGES',
      title: 'Secure Messaging',
      featureName: 'PSW Communications',
      routePath: '/offices/clinical/roles/psw/messages',
      office: 'Clinical',
      role: 'PSW',
      allowedRoles: ['PSW', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/e73998b31a314b988f00038891392683',
      generationPrompt: 'PrimeCare V4: PSW Secure Messaging portal for team coordination and clinical supervisor consultations.',
      generateScreen: true,
      implementedComponents: ["Clinical Chat Thread","Supervisor Direct Link","Attachment Manager"],
    ),
    'SCREEN_PSW_VISIT_NOTES': ScreenMetadata(
      id: 'SCREEN_PSW_VISIT_NOTES',
      title: 'Visit Reporting',
      featureName: 'PSW Visit Documentation',
      routePath: '/offices/clinical/roles/psw/visit-notes',
      office: 'Clinical',
      role: 'PSW',
      allowedRoles: ['PSW', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/a49285098e9b41a39626388471168294',
      generationPrompt: 'PrimeCare V4: PSW Visit Notes interface with voice-to-text reporting, wound photo uploads, and family communication logging.',
      generateScreen: true,
      implementedComponents: ["Narrative Note Editor","Wound Imaging Module","Family Connect Log","Interactive Route Logistics"],
    ),
        'SCREEN_SOCIAL_WORKER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_SOCIAL_WORKER_DASHBOARD',
      title: 'Social Worker Dashboard',
      featureName: 'Social Work Clinical Hub',
      routePath: '/offices/clinical/roles/sw/dashboard',
      office: 'Clinical',
      role: 'SW',
      allowedRoles: ['SW', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/sw_dashboard_v4',
      generationPrompt: 'PrimeCare V4: Social Worker Dashboard with crisis response monitoring, psychosocial logs, and community resource mapping.',
      generateScreen: true,
      implementedComponents: ["Aura HUD (Crisis Response Time)","Psychosocial Observation Log","Resource Mapping Tool","Intervention Tracker"],
    ),
    'SCREEN_CHIROPRACTOR_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_CHIROPRACTOR_DASHBOARD',
      title: 'Chiropractor Dashboard',
      featureName: 'Chiropractor Clinical Hub',
      routePath: '/offices/clinical/roles/chiro/dashboard',
      office: 'Clinical',
      role: 'CHIRO',
      allowedRoles: ['CHIRO', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/chiro_dashboard_v4',
      generationPrompt: 'PrimeCare V4: Chiropractor Dashboard with spinal health tracking, adjustment protocol logs, and DICOM imaging integration.',
      generateScreen: true,
      implementedComponents: ["Aura HUD","Patient Spine Health Tracker","Adjustment Protocol Log","Imaging View"],
    ),
    'SCREEN_PHYSIOTHERAPIST_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_PHYSIOTHERAPIST_DASHBOARD',
      title: 'Physiotherapist Dashboard',
      featureName: 'PT Clinical Hub',
      routePath: '/offices/clinical/roles/pt/dashboard',
      office: 'Clinical',
      role: 'PT',
      allowedRoles: ['PT', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/pt_dashboard_v4',
      generationPrompt: 'PrimeCare V4: Physiotherapist Dashboard with mobility progress charts, treatment session timers, and rehab plan builders.',
      generateScreen: true,
      implementedComponents: ["Aura HUD","Mobility Progress Chart","Treatment Session Timer","Rehab Plan Builder"],
    ),
        'SCREEN_INFECTION_CONTROL_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_INFECTION_CONTROL_DASHBOARD',
      title: 'infection Control Dashboard',
      featureName: 'infection Control Dashboard',
      routePath: '/infection-control-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'infection_control_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Infection Velocity)","Transmission Trend","Outbreak Monitoring Grid","Immunization Tracker"],
    ),
        'SCREEN_CUSTOMER_SUPPORT_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_CUSTOMER_SUPPORT_DASHBOARD',
      title: 'customer Support Dashboard',
      featureName: 'customer Support Dashboard',
      routePath: '/customer-support-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'customer_support_dashboard_view.dart',
      implementedComponents: ["Aura HUD (MTTR)","Live Ticket Queue","SLA Performance Grid","Customer Sentiment Hub"],
    ),
        'SCREEN_SUPPORT_INTAKE_COORDINATOR_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_SUPPORT_INTAKE_COORDINATOR_DASHBOARD',
      title: 'support Intake Coordinator Dashboard',
      featureName: 'support Intake Coordinator Dashboard',
      routePath: '/support-intake-coordinator-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Intake Velocity)","Referral Pipeline","Payer Verification","Coordination Log"],
    ),
        'SCREEN_QUALITY_ASSURANCE_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_QUALITY_ASSURANCE_DASHBOARD',
      title: 'quality Assurance Dashboard',
      featureName: 'quality Assurance Dashboard',
      routePath: '/quality-assurance-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'quality_assurance_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Compliance Drift)","Medication Safety Log","Incident Trend Analysis","Compliance Audit Grid"],
    ),
        'SCREEN_INTAKE_COORDINATOR_REFERRALS': ScreenMetadata(
      id: 'SCREEN_INTAKE_COORDINATOR_REFERRALS',
      title: 'intake Coordinator Referrals',
      featureName: 'intake Coordinator Referrals',
      routePath: '/intake-coordinator-referrals',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Conversion Rate %)","Referral Source Grid","Lead Prioritization List","Inquiry Log"],
    ),
        'SCREEN_INTAKE_COORDINATOR_ASSESSMENTS': ScreenMetadata(
      id: 'SCREEN_INTAKE_COORDINATOR_ASSESSMENTS',
      title: 'intake Coordinator Assessments',
      featureName: 'intake Coordinator Assessments',
      routePath: '/intake-coordinator-assessments',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Intake Time)","Smart Intake Form","Document Verification Status","Risk Triage Indicator"],
    ),
        'SCREEN_CLINICAL_DIRECTOR_QUALITY_METRICS': ScreenMetadata(
      id: 'SCREEN_CLINICAL_DIRECTOR_QUALITY_METRICS',
      title: 'clinical Director Quality Metrics',
      featureName: 'clinical Director Quality Metrics',
      routePath: '/clinical-director-quality-metrics',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Outcome Variance Chart","Sentinel Event Log","Best-Practice Audit"],
    ),
        'SCREEN_SCHEDULER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_SCHEDULER_DASHBOARD',
      title: 'scheduler Dashboard',
      featureName: 'scheduler Dashboard',
      routePath: '/scheduler-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'scheduler_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Shift Coverage)","Scheduling Stat Grid","Shift Coordination Calendar","Urgent Coverage List"],
    ),
        'SCREEN_BILLING_ADMIN_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_BILLING_ADMIN_DASHBOARD',
      title: 'billing Admin Dashboard',
      featureName: 'billing Admin Dashboard',
      routePath: '/billing-admin-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'billing_admin_dashboard_view.dart',
      implementedComponents: ["Aura HUD (AR Velocity)","Billing Stat Grid","Pending Claims Ledger","Collection Status Chart"],
    ),
        'SCREEN_HR_HIRING_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_HR_HIRING_DASHBOARD',
      title: 'hr Hiring Dashboard',
      featureName: 'hr Hiring Dashboard',
      routePath: '/hr-hiring-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'hr_hiring_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Candidate Pipeline","Onboarding Checklist","Recruitment KPI Grid"],
    ),
        'SCREEN_OFFICES_ROLES_PATIENT_DASHBOARD_': ScreenMetadata(
      id: 'SCREEN_OFFICES_ROLES_PATIENT_DASHBOARD_',
      title: '/offices/roles/patient/dashboard',
      featureName: '/offices/roles/patient/dashboard',
      routePath: '/offices/roles/patient/dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Wellness Score)","Action Hub","Care Plan Progress","Vitals Telemetry"],
    ),
        'SCREEN_OFFICES_ROLES_PARTNERSHIP_MANAGER_DASHBOARD_': ScreenMetadata(
      id: 'SCREEN_OFFICES_ROLES_PARTNERSHIP_MANAGER_DASHBOARD_',
      title: '/offices/roles/partnership_manager/dashboard',
      featureName: '/offices/roles/partnership_manager/dashboard',
      routePath: '/offices/roles/partnership_manager/dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Partnership Health)","Contract Lifecycle Grid","Revenue Share Analytics","Referral Network Map"],
    ),
        'SCREEN_OFFICES_ROLES_OWNER_DASHBOARD_': ScreenMetadata(
      id: 'SCREEN_OFFICES_ROLES_OWNER_DASHBOARD_',
      title: '/offices/roles/owner/dashboard',
      featureName: '/offices/roles/owner/dashboard',
      routePath: '/offices/roles/owner/dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Enterprise Valuation)","Portfolio Performance Grid","Strategic Growth Insights","Global Risk Assessment"],
    ),
        'SCREEN_OFFICES_ROLES_FRANCHISE_OWNER_DASHBOARD_': ScreenMetadata(
      id: 'SCREEN_OFFICES_ROLES_FRANCHISE_OWNER_DASHBOARD_',
      title: '/offices/roles/franchise_owner/dashboard',
      featureName: '/offices/roles/franchise_owner/dashboard',
      routePath: '/offices/roles/franchise_owner/dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Unit Profitability)","Operational Health Grid","Staffing Utilization","Revenue Projections"],
    ),
        'SCREEN_OFFICES_ROLES_LOCAL_MARKETING_MANAGER_DASHBOARD_': ScreenMetadata(
      id: 'SCREEN_OFFICES_ROLES_LOCAL_MARKETING_MANAGER_DASHBOARD_',
      title: '/offices/roles/local_marketing_manager/dashboard',
      featureName: '/offices/roles/local_marketing_manager/dashboard',
      routePath: '/offices/roles/local_marketing_manager/dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Lead Velocity)","Campaign Performance Grid","Referral Source Tracking","Outreach Event Calendar"],
    ),
        'SCREEN_RMT_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_RMT_DASHBOARD',
      title: 'RMT Dashboard',
      featureName: 'RMT Clinical Hub',
      routePath: '/offices/clinical/roles/rmt/dashboard',
      office: 'Clinical',
      role: 'RMT',
      allowedRoles: ['RMT', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/rmt_dashboard_v4',
      generationPrompt: 'PrimeCare V4: RMT Dashboard with therapeutic goal tracking, client trigger point mapping, and session log history.',
      generateScreen: true,
      implementedComponents: ["Aura HUD","Massage Session Log","Client Trigger Point Map","Therapeutic Goal Tracker"],
    ),
        'SCREEN_RPN_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_RPN_DASHBOARD',
      title: 'RPN Dashboard',
      featureName: 'RPN Clinical Hub',
      routePath: '/offices/clinical/roles/rpn/dashboard',
      office: 'Clinical',
      role: 'RPN',
      allowedRoles: ['RPN', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/rpn_dashboard_v4',
      generationPrompt: 'PrimeCare V4: RPN Dashboard with real-time vitals monitoring, medication queues, and shift handover automation.',
      generateScreen: true,
      implementedComponents: ["Aura HUD","Vitals Monitor","Medication Queue","Shift Handover Notes"],
    ),
        'SCREEN_VOLUNTEER_COORDINATOR_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_VOLUNTEER_COORDINATOR_DASHBOARD',
      title: 'Volunteer Coordinator Dashboard',
      featureName: 'Volunteer Coordinator Dashboard',
      routePath: '/volunteer-coordinator-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'volunteer_coordinator_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Volunteer Roster","Impact Heatmap","Orientation Progress"],
    ),
        'SCREEN_QA_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_QA_DASHBOARD',
      title: 'Quality Assurance Dashboard',
      featureName: 'Quality Assurance Dashboard',
      routePath: '/qa-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'qa_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Drift Score)","Registry Parity Monitor","Blueprint Compliance Audit","Remediation Queue"],
    ),
        'SCREEN_TRAINING_DIRECTOR_CERTIFICATE_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_TRAINING_DIRECTOR_CERTIFICATE_DASHBOARD',
      title: 'Training Director Certificate Dashboard',
      featureName: 'Training Administration',
      routePath: '/training-director-certificate-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'training_director_certificate_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Certificate Issuance Hook","Validator Credentialing","Audit Trail"],
    ),
        'SCREEN_TRAINING_COORDINATOR_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_TRAINING_COORDINATOR_DASHBOARD',
      title: 'Training Coordinator Dashboard',
      featureName: 'Training Coordination',
      routePath: '/training-coordinator-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'training_coordinator_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Session Scheduling Grid","Attendee Tracking","Material Management"],
    ),
        'SCREEN_TRAINING_HUB': ScreenMetadata(
      id: 'SCREEN_TRAINING_HUB',
      title: 'Training Hub Dashboard',
      featureName: 'Training Hub',
      routePath: '/training-hub-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'training_hub_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Learning Management UI","Course Progression Heatmap","Resource Library"],
    ),



  };
}
