import '../screen_metadata.dart';

class ClinicalRegistryRegistry {
  static const Map<String, ScreenMetadata> screens = {
        'SCREEN_CLINICAL_DIRECTOR_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_CLINICAL_DIRECTOR_DASHBOARD',
      title: 'clinical Director Dashboard',
      featureName: 'clinical Director Dashboard',
      routePath: '/clinical-director-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'clinical_director_dashboard_view.dart',
      implementedComponents: ["Clinical Safety Score","Staffing Heatmap","Protocol Compliance"],
    ),
        'SCREEN_INTAKE_COORDINATOR_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_INTAKE_COORDINATOR_DASHBOARD',
      title: 'intake Coordinator Dashboard',
      featureName: 'intake Coordinator Dashboard',
      routePath: '/intake-coordinator-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'intake_coordinator_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Total Active Intakes)","Intake Funnel Chart","Urgent Referral List","Capacity Availability Grid"],
    ),
        'SCREEN_NURSE_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_NURSE_DASHBOARD',
      title: 'nurse Dashboard',
      featureName: 'nurse Dashboard',
      routePath: '/nurse-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Critical Alerts)","MAR (Medication Record)","Nurse Assessment Grid"],
    ),
        'SCREEN_RN_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_RN_DASHBOARD',
      title: 'rn Dashboard',
      featureName: 'rn Dashboard',
      routePath: '/rn-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'rn_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Medication Administration Record","Wound Care Module"],
    ),
        'SCREEN_THERAPIST_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_THERAPIST_DASHBOARD',
      title: 'therapist Dashboard',
      featureName: 'therapist Dashboard',
      routePath: '/therapist-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Treatment Velocity)","Patient Anatomy Map","SOAP Note Builder","Treatment Plan View"],
    ),
        'SCREEN_PSW_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_PSW_DASHBOARD',
      title: 'psw Dashboard',
      featureName: 'psw Dashboard',
      routePath: '/psw-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'psw_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Clinical Summary","Care Plan Checklist","Incident Quick-Report"],
    ),
        'SCREEN_SOCIAL_WORKER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_SOCIAL_WORKER_DASHBOARD',
      title: 'social Worker Dashboard',
      featureName: 'social Worker Dashboard',
      routePath: '/social-worker-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'social_worker_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Crisis Response Time)","Psychosocial Observation Log","Resource Mapping Tool","Intervention Tracker"],
    ),
    'SCREEN_CHIROPRACTOR_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_CHIROPRACTOR_DASHBOARD',
      title: 'Chiropractor Dashboard',
      featureName: 'Chiropractor Dashboard',
      routePath: '/chiropractor-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'chiropractor_view.dart',
      implementedComponents: ["Aura HUD","Patient Spine Health Tracker","Adjustment Protocol Log","Imaging View"],
    ),
    'SCREEN_PHYSIOTHERAPIST_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_PHYSIOTHERAPIST_DASHBOARD',
      title: 'Physiotherapist Dashboard',
      featureName: 'Physiotherapist Dashboard',
      routePath: '/physiotherapist-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'physiotherapist_view.dart',
      implementedComponents: ["Aura HUD","Mobility Progress Chart","Treatment Session Timer","Rehab Plan Builder"],
    ),
        'SCREEN_INFECTION_CONTROL_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_INFECTION_CONTROL_DASHBOARD',
      title: 'infection Control Dashboard',
      featureName: 'infection Control Dashboard',
      routePath: '/infection-control-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'infection_control_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Infection Velocity)","Transmission Trend","Outbreak Monitoring Grid","Immunization Tracker"],
    ),
        'SCREEN_CUSTOMER_SUPPORT_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_CUSTOMER_SUPPORT_DASHBOARD',
      title: 'customer Support Dashboard',
      featureName: 'customer Support Dashboard',
      routePath: '/customer-support-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'customer_support_dashboard_view.dart',
      implementedComponents: ["Aura HUD (MTTR)","Live Ticket Queue","SLA Performance Grid","Customer Sentiment Hub"],
    ),
        'SCREEN_SUPPORT_INTAKE_COORDINATOR_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_SUPPORT_INTAKE_COORDINATOR_DASHBOARD',
      title: 'support Intake Coordinator Dashboard',
      featureName: 'support Intake Coordinator Dashboard',
      routePath: '/support-intake-coordinator-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Intake Velocity)","Referral Pipeline","Payer Verification","Coordination Log"],
    ),
        'SCREEN_QUALITY_ASSURANCE_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_QUALITY_ASSURANCE_DASHBOARD',
      title: 'quality Assurance Dashboard',
      featureName: 'quality Assurance Dashboard',
      routePath: '/quality-assurance-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'quality_assurance_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Compliance Drift)","Medication Safety Log","Incident Trend Analysis","Compliance Audit Grid"],
    ),
        'SCREEN_INTAKE_COORDINATOR_REFERRALS': ScreenMetadata(
      id: 'SCREEN_INTAKE_COORDINATOR_REFERRALS',
      title: 'intake Coordinator Referrals',
      featureName: 'intake Coordinator Referrals',
      routePath: '/intake-coordinator-referrals',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Conversion Rate %)","Referral Source Grid","Lead Prioritization List","Inquiry Log"],
    ),
        'SCREEN_INTAKE_COORDINATOR_ASSESSMENTS': ScreenMetadata(
      id: 'SCREEN_INTAKE_COORDINATOR_ASSESSMENTS',
      title: 'intake Coordinator Assessments',
      featureName: 'intake Coordinator Assessments',
      routePath: '/intake-coordinator-assessments',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Intake Time)","Smart Intake Form","Document Verification Status","Risk Triage Indicator"],
    ),
        'SCREEN_CLINICAL_DIRECTOR_QUALITY_METRICS': ScreenMetadata(
      id: 'SCREEN_CLINICAL_DIRECTOR_QUALITY_METRICS',
      title: 'clinical Director Quality Metrics',
      featureName: 'clinical Director Quality Metrics',
      routePath: '/clinical-director-quality-metrics',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Outcome Variance Chart","Sentinel Event Log","Best-Practice Audit"],
    ),
        'SCREEN_SCHEDULER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_SCHEDULER_DASHBOARD',
      title: 'scheduler Dashboard',
      featureName: 'scheduler Dashboard',
      routePath: '/scheduler-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'scheduler_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Shift Coverage)","Scheduling Stat Grid","Shift Coordination Calendar","Urgent Coverage List"],
    ),
        'SCREEN_BILLING_ADMIN_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_BILLING_ADMIN_DASHBOARD',
      title: 'billing Admin Dashboard',
      featureName: 'billing Admin Dashboard',
      routePath: '/billing-admin-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'billing_admin_dashboard_view.dart',
      implementedComponents: ["Aura HUD (AR Velocity)","Billing Stat Grid","Pending Claims Ledger","Collection Status Chart"],
    ),
        'SCREEN_HR_HIRING_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_HR_HIRING_DASHBOARD',
      title: 'hr Hiring Dashboard',
      featureName: 'hr Hiring Dashboard',
      routePath: '/hr-hiring-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'hr_hiring_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Candidate Pipeline","Onboarding Checklist","Recruitment KPI Grid"],
    ),
        'SCREEN_OFFICES_ROLES_PATIENT_DASHBOARD_': ScreenMetadata(
      id: 'SCREEN_OFFICES_ROLES_PATIENT_DASHBOARD_',
      title: '/offices/roles/patient/dashboard',
      featureName: '/offices/roles/patient/dashboard',
      routePath: '/offices/roles/patient/dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Wellness Score)","Action Hub","Care Plan Progress","Vitals Telemetry"],
    ),
        'SCREEN_OFFICES_ROLES_PARTNERSHIP_MANAGER_DASHBOARD_': ScreenMetadata(
      id: 'SCREEN_OFFICES_ROLES_PARTNERSHIP_MANAGER_DASHBOARD_',
      title: '/offices/roles/partnership_manager/dashboard',
      featureName: '/offices/roles/partnership_manager/dashboard',
      routePath: '/offices/roles/partnership_manager/dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Partnership Health)","Contract Lifecycle Grid","Revenue Share Analytics","Referral Network Map"],
    ),
        'SCREEN_OFFICES_ROLES_OWNER_DASHBOARD_': ScreenMetadata(
      id: 'SCREEN_OFFICES_ROLES_OWNER_DASHBOARD_',
      title: '/offices/roles/owner/dashboard',
      featureName: '/offices/roles/owner/dashboard',
      routePath: '/offices/roles/owner/dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Enterprise Valuation)","Portfolio Performance Grid","Strategic Growth Insights","Global Risk Assessment"],
    ),
        'SCREEN_OFFICES_ROLES_FRANCHISE_OWNER_DASHBOARD_': ScreenMetadata(
      id: 'SCREEN_OFFICES_ROLES_FRANCHISE_OWNER_DASHBOARD_',
      title: '/offices/roles/franchise_owner/dashboard',
      featureName: '/offices/roles/franchise_owner/dashboard',
      routePath: '/offices/roles/franchise_owner/dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Unit Profitability)","Operational Health Grid","Staffing Utilization","Revenue Projections"],
    ),
        'SCREEN_OFFICES_ROLES_LOCAL_MARKETING_MANAGER_DASHBOARD_': ScreenMetadata(
      id: 'SCREEN_OFFICES_ROLES_LOCAL_MARKETING_MANAGER_DASHBOARD_',
      title: '/offices/roles/local_marketing_manager/dashboard',
      featureName: '/offices/roles/local_marketing_manager/dashboard',
      routePath: '/offices/roles/local_marketing_manager/dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Lead Velocity)","Campaign Performance Grid","Referral Source Tracking","Outreach Event Calendar"],
    ),
        'SCREEN_RMT_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_RMT_DASHBOARD',
      title: 'RMT Dashboard',
      featureName: 'RMT Dashboard',
      routePath: '/rmt-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'rmt_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Massage Session Log","Client Trigger Point Map","Therapeutic Goal Tracker"],
    ),
        'SCREEN_RPN_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_RPN_DASHBOARD',
      title: 'RPN Dashboard',
      featureName: 'RPN Dashboard',
      routePath: '/rpn-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'rpn_view.dart',
      implementedComponents: ["Aura HUD","Vitals Monitor","Medication Queue","Shift Handover Notes"],
    ),
        'SCREEN_VOLUNTEER_COORDINATOR_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_VOLUNTEER_COORDINATOR_DASHBOARD',
      title: 'Volunteer Coordinator Dashboard',
      featureName: 'Volunteer Coordinator Dashboard',
      routePath: '/volunteer-coordinator-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'volunteer_coordinator_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Volunteer Roster","Impact Heatmap","Orientation Progress"],
    ),
        'SCREEN_QA_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_QA_DASHBOARD',
      title: 'Quality Assurance Dashboard',
      featureName: 'Quality Assurance Dashboard',
      routePath: '/qa-dashboard',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'qa_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Drift Score)","Registry Parity Monitor","Blueprint Compliance Audit","Remediation Queue"],
    ),
        'SCREEN_TRAINING_DIRECTOR_CERTIFICATE_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_TRAINING_DIRECTOR_CERTIFICATE_DASHBOARD',
      title: 'Training Director Certificate Dashboard',
      featureName: 'Training Administration',
      routePath: '/training-director-certificate-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'training_director_certificate_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Certificate Issuance Hook","Validator Credentialing","Audit Trail"],
    ),
        'SCREEN_TRAINING_COORDINATOR_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_TRAINING_COORDINATOR_DASHBOARD',
      title: 'Training Coordinator Dashboard',
      featureName: 'Training Coordination',
      routePath: '/training-coordinator-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'training_coordinator_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Session Scheduling Grid","Attendee Tracking","Material Management"],
    ),
        'SCREEN_TRAINING_HUB': ScreenMetadata(
      id: 'SCREEN_TRAINING_HUB',
      title: 'Training Hub Dashboard',
      featureName: 'Training Hub',
      routePath: '/training-hub-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'training_hub_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Learning Management UI","Course Progression Heatmap","Resource Library"],
    ),
    'SCREEN_CLINICAL_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_CLINICAL_DASHBOARD',
      title: 'ClinicalDashboard',
      featureName: 'ClinicalDashboard',
      routePath: '/generated/clinic-dashboard',
      office: 'Clinical',
      role: 'PSW',
      allowedRoles: ['PSW'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_CLINICAL_DIRECTOR_LABELS': ScreenMetadata(
      id: 'SCREEN_CLINICAL_DIRECTOR_LABELS',
      title: 'clinical_director_labels',
      featureName: 'clinical_director_labels',
      routePath: '/legacy/clinical_director_labels',
      office: 'Clinical',
      role: 'Guest',
      allowedRoles: ['Guest'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_CLINICAL_LABELS': ScreenMetadata(
      id: 'SCREEN_CLINICAL_LABELS',
      title: 'clinical_labels',
      featureName: 'clinical_labels',
      routePath: '/legacy/clinical_labels',
      office: 'Clinical',
      role: 'Guest',
      allowedRoles: ['Guest'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
  };
}
