import '../screen_metadata.dart';

class CorporateRegistryRegistry {
  static const Map<String, ScreenMetadata> screens = {
        'SCREEN_CEO_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_CEO_DASHBOARD',
      title: 'ceo Dashboard',
      featureName: 'ceo Dashboard',
      routePath: '/ceo-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'ceo_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Global KPI DashboardMetrics","Region Comparison","Strategic Initiatives"],
    ),
        'SCREEN_COO_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_COO_DASHBOARD',
      title: 'coo Dashboard',
      featureName: 'coo Dashboard',
      routePath: '/coo-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'coo_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Operational KPI Grid","Branch Efficiency Table","Service Quality Log"],
    ),
        'SCREEN_CFO_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_CFO_DASHBOARD',
      title: 'cfo Dashboard',
      featureName: 'cfo Dashboard',
      routePath: '/cfo-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'cfo_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Liquidity Index","Burn Rate Analysis","Capital Allocation"],
    ),
        'SCREEN_COMPLIANCE_MANAGER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_COMPLIANCE_MANAGER_DASHBOARD',
      title: 'compliance Manager Dashboard',
      featureName: 'compliance Manager Dashboard',
      routePath: '/compliance-manager-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'compliance_manager_view.dart',
      implementedComponents: ["Aura HUD","DashboardRegistry Integrity Score","Anomaly Heatmap","Execution Gate Logs"],
    ),
        'SCREEN_TRAINING_DIRECTOR_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_TRAINING_DIRECTOR_DASHBOARD',
      title: 'training Director Dashboard',
      featureName: 'training Director Dashboard',
      routePath: '/training-director-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'training_director_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Certification Heatmap","Active Course Enrollment","Competency Drift Alert"],
    ),
        'SCREEN_FINANCE_DIRECTOR_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_FINANCE_DIRECTOR_DASHBOARD',
      title: 'finance Director Dashboard',
      featureName: 'finance Director Dashboard',
      routePath: '/finance-director-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'finance_director_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Financial Summary Grid","Cash Flow Forecast","Budget Distribution"],
    ),
        'SCREEN_HEAD_OF_BUS_DEV_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_HEAD_OF_BUS_DEV_DASHBOARD',
      title: 'head Of Bus Dev Dashboard',
      featureName: 'head Of Bus Dev Dashboard',
      routePath: '/head-of-bus-dev-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'head_of_bus_dev_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Pipeline Velocity)","Pipeline Velocity Chart","Expansion Roadmap Heatmap","Partner Synergy Matrix"],
    ),
        'SCREEN_HEAD_OF_MARKETING_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_HEAD_OF_MARKETING_DASHBOARD',
      title: 'head Of Marketing Dashboard',
      featureName: 'head Of Marketing Dashboard',
      routePath: '/head-of-marketing-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'head_of_marketing_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Campaign Heatmap","Funnel Grid","Brand Awareness"],
    ),
        'SCREEN_HR_MANAGER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_HR_MANAGER_DASHBOARD',
      title: 'hr Manager Dashboard',
      featureName: 'hr Manager Dashboard',
      routePath: '/hr-manager-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'hr_manager_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Operational DashboardMetrics","HR Action Hub","Staffing Velocity","Compliance Audit"],
    ),
        'SCREEN_HR_HIRING_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_HR_HIRING_DASHBOARD',
      title: 'hr Hiring Dashboard',
      featureName: 'hr Hiring Dashboard',
      routePath: '/hr-hiring-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'hr_hiring_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Candidate Pipeline","Onboarding Checklist","Recruitment KPI Grid"],
    ),
        'SCREEN_HR_DIRECTOR_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_HR_DIRECTOR_DASHBOARD',
      title: 'hr Director Dashboard',
      featureName: 'hr Director Dashboard',
      routePath: '/hr-director-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'hr_director_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Talent Retention)","Succession Planning","Workforce Diversity","Global Compensation"],
    ),
        'SCREEN_CX_DIRECTOR_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_CX_DIRECTOR_DASHBOARD',
      title: 'cx Director Dashboard',
      featureName: 'cx Director Dashboard',
      routePath: '/cx-director-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'cx_director_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Experience Velocity)","Sentiment Scorecard","Retention Analysis","Customer Journey Drift"],
    ),
        'SCREEN_IT_ADMIN_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_IT_ADMIN_DASHBOARD',
      title: 'it Admin Dashboard',
      featureName: 'it Admin Dashboard',
      routePath: '/it-admin-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (System Uptime)","Resource Allocation","Maintenance Queue","System Logs"],
    ),

        'SCREEN_SHAREHOLDER_INTELLIGENCE_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_SHAREHOLDER_INTELLIGENCE_DASHBOARD',
      title: 'shareholder Intelligence Dashboard',
      featureName: 'shareholder Intelligence Dashboard',
      routePath: '/shareholder-intelligence-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'shareholder_intelligence_view.dart',
      implementedComponents: ["Aura HUD","Global Header","Stage 1: Initial","Stage 2: In Processing","Stage 3: Implemented","Stage 4: Tested & Done","Telemetry Table"],
    ),
        'SCREEN_CORPORATE_GOVERNANCE_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_CORPORATE_GOVERNANCE_DASHBOARD',
      title: 'Corporate Governance Dashboard',
      featureName: 'Corporate Governance Dashboard',
      routePath: '/corporate-governance-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'corporate_governance_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Subsystem Parity Matrix","Autonomous Remediation HUD","Audit Lifecycle Monitor"],
    ),
        'SCREEN_CTO_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_CTO_DASHBOARD',
      title: 'CTO Dashboard',
      featureName: 'CTO Dashboard',
      routePath: '/cto-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'cto_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Cloudflare Stack Health","API Gateway Performance","CI/CD Pipeline Velocity"],
    ),
        'SCREEN_OWNER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_OWNER_DASHBOARD',
      title: 'Owner Dashboard',
      featureName: 'Owner Dashboard',
      routePath: '/owner-dashboard',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'owner_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Portfolio Yield","Equity Growth Heatmap","Strategic Risk Matrix"],
    ),
        'SCREEN_FINANCE_LEDGER': ScreenMetadata(
      id: 'SCREEN_FINANCE_LEDGER',
      title: 'Finance Ledger Dashboard',
      featureName: 'Double-Entry Finance',
      routePath: '/finance-ledger',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'finance_ledger_1_view.dart',
      implementedComponents: ["Aura HUD","Double-Entry Balance Sheet","Journal Entry Grid","Cash Flow Forecast"],
    ),
    'SCREEN_ENTERPRISE_OVERVIEW': ScreenMetadata(
      id: 'SCREEN_ENTERPRISE_OVERVIEW',
      title: 'EnterpriseOverview',
      featureName: 'EnterpriseOverview',
      routePath: '/offices/corporate/roles/ceo/enterprise-overview',
      office: 'Corporate',
      role: 'CEO',
      allowedRoles: ['CEO'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_STRATEGIC_KPIS': ScreenMetadata(
      id: 'SCREEN_STRATEGIC_KPIS',
      title: 'StrategicKPIs',
      featureName: 'StrategicKPIs',
      routePath: '/offices/corporate/roles/ceo/strategic-kpis',
      office: 'Corporate',
      role: 'CEO',
      allowedRoles: ['CEO'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_FINANCIAL_OVERVIEW': ScreenMetadata(
      id: 'SCREEN_FINANCIAL_OVERVIEW',
      title: 'FinancialOverview',
      featureName: 'FinancialOverview',
      routePath: '/offices/corporate/roles/cfo/financial-overview',
      office: 'Corporate',
      role: 'CFO',
      allowedRoles: ['CFO'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_OPERATIONS_BOARD': ScreenMetadata(
      id: 'SCREEN_OPERATIONS_BOARD',
      title: 'OperationsBoard',
      featureName: 'OperationsBoard',
      routePath: '/offices/corporate/roles/coo/operations-overview',
      office: 'Corporate',
      role: 'COO',
      allowedRoles: ['COO'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_SYSTEM_HEALTH': ScreenMetadata(
      id: 'SCREEN_SYSTEM_HEALTH',
      title: 'SystemHealth',
      featureName: 'SystemHealth',
      routePath: '/offices/corporate/roles/cto/system-health',
      office: 'Corporate',
      role: 'CTO',
      allowedRoles: ['CTO'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
  };
}
