import '../screen_metadata.dart';

class FranchiseRegistryRegistry {
  static const Map<String, ScreenMetadata> screens = {
        'SCREEN_FRANCHISE_OWNER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_FRANCHISE_OWNER_DASHBOARD',
      title: 'franchise Owner Dashboard',
      featureName: 'franchise Owner Dashboard',
      routePath: '/franchise-owner-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'franchise_owner_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Weekly Revenue)","Business KPI Grid","Staff Oversight Table","Revenue Growth Chart"],
    ),
        'SCREEN_OPERATIONS_MANAGER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_OPERATIONS_MANAGER_DASHBOARD',
      title: 'operations Manager Dashboard',
      featureName: 'operations Manager Dashboard',
      routePath: '/operations-manager-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'operations_manager_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Utilization Score)","Logistics KPI Grid","Resource Allocation Map","Efficiency DashboardMetrics"],
    ),
        'SCREEN_SCHEDULER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_SCHEDULER_DASHBOARD',
      title: 'scheduler Dashboard',
      featureName: 'scheduler Dashboard',
      routePath: '/scheduler-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'scheduler_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Logistics Command Center","Staffing Grid","Coverage Velocity Chart","Telemetry Table"],
    ),
        'SCREEN_BILLING_ADMIN_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_BILLING_ADMIN_DASHBOARD',
      title: 'billing Admin Dashboard',
      featureName: 'billing Admin Dashboard',
      routePath: '/billing-admin-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'billing_admin_dashboard_view.dart',
      implementedComponents: ["Aura HUD (AR Velocity)","Billing Stat Grid","Pending Claims Ledger","Collection Status Chart"],
    ),
        'SCREEN_HR_HIRING_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_HR_HIRING_DASHBOARD',
      title: 'hr Hiring Dashboard',
      featureName: 'hr Hiring Dashboard',
      routePath: '/hr-hiring-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'hr_hiring_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Pipeline Velocity)","Recruitment KPI Grid","Candidate Pipeline View","Onboarding Checklist"],
    ),
        'SCREEN_REGIONAL_MANAGER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_REGIONAL_MANAGER_DASHBOARD',
      title: 'regional Manager Dashboard',
      featureName: 'regional Manager Dashboard',
      routePath: '/regional-manager-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'regional_manager_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Regional Growth)","Regional KPI Grid","Multi-site Performance Table","Synergy Audit Log"],
    ),
        'SCREEN_MARKETING_MANAGER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_MARKETING_MANAGER_DASHBOARD',
      title: 'marketing Manager Dashboard',
      featureName: 'marketing Manager Dashboard',
      routePath: '/marketing-manager-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'marketing_manager_dashboard_view.dart',
      implementedComponents: ["Aura HUD (Lead Conversion)","Marketing KPI Grid","Lead Conversion Funnel","Brand Awareness DashboardMetrics"],
    ),
        'SCREEN_FRANCHISE_OWNER_FINANCIAL_SNAPSHOT': ScreenMetadata(
      id: 'SCREEN_FRANCHISE_OWNER_FINANCIAL_SNAPSHOT',
      title: 'franchise Owner Financial Snapshot',
      featureName: 'franchise Owner Financial Snapshot',
      routePath: '/franchise-owner-financial-snapshot',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Cash Flow)","Balance Sheet Grid","P&L Waterfall Chart","Cash Flow Forecast"],
    ),
        'SCREEN_HR_HIRING_ONBOARDING': ScreenMetadata(
      id: 'SCREEN_HR_HIRING_ONBOARDING',
      title: 'hr Hiring Onboarding',
      featureName: 'hr Hiring Onboarding',
      routePath: '/hr-hiring-onboarding',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Verification Rate)","Multi-step Progress Bar","Document Upload Zone","Credential Verification"],
    ),
        'SCREEN_ADMIN_INVOICES': ScreenMetadata(
      id: 'SCREEN_ADMIN_INVOICES',
      title: 'admin Invoices',
      featureName: 'admin Invoices',
      routePath: '/admin-invoices',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD (Billing Accuracy)","Invoice SystemVerificationData Table","Batch Processing Actions","Tax Summary Card"],
    ),
  };
}
