import '../screen_metadata.dart';

class OperationalRegistryRegistry {
  static const Map<String, ScreenMetadata> screens = {
        'SCREEN_RECEPTIONIST_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_RECEPTIONIST_DASHBOARD',
      title: 'receptionist Dashboard',
      featureName: 'receptionist Dashboard',
      routePath: '/receptionist-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'receptionist_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Appointment Calendar","Check-in Queue","Directory Search"],
    ),
        'SCREEN_ADMIN_SETTINGS_': ScreenMetadata(
      id: 'SCREEN_ADMIN_SETTINGS_',
      title: '/admin-settings',
      featureName: '/admin-settings',
      routePath: '/admin-settings',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Operational Metric","Drift Detection"],
    ),
        'SCREEN_ARCHITECTURE_GOVERNANCE_': ScreenMetadata(
      id: 'SCREEN_ARCHITECTURE_GOVERNANCE_',
      title: '/architecture-governance',
      featureName: '/architecture-governance',
      routePath: '/architecture-governance',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Operational Metric","Drift Detection"],
    ),
        'SCREEN_LOGISTICS_HUB_': ScreenMetadata(
      id: 'SCREEN_LOGISTICS_HUB_',
      title: '/logistics-hub',
      featureName: '/logistics-hub',
      routePath: '/logistics-hub',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Operational Metric","Drift Detection"],
    ),
        'SCREEN_OPERATIONAL_STAFFING_DIRECTOR_': ScreenMetadata(
      id: 'SCREEN_OPERATIONAL_STAFFING_DIRECTOR_',
      title: '/operational/staffing-director',
      featureName: '/operational/staffing-director',
      routePath: '/operational/staffing-director',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Staffing Forecast Grid","Shift Optimization Heatmap","Credentialing Pipeline"],
    ),
        'SCREEN_OPERATIONAL_REGIONAL_MANAGER_': ScreenMetadata(
      id: 'SCREEN_OPERATIONAL_REGIONAL_MANAGER_',
      title: '/operational/regional-manager',
      featureName: '/operational/regional-manager',
      routePath: '/operational/regional-manager',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Regional KPI Matrix","Branch Health Scorecard","Incident Aggregator"],
    ),
        'SCREEN_COMPLIANCE_HUB': ScreenMetadata(
      id: 'SCREEN_COMPLIANCE_HUB',
      title: 'Compliance Hub',
      featureName: 'Compliance Hub',
      routePath: '/compliance-hub',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'compliance_hub_view.dart',
      implementedComponents: ["Aura HUD","Regulatory Alignment Score","Audit Trailing Grid","Compliance Deadlines"],
    ),
        'SCREEN_VERIFICATION_HUB': ScreenMetadata(
      id: 'SCREEN_VERIFICATION_HUB',
      title: 'Verification Hub',
      featureName: 'Verification Hub',
      routePath: '/verification-hub',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'verification_hub_view.dart',
      implementedComponents: ["Aura HUD","Identity Verification Queue","Credential Validation Heatmap","Security Checkpoint Logs"],
    ),
        'SCREEN_REGION_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_REGION_DASHBOARD',
      title: 'Region Dashboard',
      featureName: 'Region Dashboard',
      routePath: '/region-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'region_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Regional Performance Comparison","Site Health Overlays","Local Management Controls"],
    ),
        'SCREEN_SUPPORT_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_SUPPORT_DASHBOARD',
      title: 'Support Dashboard',
      featureName: 'System Support',
      routePath: '/support-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'support_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Ticket Lifecycle Tracker","SLA Compliance Monitor","Support Knowledge Base"],
    ),
    'SCREEN_LIVE_DISPATCH_MAP': ScreenMetadata(
      id: 'SCREEN_LIVE_DISPATCH_MAP',
      title: 'LiveDispatchMap',
      featureName: 'LiveDispatchMap',
      routePath: '/dispatch/live',
      office: 'Operational',
      role: 'admin_portal',
      allowedRoles: ['admin_portal', 'dispatch_portal'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
  };
}
