import '../screen_metadata.dart';

class OperationalRegistryRegistry {
  static const Map<String, ScreenMetadata> screens = {
        'SCREEN_RECEPTIONIST_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_RECEPTIONIST_DASHBOARD',
      title: 'receptionist Dashboard',
      featureName: 'receptionist Dashboard',
      routePath: '/receptionist-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'receptionist_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Appointment Calendar","Check-in Queue","Directory Search"],
    ),
        'SCREEN_ADMIN_SETTINGS_': ScreenMetadata(
      id: 'SCREEN_ADMIN_SETTINGS_',
      title: '/admin-settings',
      featureName: '/admin-settings',
      routePath: '/admin-settings',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Operational Metric","Drift Detection"],
    ),
        'SCREEN_ARCHITECTURE_GOVERNANCE_': ScreenMetadata(
      id: 'SCREEN_ARCHITECTURE_GOVERNANCE_',
      title: '/architecture-governance',
      featureName: '/architecture-governance',
      routePath: '/architecture-governance',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Operational Metric","Drift Detection"],
    ),
        'SCREEN_LOGISTICS_HUB_': ScreenMetadata(
      id: 'SCREEN_LOGISTICS_HUB_',
      title: 'Logistics Hub',
      featureName: 'Logistics Control Center',
      routePath: '/offices/operational/logistics',
      office: 'Operational',
      role: 'Coordinator',
      allowedRoles: ['Coordinator', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/logistics_hub_v4',
      generationPrompt: 'PrimeCare V4: Logistics Control Center for supply chain monitoring, fleet tracking, and real-time inventory adjustments.',
      generateScreen: true,
      implementedComponents: ["Aura HUD","Supply Chain Monitor","Fleet Tracker","Inventory Controller"],
    ),
    'SCREEN_COORDINATOR_HUB': ScreenMetadata(
      id: 'SCREEN_COORDINATOR_HUB',
      title: 'Coordinator Hub',
      featureName: 'Coordinator Scheduling Center',
      routePath: '/offices/operational/roles/coordinator/hub',
      office: 'Operational',
      role: 'Coordinator',
      allowedRoles: ['Coordinator', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/coordinator_hub_v4',
      generationPrompt: 'PrimeCare V4: Coordinator Scheduling Hub with real-time staff allocation, shift swap management, and coverage heatmaps.',
      generateScreen: true,
      implementedComponents: ["Aura HUD","Scheduling Hub","Staff Allocation Matrix","Shift Swap Manager"],
    ),
    'SCREEN_COORDINATOR_SOS': ScreenMetadata(
      id: 'SCREEN_COORDINATOR_SOS',
      title: 'SOS Emergency Triage',
      featureName: 'Coordinator SOS Center',
      routePath: '/offices/operational/roles/coordinator/sos',
      office: 'Operational',
      role: 'Coordinator',
      allowedRoles: ['Coordinator', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/coordinator_sos_v4',
      generationPrompt: 'PrimeCare V4: Coordinator SOS Emergency Triage with real-time alert monitoring, clinical escalation links, and resolution tracking.',
      generateScreen: true,
      implementedComponents: ["Aura HUD","SOS Alert Monitor","Clinical Escalation Link","Resolution Tracker"],
    ),
    'SCREEN_COORDINATOR_WAITLIST': ScreenMetadata(
      id: 'SCREEN_COORDINATOR_WAITLIST',
      title: 'Waitlist Triage',
      featureName: 'Coordinator Waitlist Center',
      routePath: '/offices/operational/roles/coordinator/waitlist',
      office: 'Operational',
      role: 'Coordinator',
      allowedRoles: ['Coordinator', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/coordinator_waitlist_v4',
      generationPrompt: 'PrimeCare V4: Coordinator Waitlist Triage for new referrals with assessment status tracking and case priority scoring.',
      generateScreen: true,
      implementedComponents: ["Aura HUD","Waitlist Queue","Priority Scoring Engine","Assessment Status Tracker"],
    ),
        'SCREEN_OPERATIONAL_STAFFING_DIRECTOR_': ScreenMetadata(
      id: 'SCREEN_OPERATIONAL_STAFFING_DIRECTOR_',
      title: '/operational/staffing-director',
      featureName: '/operational/staffing-director',
      routePath: '/operational/staffing-director',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Staffing Forecast Grid","Shift Optimization Heatmap","Credentialing Pipeline"],
    ),
        'SCREEN_OPERATIONAL_REGIONAL_MANAGER_': ScreenMetadata(
      id: 'SCREEN_OPERATIONAL_REGIONAL_MANAGER_',
      title: '/operational/regional-manager',
      featureName: '/operational/regional-manager',
      routePath: '/operational/regional-manager',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Regional KPI Matrix","Branch Health Scorecard","Incident Aggregator"],
    ),
        'SCREEN_COMPLIANCE_HUB': ScreenMetadata(
      id: 'SCREEN_COMPLIANCE_HUB',
      title: 'Compliance Hub',
      featureName: 'Compliance Hub',
      routePath: '/compliance-hub',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'compliance_hub_view.dart',
      implementedComponents: ["Aura HUD","Regulatory Alignment Score","Audit Trailing Grid","Compliance Deadlines"],
    ),
        'SCREEN_VERIFICATION_HUB': ScreenMetadata(
      id: 'SCREEN_VERIFICATION_HUB',
      title: 'Verification Hub',
      featureName: 'Verification Hub',
      routePath: '/verification-hub',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'verification_hub_view.dart',
      implementedComponents: ["Aura HUD","Identity Verification Queue","Credential Validation Heatmap","Security Checkpoint Logs"],
    ),
        'SCREEN_REGION_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_REGION_DASHBOARD',
      title: 'Region Dashboard',
      featureName: 'Region Dashboard',
      routePath: '/region-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'region_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Regional Performance Comparison","Site Health Overlays","Local Management Controls"],
    ),
        'SCREEN_SUPPORT_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_SUPPORT_DASHBOARD',
      title: 'Support Dashboard',
      featureName: 'System Support',
      routePath: '/support-dashboard',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'support_dashboard_view.dart',
      implementedComponents: ["Aura HUD","Ticket Lifecycle Tracker","SLA Compliance Monitor","Support Knowledge Base"],
    ),
    'SCREEN_LIVE_DISPATCH_MAP': ScreenMetadata(
      id: 'SCREEN_LIVE_DISPATCH_MAP',
      title: 'Live Dispatch Map',
      featureName: 'Operational Dispatch Map',
      routePath: '/offices/operational/roles/coordinator/dispatch',
      office: 'Operational',
      role: 'Coordinator',
      allowedRoles: ['Coordinator', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      stitchProject: '4678485121313267160',
      stitchUrl: 'https://stitch.withgoogle.com/projects/4678485121313267160/screens/dispatch_map_v4',
      generationPrompt: 'PrimeCare V4: Live Operational Dispatch Map with fleet GPS heartbeats, SOS alert overlays, and region health scorecards.',
      generateScreen: true,
      implementedComponents: ["Aura HUD","Interactive Route Logistics","SOS Alert Overlay","Fleet GPS Heartbeats"],
    ),
  };
}
