import '../screen_metadata.dart';

class WorkflowsFormsRegistryRegistry {
  static const Map<String, ScreenMetadata> screens = {
        'SCREEN_WF_ADD_FRANCHISE_LEAD_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_ADD_FRANCHISE_LEAD_FORM_',
      title: '/workflows-and-forms/add-franchise-lead-form',
      featureName: '/workflows-and-forms/add-franchise-lead-form',
      routePath: '/workflows-and-forms/add-franchise-lead-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_APPROVE_EXPENSE_REIMBURSEMENT_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_APPROVE_EXPENSE_REIMBURSEMENT_FORM_',
      title: '/workflows-and-forms/approve-expense-reimbursement-form',
      featureName: '/workflows-and-forms/approve-expense-reimbursement-form',
      routePath: '/workflows-and-forms/approve-expense-reimbursement-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_APPROVE_FRANCHISE_DISCLOSURE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_APPROVE_FRANCHISE_DISCLOSURE_FORM_',
      title: '/workflows-and-forms/approve-franchise-disclosure-form',
      featureName: '/workflows-and-forms/approve-franchise-disclosure-form',
      routePath: '/workflows-and-forms/approve-franchise-disclosure-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_APPROVE_LEAVE_REQUEST_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_APPROVE_LEAVE_REQUEST_FORM_',
      title: '/workflows-and-forms/approve-leave-request-form',
      featureName: '/workflows-and-forms/approve-leave-request-form',
      routePath: '/workflows-and-forms/approve-leave-request-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_APPROVE_MEDICATION_REFILL_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_APPROVE_MEDICATION_REFILL_FORM_',
      title: '/workflows-and-forms/approve-medication-refill-form',
      featureName: '/workflows-and-forms/approve-medication-refill-form',
      routePath: '/workflows-and-forms/approve-medication-refill-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_APPROVE_PAYROLL_RUN_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_APPROVE_PAYROLL_RUN_FORM_',
      title: '/workflows-and-forms/approve-payroll-run-form',
      featureName: '/workflows-and-forms/approve-payroll-run-form',
      routePath: '/workflows-and-forms/approve-payroll-run-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_APPROVE_REAL_ESTATE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_APPROVE_REAL_ESTATE_FORM_',
      title: '/workflows-and-forms/approve-real-estate-form',
      featureName: '/workflows-and-forms/approve-real-estate-form',
      routePath: '/workflows-and-forms/approve-real-estate-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_APPROVE_SYSTEM_ACCESS_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_APPROVE_SYSTEM_ACCESS_FORM_',
      title: '/workflows-and-forms/approve-system-access-form',
      featureName: '/workflows-and-forms/approve-system-access-form',
      routePath: '/workflows-and-forms/approve-system-access-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_ASSIGN_CARE_POD_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_ASSIGN_CARE_POD_FORM_',
      title: '/workflows-and-forms/assign-care-pod-form',
      featureName: '/workflows-and-forms/assign-care-pod-form',
      routePath: '/workflows-and-forms/assign-care-pod-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_ASSIGN_LEAD_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_ASSIGN_LEAD_FORM_',
      title: '/workflows-and-forms/assign-lead-form',
      featureName: '/workflows-and-forms/assign-lead-form',
      routePath: '/workflows-and-forms/assign-lead-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_ASSIGN_TRAINING_MODULE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_ASSIGN_TRAINING_MODULE_FORM_',
      title: '/workflows-and-forms/assign-training-module-form',
      featureName: '/workflows-and-forms/assign-training-module-form',
      routePath: '/workflows-and-forms/assign-training-module-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_AUDIT_COMPLIANCE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_AUDIT_COMPLIANCE_FORM_',
      title: '/workflows-and-forms/audit-compliance-form',
      featureName: '/workflows-and-forms/audit-compliance-form',
      routePath: '/workflows-and-forms/audit-compliance-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_AUDIT_GLOBAL_EDUCATION_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_AUDIT_GLOBAL_EDUCATION_FORM_',
      title: '/workflows-and-forms/audit-global-education-form',
      featureName: '/workflows-and-forms/audit-global-education-form',
      routePath: '/workflows-and-forms/audit-global-education-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_AUDIT_OVERRIDE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_AUDIT_OVERRIDE_FORM_',
      title: '/workflows-and-forms/audit-override-form',
      featureName: '/workflows-and-forms/audit-override-form',
      routePath: '/workflows-and-forms/audit-override-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_AUDIT_PAYROLL_DISCREPANCY_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_AUDIT_PAYROLL_DISCREPANCY_FORM_',
      title: '/workflows-and-forms/audit-payroll-discrepancy-form',
      featureName: '/workflows-and-forms/audit-payroll-discrepancy-form',
      routePath: '/workflows-and-forms/audit-payroll-discrepancy-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_AUDIT_ROYALTY_PAYMENT_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_AUDIT_ROYALTY_PAYMENT_FORM_',
      title: '/workflows-and-forms/audit-royalty-payment-form',
      featureName: '/workflows-and-forms/audit-royalty-payment-form',
      routePath: '/workflows-and-forms/audit-royalty-payment-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_AUDIT_SECURITY_COMPLIANCE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_AUDIT_SECURITY_COMPLIANCE_FORM_',
      title: '/workflows-and-forms/audit-security-compliance-form',
      featureName: '/workflows-and-forms/audit-security-compliance-form',
      routePath: '/workflows-and-forms/audit-security-compliance-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_AUDIT_SYSTEM_LOGS_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_AUDIT_SYSTEM_LOGS_FORM_',
      title: '/workflows-and-forms/audit-system-logs-form',
      featureName: '/workflows-and-forms/audit-system-logs-form',
      routePath: '/workflows-and-forms/audit-system-logs-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_CARE_PLAN_EVALUATION_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_CARE_PLAN_EVALUATION_FORM_',
      title: '/workflows-and-forms/care-plan-evaluation-form',
      featureName: '/workflows-and-forms/care-plan-evaluation-form',
      routePath: '/workflows-and-forms/care-plan-evaluation-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_CREATE_AD_PLACEMENT_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_CREATE_AD_PLACEMENT_FORM_',
      title: '/workflows-and-forms/create-ad-placement-form',
      featureName: '/workflows-and-forms/create-ad-placement-form',
      routePath: '/workflows-and-forms/create-ad-placement-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_CREATE_CANNED_RESPONSE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_CREATE_CANNED_RESPONSE_FORM_',
      title: '/workflows-and-forms/create-canned-response-form',
      featureName: '/workflows-and-forms/create-canned-response-form',
      routePath: '/workflows-and-forms/create-canned-response-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_CREATE_CUSTOM_INVOICE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_CREATE_CUSTOM_INVOICE_FORM_',
      title: '/workflows-and-forms/create-custom-invoice-form',
      featureName: '/workflows-and-forms/create-custom-invoice-form',
      routePath: '/workflows-and-forms/create-custom-invoice-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_CREATE_REVENUE_REPORT_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_CREATE_REVENUE_REPORT_FORM_',
      title: '/workflows-and-forms/create-revenue-report-form',
      featureName: '/workflows-and-forms/create-revenue-report-form',
      routePath: '/workflows-and-forms/create-revenue-report-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_CREATE_SUPPLY_ORDER_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_CREATE_SUPPLY_ORDER_FORM_',
      title: '/workflows-and-forms/create-supply-order-form',
      featureName: '/workflows-and-forms/create-supply-order-form',
      routePath: '/workflows-and-forms/create-supply-order-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_DAILY_VITALS_CARD_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_DAILY_VITALS_CARD_FORM_',
      title: '/workflows-and-forms/daily-vitals-card-form',
      featureName: '/workflows-and-forms/daily-vitals-card-form',
      routePath: '/workflows-and-forms/daily-vitals-card-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_DISCIPLINE_LOG_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_DISCIPLINE_LOG_FORM_',
      title: '/workflows-and-forms/discipline-log-form',
      featureName: '/workflows-and-forms/discipline-log-form',
      routePath: '/workflows-and-forms/discipline-log-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_FRANCHISE_ONBOARDING_CHECKLIST_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_FRANCHISE_ONBOARDING_CHECKLIST_FORM_',
      title: '/workflows-and-forms/franchise-onboarding-checklist-form',
      featureName: '/workflows-and-forms/franchise-onboarding-checklist-form',
      routePath: '/workflows-and-forms/franchise-onboarding-checklist-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_LEAVE_REQUEST_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_LEAVE_REQUEST_FORM_',
      title: '/workflows-and-forms/leave-request-form',
      featureName: '/workflows-and-forms/leave-request-form',
      routePath: '/workflows-and-forms/leave-request-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_LOG_CLINICAL_INCIDENT_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_LOG_CLINICAL_INCIDENT_FORM_',
      title: '/workflows-and-forms/log-clinical-incident-form',
      featureName: '/workflows-and-forms/log-clinical-incident-form',
      routePath: '/workflows-and-forms/log-clinical-incident-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_LOG_EMPLOYEE_GRIEVANCE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_LOG_EMPLOYEE_GRIEVANCE_FORM_',
      title: '/workflows-and-forms/log-employee-grievance-form',
      featureName: '/workflows-and-forms/log-employee-grievance-form',
      routePath: '/workflows-and-forms/log-employee-grievance-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_LOG_FRANCHISEE_VETTING_CALL_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_LOG_FRANCHISEE_VETTING_CALL_FORM_',
      title: '/workflows-and-forms/log-franchisee-vetting-call-form',
      featureName: '/workflows-and-forms/log-franchisee-vetting-call-form',
      routePath: '/workflows-and-forms/log-franchisee-vetting-call-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_LOG_INFECTION_CONTROL_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_LOG_INFECTION_CONTROL_FORM_',
      title: '/workflows-and-forms/log-infection-control-form',
      featureName: '/workflows-and-forms/log-infection-control-form',
      routePath: '/workflows-and-forms/log-infection-control-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_LOG_INVENTORY_SPOILAGE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_LOG_INVENTORY_SPOILAGE_FORM_',
      title: '/workflows-and-forms/log-inventory-spoilage-form',
      featureName: '/workflows-and-forms/log-inventory-spoilage-form',
      routePath: '/workflows-and-forms/log-inventory-spoilage-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_LOG_PETTY_CASH_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_LOG_PETTY_CASH_FORM_',
      title: '/workflows-and-forms/log-petty-cash-form',
      featureName: '/workflows-and-forms/log-petty-cash-form',
      routePath: '/workflows-and-forms/log-petty-cash-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_NEW_EMPLOYEE_ONBOARDING_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_NEW_EMPLOYEE_ONBOARDING_FORM_',
      title: '/workflows-and-forms/new-employee-onboarding-form',
      featureName: '/workflows-and-forms/new-employee-onboarding-form',
      routePath: '/workflows-and-forms/new-employee-onboarding-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_NURTURE_LOCALIZED_LEAD_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_NURTURE_LOCALIZED_LEAD_FORM_',
      title: '/workflows-and-forms/nurture-localized-lead-form',
      featureName: '/workflows-and-forms/nurture-localized-lead-form',
      routePath: '/workflows-and-forms/nurture-localized-lead-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_OVERRIDE_GLOBAL_SCHEDULE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_OVERRIDE_GLOBAL_SCHEDULE_FORM_',
      title: '/workflows-and-forms/override-global-schedule-form',
      featureName: '/workflows-and-forms/override-global-schedule-form',
      routePath: '/workflows-and-forms/override-global-schedule-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_PATIENT_INTAKE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_PATIENT_INTAKE_FORM_',
      title: '/workflows-and-forms/patient-intake-form',
      featureName: '/workflows-and-forms/patient-intake-form',
      routePath: '/workflows-and-forms/patient-intake-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_REGISTER_CORPORATE_RISK_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_REGISTER_CORPORATE_RISK_FORM_',
      title: '/workflows-and-forms/register-corporate-risk-form',
      featureName: '/workflows-and-forms/register-corporate-risk-form',
      routePath: '/workflows-and-forms/register-corporate-risk-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_REQUEST_SHIFT_ADJUSTMENT_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_REQUEST_SHIFT_ADJUSTMENT_FORM_',
      title: '/workflows-and-forms/request-shift-adjustment-form',
      featureName: '/workflows-and-forms/request-shift-adjustment-form',
      routePath: '/workflows-and-forms/request-shift-adjustment-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_REVIEW_CARE_PLAN_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_REVIEW_CARE_PLAN_FORM_',
      title: '/workflows-and-forms/review-care-plan-form',
      featureName: '/workflows-and-forms/review-care-plan-form',
      routePath: '/workflows-and-forms/review-care-plan-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_REVIEW_CLINICAL_INCIDENT_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_REVIEW_CLINICAL_INCIDENT_FORM_',
      title: '/workflows-and-forms/review-clinical-incident-form',
      featureName: '/workflows-and-forms/review-clinical-incident-form',
      routePath: '/workflows-and-forms/review-clinical-incident-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_REVIEW_FLEET_MAINTENANCE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_REVIEW_FLEET_MAINTENANCE_FORM_',
      title: '/workflows-and-forms/review-fleet-maintenance-form',
      featureName: '/workflows-and-forms/review-fleet-maintenance-form',
      routePath: '/workflows-and-forms/review-fleet-maintenance-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_REVIEW_LEAD_CONVERSION_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_REVIEW_LEAD_CONVERSION_FORM_',
      title: '/workflows-and-forms/review-lead-conversion-form',
      featureName: '/workflows-and-forms/review-lead-conversion-form',
      routePath: '/workflows-and-forms/review-lead-conversion-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_REVIEW_LEGAL_CONTRACT_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_REVIEW_LEGAL_CONTRACT_FORM_',
      title: '/workflows-and-forms/review-legal-contract-form',
      featureName: '/workflows-and-forms/review-legal-contract-form',
      routePath: '/workflows-and-forms/review-legal-contract-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_REVIEW_MARKET_SHARE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_REVIEW_MARKET_SHARE_FORM_',
      title: '/workflows-and-forms/review-market-share-form',
      featureName: '/workflows-and-forms/review-market-share-form',
      routePath: '/workflows-and-forms/review-market-share-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_REVIEW_MEDICATION_INVENTORY_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_REVIEW_MEDICATION_INVENTORY_FORM_',
      title: '/workflows-and-forms/review-medication-inventory-form',
      featureName: '/workflows-and-forms/review-medication-inventory-form',
      routePath: '/workflows-and-forms/review-medication-inventory-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_REVIEW_MONTHLY_EXPENSES_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_REVIEW_MONTHLY_EXPENSES_FORM_',
      title: '/workflows-and-forms/review-monthly-expenses-form',
      featureName: '/workflows-and-forms/review-monthly-expenses-form',
      routePath: '/workflows-and-forms/review-monthly-expenses-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_REVIEW_ONBOARDING_STATUS_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_REVIEW_ONBOARDING_STATUS_FORM_',
      title: '/workflows-and-forms/review-onboarding-status-form',
      featureName: '/workflows-and-forms/review-onboarding-status-form',
      routePath: '/workflows-and-forms/review-onboarding-status-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_REVIEW_PEER_PERFORMANCE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_REVIEW_PEER_PERFORMANCE_FORM_',
      title: '/workflows-and-forms/review-peer-performance-form',
      featureName: '/workflows-and-forms/review-peer-performance-form',
      routePath: '/workflows-and-forms/review-peer-performance-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_REVIEW_VENDOR_CONTRACTS_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_REVIEW_VENDOR_CONTRACTS_FORM_',
      title: '/workflows-and-forms/review-vendor-contracts-form',
      featureName: '/workflows-and-forms/review-vendor-contracts-form',
      routePath: '/workflows-and-forms/review-vendor-contracts-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_SCHEDULE_CLINICAL_AUDIT_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_SCHEDULE_CLINICAL_AUDIT_FORM_',
      title: '/workflows-and-forms/schedule-clinical-audit-form',
      featureName: '/workflows-and-forms/schedule-clinical-audit-form',
      routePath: '/workflows-and-forms/schedule-clinical-audit-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_SCHEDULE_FACILITY_MAINTENANCE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_SCHEDULE_FACILITY_MAINTENANCE_FORM_',
      title: '/workflows-and-forms/schedule-facility-maintenance-form',
      featureName: '/workflows-and-forms/schedule-facility-maintenance-form',
      routePath: '/workflows-and-forms/schedule-facility-maintenance-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_SCHEDULE_INTERVIEW_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_SCHEDULE_INTERVIEW_FORM_',
      title: '/workflows-and-forms/schedule-interview-form',
      featureName: '/workflows-and-forms/schedule-interview-form',
      routePath: '/workflows-and-forms/schedule-interview-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_SCHEDULE_OPEN_HOUSE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_SCHEDULE_OPEN_HOUSE_FORM_',
      title: '/workflows-and-forms/schedule-open-house-form',
      featureName: '/workflows-and-forms/schedule-open-house-form',
      routePath: '/workflows-and-forms/schedule-open-house-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_SUBMIT_ADL_CHECKLIST_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_SUBMIT_ADL_CHECKLIST_FORM_',
      title: '/workflows-and-forms/submit-adl-checklist-form',
      featureName: '/workflows-and-forms/submit-adl-checklist-form',
      routePath: '/workflows-and-forms/submit-adl-checklist-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_SUBMIT_DAILY_CENSUS_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_SUBMIT_DAILY_CENSUS_FORM_',
      title: '/workflows-and-forms/submit-daily-census-form',
      featureName: '/workflows-and-forms/submit-daily-census-form',
      routePath: '/workflows-and-forms/submit-daily-census-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_SUBMIT_EXIT_INTERVIEW_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_SUBMIT_EXIT_INTERVIEW_FORM_',
      title: '/workflows-and-forms/submit-exit-interview-form',
      featureName: '/workflows-and-forms/submit-exit-interview-form',
      routePath: '/workflows-and-forms/submit-exit-interview-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_SUBMIT_HEALTHCARE_CLAIM_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_SUBMIT_HEALTHCARE_CLAIM_FORM_',
      title: '/workflows-and-forms/submit-healthcare-claim-form',
      featureName: '/workflows-and-forms/submit-healthcare-claim-form',
      routePath: '/workflows-and-forms/submit-healthcare-claim-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_SUBMIT_MARKETING_BUDGET_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_SUBMIT_MARKETING_BUDGET_FORM_',
      title: '/workflows-and-forms/submit-marketing-budget-form',
      featureName: '/workflows-and-forms/submit-marketing-budget-form',
      routePath: '/workflows-and-forms/submit-marketing-budget-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_WF_VERIFY_CERTIFICATE_FORM_': ScreenMetadata(
      id: 'SCREEN_WF_VERIFY_CERTIFICATE_FORM_',
      title: '/workflows-and-forms/verify-certificate-form',
      featureName: '/workflows-and-forms/verify-certificate-form',
      routePath: '/workflows-and-forms/verify-certificate-form',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD","Dynamic Form Engine","Execution Gate Guard"],
    ),
        'SCREEN_ADMINISTRATIVE_FORMS': ScreenMetadata(
      id: 'SCREEN_ADMINISTRATIVE_FORMS',
      title: 'Administrative Forms',
      featureName: 'Form Architecture',
      routePath: '/administrative-forms',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'administrative_forms_view.dart',
      implementedComponents: ["Aura HUD","Dynamic Form Factory","Validation Schema Monitor","Submission Gateway"],
    ),
        'SCREEN_CLINICAL_FORMS': ScreenMetadata(
      id: 'SCREEN_CLINICAL_FORMS',
      title: 'Clinical Forms',
      featureName: 'Form Architecture',
      routePath: '/clinical-forms',
      office: 'Clinical',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'clinical_forms_view.dart',
      implementedComponents: ["Aura HUD","PHIPA Compliance Engine","Clinical Logic Mapper","Audit Trailing"],
    ),
        'SCREEN_COMMON_FORMS': ScreenMetadata(
      id: 'SCREEN_COMMON_FORMS',
      title: 'Common Forms',
      featureName: 'Form Architecture',
      routePath: '/common-forms',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'common_forms_view.dart',
      implementedComponents: ["Aura HUD","Shared Component Library","Global Validation Hooks","Multi-Tenant Logic"],
    ),
        'SCREEN_CRM_FORMS': ScreenMetadata(
      id: 'SCREEN_CRM_FORMS',
      title: 'CRM Forms',
      featureName: 'Form Architecture',
      routePath: '/crm-forms',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'crm_forms_view.dart',
      implementedComponents: ["Aura HUD","Lead Capture Hook","Contact Field Synchronization","Pipeline Event Trigger"],
    ),
        'SCREEN_FINANCIAL_FORMS': ScreenMetadata(
      id: 'SCREEN_FINANCIAL_FORMS',
      title: 'Financial Forms',
      featureName: 'Form Architecture',
      routePath: '/financial-forms',
      office: 'Corporate',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'financial_forms_view.dart',
      implementedComponents: ["Aura HUD","Double-Entry Verification","Tax Calculation Engine","Ledger Sync Guard"],
    ),
        'SCREEN_HR_FORMS': ScreenMetadata(
      id: 'SCREEN_HR_FORMS',
      title: 'HR Forms',
      featureName: 'Form Architecture',
      routePath: '/hr-forms',
      office: 'Operational',
      role: 'Staff',
      allowedRoles: ['Staff', 'Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: false,
      sourcePath: 'hr_forms_view.dart',
      implementedComponents: ["Aura HUD","Onboarding Checklist Hook","Payroll Data Bindings","Performance Review Logic"],
    ),
    'SCREEN_AUTH_LAYOUT': ScreenMetadata(
      id: 'SCREEN_AUTH_LAYOUT',
      title: 'AuthLayout',
      featureName: 'AuthLayout',
      routePath: '/auth',
      office: 'Workflows',
      role: 'public',
      allowedRoles: ['public'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_GLOBAL_SETTINGS': ScreenMetadata(
      id: 'SCREEN_GLOBAL_SETTINGS',
      title: 'GlobalSettings',
      featureName: 'GlobalSettings',
      routePath: '/generated/globalSettings',
      office: 'Workflows',
      role: 'all',
      allowedRoles: ['all'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_GROWTH_PIPELINE': ScreenMetadata(
      id: 'SCREEN_GROWTH_PIPELINE',
      title: 'GrowthPipeline',
      featureName: 'GrowthPipeline',
      routePath: '/generated/ceoGrowthPipeline',
      office: 'Workflows',
      role: 'CEO',
      allowedRoles: ['CEO'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_REGION_PERFORMANCE': ScreenMetadata(
      id: 'SCREEN_REGION_PERFORMANCE',
      title: 'RegionPerformance',
      featureName: 'RegionPerformance',
      routePath: '/generated/ceoRegionPerformance',
      office: 'Workflows',
      role: 'CEO',
      allowedRoles: ['CEO'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_LEADERSHIP_REPORTS': ScreenMetadata(
      id: 'SCREEN_LEADERSHIP_REPORTS',
      title: 'LeadershipReports',
      featureName: 'LeadershipReports',
      routePath: '/generated/ceoLeadershipReports',
      office: 'Workflows',
      role: 'CEO',
      allowedRoles: ['CEO'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_REVENUE_TRACKER': ScreenMetadata(
      id: 'SCREEN_REVENUE_TRACKER',
      title: 'RevenueTracker',
      featureName: 'RevenueTracker',
      routePath: '/generated/cfoRevenue',
      office: 'Workflows',
      role: 'CFO',
      allowedRoles: ['CFO'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_PROFITABILITY': ScreenMetadata(
      id: 'SCREEN_PROFITABILITY',
      title: 'Profitability',
      featureName: 'Profitability',
      routePath: '/generated/cfoProfitability',
      office: 'Workflows',
      role: 'CFO',
      allowedRoles: ['CFO'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_TAX_REMITTANCE': ScreenMetadata(
      id: 'SCREEN_TAX_REMITTANCE',
      title: 'Tax&Remittance',
      featureName: 'Tax&Remittance',
      routePath: '/generated/cfoTaxAndRemittance',
      office: 'Workflows',
      role: 'CFO',
      allowedRoles: ['CFO'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_BRANCH_OPERATIONS': ScreenMetadata(
      id: 'SCREEN_BRANCH_OPERATIONS',
      title: 'BranchOperations',
      featureName: 'BranchOperations',
      routePath: '/generated/cooBranchOperations',
      office: 'Workflows',
      role: 'COO',
      allowedRoles: ['COO'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_SCHEDULING_HEALTH': ScreenMetadata(
      id: 'SCREEN_SCHEDULING_HEALTH',
      title: 'SchedulingHealth',
      featureName: 'SchedulingHealth',
      routePath: '/generated/cooSchedulingHealth',
      office: 'Workflows',
      role: 'COO',
      allowedRoles: ['COO'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_INCIDENT_REVIEWS': ScreenMetadata(
      id: 'SCREEN_INCIDENT_REVIEWS',
      title: 'IncidentReviews',
      featureName: 'IncidentReviews',
      routePath: '/generated/cooIssueEscalations',
      office: 'Workflows',
      role: 'COO',
      allowedRoles: ['COO'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_PLATFORM_USAGE': ScreenMetadata(
      id: 'SCREEN_PLATFORM_USAGE',
      title: 'PlatformUsage',
      featureName: 'PlatformUsage',
      routePath: '/generated/ctoPlatformUsage',
      office: 'Workflows',
      role: 'CTO',
      allowedRoles: ['CTO', 'Corporate Developer'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_API_MONITORING': ScreenMetadata(
      id: 'SCREEN_API_MONITORING',
      title: 'APIMonitoring',
      featureName: 'APIMonitoring',
      routePath: '/generated/ctoApiMonitoring',
      office: 'Workflows',
      role: 'CTO',
      allowedRoles: ['CTO', 'Corporate Developer'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_AUDIT_LOGS': ScreenMetadata(
      id: 'SCREEN_AUDIT_LOGS',
      title: 'AuditLogs',
      featureName: 'AuditLogs',
      routePath: '/generated/ctoAuditLogs',
      office: 'Workflows',
      role: 'CTO',
      allowedRoles: ['CTO'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_CASES': ScreenMetadata(
      id: 'SCREEN_CASES',
      title: 'Cases',
      featureName: 'Cases',
      routePath: '/generated/complianceManagerComplianceCases',
      office: 'Workflows',
      role: 'Compliance Manager',
      allowedRoles: ['Compliance Manager'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_POLICY_MANAGER': ScreenMetadata(
      id: 'SCREEN_POLICY_MANAGER',
      title: 'PolicyManager',
      featureName: 'PolicyManager',
      routePath: '/generated/complianceManagerPolicies',
      office: 'Workflows',
      role: 'Compliance Manager',
      allowedRoles: ['Compliance Manager'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_AUDITS': ScreenMetadata(
      id: 'SCREEN_AUDITS',
      title: 'Audits',
      featureName: 'Audits',
      routePath: '/generated/complianceManagerAudits',
      office: 'Workflows',
      role: 'Compliance Manager',
      allowedRoles: ['Compliance Manager'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_RISK_REGISTER': ScreenMetadata(
      id: 'SCREEN_RISK_REGISTER',
      title: 'RiskRegister',
      featureName: 'RiskRegister',
      routePath: '/generated/complianceManagerRiskRegister',
      office: 'Workflows',
      role: 'Compliance Manager',
      allowedRoles: ['Compliance Manager'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_CURRICULUM_HUB': ScreenMetadata(
      id: 'SCREEN_CURRICULUM_HUB',
      title: 'CurriculumHub',
      featureName: 'CurriculumHub',
      routePath: '/generated/trainingDirectorDashboard',
      office: 'Workflows',
      role: 'Training Director',
      allowedRoles: ['Training Director'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_SKILL_MATRIX': ScreenMetadata(
      id: 'SCREEN_SKILL_MATRIX',
      title: 'SkillMatrix',
      featureName: 'SkillMatrix',
      routePath: '/generated/trainingDirectorAnalytics',
      office: 'Workflows',
      role: 'Training Director',
      allowedRoles: ['Training Director'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_BRANCH_COMPARISON': ScreenMetadata(
      id: 'SCREEN_BRANCH_COMPARISON',
      title: 'BranchComparison',
      featureName: 'BranchComparison',
      routePath: '/generated/regionalManagerBranchComparison',
      office: 'Workflows',
      role: 'Regional Manager',
      allowedRoles: ['Regional Manager'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_LEDGER_COMMAND': ScreenMetadata(
      id: 'SCREEN_LEDGER_COMMAND',
      title: 'LedgerCommand',
      featureName: 'LedgerCommand',
      routePath: '/generated/financeDirectorDashboard',
      office: 'Workflows',
      role: 'Finance Director',
      allowedRoles: ['Finance Director'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_CASH_FLOW': ScreenMetadata(
      id: 'SCREEN_CASH_FLOW',
      title: 'CashFlow',
      featureName: 'CashFlow',
      routePath: '/generated/financeDirectorCashFlow',
      office: 'Workflows',
      role: 'Finance Director',
      allowedRoles: ['Finance Director'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_INTAKE_PIPELINE': ScreenMetadata(
      id: 'SCREEN_INTAKE_PIPELINE',
      title: 'IntakePipeline',
      featureName: 'IntakePipeline',
      routePath: '/generated/intakeCoordinatorDashboard',
      office: 'Workflows',
      role: 'Intake Coordinator',
      allowedRoles: ['Intake Coordinator'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_REFERRALS': ScreenMetadata(
      id: 'SCREEN_REFERRALS',
      title: 'Referrals',
      featureName: 'Referrals',
      routePath: '/generated/intakeCoordinatorReferrals',
      office: 'Workflows',
      role: 'Intake Coordinator',
      allowedRoles: ['Intake Coordinator'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_PENDING_ASSESSMENTS': ScreenMetadata(
      id: 'SCREEN_PENDING_ASSESSMENTS',
      title: 'Pendingassessments',
      featureName: 'Pendingassessments',
      routePath: '/generated/intakeCoordinatorAssessments',
      office: 'Workflows',
      role: 'Intake Coordinator',
      allowedRoles: ['Intake Coordinator'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_BILLING_CONSOLE': ScreenMetadata(
      id: 'SCREEN_BILLING_CONSOLE',
      title: 'BillingConsole',
      featureName: 'BillingConsole',
      routePath: '/generated/billingAdminDashboard',
      office: 'Workflows',
      role: 'Billing Admin',
      allowedRoles: ['Billing Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_INVOICES': ScreenMetadata(
      id: 'SCREEN_INVOICES',
      title: 'Invoices',
      featureName: 'Invoices',
      routePath: '/generated/billingAdminInvoices',
      office: 'Workflows',
      role: 'Billing Admin',
      allowedRoles: ['Billing Admin'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_MARKETING_HUB': ScreenMetadata(
      id: 'SCREEN_MARKETING_HUB',
      title: 'MarketingHub',
      featureName: 'MarketingHub',
      routePath: '/generated/marketingManagerDashboard',
      office: 'Workflows',
      role: 'Marketing Manager',
      allowedRoles: ['Marketing Manager'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_CAMPAIGN_ANALYTICS': ScreenMetadata(
      id: 'SCREEN_CAMPAIGN_ANALYTICS',
      title: 'CampaignAnalytics',
      featureName: 'CampaignAnalytics',
      routePath: '/generated/marketingManagerCampaigns',
      office: 'Workflows',
      role: 'Marketing Manager',
      allowedRoles: ['Marketing Manager'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_BUSINESS_OVERVIEW': ScreenMetadata(
      id: 'SCREEN_BUSINESS_OVERVIEW',
      title: 'BusinessOverview',
      featureName: 'BusinessOverview',
      routePath: '/generated/franchiseOwnerDashboard',
      office: 'Workflows',
      role: 'Franchise Owner',
      allowedRoles: ['Franchise Owner'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_FINANCIAL_PERFORMANCE': ScreenMetadata(
      id: 'SCREEN_FINANCIAL_PERFORMANCE',
      title: 'FinancialPerformance',
      featureName: 'FinancialPerformance',
      routePath: '/generated/franchiseOwnerFinancialSnapshot',
      office: 'Workflows',
      role: 'Franchise Owner',
      allowedRoles: ['Franchise Owner'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_COMPLIANCE_STATUS': ScreenMetadata(
      id: 'SCREEN_COMPLIANCE_STATUS',
      title: 'ComplianceStatus',
      featureName: 'ComplianceStatus',
      routePath: '/generated/franchiseOwnerCompliance',
      office: 'Workflows',
      role: 'Franchise Owner',
      allowedRoles: ['Franchise Owner'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_SHIFT_TRACKER': ScreenMetadata(
      id: 'SCREEN_SHIFT_TRACKER',
      title: 'ShiftTracker',
      featureName: 'ShiftTracker',
      routePath: '/generated/clinicMyShifts',
      office: 'Workflows',
      role: 'PSW',
      allowedRoles: ['PSW'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_MESSAGES': ScreenMetadata(
      id: 'SCREEN_MESSAGES',
      title: 'Messages',
      featureName: 'Messages',
      routePath: '/generated/messagingHub',
      office: 'Workflows',
      role: 'PSW',
      allowedRoles: ['PSW'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_FAMILY_HOME': ScreenMetadata(
      id: 'SCREEN_FAMILY_HOME',
      title: 'FamilyHome',
      featureName: 'FamilyHome',
      routePath: '/generated/clientDashboard',
      office: 'Workflows',
      role: 'Client',
      allowedRoles: ['Client'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_CARE_PLAN': ScreenMetadata(
      id: 'SCREEN_CARE_PLAN',
      title: 'CarePlan',
      featureName: 'CarePlan',
      routePath: '/generated/clientTreatmentHistory',
      office: 'Workflows',
      role: 'Client',
      allowedRoles: ['Client'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_BILLING': ScreenMetadata(
      id: 'SCREEN_BILLING',
      title: 'Billing',
      featureName: 'Billing',
      routePath: '/generated/clientPayments',
      office: 'Workflows',
      role: 'Client',
      allowedRoles: ['Client'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_MESSAGING_HUB': ScreenMetadata(
      id: 'SCREEN_MESSAGING_HUB',
      title: 'MessagingHub',
      featureName: 'MessagingHub',
      routePath: '/generated/messagingHub',
      office: 'Workflows',
      role: 'all',
      allowedRoles: ['all'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_DOCUMENT_VAULT': ScreenMetadata(
      id: 'SCREEN_DOCUMENT_VAULT',
      title: 'DocumentVault',
      featureName: 'DocumentVault',
      routePath: '/generated/documentVault',
      office: 'Workflows',
      role: 'all',
      allowedRoles: ['all'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_NOTIFICATION_CENTER': ScreenMetadata(
      id: 'SCREEN_NOTIFICATION_CENTER',
      title: 'Notifications',
      featureName: 'Notifications',
      routePath: '/generated/notificationCenter',
      office: 'Workflows',
      role: 'all',
      allowedRoles: ['all'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_SHAREHOLDER_DASHBOARD': ScreenMetadata(
      id: 'SCREEN_SHAREHOLDER_DASHBOARD',
      title: 'ShareholderDashboard',
      featureName: 'ShareholderDashboard',
      routePath: '/generated/shareholderIntelligenceDashboard',
      office: 'Workflows',
      role: 'Shareholder',
      allowedRoles: ['Shareholder'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_COMMON_DASHBOARD_LABELS': ScreenMetadata(
      id: 'SCREEN_COMMON_DASHBOARD_LABELS',
      title: 'CommonDashboardLabels',
      featureName: 'CommonDashboardLabels',
      routePath: '/legacy/common_dashboard_labels',
      office: 'Workflows',
      role: 'all',
      allowedRoles: ['all'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_REGIONAL_MANAGER_LABELS': ScreenMetadata(
      id: 'SCREEN_REGIONAL_MANAGER_LABELS',
      title: 'regional_manager_labels',
      featureName: 'regional_manager_labels',
      routePath: '/legacy/regional_manager_labels',
      office: 'Workflows',
      role: 'Guest',
      allowedRoles: ['Guest'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_COMMAND_CENTER_LABELS': ScreenMetadata(
      id: 'SCREEN_COMMAND_CENTER_LABELS',
      title: 'command_center_labels',
      featureName: 'command_center_labels',
      routePath: '/legacy/command_center_labels',
      office: 'Workflows',
      role: 'Guest',
      allowedRoles: ['Guest'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_CTO_DASHBOARD_LABELS': ScreenMetadata(
      id: 'SCREEN_CTO_DASHBOARD_LABELS',
      title: 'cto_dashboard_labels',
      featureName: 'cto_dashboard_labels',
      routePath: '/legacy/cto_dashboard_labels',
      office: 'Workflows',
      role: 'Guest',
      allowedRoles: ['Guest'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_CEO_DASHBOARD_LABELS': ScreenMetadata(
      id: 'SCREEN_CEO_DASHBOARD_LABELS',
      title: 'ceo_dashboard_labels',
      featureName: 'ceo_dashboard_labels',
      routePath: '/legacy/ceo_dashboard_labels',
      office: 'Workflows',
      role: 'Guest',
      allowedRoles: ['Guest'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_CFO_DASHBOARD_LABELS': ScreenMetadata(
      id: 'SCREEN_CFO_DASHBOARD_LABELS',
      title: 'cfo_dashboard_labels',
      featureName: 'cfo_dashboard_labels',
      routePath: '/legacy/cfo_dashboard_labels',
      office: 'Workflows',
      role: 'Guest',
      allowedRoles: ['Guest'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_SUPPORT_DASHBOARD_LABELS': ScreenMetadata(
      id: 'SCREEN_SUPPORT_DASHBOARD_LABELS',
      title: 'support_dashboard_labels',
      featureName: 'support_dashboard_labels',
      routePath: '/legacy/support_dashboard_labels',
      office: 'Workflows',
      role: 'Guest',
      allowedRoles: ['Guest'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
    'SCREEN_MARKETING_DASHBOARD_LABELS': ScreenMetadata(
      id: 'SCREEN_MARKETING_DASHBOARD_LABELS',
      title: 'marketing_dashboard_labels',
      featureName: 'marketing_dashboard_labels',
      routePath: '/legacy/marketing_dashboard_labels',
      office: 'Workflows',
      role: 'Guest',
      allowedRoles: ['Guest'],
      lifecycleStatus: LifecycleStatus.completed,
      isRenderOk: true,
      userApprovedLayout: true,
      isVirtual: true,
      sourcePath: 'virtual',
      implementedComponents: ["Aura HUD", "Standard View"],
    ),
  };
}
