// Governance - Category: service | Purpose: Core implementation file for the Base Growth platform logic.
export const baseGrowthContent = {
    MARKETPLACE: {
        TITLE: 'Integration Marketplace',
        SUBTITLE: 'Browse and manage third-party integrations.',
        SEARCH: 'Search integrations...',
        INSTALL: 'Install',
        INSTALLED: 'Installed',
        CATEGORY: 'Category',
        ALL: 'All',
        PRICE_UNIT: '/mo',
        INQUIRE_BTN: 'Inquire',
        OFFER_TITLE: 'Custom Integration',
        OFFER_DESC: 'Need a bespoke integration? Contact our engineering team.',
        CREATE_BTN: 'Request Custom Build',
        FORM: {
            API_KEY: 'API Key',
            WEBHOOK_URL: 'Webhook URL',
            CONNECT_BTN: 'Connect',
            DISCONNECT_BTN: 'Disconnect',
        },
    },
    ADMIN_LEADS: {
        TITLE: 'Growth Pipeline',
        SUBTITLE: 'Manage incoming leads and conversion metrics.',
        STATUS: {
            NEW: 'New',
            CONTACTED: 'Contacted',
            CONSULTATION: 'Consultation',
            CONVERTED: 'Converted',
            LOST: 'Lost',
        },
        TABLE: {
            NAME: 'Name',
            CONTACT: 'Contact',
            INTEREST: 'Interest',
            STATUS: 'Status',
            DATE: 'Date',
            ACTIONS: 'Actions',
        },
        MESSAGES: {
            LOADING: 'Loading leads...',
            EMPTY_SEARCH: 'No leads match your search.',
            EMPTY_LIST: 'No leads yet.',
            CONFIRM_DELETE: 'Are you sure you want to delete this lead?',
        },
    },
    LOCATIONS: {
        TITLE: 'Branch Mapping',
        SUBTITLE: 'Regional branch offices and service areas.',
        MESSAGES: {
            SUCCESS: 'Location saved successfully!',
            ERROR: 'Failed to save location.',
            ERROR_SUBMISSION: 'Submission error. Please try again.',
        },
        FORM: {
            DISCARD_TITLE: 'Discard Changes?',
            DISCARD_DESC: 'You have unsaved changes that will be lost.',
            NAME: 'Branch Name',
            MANAGER: 'Branch Manager',
            MANAGER_SELECT: 'Select a manager...',
            CAPACITY: 'Client Capacity',
            ADDRESS: 'Address',
            CANCEL: 'Cancel',
            SAVE_BTN: 'Save Branch',
            SAVING: 'Saving...',
        },
    },
} as const;
