// Governance - Category: service | Purpose: Core implementation file for the Base platform logic.
import { baseAdminContent } from './base-admin';
import { baseGrowthContent } from './base-growth';

const baseCoreContent = {
    APP: {
        NAME: 'PrimeCare',
        TAGLINE: 'Compassionate Care, Professional Service',
    },
    AUTH: {
        LOGIN_TITLE: 'Sign in to your account',
        LOGIN_TITLE_CLIENT: 'Client Portal Login',
        LOGIN_TITLE_STAFF: 'Staff Portal Login',
        LOGIN_TITLE_PSW: 'Caregiver Portal Login',
        LOGIN_TITLE_RN: 'Registered Nurse Portal Login',
        BUTTON: 'Sign in',
        BUTTON_CLIENT: 'Sign In as Client',
        BUTTON_PSW: 'Sign In as Caregiver',
        BUTTON_RN: 'Sign In as RN',
        BUTTON_STAFF: 'Sign In as Staff',
        EMAIL_LABEL: 'Email address',
        PASSWORD_LABEL: 'Password',
        FORGOT_PASSWORD: 'Forgot password?',
        REGISTER_TITLE: 'Create your account',
        BUTTON_REGISTER: 'Sign up',
        SIGNUP_LINK: "Don't have an account? Sign up",
    },
    ROLES: {
        ADMIN: 'Master Franchise',
        STAFF: 'Staff Member',
        PSW: 'Personal Support Worker',
        RN: 'Registered Nurse',
        CLIENT: 'Client',
        COORDINATOR: 'Scheduling Coordinator',
        FINANCE: 'Finance Manager',
        HR: 'HR Manager',
        COMPLIANCE: 'Compliance Officer',
        CRM: 'Client Relationship Manager',
        TRAINING: 'Training Manager',
    },
    ROLE_LABELS: {
        ADMIN: 'Master Franchise',
        SCRUM_MASTER: 'Scrum Master (Orchestrator)',
        MANAGER: 'Agency Operator',
        STAFF: 'Staff Member',
        PSW: 'Caregiver (PSW)',
        RN: 'Registered Nurse (RN)',
        CLIENT: 'Client / Family',
        FINANCE_DIRECTOR: 'Finance Director',
    },
    MENU: {
        HOME: 'Home',
        USERS: 'Users & PSWs',
        SCHEDULE: 'Schedule',
        INCIDENTS: 'Incidents',
        TIMESHEETS: 'Timesheets',
        LEADS: 'Lead Inquiries',
        SERVICES: 'Services',
        AUDITS: 'Call Audits',
        CONTENT: 'Content',
        REPORTS: 'Reports',
        SETTINGS: 'Settings',
        SUPPORT: 'Support',
        DEVELOPER: 'Developer',
        THEME: 'Theme Center',
        INSIGHTS: 'Insights',
        CLINICAL_AI: 'Clinical AI',
        INTEROPERABILITY: 'Interoperability',
        AUTOMATION: 'Automation',
        GROWTH: 'Growth Strategy',
        KNOWLEDGE_BASE: 'Knowledge Base',
        RESELLER: 'Reseller Hub',
        MARKETPLACE: 'Marketplace',
        PRIVATE_MARKET: 'Private Market',
        IDENTITY: 'My Identity',
        TRAINING: 'System Training',
        DEV_AUDIT: 'Developer Audit',
        CLIENT_HUB: 'My Care Hub',
        CLIENT_BOOKINGS: 'My Bookings',
        CLIENT_BILLING: 'Billing',
        PROFILE: 'Account Profile',
        STAFF_HUB: 'Staff Hub',
        CUSTOMERS: 'Customer Mgmt',
        TICKETS: 'Tickets',
        WORK_SCHEDULE: 'Work Schedule',
        OPEN_SHIFTS: 'Open Shifts',
        MY_SHIFTS: 'My Shifts',
        MY_EARNINGS: 'My Earnings',
        MY_CREDENTIALS: 'My Credentials',
        HELP_DESK: 'Help Desk',
        CLINICAL_HOME: 'Clinical Home',
        ACCOUNTING_INTELLIGENCE: 'Accounting Intelligence',
        CLINIENT_ADMISSION: 'Clients admission',
        DAILY_ENTRY: 'Daily Entry',
        EVALUATIONS: 'Evaluations',
        SERVICE_REVIEW: 'Service Review',
        ONBOARDING: 'Onboarding',
        COMPLIANCE: 'Compliance',
        INQUIRIES: 'Inquiries',
        SATISFACTION: 'Satisfaction',
        MODULES: 'Modules',
        SKILLS: 'Staff Skills',
        CARE_PLANS: 'Care Plans',
    },
    LAYOUT: {
        LOGOUT: 'Sign Out',
        PROFILE_TITLE: 'Account Profile',
        PERSPECTIVE: 'Perspective',
        IMPERSONATING: 'Impersonating profile',
        SWITCH_PERSPECTIVE: 'Choose Perspective',
        SEARCH_USERS: 'Search system users...',
        ONLINE_STATUS: 'STATUS: ONLINE',
        FULLSCREEN_ENTER: 'Enter Fullscreen',
        FULLSCREEN_EXIT: 'Exit Fullscreen',
        MOBILE_MENU: 'Toggle Menu',
        SEARCH_LABEL: 'Search Registry',
        LOGGED_IN_AS: 'Active Session: ',
        PERSPECTIVE_MODAL: {
            TITLE_MAIN: 'Umbrella Perspective',
            TITLE_IMPERSONATE: 'User Impersonation Tool',
            SUBTITLE_MAIN: 'Switch between platform umbrellas or impersonate users',
            SUBTITLE_IMPERSONATE: 'Viewing system as another user',
            SECTION_ROLE: 'SWITCH UMBRELLA',
            SECTION_IMPERSONATE: 'SEARCH SYSTEM USERS',
            EXIT_IMPERSONATE: 'EXIT IMPERSONATION',
            SEARCH_PLACEHOLDER: 'Search by name, email or UID...',
            IMPERSONATE_ACTION: 'IMPERSONATE →',
            GROUPS: {
                ADMIN: 'Administration',
                STAFF: 'Staff Operations',
                MANAGEMENT: 'Management',
                HEALTHCARE: 'Healthcare Workers',
            }
        }
    },
    COMMON: {
        LOAD_MORE: 'Load More',
        RETRY: 'Retry',
        SEARCH_PLACEHOLDER: 'Search...',
        NO_RESULTS: 'No results found.',
        SAVE: 'Save',
        CLOSE: 'Close',
        BACK: 'Back',
        EDIT: 'Edit',
        DELETE: 'Delete',
        NETWORK_ERROR: 'Network error',
        PROCESSING: 'Processing...',
        FALLBACKS: {
            REGISTRY_NODE: 'Registry Node',
            CARE_SERVICE: 'Care Service',
            NA: 'N/A',
            TBD: 'TBD',
        },
        UNITS: {
            MMHG: 'mmHg',
            METERS: 'm',
            HOURS: 'h',
        },
        TABLE: {
            NAME: 'Name',
            EMAIL: 'Email',
            PHONE: 'Phone',
            DATE: 'Date',
            STATUS: 'Status',
            ACTIONS: 'Actions',
            SEARCH_PLACEHOLDER: 'Search records...',
            NO_RESULTS: 'No matching records found.',
            LOADING: 'Synchronizing data...',
        }
    },
} as const;

export const baseContent = {
    ...baseCoreContent,
    ...baseAdminContent,
    ...baseGrowthContent,
} as const;
