export const opsDailyContent = {
    DAILY_ENTRY: {
        TITLE: 'Daily Care Entry',
        LEFT_PANEL_TITLE: 'Select Context',
        CLIENT_LABEL: 'Client',
        CLIENT_PLACEHOLDER: 'Select Client...',
        TIP_TITLE: '💡 Tip',
        TIP_CONTENT: 'Auto-save is enabled for drafts. Submitting requires a signature.',
        ADL_TITLE: 'ADL Checklist',
        VITALS_TITLE: 'Vitals & Wellness',
        VITALS: {
            BP: 'BP',
            PULSE: 'Pulse',
            TEMP: 'Temp',
            MOOD_LABEL: 'Client Mood (1-5)',
        },
        NOTES_TITLE: 'Notes & Signature',
        NOTES_PLACEHOLDER: 'Daily progress notes, observations, or incidents...',
        SIGNATURE_LABEL: 'Digital Signature',
        SIGNATURE_PLACEHOLDER: 'Type full name to sign',
        SAVE_DRAFT: 'Save Draft',
        SUBMIT: 'Submit Entry',
        SUBMITTING: 'Submitting...',
        GUARD: {
            TITLE: 'Unsaved Changes',
            DESC: 'You have unsaved changes. Navigating away will discard them. Would you like to stay and save?',
            LEAVE: 'Leave',
            STAY: 'Stay',
        },
        MESSAGES: {
            SELECT_CLIENT: 'Please select a client',
            SIGNATURE_REQUIRED: 'Signature required for submission',
            SUCCESS_DRAFT: 'Draft saved!',
            SUCCESS_SUBMIT: 'Daily entry submitted successfully!',
            ERROR_SAVE: 'Failed to save entry',
            ERROR_SERVER: 'Error communicating with server',
        }
    },
    INVOICES: {
        TITLE: 'Invoice Management',
        SUBTITLE: 'Generate and track billing across the network.',
        FORM: {
            CREATE_TITLE: 'Create New Invoice',
            DESC_PLACEHOLDER: 'Description of service',
            AMOUNT_PLACEHOLDER: 'Amount ($)',
            ADD_ITEM: '+ Add Line Item',
            SUBMIT_BTN: 'Generate & Send Invoice',
            CANCEL_BTN: 'Cancel',
            DISCARD_TITLE: 'Discard Invoice?',
            DISCARD_DESC: 'Are you sure you want to cancel this invoice? Unsaved changes will be lost.',
        },
        MESSAGES: {
            SUCCESS_GENERATE: 'Invoice generated and sent successfully',
            ERROR_GENERATE: 'Failed to generate invoice',
        }
    },
    REPORTS: {
        TITLE: 'Reports & Analytics',
        SUBTITLE: 'Visualize key performance indicators and operational metrics.',
        EXPORT_BTN: 'Export CSV',
        DATE_RANGES: {
            7: 'Last 7 Days',
            30: 'Last 30 Days',
            90: 'Last Quarter',
            YEAR: 'Year to Date',
        },
        TABS: {
            OVERVIEW: 'Overview',
            FINANCIAL: 'Financials',
            STAFF: 'Staff Utilization',
            CLIENTS: 'Client Growth',
        }
    },
    MANAGER_COMPLIANCE: {
        TITLE: 'Branch Compliance Monitor',
        SUBTITLE: 'Audit staff and client documentation parity.',
        ALERTS: {
            MISSED_VISIT: 'Missed Visit Alert',
            LATE_ENTRY: 'Late Daily Entry',
            DOC_GAP: 'Missing Clinical Note',
        },
        STATUS: {
            COMPLIANT: 'Compliant',
            NON_COMPLIANT: 'Non-Compliant',
            EXPIRING: 'Expiring Soon',
            PENDING: 'Pending Review',
            WARNING: 'Compliance Warning',
            SYNCED: 'Satellite Synchronized',
        },
        TABLE: {
            PROVIDER: 'Clinical Provider',
            CAREGIVER: 'Caregiver',
            CLIENT: 'Client',
            VISIT: 'Visit Type',
            DOCUMENT: 'Clinical Document',
            COMPLIANCE: 'Compliance Status',
            STATUS: 'Overall Status',
            EXPIRY: 'Expiration Date',
            DATE: 'Last Activity',
        },
        MESSAGES: {
            AUDIT_DONE: 'Compliance Audit completed successfully',
            SUCCESS_AUDIT: 'Compliance Audit Complete',
            SYNC_SUCCESS: 'Registry Synchronized',
            ERROR_AUDIT: 'Failed to complete audit',
        }
    },
    EARNINGS: {
        TITLE: 'Earnings Center',
        SUBTITLE: 'Enterprise-grade financial oversight and payout management',
        STATS: {
            REVENUE: 'Total Revenue',
            PAYROLL: 'Total Payroll',
            PROFIT: 'Net Profit',
            PENDING: 'Payouts Pending',
        },
        TABS: {
            OVERVIEW: 'Overview',
            INVOICES: 'Invoices',
            PAYOUTS: 'Payouts',
            REPORTS: 'Reports',
        },
        ACTIONS: {
            EXPORT: 'Export Report',
            DATE_RANGE: 'Date Range',
            FILTER_ACTIVE: 'Filter Active',
        },
        INVOICE_ID: 'Invoice ID',
        CLIENT: 'Client',
        PSW: 'PSW',
        REVENUE: 'Revenue',
        PAYROLL: 'Payroll',
        PROFIT: 'Profit',
    },
    STAFF_PORTAL: {
        TASKS: {
            TITLE: 'Operational Tasks',
            SUBTITLE: 'Daily workflow management',
            EMPTY: 'No pending tasks.',
        },
        MESSAGES: {
            FETCH_ERROR: 'Failed to load messages',
            SAVE_SUCCESS: 'Message sent successfully!',
            SAVE_ERROR: 'Failed to send message',
            SEND_BTN: 'Send Message',
            TITLE: 'Message Center',
            INPUT_PLACEHOLDER: 'Type your message here...',
            SEARCH_PLACEHOLDER: 'Search messages...',
            LOADING: 'Loading messages...',
        }
    },
    WAITLIST: {
        TITLE: 'Inflow Waitlist',
        SUBTITLE: 'Pending client admissions',
        EMPTY: 'Waitlist is clear.',
    },
    QUICK_ACTIONS: {
        TITLE: 'Quick Actions',
        ADD_CLIENT: 'Add Client',
        ADD_STAFF: 'Add Staff',
        ADD_USER: 'Add User',
        CREATE_VISIT: 'Create Visit',
        POST_SHIFT: 'Post Shift',
        FINAL_CHECK: 'Final Check',
        LOG_INCIDENT: 'Log Incident',
        BROADCAST: 'Broadcast SOS',
        CRISIS_ALERTS: 'Crisis Alerts',
        CRISIS_ACTIVE: 'CRISIS ACTIVE',
        WAITING: 'WAITING',
        MESSAGES: {
            SUCCESS: 'Action completed successfully',
            SYNC_SUCCESS: 'Registry Synchronized',
            CRISIS_ACTIVATED: 'CRISIS ACTIVATED',
            CRISIS_DEACTIVATED: 'CRISIS DEACTIVATED',
            CRISIS_DEACTIVATE: 'Are you sure you want to deactivate the crisis alert?',
            CRISIS_CONFIRM: 'Are you sure you want to broadcast a crisis alert?',
            ADMIN_ONLY: 'This action is restricted to administrators',
            TEMP_ERROR: 'Temporary Error',
            ERROR: 'Failed to complete action',
        }
    },
} as const;
