import type { PageType, PageEntry, MasterEntry } from '../PageRegistry';

export const MASTER_REGISTRY: Record<string, MasterEntry> = {
    // ── Auth Forms (F1–F5) ──
    F1:  { file: 'apps/web-admin/src/app/routes/auth/pages/login/F1-Login.tsx',                     label: 'Login',           type: 'form', owner: 'auth', associates: ['F2', 'F3'] },
    F2:  { file: 'apps/web-admin/src/app/routes/auth/pages/register/F2-Register.tsx',               label: 'Register',        type: 'form', owner: 'auth', associates: ['F1'] },
    F3:  { file: 'apps/web-admin/src/app/routes/auth/pages/forgot-password/F3-ForgotPassword.tsx',  label: 'Forgot Password', type: 'form', owner: 'auth', associates: ['F1', 'F4'] },
    F4:  { file: 'apps/web-admin/src/app/routes/auth/pages/reset-password/F4-ResetPassword.tsx',    label: 'Reset Password',  type: 'form', owner: 'auth', associates: ['F3'] },
    F5:  { file: 'apps/web-admin/src/app/routes/auth/pages/onboard-business/F5-BusinessOnboard.tsx',label: 'Business Onboard',type: 'form', owner: 'auth', associates: ['W1'] },
    // ── Admin Dashboards (D1–D6) ──
    D1:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/dashboard/D1-AdminDashboard.tsx',     label: 'Admin Dashboard',     type: 'dashboard', owner: 'admin', associates: ['D2', 'G1', 'G2'] },
    D2:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/dashboard/D2-RegistrySummary.tsx',    label: 'Registry Summary',    type: 'dashboard', owner: 'admin', associates: ['D1', 'G1', 'G2'] },
    D3:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/security/D3-AccountingDashboard.tsx', label: 'Accounting Dashboard',type: 'dashboard', owner: 'admin', associates: ['T17', 'T18', 'T59'] },
    D4:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/evv/D4-EvvDashboard.tsx',             label: 'EVV Dashboard',       type: 'dashboard', owner: 'admin', associates: ['L22', 'R8'] },
    D5:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/ai/D5-AiDashboard.tsx',               label: 'AI Dashboard',        type: 'dashboard', owner: 'admin', associates: ['T52', 'T53', 'T54', 'T55'] },
    D6:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/cron/D6-CronDashboard.tsx',           label: 'Cron Dashboard',      type: 'dashboard', owner: 'admin', associates: ['T7'] },
    // ── Admin Forms (F6–F12) ──
    F6:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/admission/F6-ClientAdmission.tsx',              label: 'Client Admission',     type: 'form', owner: 'admin', associates: ['F7'] },
    F7:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/onboarding/F7-StaffOnboarding.tsx',             label: 'Staff Onboarding',     type: 'form', owner: 'admin', associates: ['F6', 'W2'] },
    F8:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/timesheet-adjustment/F8-TimesheetAdjustment.tsx',label: 'Timesheet Adjustment', type: 'form', owner: 'admin', associates: ['L4'] },
    F9:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/invoices/F9-InvoiceEntry.tsx',                  label: 'Invoice Entry',        type: 'form', owner: 'admin', associates: ['H3'] },
    F9a: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/users/F9a-UserEntry.tsx',                       label: 'User Entry',           type: 'form', owner: 'admin', associates: ['L3a'] },
    F10: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/incidents/F10-IncidentEntry.tsx',               label: 'Incident Entry',       type: 'form', owner: 'admin', associates: ['L2'] },
    F11: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/leads/F11-LeadEntry.tsx',                       label: 'Lead Entry',           type: 'form', owner: 'admin', associates: ['L3', 'T66'] },
    F12: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/locations/F12-Locations.tsx',                   label: 'Locations',            type: 'form', owner: 'admin', associates: ['T64'] },
    // ── Admin Lists (L1–L15, L22) ──
    L1:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/schedule/L1-Schedule.tsx',                label: 'Schedule',           type: 'list', owner: 'admin', associates: ['L16'] },
    L2:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/incidents/L2-IncidentList.tsx',           label: 'Incident List',      type: 'list', owner: 'admin', associates: ['F10'] },
    L3:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/leads/L3-LeadList.tsx',                   label: 'Lead List',          type: 'list', owner: 'admin', associates: ['F11', 'T66'] },
    L3a: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/users/L3a-UserList.tsx',                  label: 'User List',          type: 'list', owner: 'admin', associates: ['F9a'] },
    L4:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/timesheets/L4-Timesheets.tsx',            label: 'Timesheets',         type: 'list', owner: 'admin', associates: ['F8'] },
    L5:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/services/L5-Services.tsx',                label: 'Services',           type: 'list', owner: 'admin', associates: ['T34'] },
    L6:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/audits/L6-AuditLogs.tsx',                 label: 'Audit Logs',         type: 'list', owner: 'admin', associates: ['R9', 'R10', 'R13'] },
    L7:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/authorizations/L7-AuthList.tsx',          label: 'Auth List',          type: 'list', owner: 'admin', associates: ['T49', 'R6'] },
    L8:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/consent/L8-ConsentList.tsx',              label: 'Consent List',       type: 'list', owner: 'admin', associates: ['T50', 'R7'] },
    L9:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/referrals/L9-ReferralList.tsx',           label: 'Referral List',      type: 'list', owner: 'admin', associates: ['R11'] },
    L10: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/claims/L10-ClaimsList.tsx',               label: 'Claims List',        type: 'list', owner: 'admin', associates: ['R12'] },
    L11: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/webhooks/L11-WebhookList.tsx',            label: 'Webhook List',       type: 'list', owner: 'admin', associates: ['T51'] },
    L12: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/booking-requests/L12-BookingRequestQueue.tsx', label: 'Booking Queue', type: 'list', owner: 'admin', associates: ['L14', 'F17'] },
    L15: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/customers/L15-CustomerList.tsx',          label: 'Customer List',      type: 'list', owner: 'admin', associates: ['T4'] },
    L22: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/evv/L22-EvvExceptions.tsx',               label: 'EVV Exceptions',     type: 'list', owner: 'admin', associates: ['D4', 'R8'] },
    // ── Admin Hubs (H1–H9, H19) ──
    H1:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/telehealth/H1-TelehealthCenter.tsx',  label: 'Telehealth Center', type: 'hub', owner: 'admin', associates: ['T8'] },
    H2:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/pharmacy/H2-PharmacyHub.tsx',         label: 'Pharmacy Hub',      type: 'hub', owner: 'admin', associates: ['H4'] },
    H3:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/rcm/H3-RevenueCycleHub.tsx',          label: 'Revenue Cycle Hub', type: 'hub', owner: 'admin', associates: ['F9'] },
    H4:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/erp/H4-SupplyChainHub.tsx',           label: 'Supply Chain Hub',  type: 'hub', owner: 'admin', associates: ['H20'] },
    H5:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/notifications/H5-NotificationsHub.tsx',label: 'Notifications Hub', type: 'hub', owner: 'admin', associates: ['H6'] },
    H6:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/documents/H6-DocumentCenter.tsx',     label: 'Document Center',   type: 'hub', owner: 'admin', associates: ['H5'] },
    H7:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/payroll/H7-PayrollHub.tsx',            label: 'Payroll Hub',       type: 'hub', owner: 'admin', associates: ['T24', 'D9'] },
    H8:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/knowledge-base/H8-KnowledgeBase.tsx', label: 'Knowledge Base',    type: 'hub', owner: 'admin', associates: ['T48'] },
    H9:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/reference-data/H9-ReferenceDataHub.tsx',label: 'Reference Data',   type: 'hub', owner: 'admin', associates: ['T11'] },
    H19: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/setup/H19-WizardHub.tsx',             label: 'Wizard Hub',        type: 'hub', owner: 'admin', associates: ['W1', 'W2', 'W3', 'W4', 'W5', 'T12'] },
    // ── Admin Wizards (W1–W5) ──
    W1:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/setup/W1-BusinessSetupWizard.tsx',    label: 'Business Setup',    type: 'wizard', owner: 'admin', associates: ['H19', 'T12'] },
    W2:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/setup/W2-StaffOnboardingWizard.tsx',  label: 'Staff Onboarding',  type: 'wizard', owner: 'admin', associates: ['H19', 'F7'] },
    W3:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/setup/W3-CarePlanWizard.tsx',         label: 'Care Plan',         type: 'wizard', owner: 'admin', associates: ['H19'] },
    W4:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/setup/W4-RevenueWizard.tsx',          label: 'Revenue',           type: 'wizard', owner: 'admin', associates: ['H19', 'H3'] },
    W5:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/setup/W5-BusinessModelWizard.tsx',    label: 'Business Model',    type: 'wizard', owner: 'admin', associates: ['H19'] },
    // ── Admin Reports (R1–R2, R6–R13) ──
    R1:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/reports/R1-ReportCenter.tsx',            label: 'Report Center',     type: 'report', owner: 'admin', associates: ['R2'] },
    R2:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/reports/R2-ExportPage.tsx',              label: 'Export Page',       type: 'report', owner: 'admin', associates: ['R1'] },
    R6:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/authorizations/R6-AuthUtilization.tsx', label: 'Auth Utilization',  type: 'report', owner: 'admin', associates: ['L7', 'T49'] },
    R7:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/consent/R7-ConsentExpiring.tsx',        label: 'Consent Expiring',  type: 'report', owner: 'admin', associates: ['L8', 'T50'] },
    R8:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/evv/R8-EvvExport.tsx',                  label: 'EVV Export',        type: 'report', owner: 'admin', associates: ['D4', 'L22'] },
    R9:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/audit-export/R9-AuditDownload.tsx',     label: 'Audit Download',    type: 'report', owner: 'admin', associates: ['L6', 'R10', 'R13'] },
    R10: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/audit-export/R10-ComplianceExport.tsx', label: 'Compliance Export', type: 'report', owner: 'admin', associates: ['L6', 'R9', 'R13'] },
    R11: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/referrals/R11-ReferralAnalytics.tsx',   label: 'Referral Analytics',type: 'report', owner: 'admin', associates: ['L9'] },
    R12: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/claims/R12-ClaimsEra.tsx',              label: 'Claims ERA',        type: 'report', owner: 'admin', associates: ['L10'] },
    R13: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/audit-export/R13-RegulatoryExport.tsx', label: 'Regulatory Export', type: 'report', owner: 'admin', associates: ['L6', 'R9', 'R10'] },
    // ── Admin Tools (T1–T18, T48–T59, T66–T67) ──
    T1:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/search/T1-SearchPage.tsx',              label: 'Search',            type: 'tool', owner: 'admin', associates: ['T2'] },
    T2:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/content/T2-ContentManager.tsx',         label: 'Content Manager',   type: 'tool', owner: 'admin', associates: ['T1', 'T3'] },
    T3:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/template-editor/T3-TemplateEditor.tsx', label: 'Template Editor',   type: 'tool', owner: 'admin', associates: ['T2'] },
    T4:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/role-editor/T4-RoleEditor.tsx',         label: 'Role Editor',       type: 'tool', owner: 'admin', associates: ['L15'] },
    T5:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/interoperability/T5-FHIRCenter.tsx',    label: 'FHIR Center',       type: 'tool', owner: 'admin', associates: ['T6'] },
    T6:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/sovereign/T6-SovereignWallet.tsx',      label: 'Sovereign Wallet',  type: 'tool', owner: 'admin', associates: ['T5'] },
    T7:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/automation/T7-AutoPilot.tsx',           label: 'AutoPilot',         type: 'tool', owner: 'admin', associates: ['D6'] },
    T8:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/clinical-assistant/T8-ClinicalAssistant.tsx', label: 'Clinical Assistant', type: 'tool', owner: 'admin', associates: ['H1', 'T9'] },
    T9:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/insights/T9-AiInsights.tsx',            label: 'AI Insights',       type: 'tool', owner: 'admin', associates: ['T8', 'D5'] },
    T10: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/security/T10-SecurityGovernance.tsx',   label: 'Security Gov',      type: 'tool', owner: 'admin', associates: ['T13', 'T14', 'T15', 'T16', 'T56', 'T57', 'T58'] },
    T11: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/settings/T11-Settings.tsx',             label: 'Settings',          type: 'tool', owner: 'admin', associates: ['D1'] },
    T12: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/setup/T12-BusinessStatus.tsx',          label: 'Business Status',   type: 'tool', owner: 'admin', associates: ['H19', 'W1'] },
    T13: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/security/T13-DeviceManagement.tsx',     label: 'Device Mgmt',       type: 'tool', owner: 'admin', associates: ['T10'] },
    T14: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/security/T14-ForensicTrails.tsx',       label: 'Forensic Trails',   type: 'tool', owner: 'admin', associates: ['T10'] },
    T15: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/security/T15-CorsSettings.tsx',         label: 'CORS Settings',     type: 'tool', owner: 'admin', associates: ['T10'] },
    T16: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/security/T16-IntegrityVerification.tsx',label: 'Integrity Verify',  type: 'tool', owner: 'admin', associates: ['T10'] },
    T17: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/security/T17-FinancialLedger.tsx',      label: 'Financial Ledger',  type: 'tool', owner: 'admin', associates: ['D3', 'T18', 'T59'] },
    T18: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/security/T18-TaxComplianceHub.tsx',     label: 'Tax Compliance',    type: 'tool', owner: 'admin', associates: ['D3', 'T17'] },
    T48: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/knowledge-base/T48-KBArticle.tsx',     label: 'KB Article',        type: 'tool', owner: 'admin', associates: ['H8'] },
    T49: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/authorizations/T49-AuthAlerts.tsx',     label: 'Auth Alerts',       type: 'tool', owner: 'admin', associates: ['L7', 'R6'] },
    T50: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/consent/T50-ConsentTemplates.tsx',      label: 'Consent Templates', type: 'tool', owner: 'admin', associates: ['L8', 'R7'] },
    T51: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/webhooks/T51-WebhookDeliveries.tsx',    label: 'Webhook Deliveries',type: 'tool', owner: 'admin', associates: ['L11'] },
    T52: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/ai/T52-PredictiveAnalytics.tsx',        label: 'Predictive Analytics',type: 'tool', owner: 'admin', associates: ['D5', 'T53', 'T54', 'T55'] },
    T53: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/ai/T53-ChurnRisk.tsx',                  label: 'Churn Risk',        type: 'tool', owner: 'admin', associates: ['D5', 'T52', 'T54', 'T55'] },
    T54: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/ai/T54-VisitOptimization.tsx',          label: 'Visit Optimization',type: 'tool', owner: 'admin', associates: ['D5', 'T52', 'T53', 'T55'] },
    T55: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/ai/T55-SentimentAnalysis.tsx',          label: 'Sentiment Analysis',type: 'tool', owner: 'admin', associates: ['D5', 'T52', 'T53', 'T54'] },
    T56: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/security/T56-PermissionGrid.tsx',       label: 'Permission Grid',   type: 'tool', owner: 'admin', associates: ['T10'] },
    T57: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/security/T57-SessionMonitor.tsx',       label: 'Session Monitor',   type: 'tool', owner: 'admin', associates: ['T10'] },
    T58: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/security/T58-ThreatDetection.tsx',      label: 'Threat Detection',  type: 'tool', owner: 'admin', associates: ['T10'] },
    T59: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/finance/reconciliation/T59-Reconciliation.tsx', label: 'Reconciliation', type: 'tool', owner: 'admin', associates: ['D3', 'T17'] },
    T66: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/leads/T66-LeadConversion.tsx',          label: 'Lead Conversion',   type: 'tool', owner: 'admin', associates: ['L3', 'F11'] },
    T67: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/ops/T67-SupplyDemand.tsx',              label: 'Supply & Demand',   type: 'tool', owner: 'admin', associates: ['H20'] },
    // ── Manager Portal ──
    D7:  { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/dashboard/D7-ManagerDashboard.tsx', label: 'Manager Dashboard', type: 'dashboard', owner: 'manager', associates: ['H12', 'D9', 'D10', 'T19', 'L13', 'T21', 'H11', 'T22', 'T23', 'T25'] },
    D9:  { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/finance/D9-BranchPL.tsx',           label: 'Branch P&L',       type: 'dashboard', owner: 'manager', associates: ['H7', 'T24'] },
    D10: { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/D10-RegionalStats.tsx',             label: 'Regional Stats',   type: 'dashboard', owner: 'manager', associates: ['D7'] },
    D11: { file: 'apps/web-admin/src/app/routes/tenancy/marketing/D11-MarketingDashboard.tsx',            label: 'Marketing',        type: 'dashboard', owner: 'manager', associates: ['D7'] },
    D12: { file: 'apps/web-admin/src/app/routes/tenancy/finance/D12-FinanceRegionalHub.tsx',              label: 'Finance Regional', type: 'dashboard', owner: 'manager', associates: ['D7', 'D9'] },
    D13: { file: 'apps/web-admin/src/app/routes/tenancy/qa/D13-ClinicalQaDashboard.tsx',                  label: 'Clinical QA',      type: 'dashboard', owner: 'manager', associates: ['D15'] },
    H11: { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/training/H11-TrainingHub.tsx',      label: 'Training Hub',     type: 'hub', owner: 'manager', associates: ['D7'] },
    H12: { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/operations/H12-OperationsHub.tsx',  label: 'Operations Hub',   type: 'hub', owner: 'manager', associates: ['D7'] },
    H13: { file: 'apps/web-admin/src/app/routes/tenancy/hr/H13-HrRecruitmentPortal.tsx',                  label: 'HR Recruitment',   type: 'hub', owner: 'manager', associates: ['D7'] },
    L13: { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/evaluations/L13-Evaluations.tsx',   label: 'Evaluations',      type: 'list', owner: 'manager', associates: ['D7'] },
    T19: { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/portfolio/T19-Portfolio.tsx',        label: 'Portfolio',        type: 'tool', owner: 'manager', associates: ['D7'] },
    T20: { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/daily-entry/T20-DailyEntry.tsx',    label: 'Daily Entry',      type: 'tool', owner: 'manager', associates: ['D7'] },
    T21: { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/service-review/T21-ServiceReview.tsx',label: 'Service Review',  type: 'tool', owner: 'manager', associates: ['D7'] },
    T22: { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/surveys/T22-SurveyManager.tsx',     label: 'Survey Manager',   type: 'tool', owner: 'manager', associates: ['D7'] },
    T23: { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/performance/T23-StaffRanker.tsx',   label: 'Staff Ranker',     type: 'tool', owner: 'manager', associates: ['D7'] },
    T24: { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/finance/T24-PayrollVerification.tsx',label: 'Payroll Verify',   type: 'tool', owner: 'manager', associates: ['H7', 'D9'] },
    T25: { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/compliance/T25-ComplianceSync.tsx', label: 'Compliance Sync',  type: 'tool', owner: 'manager', associates: ['D7'] },
    // ── PSW Portal ──
    D14: { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/dashboard/D14-PswDashboard.tsx',              label: 'PSW Dashboard',    type: 'dashboard', owner: 'psw', associates: ['L16', 'F13', 'F14', 'F15', 'R3'] },
    F13: { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/handover/F13-ShiftHandover.tsx',              label: 'Shift Handover',   type: 'form', owner: 'psw', associates: ['D14'] },
    F14: { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/expenses/F14-ExpenseClaim.tsx',               label: 'Expense Claim',    type: 'form', owner: 'psw', associates: ['R4'] },
    F15: { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/availability/F15-Availability.tsx',           label: 'Availability',     type: 'form', owner: 'psw', associates: ['D14'] },
    H14: { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/credentials/H14-CredentialVault.tsx',         label: 'Credential Vault', type: 'hub', owner: 'psw', associates: ['H15'] },
    H15: { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/training/H15-PswTrainingHub.tsx',             label: 'PSW Training',     type: 'hub', owner: 'psw', associates: ['H14'] },
    L16: { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/schedule/L16-PswSchedule.tsx',                label: 'PSW Schedule',     type: 'list', owner: 'psw', associates: ['L17', 'T60', 'T61', 'T62'] },
    L17: { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/OpenShifts/L17-OpenShifts.tsx',               label: 'Open Shifts',      type: 'list', owner: 'psw', associates: ['L16', 'T60'] },
    R3:  { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/earnings/R3-PswEarnings.tsx',                 label: 'PSW Earnings',     type: 'report', owner: 'psw', associates: ['R4'] },
    R4:  { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/payouts/R4-PayoutHistory.tsx',                label: 'Payout History',   type: 'report', owner: 'psw', associates: ['F14', 'R3'] },
    T26: { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/shift-confirmation/T26-ShiftConfirmation.tsx',label: 'Shift Confirm',    type: 'tool', owner: 'psw', associates: ['D14'] },
    T27: { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/feed/T27-ProviderSocial.tsx',                 label: 'Provider Social',  type: 'tool', owner: 'psw', associates: ['D14'] },
    T28: { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/mileage/T28-MileageTracker.tsx',              label: 'Mileage Tracker',  type: 'tool', owner: 'psw', associates: ['D14'] },
    T60: { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/OpenShifts/T60-OpenOffers.tsx',               label: 'Open Offers',      type: 'tool', owner: 'psw', associates: ['L17', 'L16'] },
    T61: { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/schedule/T61-LiveVisit.tsx',                  label: 'Live Visit',       type: 'tool', owner: 'psw', associates: ['L16', 'T62'] },
    T62: { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/schedule/T62-CheckInScreen.tsx',              label: 'Check-In',         type: 'tool', owner: 'psw', associates: ['L16', 'T61'] },
    // ── RN Portal ──
    D15: { file: 'apps/web-admin/src/app/routes/tenancy/rn/pages/dashboard/D15-RnDashboard.tsx',         label: 'RN Dashboard',    type: 'dashboard', owner: 'rn', associates: ['T29', 'T30', 'H16', 'L18'] },
    D16: { file: 'apps/web-admin/src/app/routes/tenancy/rn/pages/mar/D16-MarDashboard.tsx',              label: 'MAR Dashboard',   type: 'dashboard', owner: 'rn', associates: ['T31'] },
    D17: { file: 'apps/web-admin/src/app/routes/tenancy/rn/pages/wound-care/D17-WoundCareDashboard.tsx', label: 'Wound Care',      type: 'dashboard', owner: 'rn', associates: ['T32'] },
    H16: { file: 'apps/web-admin/src/app/routes/tenancy/rn/pages/supervision/H16-SupervisionHub.tsx',    label: 'Supervision Hub', type: 'hub', owner: 'rn', associates: ['D15'] },
    L18: { file: 'apps/web-admin/src/app/routes/tenancy/rn/pages/assessments/L18-AssessmentsHub.tsx',    label: 'Assessments Hub', type: 'list', owner: 'rn', associates: ['D15'] },
    L19: { file: 'apps/web-admin/src/app/routes/tenancy/rn/pages/rai/L19-RaiAssessments.tsx',            label: 'RAI Assessments', type: 'list', owner: 'rn', associates: ['T33'] },
    T29: { file: 'apps/web-admin/src/app/routes/tenancy/rn/pages/care-plans/T29-CarePlanManager.tsx',    label: 'Care Plan Mgr',   type: 'tool', owner: 'rn', associates: ['D15'] },
    T30: { file: 'apps/web-admin/src/app/routes/tenancy/rn/pages/audit/T30-EntryVerify.tsx',             label: 'Entry Verify',    type: 'tool', owner: 'rn', associates: ['D15'] },
    T31: { file: 'apps/web-admin/src/app/routes/tenancy/rn/pages/mar/T31-MarClient.tsx',                 label: 'MAR Client',      type: 'tool', owner: 'rn', associates: ['D16'] },
    T32: { file: 'apps/web-admin/src/app/routes/tenancy/rn/pages/wound-care/T32-WoundCareClient.tsx',    label: 'Wound Client',    type: 'tool', owner: 'rn', associates: ['D17'] },
    T33: { file: 'apps/web-admin/src/app/routes/tenancy/rn/pages/rai/T33-RaiAssessmentDetail.tsx',       label: 'RAI Detail',      type: 'tool', owner: 'rn', associates: ['L19'] },
    T63: { file: 'apps/web-admin/src/app/routes/tenancy/rn/pages/schedule/T63-RnCheckInScreen.tsx',      label: 'RN Check-In',     type: 'tool', owner: 'rn', associates: ['D15'] },
    // ── Client Portal ──
    D8:  { file: 'apps/web-admin/src/app/routes/tenancy/client/pages/dashboard/D8-ClientDashboard.tsx',      label: 'Client Dashboard', type: 'dashboard', owner: 'client', associates: ['L14', 'H10', 'F16', 'F17', 'T34', 'T35', 'T36', 'T37', 'H17', 'R5', 'P1'] },
    F16: { file: 'apps/web-admin/src/app/routes/tenancy/client/pages/feedback/F16-SubmitFeedback.tsx',       label: 'Submit Feedback',  type: 'form', owner: 'client', associates: ['D8'] },
    F17: { file: 'apps/web-admin/src/app/routes/tenancy/client/pages/request-booking/F17-RequestBooking.tsx',label: 'Request Booking',  type: 'form', owner: 'client', associates: ['L12', 'L14'] },
    H10: { file: 'apps/web-admin/src/app/routes/tenancy/client/pages/billing/H10-BillingHub.tsx',            label: 'Billing Hub',      type: 'hub', owner: 'client', associates: ['D8'] },
    H17: { file: 'apps/web-admin/src/app/routes/tenancy/client/pages/engagement/H17-FamilyCareHub.tsx',      label: 'Family Care Hub',  type: 'hub', owner: 'client', associates: ['D8', 'P1'] },
    L14: { file: 'apps/web-admin/src/app/routes/tenancy/client/pages/bookings/L14-ClientBookings.tsx',       label: 'Client Bookings',  type: 'list', owner: 'client', associates: ['L12', 'F17'] },
    R5:  { file: 'apps/web-admin/src/app/routes/tenancy/client/pages/medical/R5-MedicalSummary.tsx',         label: 'Medical Summary',  type: 'report', owner: 'client', associates: ['D8'] },
    P1:  { file: 'apps/web-admin/src/app/routes/tenancy/client/pages/family/P1-FamilyPortal.tsx',            label: 'Family Portal',    type: 'portal', owner: 'client', associates: ['D8', 'H17'] },
    T34: { file: 'apps/web-admin/src/app/routes/tenancy/client/pages/services/T34-CatalogBrowser.tsx',       label: 'Catalog Browser',  type: 'tool', owner: 'client', associates: ['L5'] },
    T35: { file: 'apps/web-admin/src/app/routes/tenancy/client/pages/support/T35-ClientMessaging.tsx',       label: 'Client Messaging', type: 'tool', owner: 'client', associates: ['D8', 'T37'] },
    T36: { file: 'apps/web-admin/src/app/routes/tenancy/client/pages/team/T36-TeamRoster.tsx',               label: 'Team Roster',      type: 'tool', owner: 'client', associates: ['D8'] },
    T37: { file: 'apps/web-admin/src/app/routes/tenancy/client/pages/support/T37-FeedbackLoop.tsx',          label: 'Feedback Loop',    type: 'tool', owner: 'client', associates: ['D8', 'T35'] },
    // ── Coordinator Portal ──
    H18: { file: 'apps/web-admin/src/app/routes/tenancy/coordinator/pages/hub/H18-CoordinatorHub.tsx',       label: 'Coordinator Hub',  type: 'hub', owner: 'coordinator', associates: ['T38', 'T39', 'L20', 'T40', 'T41'] },
    L20: { file: 'apps/web-admin/src/app/routes/tenancy/coordinator/pages/waitlist/L20-WaitlistManager.tsx', label: 'Waitlist Manager', type: 'list', owner: 'coordinator', associates: ['H18'] },
    T38: { file: 'apps/web-admin/src/app/routes/tenancy/coordinator/pages/map/T38-DispatchMap.tsx',          label: 'Dispatch Map',     type: 'tool', owner: 'coordinator', associates: ['H18'] },
    T39: { file: 'apps/web-admin/src/app/routes/tenancy/coordinator/pages/sos/T39-SosCenter.tsx',            label: 'SOS Center',       type: 'tool', owner: 'coordinator', associates: ['H18'] },
    T40: { file: 'apps/web-admin/src/app/routes/tenancy/coordinator/pages/fleet/T40-FleetManagement.tsx',    label: 'Fleet Management', type: 'tool', owner: 'coordinator', associates: ['H18'] },
    T41: { file: 'apps/web-admin/src/app/routes/tenancy/coordinator/pages/shift-swap/T41-ShiftSwap.tsx',     label: 'Shift Swap',       type: 'tool', owner: 'coordinator', associates: ['H18'] },
    // ── Allied Health / Staff / Ops ──
    D18: { file: 'apps/web-admin/src/app/routes/tenancy/allied-health/D18-AlliedHealthDashboard.tsx',               label: 'Allied Health',     type: 'dashboard', owner: 'allied', associates: ['L21', 'T42'] },
    L21: { file: 'apps/web-admin/src/app/routes/tenancy/allied-health/pages/treatments/L21-TreatmentList.tsx',      label: 'Treatment List',    type: 'list', owner: 'allied', associates: ['D18', 'T42'] },
    T42: { file: 'apps/web-admin/src/app/routes/tenancy/allied-health/pages/sign-off/T42-SignOff.tsx',              label: 'Sign Off',          type: 'tool', owner: 'allied', associates: ['D18', 'L21'] },
    D19: { file: 'apps/web-admin/src/app/routes/tenancy/staff/pages/dashboard/D19-StaffDashboard.tsx',              label: 'Staff Dashboard',   type: 'dashboard', owner: 'staff', associates: ['T43', 'T44', 'T45', 'T46'] },
    T43: { file: 'apps/web-admin/src/app/routes/tenancy/staff/pages/tasks/T43-TaskGrid.tsx',                        label: 'Task Grid',         type: 'tool', owner: 'staff', associates: ['D19'] },
    T44: { file: 'apps/web-admin/src/app/routes/tenancy/staff/pages/messages/T44-MessageCenter.tsx',                label: 'Message Center',    type: 'tool', owner: 'staff', associates: ['D19'] },
    T45: { file: 'apps/web-admin/src/app/routes/tenancy/staff/pages/operations/T45-IncidentPortal.tsx',             label: 'Incident Portal',   type: 'tool', owner: 'staff', associates: ['D19'] },
    T46: { file: 'apps/web-admin/src/app/routes/tenancy/staff/pages/operations/T46-ComplianceMonitor.tsx',          label: 'Compliance Monitor',type: 'tool', owner: 'staff', associates: ['D19'] },
    H20: { file: 'apps/web-admin/src/app/routes/tenancy/admin/pages/ops/H20-LogisticsHub.tsx',                      label: 'Logistics Hub',     type: 'hub', owner: 'admin', associates: ['T64', 'T65', 'T67', 'H4'] },
    T64: { file: 'apps/web-admin/src/app/routes/tenancy/admin/pages/ops/T64-RegionMapping.tsx',                     label: 'Region Mapping',    type: 'tool', owner: 'admin', associates: ['H20', 'T65'] },
    T65: { file: 'apps/web-admin/src/app/routes/tenancy/admin/pages/ops/T65-RealtimeCapacity.tsx',                  label: 'Realtime Capacity', type: 'tool', owner: 'admin', associates: ['H20', 'T64'] },
    // ── Scrum Master / Registries ──
    T47: { file: 'apps/web-admin/src/app/routes/tenancy/scrum-master/pages/T47-ResponseBotAudit.tsx', label: 'Response Bot Audit', type: 'tool', owner: 'scrum-master', associates: ['T7'] },
    G1:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/form-registry/index.tsx',        label: 'Form Registry',     type: 'registry', owner: 'admin', associates: ['G2', 'D2'] },
    G2:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/page-registry/index.tsx',        label: 'Page Registry',     type: 'registry', owner: 'admin', associates: ['G1', 'D2'] },
    // ── Premium Pages (Sprint 3-6) ──
    H25: { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/engagement/H19-GamificationHub.tsx',     label: 'Gamification Hub',     type: 'hub', owner: 'manager', associates: ['D7'] },
    H26: { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/iot/H20-IoTMonitoring.tsx',              label: 'IoT Monitoring',       type: 'hub', owner: 'manager', associates: ['D7'] },
    H27: { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/documents/H21-DocumentSigningCenter.tsx',label: 'Document Signing',     type: 'hub', owner: 'manager', associates: ['D7', 'H6'] },
    H28: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/communications/H22-SMSHub.tsx',           label: 'SMS Hub',              type: 'hub', owner: 'manager', associates: ['D7'] },
    H29: { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/training/H24-TrainingAcademy.tsx',       label: 'Training Academy',     type: 'hub', owner: 'manager', associates: ['H11', 'D7'] },
    L23: { file: 'apps/web-admin/src/app/routes/tenancy/manager/pages/hr/L15-PerformanceReviews.tsx',          label: 'Performance Reviews',  type: 'list', owner: 'manager', associates: ['D7', 'T23'] },
    G3:  { file: 'apps/web-admin/src/app/routes/tenancy/psw/pages/guide/G1-PswUserGuide.tsx',                  label: 'PSW User Guide',       type: 'hub', owner: 'psw', associates: ['D14'] },
    D20: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/ai/D7-AICommandCenter.tsx',               label: 'AI Command Center',    type: 'dashboard', owner: 'admin', associates: ['D5', 'T9'] },
    S8:  { file: 'apps/web-admin/src/app/routes/platform/admin/pages/settings/S8-MultiCurrencySettings.tsx',   label: 'Multi-Currency',       type: 'settings', owner: 'admin', associates: ['T11'] },
    L24: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/security/L16-AuditTrailViewer.tsx',       label: 'Audit Trail Viewer',   type: 'list', owner: 'admin', associates: ['L6', 'T10'] },
    H30: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/franchise/H23-FranchiseManagement.tsx',   label: 'Franchise Management', type: 'hub', owner: 'admin', associates: ['D1'] },
    L25: { file: 'apps/web-admin/src/app/routes/platform/admin/pages/supply-chain/L14-SupplyChainManagement.tsx', label: 'Supply Chain',      type: 'list', owner: 'admin', associates: ['H4'] },
};
