import type { ToolEntry } from '../PageRegistry';

export const ToolRegistry: ToolEntry[] = [
    { id: 'admin.search', label: 'Global Search', route: '/platform/admin/search', owner: 'admin', description: 'Platform-wide search' },
    { id: 'admin.content', label: 'Content Manager', route: '/platform/admin/content', owner: 'admin', description: 'CMS & content publishing' },
    { id: 'admin.template-editor', label: 'Template Editor', route: '/platform/admin/template-editor', owner: 'admin', description: 'Edit email & notification templates' },
    { id: 'admin.role-editor', label: 'Role Editor', route: '/platform/admin/role-editor', owner: 'admin', description: 'RBAC role configuration' },
    { id: 'admin.interop', label: 'FHIR Center', route: '/platform/admin/interop', owner: 'admin', description: 'HL7 FHIR data exchange' },
    { id: 'admin.sovereign', label: 'Sovereign Wallet', route: '/platform/admin/sovereign', owner: 'admin', description: 'Decentralized identity management' },
    { id: 'admin.autopilot', label: 'Clinical AutoPilot', route: '/platform/admin/automation/clinical-autopilot', owner: 'admin', description: 'AI-powered clinical automation' },
    { id: 'admin.clinical-assistant', label: 'Clinical Assistant', route: '/platform/admin/clinical-assistant', owner: 'admin', description: 'AI clinical decision support' },
    { id: 'admin.ai-insights', label: 'AI Insights', route: '/platform/admin/insights', owner: 'admin', description: 'AI-powered platform insights' },
    // Security tools
    { id: 'admin.permission-grid', label: 'Permission Grid', route: '/platform/admin/security/permissions', owner: 'admin', description: 'Visual RBAC permission matrix' },
    { id: 'admin.session-monitor', label: 'Session Monitor', route: '/platform/admin/security/sessions', owner: 'admin', description: 'Active session monitoring' },
    { id: 'admin.threat-detection', label: 'Threat Detection', route: '/platform/admin/security/threats', owner: 'admin', description: 'Security threat monitoring' },
    { id: 'admin.device-registry', label: 'Device Registry', route: '/platform/admin/security/devices', owner: 'admin', description: 'Registered device management' },
    { id: 'admin.forensic-trails', label: 'Forensic Trails', route: '/platform/admin/security/forensic', owner: 'admin', description: 'Deep forensic audit trails' },
    { id: 'admin.cors-settings', label: 'CORS Settings', route: '/platform/admin/security/cors', owner: 'admin', description: 'Cross-origin policy configuration' },
    { id: 'admin.integrity-scan', label: 'Integrity Verification', route: '/platform/admin/security/integrity', owner: 'admin', description: 'Integrity hash verification' },
    { id: 'admin.financial-ledger', label: 'Financial Ledger', route: '/platform/admin/security/ledger', owner: 'admin', description: 'Double-entry accounting ledger' },
    { id: 'admin.tax-hub', label: 'Tax Compliance', route: '/platform/admin/security/tax-hub', owner: 'admin', description: 'HST/GST remittance management' },
    // Scrum Master tools
    { id: 'sm.api-endpoints', label: 'API Endpoints', route: '/platform/scrum-master/api-endpoints', owner: 'scrum-master', description: 'API registry & health' },
    { id: 'sm.pages', label: 'Page Catalog', route: '/platform/scrum-master/pages', owner: 'scrum-master', description: 'Frontend page registry' },
    { id: 'sm.components', label: 'Component Catalog', route: '/platform/scrum-master/components', owner: 'scrum-master', description: 'UI component registry' },
    { id: 'sm.role-flows', label: 'Role Flows', route: '/platform/scrum-master/role-flows', owner: 'scrum-master', description: 'Role-based user journey mapping' },
    { id: 'sm.monitoring', label: 'Monitoring', route: '/platform/scrum-master/monitoring', owner: 'scrum-master', description: 'Live monitoring dashboard' },
    { id: 'sm.env-audit', label: 'Environment Audit', route: '/platform/scrum-master/env-audit', owner: 'scrum-master', description: 'Environment variable audit' },
    { id: 'sm.registry-check', label: 'Registry Check', route: '/platform/scrum-master/registry-check', owner: 'scrum-master', description: 'Registry health check' },
    { id: 'sm.database-schema', label: 'Database Schema', route: '/platform/scrum-master/database-schema', owner: 'scrum-master', description: 'Schema viewer & migration tool' },
    { id: 'sm.theme-center', label: 'Theme Center', route: '/platform/scrum-master/theme-center', owner: 'scrum-master', description: 'Design system & theme tokens' },
    { id: 'sm.performance', label: 'Performance', route: '/platform/scrum-master/performance', owner: 'scrum-master', description: 'Performance profiling' },
    { id: 'sm.build-health', label: 'Build Health', route: '/platform/scrum-master/builds', owner: 'scrum-master', description: 'CI/CD build status' },
    { id: 'sm.security-scans', label: 'Security Scans', route: '/platform/scrum-master/security-scans', owner: 'scrum-master', description: 'Automated security scanning' },
    { id: 'sm.localization', label: 'Localization', route: '/platform/scrum-master/locales', owner: 'scrum-master', description: 'i18n translation management' },
    { id: 'sm.interaction-audit', label: 'Interaction Audit', route: '/platform/scrum-master/interaction-audit', owner: 'scrum-master', description: 'Interactive element audit' },
    { id: 'sm.auto-fix', label: 'Auto-Fix', route: '/platform/scrum-master/auto-fix', owner: 'scrum-master', description: 'Automated issue resolution' },
    { id: 'sm.impersonate', label: 'Impersonate User', route: '/platform/scrum-master/impersonate', owner: 'scrum-master', description: 'User impersonation for debugging' },
    { id: 'sm.response-bot', label: 'Response Bot', route: '/platform/scrum-master/response-bot', owner: 'scrum-master', description: 'Automated response validation' },
    // Coordinator tools
    { id: 'coordinator.dispatch-map', label: 'Dispatch Map', route: '/tenancy/coordinator/dispatch-map', owner: 'coordinator', description: 'Real-time dispatch map' },
    { id: 'coordinator.fleet', label: 'Fleet Tracker', route: '/tenancy/coordinator/fleet', owner: 'coordinator', description: 'Fleet GPS tracking' },
    { id: 'coordinator.shift-swap', label: 'Shift Swap', route: '/tenancy/coordinator/shift-swap', owner: 'coordinator', description: 'Shift swap request management' },
];
