/**
 * Security Route Definitions + Handlers
 * Extracted from security.routes.ts
 */
import { createRoute, z } from '@hono/zod-openapi';

export const securityConfigSchema = z.object({ enforceVpn: z.boolean(), allowedVpnRanges: z.array(z.string()), requireDeviceApproval: z.boolean(), maxDevicesPerUser: z.number() });
export const corsConfigSchema = z.object({ corsAllowedOrigins: z.array(z.string()), corsAllowedMethods: z.array(z.string()), corsAllowedHeaders: z.array(z.string()) });

export const getSecurityRoute = createRoute({ method: 'get', path: '/', summary: 'Get Tenant Security Config', tags: ['Admin Security'], responses: { 200: { content: { 'application/json': { schema: securityConfigSchema } }, description: 'Success' } } });
export const updateSecurityRoute = createRoute({ method: 'patch', path: '/', summary: 'Update Tenant Security Config', tags: ['Admin Security'], request: { body: { content: { 'application/json': { schema: securityConfigSchema.partial() } } } }, responses: { 200: { content: { 'application/json': { schema: z.object({ success: z.boolean() }) } }, description: 'Success' } } });
export const listDevicesRoute = createRoute({ method: 'get', path: '/devices', summary: 'List All Tenant Devices', tags: ['Admin Security'], responses: { 200: { content: { 'application/json': { schema: z.array(z.object({ id: z.string(), userId: z.string(), deviceId: z.string(), deviceName: z.string().nullable(), deviceType: z.string().nullable(), lastIp: z.string().nullable(), status: z.string(), isAuthorized: z.boolean(), isTemporary: z.boolean(), expiresAt: z.string().nullable(), lastActiveAt: z.string(), user: z.object({ firstName: z.string().nullable(), lastName: z.string().nullable(), email: z.string() }) })) } }, description: 'Success' } } });
export const authorizeDeviceRoute = createRoute({ method: 'post', path: '/devices/:id/authorize', summary: 'Authorize a Device', tags: ['Admin Security'], responses: { 200: { content: { 'application/json': { schema: z.object({ success: z.boolean() }) } }, description: 'Success' }, 404: { content: { 'application/json': { schema: z.object({ error: z.string() }) } }, description: 'Device not found' } } });
export const revokeDeviceRoute = createRoute({ method: 'post', path: '/devices/:id/revoke', summary: 'Revoke a Device', tags: ['Admin Security'], responses: { 200: { content: { 'application/json': { schema: z.object({ success: z.boolean() }) } }, description: 'Success' }, 404: { content: { 'application/json': { schema: z.object({ error: z.string() }) } }, description: 'Device not found' } } });
export const getDeviceActivityRoute = createRoute({ method: 'get', path: '/devices/:deviceId/activity', summary: 'Get Device Activity Logs', tags: ['Admin Security'], responses: { 200: { content: { 'application/json': { schema: z.array(z.object({ id: z.string(), action: z.string(), resourceType: z.string(), createdAt: z.string(), ipAddress: z.string().nullable(), metadataJson: z.any().nullable() })) } }, description: 'Success' } } });
export const getForensicTrailsRoute = createRoute({ method: 'get', path: '/forensic-trails', summary: 'Get Forensic System Events', tags: ['Admin Security'], responses: { 200: { content: { 'application/json': { schema: z.array(z.object({ id: z.string(), tenantId: z.string(), operation: z.string(), modelName: z.string(), entityId: z.string().nullable(), payload: z.any().nullable(), previousData: z.any().nullable(), actorUserId: z.string().nullable(), deviceId: z.string().nullable(), ipAddress: z.string().nullable(), createdAt: z.string(), actor: z.object({ email: z.string() }).nullable().optional() })) } }, description: 'Success' } } });
export const getDailySummaryRoute = createRoute({ method: 'get', path: '/daily-summary', summary: 'Get Daily Activity Summary', tags: ['Admin Security'], request: { query: z.object({ date: z.string().optional() }) }, responses: { 200: { content: { 'application/json': { schema: z.object({ date: z.string(), totalEvents: z.number(), byUser: z.array(z.object({ actorUserId: z.string().nullable(), email: z.string().optional(), count: z.number(), operations: z.record(z.number()) })), byModel: z.record(z.number()) }) } }, description: 'Success' } } });
export const getCorsRoute = createRoute({ method: 'get', path: '/cors', summary: 'Get Tenant CORS Config', tags: ['Admin Security'], responses: { 200: { content: { 'application/json': { schema: corsConfigSchema } }, description: 'Success' } } });
export const updateCorsRoute = createRoute({ method: 'patch', path: '/cors', summary: 'Update Tenant CORS Config', tags: ['Admin Security'], request: { body: { content: { 'application/json': { schema: corsConfigSchema.partial() } } } }, responses: { 200: { content: { 'application/json': { schema: z.object({ success: z.boolean() }) } }, description: 'Success' } } });
export const verifyIntegrityRoute = createRoute({ method: 'post', path: '/verify-integrity', summary: 'Verify Forensic Chain Integrity', tags: ['Admin Security'], responses: { 200: { content: { 'application/json': { schema: z.object({ isValid: z.boolean(), totalEvents: z.number(), brokenEvents: z.array(z.string()), message: z.string() }) } }, description: 'Success' } } });

// --- Handlers ---
export async function handleGetSecurity(c: any) { const prisma = c.get('prisma'); const tenantId = c.get('jwtPayload').tenantId; const tenant = await prisma.tenant.findUnique({ where: { id: tenantId }, select: { enforceVpn: true, allowedVpnRanges: true, requireDeviceApproval: true, maxDevicesPerUser: true } }); return c.json(tenant || { enforceVpn: false, allowedVpnRanges: [], requireDeviceApproval: false, maxDevicesPerUser: 5 }, 200); }
export async function handleUpdateSecurity(c: any) { const prisma = c.get('prisma'); const tenantId = c.get('jwtPayload').tenantId; await prisma.tenant.update({ where: { id: tenantId }, data: c.req.valid('json') }); return c.json({ success: true }, 200); }
export async function handleListDevices(c: any) { const prisma = c.get('prisma'); const tenantId = c.get('jwtPayload').tenantId; return c.json(await prisma.userDevice.findMany({ where: { user: { tenantId } }, include: { user: { select: { firstName: true, lastName: true, email: true } } }, orderBy: { lastActiveAt: 'desc' } }) as any, 200); }
export async function handleAuthorizeDevice(c: any) { const prisma = c.get('prisma'); const id = c.req.param('id'); const tenantId = c.get('jwtPayload').tenantId; const device = await prisma.userDevice.findUnique({ where: { id }, include: { user: true } }); if (!device || device.user.tenantId !== tenantId) return c.json({ error: 'Device not found' }, 404); await prisma.userDevice.update({ where: { id }, data: { isAuthorized: true, authorizedAt: new Date(), status: 'active' } }); return c.json({ success: true }, 200); }
export async function handleRevokeDevice(c: any) { const prisma = c.get('prisma'); const id = c.req.param('id'); const tenantId = c.get('jwtPayload').tenantId; const device = await prisma.userDevice.findUnique({ where: { id }, include: { user: true } }); if (!device || device.user.tenantId !== tenantId) return c.json({ error: 'Device not found' }, 404); await prisma.userDevice.update({ where: { id }, data: { status: 'revoked', isAuthorized: false } }); return c.json({ success: true }, 200); }
export async function handleGetDeviceActivity(c: any) { const prisma = c.get('prisma'); return c.json(await prisma.auditLog.findMany({ where: { deviceId: c.req.param('deviceId'), tenantId: c.get('jwtPayload').tenantId }, orderBy: { createdAt: 'desc' }, take: 100 }) as any, 200); }
export async function handleGetForensicTrails(c: any) { const prisma = c.get('prisma'); return c.json(await prisma.systemEvent.findMany({ where: { tenantId: c.get('jwtPayload').tenantId }, include: { actor: { select: { email: true } } }, orderBy: { createdAt: 'desc' }, take: 100 }) as any, 200); }
export async function handleGetDailySummary(c: any) {
    const prisma = c.get('prisma'); const tenantId = c.get('jwtPayload').tenantId; const dateStr = c.req.query('date') || new Date().toISOString().split('T')[0];
    const startOfDay = new Date(dateStr); startOfDay.setHours(0, 0, 0, 0); const endOfDay = new Date(dateStr); endOfDay.setHours(23, 59, 59, 999);
    const events = await prisma.systemEvent.findMany({ where: { tenantId, createdAt: { gte: startOfDay, lte: endOfDay } }, include: { actor: { select: { email: true } } } });
    const summary = { date: dateStr, totalEvents: events.length, byUser: [] as any[], byModel: {} as Record<string, number> };
    const userMap = new Map<string | null, any>();
    for (const event of events) { summary.byModel[event.modelName] = (summary.byModel[event.modelName] || 0) + 1; let u = userMap.get(event.actorUserId); if (!u) { u = { actorUserId: event.actorUserId, email: event.actor?.email || 'System/Unknown', count: 0, operations: {} as Record<string, number> }; userMap.set(event.actorUserId, u); } u.count++; u.operations[event.operation] = (u.operations[event.operation] || 0) + 1; }
    summary.byUser = Array.from(userMap.values());
    return c.json(summary as any, 200);
}
export async function handleGetCors(c: any) { const prisma = c.get('prisma'); const tenantId = c.get('jwtPayload').tenantId; const tenant = await prisma.tenant.findUnique({ where: { id: tenantId }, select: { corsAllowedOrigins: true, corsAllowedMethods: true, corsAllowedHeaders: true } }); return c.json(tenant || { corsAllowedOrigins: [], corsAllowedMethods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'], corsAllowedHeaders: ['Content-Type', 'Authorization'] }, 200); }
export async function handleUpdateCors(c: any) { const prisma = c.get('prisma'); const tenantId = c.get('jwtPayload').tenantId; await prisma.tenant.update({ where: { id: tenantId }, data: c.req.valid('json') }); return c.json({ success: true }, 200); }
export async function handleVerifyIntegrity(c: any) {
    const prisma = c.get('prisma'); const tenantId = c.get('jwtPayload').tenantId;
    const events = await prisma.systemEvent.findMany({ where: { tenantId }, orderBy: { createdAt: 'asc' } });
    let isValid = true; let lastChecksum: string | null = null; const brokenEvents: string[] = [];
    for (const event of events) {
        if (event.previousChecksum !== lastChecksum) { isValid = false; brokenEvents.push(event.id); continue; }
        const rawData = JSON.stringify({ tenantId: event.tenantId, operation: event.operation, modelName: event.modelName, entityId: event.entityId, payload: event.payload, actorUserId: event.actorUserId, deviceId: event.deviceId, ipAddress: event.ipAddress, previousChecksum: event.previousChecksum, createdAt: event.createdAt.toISOString() });
        const msgUint8 = new TextEncoder().encode(rawData); const hashBuffer = await crypto.subtle.digest('SHA-256', msgUint8); const computedChecksum = Array.from(new Uint8Array(hashBuffer)).map(b => b.toString(16).padStart(2, '0')).join('');
        if (computedChecksum !== event.checksum) { isValid = false; brokenEvents.push(event.id); }
        lastChecksum = event.checksum;
    }
    return c.json({ isValid, totalEvents: events.length, brokenEvents, message: isValid ? 'Chain integrity verified. No tampering detected.' : 'INTEGRITY BREACH: Tampering detected in the audit trail.' }, 200);
}
