export const MGR_DAILY = {
    dailyEntryPage: "form.daily.page",
    dailyEntryHeader: "form.daily.header",
    clientSelect: "form.daily.client",
    adlPrefix: "form.daily.adl.",
    adlBathing: "form.daily.adl.bathing",
    adlFeeding: "form.daily.adl.feeding",
    vitalsBp: "form.daily.vitals.bp",
    vitalsPulse: "form.daily.vitals.pulse",
    vitalsTemp: "form.daily.vitals.temp",
    notes: "form.daily.notes",
    signature: "form.daily.signature",
    saveDraft: "form.daily.save",
    submitEntry: "form.daily.submit",
    moodPrefix: "form.daily.mood.",
};
