export const baseAdminContent = {
    MODALS: {
        CREATE_VISIT: {
            TITLE_CREATE: 'Create New Shift Request',
            TITLE_EDIT: 'Edit Shift Request',
            SUBMIT_CREATE: 'Create Shift',
            SUBMIT_SAVE: 'Save Changes',
            CANCEL: 'Cancel',
            PROCESSING: 'Processing...',
            SUCCESS_CREATE: 'Shift created successfully!',
            SUCCESS_UPDATE: 'Shift updated successfully!',
            ERROR_CREATE: 'Failed to create shift',
            ERROR_UPDATE: 'Failed to update shift',
        },
        CONFIRM_DELETE: {
            TITLE: 'Confirm Deletion',
            DESC: 'Are you sure you want to delete this item? This action cannot be undone.',
            CONFIRM: 'Delete',
            CANCEL: 'Cancel',
        }
    },
    SHARED: {
        VARIABLE_KEY: 'Variable Key',
        CURRENT_VALUE: 'Current Value',
        SECURITY_LEVEL: 'Security Level',
        STATUS: 'Status',
        ARCHITECTURE_INSIGHT: 'Architecture Insight',
        SECURITY_NOTE: 'Security Note',
        HEALTHY: 'Healthy',
        VERIFIED: 'Verified',
        ACCESSIBLE: 'Accessible',
        MATCH: 'Match',
        SECURE: 'Secure',
        PUBLIC: 'Public',
        SYSTEM: 'System',
        SENSITIVE: 'Sensitive',
        LOW: 'Low',
        MEDIUM: 'Medium',
        HIGH: 'High',
    },
    LEARN: {
        TITLE: 'PrimeCare Academy',
        SUBTITLE: 'Documentation and training resources.',
        COURSES: 'Course Registry',
        VIDEO_GUIDES: 'Video Guides',
        DOCS: 'Platform Docs',
        WHAT_YOU_CAN_DO: 'Authorized Skillset',
    },
    AUDIT: {
        TITLE: 'Security Audit',
        TABLE: {
            MODULE: 'System Module',
            PATH: 'API Route',
            STATUS: 'Access Status',
            ROUTE_NAME: 'Route',
            REFERENCE: 'Reference',
            COMPONENT_NAME: 'Component',
            LAYER: 'Layer',
        },
        TABS: {
            ROUTES: 'Total Routes',
            COMPONENTS: 'UI Components',
        }
    },
    SETTINGS: {
        TITLE: 'Platform Settings',
        SUBTITLE: 'Configure system-wide preferences and operational parameters.',
        NOTIFICATIONS: {
            TITLE: 'Notification Preferences',
            EMAIL_ALERTS: 'Email Alerts',
            EMAIL_DESC: 'Receive important system notifications via email.',
        },
        SCHEDULING: {
            TITLE: 'Scheduling Rules',
            AUTO_ASSIGN: 'Auto-Assignment',
            AUTO_DESC: 'Automatically assign PSWs to open shifts based on availability.',
            GRACE_PERIOD: 'Grace Period',
            GRACE_DESC: 'Time allowed before a shift is flagged as late.',
        },
        ACTIONS: {
            SAVE: 'Save Configuration',
            RESET: 'Reset to Defaults',
            SUCCESS_SAVE: 'Settings saved successfully!',
        },
    },
    MARKETPLACE: {
        TITLE: 'Integration Marketplace',
        SUBTITLE: 'Browse and manage third-party integrations.',
        SEARCH: 'Search integrations...',
        INSTALL: 'Install',
        INSTALLED: 'Installed',
        CATEGORY: 'Category',
        ALL: 'All',
        PRICE_UNIT: '/mo',
        INQUIRE_BTN: 'Inquire',
        OFFER_TITLE: 'Custom Integration',
        OFFER_DESC: 'Need a bespoke integration? Contact our engineering team.',
        CREATE_BTN: 'Request Custom Build',
        FORM: {
            API_KEY: 'API Key',
            WEBHOOK_URL: 'Webhook URL',
            CONNECT_BTN: 'Connect',
            DISCONNECT_BTN: 'Disconnect',
        },
    },
    ADMIN_LEADS: {
        TITLE: 'Growth Pipeline',
        SUBTITLE: 'Manage incoming leads and conversion metrics.',
        STATUS: {
            NEW: 'New',
            CONTACTED: 'Contacted',
            CONSULTATION: 'Consultation',
            CONVERTED: 'Converted',
            LOST: 'Lost',
        },
        TABLE: {
            NAME: 'Name',
            CONTACT: 'Contact',
            INTEREST: 'Interest',
            STATUS: 'Status',
            DATE: 'Date',
            ACTIONS: 'Actions',
        },
        MESSAGES: {
            LOADING: 'Loading leads...',
            EMPTY_SEARCH: 'No leads match your search.',
            EMPTY_LIST: 'No leads yet.',
            CONFIRM_DELETE: 'Are you sure you want to delete this lead?',
        },
    },
    LOCATIONS: {
        TITLE: 'Branch Mapping',
        SUBTITLE: 'Regional branch offices and service areas.',
        MESSAGES: {
            SUCCESS: 'Location saved successfully!',
            ERROR: 'Failed to save location.',
            ERROR_SUBMISSION: 'Submission error. Please try again.',
        },
        FORM: {
            DISCARD_TITLE: 'Discard Changes?',
            DISCARD_DESC: 'You have unsaved changes that will be lost.',
            NAME: 'Branch Name',
            MANAGER: 'Branch Manager',
            MANAGER_SELECT: 'Select a manager...',
            CAPACITY: 'Client Capacity',
            ADDRESS: 'Address',
            CANCEL: 'Cancel',
            SAVE_BTN: 'Save Branch',
            SAVING: 'Saving...',
        },
    },
} as const;
