export const baseContent = {
    APP: {
        NAME: 'PrimeCare',
        TAGLINE: 'Compassionate Care, Professional Service',
    },
    AUTH: {
        LOGIN_TITLE: 'Sign in to your account',
        LOGIN_TITLE_CLIENT: 'Client Portal Login',
        LOGIN_TITLE_STAFF: 'Staff Portal Login',
        LOGIN_TITLE_PSW: 'Caregiver Portal Login',
        LOGIN_TITLE_RN: 'Registered Nurse Portal Login',
        BUTTON: 'Sign in',
        BUTTON_CLIENT: 'Sign In as Client',
        BUTTON_PSW: 'Sign In as Caregiver',
        BUTTON_RN: 'Sign In as RN',
        BUTTON_STAFF: 'Sign In as Staff',
        EMAIL_LABEL: 'Email address',
        PASSWORD_LABEL: 'Password',
        FORGOT_PASSWORD: 'Forgot password?',
        REGISTER_TITLE: 'Create your account',
        BUTTON_REGISTER: 'Sign up',
        SIGNUP_LINK: "Don't have an account? Sign up",
    },
    ROLES: {
        ADMIN: 'Master Franchise',
        STAFF: 'Staff Member',
        PSW: 'Personal Support Worker',
        RN: 'Registered Nurse',
        CLIENT: 'Client',
        COORDINATOR: 'Scheduling Coordinator',
        FINANCE: 'Finance Manager',
        HR: 'HR Manager',
        COMPLIANCE: 'Compliance Officer',
        CRM: 'Client Relationship Manager',
        TRAINING: 'Training Manager',
    },
    ROLE_LABELS: {
        ADMIN: 'Master Franchise',
        SCRUM_MASTER: 'Scrum Master (Orchestrator)',
        MANAGER: 'Agency Operator',
        STAFF: 'Staff Member',
        PSW: 'Caregiver (PSW)',
        RN: 'Registered Nurse (RN)',
        CLIENT: 'Client / Family',
        FINANCE_DIRECTOR: 'Finance Director',
    },
    MENU: {
        DASHBOARD: 'Dashboard',
        USERS: 'Users & PSWs',
        SCHEDULE: 'Schedule',
        INCIDENTS: 'Incidents',
        TIMESHEETS: 'Timesheets',
        LEADS: 'Lead Inquiries',
        SERVICES: 'Services',
        AUDITS: 'Call Audits',
        CONTENT: 'Content',
        REPORTS: 'Reports',
        SETTINGS: 'Settings',
        SUPPORT: 'Support',
        DEVELOPER: 'Developer',
        THEME: 'Theme Center',
        INSIGHTS: 'Insights',
        CLINICAL_AI: 'Clinical AI',
        INTEROPERABILITY: 'Interoperability',
        AUTOMATION: 'Automation',
        GROWTH: 'Growth Strategy',
        KNOWLEDGE_BASE: 'Knowledge Base',
        RESELLER: 'Reseller Hub',
        MARKETPLACE: 'Marketplace',
        PRIVATE_MARKET: 'Private Market',
        IDENTITY: 'My Identity',
        TRAINING: 'System Training',
        DEV_AUDIT: 'Developer Audit',
        CLIENT_HUB: 'My Care Hub',
        CLIENT_BOOKINGS: 'My Bookings',
        CLIENT_BILLING: 'Billing',
        PROFILE: 'Account Profile',
        STAFF_HUB: 'Staff Hub',
        CUSTOMERS: 'Customer Mgmt',
        TICKETS: 'Tickets',
        WORK_SCHEDULE: 'Work Schedule',
        OPEN_SHIFTS: 'Open Shifts',
        MY_SHIFTS: 'My Shifts',
        MY_EARNINGS: 'My Earnings',
        MY_CREDENTIALS: 'My Credentials',
        HELP_DESK: 'Help Desk',
        CLINICAL_DASHBOARD: 'Clinical Dashboard',
        ACCOUNTING_INTELLIGENCE: 'Accounting Intelligence',
        CLINIENT_ADMISSION: 'Clients admission',
        DAILY_ENTRY: 'Daily Entry',
        EVALUATIONS: 'Evaluations',
        SERVICE_REVIEW: 'Service Review',
        ONBOARDING: 'Onboarding',
        COMPLIANCE: 'Compliance',
        INQUIRIES: 'Inquiries',
        SATISFACTION: 'Satisfaction',
        MODULES: 'Modules',
        SKILLS: 'Staff Skills',
        CARE_PLANS: 'Care Plans',
    },
    USERS: {
        TITLE: 'Users & PSWs',
        SUBTITLE: 'Manage staff, caregivers, and administrative users.',
        ADD_USER_BTN: '+ Add New User',
        SEARCH_PLACEHOLDER: 'Search by name or email...',
        TABLE: {
            NAME: 'Full Name',
            EMAIL: 'Email',
            ROLE: 'System Role',
            STATUS: 'Status',
            ACTIONS: 'Actions',
        },
        TABS: {
            STAFF: 'Office Staff',
            PSW: 'Caregivers (PSW)',
            RN: 'Clinical (RN)',
            ADMIN: 'Administrators',
        }
    },
    LAYOUT: {
        LOGOUT: 'Sign Out',
        PROFILE_TITLE: 'Account Profile',
        PERSPECTIVE: 'Perspective',
        IMPERSONATING: 'Impersonating profile',
        SWITCH_PERSPECTIVE: 'Choose Perspective',
        SEARCH_USERS: 'Search system users...',
        ONLINE_STATUS: 'STATUS: ONLINE',
        FULLSCREEN_ENTER: 'Enter Fullscreen',
        FULLSCREEN_EXIT: 'Exit Fullscreen',
        MOBILE_MENU: 'Toggle Menu',
        SEARCH_LABEL: 'Search Registry',
        LOGGED_IN_AS: 'Active Session: ',
        PERSPECTIVE_MODAL: {
            TITLE_MAIN: 'Umbrella Perspective',
            TITLE_IMPERSONATE: 'User Impersonation Tool',
            SUBTITLE_MAIN: 'Switch between platform umbrellas or impersonate users',
            SUBTITLE_IMPERSONATE: 'Viewing system as another user',
            SECTION_ROLE: 'SWITCH UMBRELLA',
            SECTION_IMPERSONATE: 'SEARCH SYSTEM USERS',
            EXIT_IMPERSONATE: 'EXIT IMPERSONATION',
            SEARCH_PLACEHOLDER: 'Search by name, email or UID...',
            IMPERSONATE_ACTION: 'IMPERSONATE →',
            GROUPS: {
                ADMIN: 'Administration',
                STAFF: 'Staff Operations',
                MANAGEMENT: 'Management',
                HEALTHCARE: 'Healthcare Workers',
            }
        }
    },
    COMMON: {
        LOAD_MORE: 'Load More',
        RETRY: 'Retry',
        SEARCH_PLACEHOLDER: 'Search...',
        NO_RESULTS: 'No results found.',
        SAVE: 'Save',
        CLOSE: 'Close',
        BACK: 'Back',
        EDIT: 'Edit',
        DELETE: 'Delete',
        NETWORK_ERROR: 'Network error',
        PROCESSING: 'Processing...',
        FALLBACKS: {
            REGISTRY_NODE: 'Registry Node',
            CARE_SERVICE: 'Care Service',
            NA: 'N/A',
            TBD: 'TBD',
        },
        UNITS: {
            MMHG: 'mmHg',
            METERS: 'm',
            HOURS: 'h',
        },
        TABLE: {
            NAME: 'Name',
            EMAIL: 'Email',
            PHONE: 'Phone',
            DATE: 'Date',
            STATUS: 'Status',
            ACTIONS: 'Actions',
            SEARCH_PLACEHOLDER: 'Search records...',
            NO_RESULTS: 'No matching records found.',
            LOADING: 'Synchronizing data...',
        }
    },
    MODALS: {
        CREATE_VISIT: {
            TITLE_CREATE: 'Create New Shift Request',
            TITLE_EDIT: 'Edit Shift Request',
            SUBMIT_CREATE: 'Create Shift',
            SUBMIT_SAVE: 'Save Changes',
            CANCEL: 'Cancel',
            PROCESSING: 'Processing...',
            SUCCESS_CREATE: 'Shift created successfully!',
            SUCCESS_UPDATE: 'Shift updated successfully!',
            ERROR_CREATE: 'Failed to create shift',
            ERROR_UPDATE: 'Failed to update shift',
        },
        CONFIRM_DELETE: {
            TITLE: 'Confirm Deletion',
            DESC: 'Are you sure you want to delete this item? This action cannot be undone.',
            CONFIRM: 'Delete',
            CANCEL: 'Cancel',
        }
    },
    SHARED: {
        VARIABLE_KEY: 'Variable Key',
        CURRENT_VALUE: 'Current Value',
        SECURITY_LEVEL: 'Security Level',
        STATUS: 'Status',
        ARCHITECTURE_INSIGHT: 'Architecture Insight',
        SECURITY_NOTE: 'Security Note',
        HEALTHY: 'Healthy',
        VERIFIED: 'Verified',
        ACCESSIBLE: 'Accessible',
        MATCH: 'Match',
        SECURE: 'Secure',
        PUBLIC: 'Public',
        SYSTEM: 'System',
        SENSITIVE: 'Sensitive',
        LOW: 'Low',
        MEDIUM: 'Medium',
        HIGH: 'High',
    },
} as const;
