export const operationsContent = {
    ADMISSION: {
        TITLE: 'Client Admission',
        SUBTITLE: 'Register a new client and configure their care requirements.',
        FORM: {
            FULL_NAME: 'Full Name',
            EMAIL: 'Email Address',
            PHONE: 'Phone Number',
            ADDRESS: 'Residential Address',
            EMERGENCY: 'Emergency Contact Name & Phone',
            NOTES: 'Medical Notes / Primary Concern',
            SUBMIT: 'Complete Admission',
            PROCESSING: 'Processing...',
            CANCEL: 'Cancel',
            DISCARD_TITLE: 'Unsaved Changes',
            DISCARD_DESC: 'You have unsaved admission data. Navigating away will discard it.',
        },
        MESSAGES: {
            SUCCESS: 'Client admitted successfully!',
            ERROR: 'Failed to admit client',
            ERROR_SUBMISSION: 'Error during admission',
        }
    },
    ONBOARDING: {
        TITLE: 'PSW Professional Onboarding',
        SUBTITLE: 'Register a new Personal Support Worker and verify credentials.',
        FORM: {
            FULL_NAME: 'Full Name',
            EMAIL: 'Email Address',
            PHONE: 'Phone Number',
            ADDRESS: 'Home Address',
            SIN: 'SIN (Security Encrypted)',
            BACKGROUND_CHECK: 'Background Check Status',
            CERTIFICATIONS: 'Certifications',
            SUBMIT: 'Complete Onboarding',
            PROCESSING: 'Registering...',
            CANCEL: 'Cancel',
            DISCARD_TITLE: 'Unsaved Changes',
            DISCARD_DESC: 'You have unsaved onboarding data. Navigating away will discard it.',
            STATUS_OPTIONS: {
                PENDING: 'Pending',
                CLEARED: 'Cleared',
                FLAGGED: 'Flagged'
            }
        },
        MESSAGES: {
            SUCCESS: 'PSW onboarded successfully!',
            ERROR: 'Failed to onboard PSW',
            ERROR_SUBMISSION: 'Error during onboarding',
        }
    },
    LEADS: {
        TITLE: 'Lead Inquiries',
        SUBTITLE: 'Track and manage potential client inquiries.',
        ADD_BTN: 'New Lead',
        SEARCH_PLACEHOLDER: 'Search leads...',
        ACTIONS: {
            EXPORT: 'Export CSV',
            REFRESH: 'Refresh',
            REFRESHING: 'Refreshing...',
            MARK_CONTACTED: 'Mark Contacted',
            CONVERT: 'Convert',
            CLOSE: 'Close',
        },
        FORM: {
            TITLE: 'New Lead Entry',
            SUBTITLE: 'Record an offline inquiry.',
            SOURCE_LABEL: 'Inquiry Source',
            NAME_LABEL: 'Lead Name',
            SUBMIT_BTN: 'Create Lead',
            SAVING: 'Saving...',
            SUCCESS_MSG: 'Lead created successfully',
            ERROR_MSG: 'Error creating lead',
            DISCARD_TITLE: 'Discard Lead?',
        },
        TABLE: {
            NAME: 'Name',
            CONTACT: 'Contact',
            INTEREST: 'Interest',
            STATUS: 'Status',
            DATE: 'Date',
            ACTIONS: 'Actions',
            NO_LEADS: 'No leads found matching your search.',
        },
        STATUS: {
            NEW: 'New',
            CONTACTED: 'Contacted',
            CONSULTATION: 'Consultation',
            CONVERTED: 'Converted',
            LOST: 'Lost',
        },
        MESSAGES: {
            LOADING: 'Loading leads repository...',
            EMPTY: 'No leads found.',
            ERROR: 'Failed to fetch leads',
            SUCCESS_UPDATE: 'Status updated successfully',
            ERROR_UPDATE: 'Failed to update status',
            SUCCESS_DELETE: 'Lead deleted successfully',
            ERROR_DELETE: 'Error deleting lead',
        }
    },
    CUSTOMERS: {
        TITLE: 'Customer Management',
        SUBTITLE: 'Manage active clients and oversee care admissions.',
        ADD_BTN: '+ Admit New Client',
        SEARCH_PLACEHOLDER: 'Search clients...',
        TABLE: {
            NAME: 'Full Name',
            EMAIL: 'Email',
            STATUS: 'Status',
            ACTIONS: 'Actions',
            EMPTY: 'No customers found in the registry.',
            ANONYMOUS: 'Anonymous Customer',
            VIEW_DETAILS: 'View Details',
        },
        FILTERS: {
            ACTIVE_FILTERS: 'Active Filters:',
            CLEAR_ALL: 'Clear All',
            STATUS_LABEL: 'Status: ',
        },
        MESSAGES: {
            LOADING: 'Loading customer registry...',
        }
    },
    SCHEDULE: {
        TITLE: 'Visit Schedule',
        SUBTITLE: 'Coordinate care visits and assign PSWs to client requests.',
        ACTIONS: {
            CREATE: '+ Create Visit Request',
            ASSIGN: 'Assign Caregiver',
            CONFIRM_ASSIGN: 'Confirm Assignment',
            CANCEL_VISIT: 'Cancel Visit',
            CLOSE: 'Close',
            EDIT: 'Edit Details',
        },
        MODAL: {
            SELECT_PSW: 'Select Verified PSW',
            CHOOSE_WORKER: '-- Choose a worker --',
            CONFIRM_DELETE: 'Are you sure you want to cancel this visit?',
        },
        MESSAGES: {
            SUCCESS_ASSIGN: 'PSW assigned successfully!',
            SUCCESS_CANCEL: 'Visit cancelled',
            ERROR_ASSIGN: 'Assignment failed',
            ERROR_DELETE: 'Failed to delete visit',
            ERROR_UPDATE: 'Status update failed',
            OFFERS_SENT: 'Offers sent successfully',
            OFFERS_FAILED: 'Failed to send offers',
            SURGE_SUCCESS: 'Surge pricing updated successfully',
            SURGE_ERROR: 'Failed to apply surge pricing',
            NETWORK_ERROR: 'Network error while applying surge',
        }
    },
    SERVICES: {
        TITLE: 'Services & Pricing',
        SUBTITLE: 'Manage the care packages and hourly rates offered to clients.',
        ADD_BTN: '+ Add New Service',
        TABLE: {
            NAME: 'Service Name',
            CATEGORY: 'Category',
            RATE: 'Hourly Rate',
            DESC: 'Description',
            ACTIONS: 'Actions',
            LOADING: 'Loading services...',
            EMPTY: 'No services configured.',
        },
        FORM: {
            TITLE_CREATE: 'Add New Service',
            TITLE_EDIT: 'Edit Service',
            NAME_LABEL: 'Service Name',
            RATE_LABEL: 'Hourly Rate ($)',
            CATEGORY_LABEL: 'Category',
            DESC_LABEL: 'Description',
            SAVE_BTN: 'Save Service',
            CANCEL_BTN: 'Cancel',
            DISCARD_TITLE: 'Discard Changes?',
            DISCARD_DESC: 'You have unsaved changes in this service. Are you sure you want to close?',
        },
        MESSAGES: {
            SUCCESS_CREATE: 'Service created successfully!',
            SUCCESS_UPDATE: 'Service updated successfully!',
            SUCCESS_DELETE: 'Service deleted successfully',
            ERROR_SAVE: 'Failed to save service',
            ERROR_DELETE: 'Failed to delete service',
            ERROR_LOAD: 'Failed to load services',
            CONFIRM_DELETE: 'Are you sure you want to delete this service?',
        },
        CATEGORIES: {
            SENIOR_CARE: 'Senior Care',
            FOOT_CARE: 'Foot Care',
            CONSULTING: 'Consulting',
            TRAINING: 'Training',
        }
    },
    INCIDENTS: {
        TITLE: 'Incident Reports',
        SUBTITLE: 'Document clinical or operational incidents for audit.',
        ADD_BTN: 'Report Incident',
        FORM: {
            TITLE: 'Report New Incident',
            TYPE_LABEL: 'Incident Type',
            SEVERITY_LABEL: 'Severity',
            DESC_LABEL: 'Description',
            SUBMIT_BTN: 'Submit Report',
            REPORTING: 'Reporting...',
            SUCCESS_MSG: 'Incident report submitted',
            ERROR_MSG: 'Submission failed',
        },
        RESOLVE: {
            BTN: 'Resolve',
            TITLE: 'Resolve Incident',
            NOTES_LABEL: 'Resolution Notes',
            NOTES_PLACEHOLDER: 'Describe the steps taken to resolve this incident...',
            RESOLVING_LOADING: 'Resolving...',
            DISCARD_TITLE: 'Discard Changes?',
            DISCARD_DESC: 'You have typed resolution notes. Are you sure you want to cancel?',
            SUCCESS: 'Incident resolved successfully',
            ERROR: 'Failed to resolve incident',
        },
        TABLE: {
            TYPE: 'Type',
            REPORTER: 'Reporter',
            STATUS: 'Status',
            DATE: 'Date',
            ACTIONS: 'Actions',
            LOADING: 'Loading incidents...',
        }
    },
    DAILY_ENTRY: {
        TITLE: 'Daily Care Entry',
        LEFT_PANEL_TITLE: 'Select Context',
        CLIENT_LABEL: 'Client',
        CLIENT_PLACEHOLDER: 'Select Client...',
        TIP_TITLE: '💡 Tip',
        TIP_CONTENT: 'Auto-save is enabled for drafts. Submitting requires a signature.',
        ADL_TITLE: 'ADL Checklist',
        VITALS_TITLE: 'Vitals & Wellness',
        VITALS: {
            BP: 'BP',
            PULSE: 'Pulse',
            TEMP: 'Temp',
            MOOD_LABEL: 'Client Mood (1-5)',
        },
        NOTES_TITLE: 'Notes & Signature',
        NOTES_PLACEHOLDER: 'Daily progress notes, observations, or incidents...',
        SIGNATURE_LABEL: 'Digital Signature',
        SIGNATURE_PLACEHOLDER: 'Type full name to sign',
        SAVE_DRAFT: 'Save Draft',
        SUBMIT: 'Submit Entry',
        SUBMITTING: 'Submitting...',
        GUARD: {
            TITLE: 'Unsaved Changes',
            DESC: 'You have unsaved changes. Navigating away will discard them. Would you like to stay and save?',
            LEAVE: 'Leave',
            STAY: 'Stay',
        },
        MESSAGES: {
            SELECT_CLIENT: 'Please select a client',
            SIGNATURE_REQUIRED: 'Signature required for submission',
            SUCCESS_DRAFT: 'Draft saved!',
            SUCCESS_SUBMIT: 'Daily entry submitted successfully!',
            ERROR_SAVE: 'Failed to save entry',
            ERROR_SERVER: 'Error communicating with server',
        }
    },
    INVOICES: {
        TITLE: 'Invoice Management',
        SUBTITLE: 'Generate and track billing across the network.',
        FORM: {
            CREATE_TITLE: 'Create New Invoice',
            DESC_PLACEHOLDER: 'Description of service',
            AMOUNT_PLACEHOLDER: 'Amount ($)',
            ADD_ITEM: '+ Add Line Item',
            SUBMIT_BTN: 'Generate & Send Invoice',
            CANCEL_BTN: 'Cancel',
            DISCARD_TITLE: 'Discard Invoice?',
            DISCARD_DESC: 'Are you sure you want to cancel this invoice? Unsaved changes will be lost.',
        },
        MESSAGES: {
            SUCCESS_GENERATE: 'Invoice generated and sent successfully',
            ERROR_GENERATE: 'Failed to generate invoice',
        }
    },
    REPORTS: {
        TITLE: 'Reports & Analytics',
        SUBTITLE: 'Visualize key performance indicators and operational metrics.',
        EXPORT_BTN: 'Export CSV',
        DATE_RANGES: {
            7: 'Last 7 Days',
            30: 'Last 30 Days',
            90: 'Last Quarter',
            YEAR: 'Year to Date',
        },
        TABS: {
            OVERVIEW: 'Overview',
            FINANCIAL: 'Financials',
            STAFF: 'Staff Utilization',
            CLIENTS: 'Client Growth',
        }
    },
    MANAGER_COMPLIANCE: {
        TITLE: 'Branch Compliance Monitor',
        SUBTITLE: 'Audit staff and client documentation parity.',
        ALERTS: {
            MISSED_VISIT: 'Missed Visit Alert',
            LATE_ENTRY: 'Late Daily Entry',
            DOC_GAP: 'Missing Clinical Note',
        },
        STATUS: {
            COMPLIANT: 'Compliant',
            NON_COMPLIANT: 'Non-Compliant',
            EXPIRING: 'Expiring Soon',
            PENDING: 'Pending Review',
            WARNING: 'Compliance Warning',
            SYNCED: 'Satellite Synchronized',
        },
        TABLE: {
            PROVIDER: 'Clinical Provider',
            CAREGIVER: 'Caregiver',
            CLIENT: 'Client',
            VISIT: 'Visit Type',
            DOCUMENT: 'Clinical Document',
            COMPLIANCE: 'Compliance Status',
            STATUS: 'Overall Status',
            EXPIRY: 'Expiration Date',
            DATE: 'Last Activity',
        },
        MESSAGES: {
            AUDIT_DONE: 'Compliance Audit completed successfully',
            SUCCESS_AUDIT: 'Compliance Audit Complete',
            SYNC_SUCCESS: 'Registry Synchronized',
            ERROR_AUDIT: 'Failed to complete audit',
        }
    },
    EARNINGS: {
        TITLE: 'Earnings Center',
        SUBTITLE: 'Enterprise-grade financial oversight and payout management',
        STATS: {
            REVENUE: 'Total Revenue',
            PAYROLL: 'Total Payroll',
            PROFIT: 'Net Profit',
            PENDING: 'Payouts Pending',
        },
        TABS: {
            OVERVIEW: 'Overview',
            INVOICES: 'Invoices',
            PAYOUTS: 'Payouts',
            REPORTS: 'Reports',
        },
        ACTIONS: {
            EXPORT: 'Export Report',
            DATE_RANGE: 'Date Range',
            FILTER_ACTIVE: 'Filter Active',
        },
        INVOICE_ID: 'Invoice ID',
        CLIENT: 'Client',
        PSW: 'PSW',
        REVENUE: 'Revenue',
        PAYROLL: 'Payroll',
        PROFIT: 'Profit',
    },
    STAFF_PORTAL: {
        TASKS: {
            TITLE: 'Operational Tasks',
            SUBTITLE: 'Daily workflow management',
            EMPTY: 'No pending tasks.',
        },
        MESSAGES: {
            FETCH_ERROR: 'Failed to load messages',
            SAVE_SUCCESS: 'Message sent successfully!',
            SAVE_ERROR: 'Failed to send message',
            SEND_BTN: 'Send Message',
            TITLE: 'Message Center',
            INPUT_PLACEHOLDER: 'Type your message here...',
            SEARCH_PLACEHOLDER: 'Search messages...',
            LOADING: 'Loading messages...',
        }
    },
    WAITLIST: {
        TITLE: 'Inflow Waitlist',
        SUBTITLE: 'Pending client admissions',
        EMPTY: 'Waitlist is clear.',
    },
    QUICK_ACTIONS: {
        TITLE: 'Quick Actions',
        ADD_CLIENT: 'Add Client',
        ADD_STAFF: 'Add Staff',
        ADD_USER: 'Add User',
        CREATE_VISIT: 'Create Visit',
        POST_SHIFT: 'Post Shift',
        FINAL_CHECK: 'Final Check',
        LOG_INCIDENT: 'Log Incident',
        BROADCAST: 'Broadcast SOS',
        CRISIS_ALERTS: 'Crisis Alerts',
        CRISIS_ACTIVE: 'CRISIS ACTIVE',
        WAITING: 'WAITING',
        MESSAGES: {
            SUCCESS: 'Action completed successfully',
            SYNC_SUCCESS: 'Registry Synchronized',
            CRISIS_ACTIVATED: 'CRISIS ACTIVATED',
            CRISIS_DEACTIVATED: 'CRISIS DEACTIVATED',
            CRISIS_DEACTIVATE: 'Are you sure you want to deactivate the crisis alert?',
            CRISIS_CONFIRM: 'Are you sure you want to broadcast a crisis alert?',
            ADMIN_ONLY: 'This action is restricted to administrators',
            TEMP_ERROR: 'Temporary Error',
            ERROR: 'Failed to complete action',
        }
    },
    RN_SUPERVISION: {
        TITLE: 'Clinical Supervision Hub',
        SUBTITLE: 'Professional RN oversight and sign-off.',
        LOG_TITLE: 'Supervision Activity Log',
        LIST: {
            PENDING: 'Pending Supervision',
            COMPLETED: 'Supervision History',
            NO_ENTRIES: 'No entries requiring supervision.',
        }
    },
    CLINICAL_MESSAGES: {
        SUCCESS_SIGN_OFF: 'RN Sign-off Complete',
        ERROR_SIGN_OFF: 'Failed to complete sign-off',
    },
    RN_CARE_PLAN: {
        TITLE: 'Clinical Care Plan Management',
        SUBTITLE: 'Design and authorize customized care pathways.',
        BUILDER_TITLE: 'Clinical Care Plan Builder',
        BUILDER_SUBTITLE: 'Structured assessment and intervention design.',
        ACTIONS: {
            CREATE: 'Create Care Plan',
            EDIT: 'Edit Plan',
            AUTHORIZE: 'Authorize Plan',
            SAVE: 'Save Plan',
        },
        TABS: {
            ASSESSMENT: 'Registered Nurse Assessment',
            DIAGNOSES: 'Associated Diagnoses',
            GOALS: 'Care Goals',
            INTERVENTIONS: 'Nursing Interventions',
        },
        SUCCESS_SAVE: 'Care plan saved successfully!',
        ERROR_SAVE: 'Failed to save care plan',
        FIELDS: {
            CLIENT: 'Client Name',
            DIAGNOSIS: 'Primary Diagnosis',
            DIAGNOSES: 'Associated Diagnoses',
            ASSESSMENT: 'Registered Nurse Assessment',
            GOALS: 'Care Goals',
            INTERVENTIONS: 'Nursing Interventions',
            FREQUENCY: 'Service Frequency',
            SIGNATURE: 'RN Digital Signature',
            DATE: 'Date Authorized',
        },
        TABLE: {
            CLIENT: 'Client',
            VERSION: 'Version',
            STATUS: 'Status',
            DATE: 'Last Updated',
        }
    },
    RN_DAILY_AUDIT: {
        TITLE: 'Clinical Daily Audit',
        SUBTITLE: 'Peer review and quality assurance of caregiver entries.',
        ACTIONS: {
            VERIFY: 'Verify Entry',
            FLAG: 'Flag for Review',
            CLOSE: 'Close Audit',
        },
        VERIFY_BUTTON: 'Confirm Clinical Integrity',
        FLAG_BUTTON: 'Flag for Clinical Review',
        TABLE: {
            CAREGIVER: 'Caregiver',
            CLIENT: 'Client',
            STATUS: 'Audit Status',
            DATE: 'Entry Date',
        }
    },
    RN_ASSESSMENTS: {
        TITLE: 'Clinical Patient Assessments',
        SUBTITLE: 'In-home evaluations and physiological audits.',
        ACTIONS: {
            NEW: 'New Assessment',
            CONTINUE: 'Continue Draft',
            VIEW: 'View Assessment',
        },
        NEW_BUTTON: 'Initiate New Assessment',
        TYPE_LABELS: {
            INITIAL: 'Initial Intake',
            QUARTERLY: 'Quarterly Review',
            POST_HOSPITAL: 'Post-Hospitalization',
            INCIDENT: 'Incident-Response',
            ADL: 'Activities of Daily Living',
            COGNITIVE: 'Cognitive Evaluation',
            VITALS: 'Vitals Monitoring',
        },
        FIELDS: {
            CLIENT: 'Client Name',
            PATIENT: 'Patient Name',
            LOCATION: 'Assessment Location',
            DURATION: 'Assessment Duration',
            INSTRUCTOR: 'Assigned RN',
            GENERAL_HEALTH: 'General Health Status',
            COGNITIVE: 'Cognitive Function',
            MOBILITY: 'Mobility & Falls Risk',
            NUTRITION: 'Nutritional Intake',
            MEDICATION: 'Medication Management',
            VITALS: 'Baseline Vitals',
            SCORE: 'Clinical Score',
            CATEGORY: 'Risk Category',
            COMMENTS: 'Nursing Comments',
        },
        TABLE: {
            CLIENT: 'Client',
            TYPE: 'Assessment Type',
            STATUS: 'Status',
            DATE: 'Date',
        }
    },
    CLINICAL_FORMS: {
        TITLE: 'Medical Documentation',
        SUBTITLE: 'Authorized clinical forms and nursing notes.',
        SEARCH_PLACEHOLDER: 'Search forms...',
        NO_FORMS: 'No authorized forms found.',
    },
    PSW_LIVE_VISIT: {
        TITLE: 'Live Visit Tracker',
        SUBTITLE: 'Real-time shift management and ADL reporting.',
        HEADER: {
            PATIENT: 'Active Client',
            START_TIME: 'Shift Start',
            ELAPSED: 'Time Elapsed',
            STATUS: 'Visit Status',
            IDLE: 'Caregiver Offline',
            IN_PROGRESS: 'Visit In-Progress',
            STAMP: 'Last Sync',
        },
        ACTIONS: {
            CLOCK_IN: 'Clock In',
            CLOCK_OUT: 'Clock Out',
            SUBMIT_ENTRY: 'Submit Care Entry',
            REPORT_INCIDENT: 'Report Incident',
        },
        CHECKOUT: {
            TITLE: 'Visit Completion',
            SUBTITLE: 'Final review and professional sign-off.',
            BUTTON: 'Finish & Checkout',
            CONFIRM: 'Are you sure you want to complete this visit?',
            GPS_LOCKED: 'Location Verified (GPS)',
            GPS_PULSE: 'Continuous Tracking Active',
            DURATION: 'Total Visit Duration',
        },
        CHECKIN: {
            TITLE: 'Visit Check-In',
            SUBTITLE: 'Authorized arrival and location verification.',
            LOADING: 'Loading visit context...',
            DESC: 'Please confirm your arrival at the client residence to begin clinical documentation.',
            BACK: 'Back to Schedule',
            BUTTON: 'Clock In Now',
            BTN_VERIFYING: 'Verifying Location...',
            BTN_VERIFIED: 'Verification Success',
            GPS_REQUIRED: 'GPS Location Required',
            GPS_TITLE: 'Authorized Arrival Distance',
            VISIT_DETAILS: {
                TITLE: 'Client & Visit Details',
                LOCATION: 'Visit Location',
                TIME_SLOT: 'Scheduled Time',
                SERVICE: 'Care Service',
            },
            GPS_IDLE: 'GPS Ready',
            GPS_VERIFYING: 'GPS Signal Search...',
            GPS_VERIFIED: (distance: number) => `GPS Verified: ${distance}m away`,
            GPS_ERROR: 'Location Verification Failed',
        },
        NAV: {
            HOME: 'Visit Home',
            VITALS: 'Vitals & Wellness',
            PROTOCOLS: 'Clinical Protocols',
            NURSING: 'Nursing Interventions',
            ADL: 'Care Tasks',
            NOTES: 'Clinical Notes',
            SUMMARY: 'Visit Summary',
            ACCOUNT: 'My Account',
        },
        CLINICAL: {
            TITLE: 'Clinical Protocol Hub',
            SUBTITLE: 'Authorized nursing and care guidelines.',
            VITALS: 'Vitals & Observation',
            NURSING: 'Medication & Nursing',
            PROTOCOLS: 'Clinical Guidelines',
            DIETARY: 'Dietary Monitoring',
            MOBILITY: 'Mobility & Physio',
            CONNECT_RN: 'Emergency RN Consultation',
            VITALS_HUB: 'Real-time Vitals Monitor',
        },
        MESSAGES: {
            SUCCESS: 'Action completed successfully',
            CLOCK_IN_SUCCESS: 'Clocked in successfully',
            CLOCK_OUT_SUCCESS: 'Clocked out successfully',
            ENTRY_SUCCESS: 'Visit entry submitted',
            DAILY_ENTRY_SUCCESS: 'Nursing entry documented successfully',
            NETWORK_ERROR: 'Network connection lost',
            DAILY_ENTRY_ERROR: 'Failed to submit clinical entry',
            CHECKOUT_ERROR: 'Failed to complete checkout',
            GEOLOCATION_NOT_SUPPORTED: 'Browser does not support geolocation',
            UNABLE_TO_RETRIEVE_LOCATION: 'Unable to retrieve GPS coordinates',
            LOAD_VISIT_NETWORK_ERROR: 'Failed to load visit details. Check connection.',
            LOAD_VISIT_ERROR: 'Failed to find visit context',
        }
    },
    PSW_MESSAGES: {
        TITLE: 'Caregiver Communications',
        SUBTITLE: 'Direct messaging with coordination and RN oversight.',
        RECIPIENTS: {
            OFFICE: 'Office Staff',
            RN: 'Supervising RN',
            FAMILY: 'Client Family',
        }
    },
    PSW_SCHEDULE: {
        TITLE: 'Shift Registry',
        SUBTITLE: 'Your upcoming and completed care visits.',
        TABS: {
            UPCOMING: 'Upcoming',
            COMPLETED: 'Completed',
            OFFERS: 'Open Offers',
        },
        ACTIONS: {
            ACCEPT: 'Accept Shift',
            DECLINE: 'Decline',
            DETAILS: 'View Details',
        },
        TABLE: {
            CLIENT: 'Client',
            TIME: 'Visit Time',
            DATETIME: 'Schedule Datetime',
            SERVICE: 'Care Service',
            LOCATION: 'Location',
            STATUS: 'Status',
            RATE: 'Pay Rate',
        },
        MESSAGES: {
            LOADING: 'Loading shift registry...',
            SUCCESS_ACCEPT: 'Shift accepted successfully!',
            SUCCESS_DECLINE: 'Shift declined',
            ERROR_ACTION: 'Failed to process shift action',
            EMPTY: 'No shifts found for this criteria.',
        }
    },
    PSW_HANDOVER: {
        TITLE: 'Shift Handover',
        SUBTITLE: 'Professional transfer of care responsibility.',
        LABEL_VISIT: 'Select Visit',
        LABEL_NOTES: 'Handover Notes',
        LABEL_SAFETY: 'Safety Concerns',
        LABEL_SUPPLIES: 'Critical Supplies Handover',
        PLACEHOLDER_NOTES: 'Summary of clinical status and ADL highlights...',
        SUCCESS_MSG: 'Handover documented successfully',
        ERROR_MSG: 'Failed to save handover',
    },
    PSW_PAYOUTS: {
        TITLE: 'Earnings & Payouts',
        SUBTITLE: 'Your payroll history and pending clinic settlements.',
        METRICS: {
            PENDING: 'Pending Approval',
            AVAILABLE: 'Available for Payout',
            TOTAL: 'Lifetime Earnings',
        },
        HISTORY_TITLE: 'Settlement History',
        TABLE: {
            DATE: 'Payout Date',
            AMOUNT: 'Amount',
            STATUS: 'Status',
            METHOD: 'Transfer Method',
        },
        ACTIONS: {
            WITHDRAW: 'Request Payout',
            HISTORY: 'Full History',
        },
        SUCCESS_REQUEST: 'Payout request submitted successfully',
        ERROR_REQUEST: 'Failed to submit payout request',
    },
    PSW_AVAILABILITY: {
        TITLE: 'Work Availability',
        SUBTITLE: 'Define your preferred clinical service hours.',
        SECTION_OVERRIDES: 'Availability Exceptions',
        ADD_OVERRIDE: 'Add Specific Date Override',
        SUCCESS_SYNC: 'Availability synced successfully',
        ERROR_SYNC: 'Failed to sync availability',
    },
    MANAGER_OPERATIONS: {
        TITLE: 'Regional Operations Hub',
        SUBTITLE: 'Cross-branch administrative and logistics triage.',
        TABS: {
            LOGISTICS: 'Logistics Overview',
            COMPLIANCE: 'Regional Compliance',
            TICKETS: 'Support Tickets',
        },
        ALERTS: {
            HIGH_RISK: 'High Risk Branch Alert',
            STAFFING_GAP: 'Regional Staffing Gap',
            COMPLIANCE_DROP: 'Compliance Variance Detected',
        },
        KPI: {
            LOGISTICS_EFFICIENCY: 'Logistics Efficiency',
            REVENUE: 'Regional Revenue Accrual',
            UTILIZATION: 'Regional Staffing Utilization',
            TURNOVER: 'Regional Turnover',
            COMPLIANCE: 'Regional Compliance',
            COMPLIANCE_RATE: 'Average Compliance Rate',
            AUDIT_PROGRESS: 'Regional Audit Progress',
        },
        GRID: {
            BRANCH: 'Branch',
            MANAGER: 'Branch Manager',
            HEALTH: 'Health Score',
            LAST_AUDIT: 'Last Audit',
        },
        ACTIONS: {
            AUDIT: 'Initiate Regional Audit',
            SYNC: 'Sync branch ledgers',
            GLOBAL_SYNC: 'Regional Satellite Sync',
            DOWNLOAD_REPORT: 'Download Operations Report',
        },
        MESSAGES: {
            AUDIT_START: 'Regional audit sequence initiated...',
            SYNC_SUCCESS: 'All branch data synchronized',
        }
    },
    COORDINATOR_WAITLIST: {
        TITLE: 'Waitlist Management',
        SUBTITLE: 'Prioritize and match clients awaiting care.',
        COLUMNS: {
            PRIORITY: 'Priority Rank',
            CLIENT: 'Client Name',
            STATUS: 'Waitlist Status',
            SINCE: 'Waiting Since',
            ENTRY_DATE: 'Date Added',
            URGENCY: 'Clinical Urgency',
            ACUITY: 'Clinical Acuity Score',
            PREFERENCE: 'Provider Preference',
        },
        ACTIONS: {
            MATCH: 'Execute Match',
            PRIORITIZE: 'Adjust Priority',
            BOOST_PRIORITY: 'Priority Elevation',
            ASSIGN_STAFF: 'Manual Caregiver Assignment',
            REMOVE: 'Remove from List',
        },
        MESSAGES: {
            SUCCESS_MATCH: 'Client matched successfully',
            ERROR_MATCH: 'Failed to find suitable match',
        }
    },
    COORDINATOR_SOS: {
        TITLE: 'Emergency Response Center',
        SUBTITLE: 'Real-time SOS monitoring and clinical triage.',
        ALERTS_TITLE: 'Active Clinical SOS Alerts',
        FORM: {
            RESOLUTION_LABEL: 'Resolution Summary',
            PLACEHOLDER_RESOLUTION: 'Describe clinical outcome, dispatch status...',
            INCIDENT_LOG: 'Emergency Incident Log',
            RESOLVE_BTN: 'Finalize Resolution',
        },
        TABLE: {
            TIME: 'Alert Time',
            PSW: 'Caregiver',
            CLIENT: 'Patient',
            LOCATION: 'Live GPS',
            STATUS: 'Alert Status',
        },
        ACTIONS: {
            ACKNOWLEDGE: 'Acknowledge SOS',
            DISPATCH: 'Dispatch Emergency Services',
            RESOLVE: 'Mark as Resolved',
        },
        MESSAGES: {
            SUCCESS_ACK: 'SOS alert acknowledged and escalated',
            ERROR_ACK: 'Failed to acknowledge SOS',
            LOCK_WARNING: 'Another coordinator is currently responding to this alert.',
            NO_ALERTS: 'No active clinical SOS alerts detected.',
        }
    },
    COORDINATOR_MAP: {
        TITLE: 'Live Logistics Map',
        SUBTITLE: 'Real-time spatial visualization of regional clinical operations.',
        LEGEND: {
            ACTIVE: 'Active Visit',
            IDLE: 'Idle/Travel',
            SOS: 'SOS Alert',
            CLIENT: 'Client Location',
        },
        ACTIONS: {
            REFRESH: 'Refresh Fleet Data',
            CENTER: 'Center on Region',
            FILTER: 'Filter Assets',
        }
    },
} as const;
