export const operationsContent = {
    ADMISSION: {
        TITLE: 'Client Admission',
        SUBTITLE: 'Register a new client and configure their care requirements.',
        FORM: {
            FULL_NAME: 'Full Name',
            EMAIL: 'Email Address',
            PHONE: 'Phone Number',
            ADDRESS: 'Residential Address',
            EMERGENCY: 'Emergency Contact Name & Phone',
            NOTES: 'Medical Notes / Primary Concern',
            SUBMIT: 'Complete Admission',
            PROCESSING: 'Processing...',
            CANCEL: 'Cancel',
            DISCARD_TITLE: 'Unsaved Changes',
            DISCARD_DESC: 'You have unsaved admission data. Navigating away will discard it.',
        },
        MESSAGES: {
            SUCCESS: 'Client admitted successfully!',
            ERROR: 'Failed to admit client',
            ERROR_SUBMISSION: 'Error during admission',
        }
    },
    ONBOARDING: {
        TITLE: 'PSW Professional Onboarding',
        SUBTITLE: 'Register a new Personal Support Worker and verify credentials.',
        FORM: {
            FULL_NAME: 'Full Name',
            EMAIL: 'Email Address',
            PHONE: 'Phone Number',
            ADDRESS: 'Home Address',
            SIN: 'SIN (Security Encrypted)',
            BACKGROUND_CHECK: 'Background Check Status',
            CERTIFICATIONS: 'Certifications',
            SUBMIT: 'Complete Onboarding',
            PROCESSING: 'Registering...',
            CANCEL: 'Cancel',
            DISCARD_TITLE: 'Unsaved Changes',
            DISCARD_DESC: 'You have unsaved onboarding data. Navigating away will discard it.',
            STATUS_OPTIONS: {
                PENDING: 'Pending',
                CLEARED: 'Cleared',
                FLAGGED: 'Flagged'
            }
        },
        MESSAGES: {
            SUCCESS: 'PSW onboarded successfully!',
            ERROR: 'Failed to onboard PSW',
            ERROR_SUBMISSION: 'Error during onboarding',
        }
    },
    LEADS: {
        TITLE: 'Lead Inquiries',
        SUBTITLE: 'Track and manage potential client inquiries.',
        ADD_BTN: 'New Lead',
        SEARCH_PLACEHOLDER: 'Search leads...',
        ACTIONS: {
            EXPORT: 'Export CSV',
            REFRESH: 'Refresh',
            REFRESHING: 'Refreshing...',
            MARK_CONTACTED: 'Mark Contacted',
            CONVERT: 'Convert',
            CLOSE: 'Close',
        },
        FORM: {
            TITLE: 'New Lead Entry',
            SUBTITLE: 'Record an offline inquiry.',
            SOURCE_LABEL: 'Inquiry Source',
            NAME_LABEL: 'Lead Name',
            SUBMIT_BTN: 'Create Lead',
            SAVING: 'Saving...',
            SUCCESS_MSG: 'Lead created successfully',
            ERROR_MSG: 'Error creating lead',
            DISCARD_TITLE: 'Discard Lead?',
        },
        TABLE: {
            NAME: 'Name',
            CONTACT: 'Contact',
            INTEREST: 'Interest',
            STATUS: 'Status',
            DATE: 'Date',
            ACTIONS: 'Actions',
            NO_LEADS: 'No leads found matching your search.',
        },
        STATUS: {
            NEW: 'New',
            CONTACTED: 'Contacted',
            CONSULTATION: 'Consultation',
            CONVERTED: 'Converted',
            LOST: 'Lost',
        },
        MESSAGES: {
            LOADING: 'Loading leads repository...',
            EMPTY: 'No leads found.',
            ERROR: 'Failed to fetch leads',
            SUCCESS_UPDATE: 'Status updated successfully',
            ERROR_UPDATE: 'Failed to update status',
            SUCCESS_DELETE: 'Lead deleted successfully',
            ERROR_DELETE: 'Error deleting lead',
        }
    },
    CUSTOMERS: {
        TITLE: 'Customer Management',
        SUBTITLE: 'Manage active clients and oversee care admissions.',
        ADD_BTN: '+ Admit New Client',
        SEARCH_PLACEHOLDER: 'Search clients...',
        TABLE: {
            NAME: 'Full Name',
            EMAIL: 'Email',
            STATUS: 'Status',
            ACTIONS: 'Actions',
            EMPTY: 'No customers found in the registry.',
            ANONYMOUS: 'Anonymous Customer',
            VIEW_DETAILS: 'View Details',
        },
        FILTERS: {
            ACTIVE_FILTERS: 'Active Filters:',
            CLEAR_ALL: 'Clear All',
            STATUS_LABEL: 'Status: ',
        },
        MESSAGES: {
            LOADING: 'Loading customer registry...',
        }
    },
    SCHEDULE: {
        TITLE: 'Visit Schedule',
        SUBTITLE: 'Coordinate care visits and assign PSWs to client requests.',
        ACTIONS: {
            CREATE: '+ Create Visit Request',
            ASSIGN: 'Assign Caregiver',
            CONFIRM_ASSIGN: 'Confirm Assignment',
            CANCEL_VISIT: 'Cancel Visit',
            CLOSE: 'Close',
            EDIT: 'Edit Details',
        },
        MODAL: {
            SELECT_PSW: 'Select Verified PSW',
            CHOOSE_WORKER: '-- Choose a worker --',
            CONFIRM_DELETE: 'Are you sure you want to cancel this visit?',
        },
        MESSAGES: {
            SUCCESS_ASSIGN: 'PSW assigned successfully!',
            SUCCESS_CANCEL: 'Visit cancelled',
            ERROR_ASSIGN: 'Assignment failed',
            ERROR_DELETE: 'Failed to delete visit',
            ERROR_UPDATE: 'Status update failed',
            OFFERS_SENT: 'Offers sent successfully',
            OFFERS_FAILED: 'Failed to send offers',
            SURGE_SUCCESS: 'Surge pricing updated successfully',
            SURGE_ERROR: 'Failed to apply surge pricing',
            NETWORK_ERROR: 'Network error while applying surge',
        }
    },
    SERVICES: {
        TITLE: 'Services & Pricing',
        SUBTITLE: 'Manage the care packages and hourly rates offered to clients.',
        ADD_BTN: '+ Add New Service',
        TABLE: {
            NAME: 'Service Name',
            CATEGORY: 'Category',
            RATE: 'Hourly Rate',
            DESC: 'Description',
            ACTIONS: 'Actions',
            LOADING: 'Loading services...',
            EMPTY: 'No services configured.',
        },
        FORM: {
            TITLE_CREATE: 'Add New Service',
            TITLE_EDIT: 'Edit Service',
            NAME_LABEL: 'Service Name',
            RATE_LABEL: 'Hourly Rate ($)',
            CATEGORY_LABEL: 'Category',
            DESC_LABEL: 'Description',
            SAVE_BTN: 'Save Service',
            CANCEL_BTN: 'Cancel',
            DISCARD_TITLE: 'Discard Changes?',
            DISCARD_DESC: 'You have unsaved changes in this service. Are you sure you want to close?',
        },
        MESSAGES: {
            SUCCESS_CREATE: 'Service created successfully!',
            SUCCESS_UPDATE: 'Service updated successfully!',
            SUCCESS_DELETE: 'Service deleted successfully',
            ERROR_SAVE: 'Failed to save service',
            ERROR_DELETE: 'Failed to delete service',
            ERROR_LOAD: 'Failed to load services',
            CONFIRM_DELETE: 'Are you sure you want to delete this service?',
        },
        CATEGORIES: {
            SENIOR_CARE: 'Senior Care',
            FOOT_CARE: 'Foot Care',
            CONSULTING: 'Consulting',
            TRAINING: 'Training',
        }
    },
    INCIDENTS: {
        TITLE: 'Incident Reports',
        SUBTITLE: 'Document clinical or operational incidents for audit.',
        ADD_BTN: 'Report Incident',
        FORM: {
            TITLE: 'Report New Incident',
            TYPE_LABEL: 'Incident Type',
            SEVERITY_LABEL: 'Severity',
            DESC_LABEL: 'Description',
            SUBMIT_BTN: 'Submit Report',
            REPORTING: 'Reporting...',
            SUCCESS_MSG: 'Incident report submitted',
            ERROR_MSG: 'Submission failed',
        },
        RESOLVE: {
            BTN: 'Resolve',
            TITLE: 'Resolve Incident',
            NOTES_LABEL: 'Resolution Notes',
            NOTES_PLACEHOLDER: 'Describe the steps taken to resolve this incident...',
            RESOLVING_LOADING: 'Resolving...',
            DISCARD_TITLE: 'Discard Changes?',
            DISCARD_DESC: 'You have typed resolution notes. Are you sure you want to cancel?',
            SUCCESS: 'Incident resolved successfully',
            ERROR: 'Failed to resolve incident',
        },
        TABLE: {
            TYPE: 'Type',
            REPORTER: 'Reporter',
            STATUS: 'Status',
            DATE: 'Date',
            ACTIONS: 'Actions',
            LOADING: 'Loading incidents...',
        }
    },
    DAILY_ENTRY: {
        TITLE: 'Daily Care Entry',
        LEFT_PANEL_TITLE: 'Select Context',
        CLIENT_LABEL: 'Client',
        CLIENT_PLACEHOLDER: 'Select Client...',
        TIP_TITLE: '💡 Tip',
        TIP_CONTENT: 'Auto-save is enabled for drafts. Submitting requires a signature.',
        ADL_TITLE: 'ADL Checklist',
        VITALS_TITLE: 'Vitals & Wellness',
        VITALS: {
            BP: 'BP',
            PULSE: 'Pulse',
            TEMP: 'Temp',
            MOOD_LABEL: 'Client Mood (1-5)',
        },
        NOTES_TITLE: 'Notes & Signature',
        NOTES_PLACEHOLDER: 'Daily progress notes, observations, or incidents...',
        SIGNATURE_LABEL: 'Digital Signature',
        SIGNATURE_PLACEHOLDER: 'Type full name to sign',
        SAVE_DRAFT: 'Save Draft',
        SUBMIT: 'Submit Entry',
        SUBMITTING: 'Submitting...',
        GUARD: {
            TITLE: 'Unsaved Changes',
            DESC: 'You have unsaved changes. Navigating away will discard them. Would you like to stay and save?',
            LEAVE: 'Leave',
            STAY: 'Stay',
        },
        MESSAGES: {
            SELECT_CLIENT: 'Please select a client',
            SIGNATURE_REQUIRED: 'Signature required for submission',
            SUCCESS_DRAFT: 'Draft saved!',
            SUCCESS_SUBMIT: 'Daily entry submitted successfully!',
            ERROR_SAVE: 'Failed to save entry',
            ERROR_SERVER: 'Error communicating with server',
        }
    },
    INVOICES: {
        TITLE: 'Invoice Management',
        SUBTITLE: 'Generate and track billing across the network.',
        FORM: {
            CREATE_TITLE: 'Create New Invoice',
            DESC_PLACEHOLDER: 'Description of service',
            AMOUNT_PLACEHOLDER: 'Amount ($)',
            ADD_ITEM: '+ Add Line Item',
            SUBMIT_BTN: 'Generate & Send Invoice',
            CANCEL_BTN: 'Cancel',
            DISCARD_TITLE: 'Discard Invoice?',
            DISCARD_DESC: 'Are you sure you want to cancel this invoice? Unsaved changes will be lost.',
        },
        MESSAGES: {
            SUCCESS_GENERATE: 'Invoice generated and sent successfully',
            ERROR_GENERATE: 'Failed to generate invoice',
        }
    },
    REPORTS: {
        TITLE: 'Reports & Analytics',
        SUBTITLE: 'Visualize key performance indicators and operational metrics.',
        EXPORT_BTN: 'Export CSV',
        DATE_RANGES: {
            7: 'Last 7 Days',
            30: 'Last 30 Days',
            90: 'Last Quarter',
            YEAR: 'Year to Date',
        },
        TABS: {
            OVERVIEW: 'Overview',
            FINANCIAL: 'Financials',
            STAFF: 'Staff Utilization',
            CLIENTS: 'Client Growth',
        }
    },
    EARNINGS: {
        TITLE: 'Earnings Center',
        SUBTITLE: 'Enterprise-grade financial oversight and payout management',
        STATS: {
            REVENUE: 'Total Revenue',
            PAYROLL: 'Total Payroll',
            PROFIT: 'Net Profit',
            PENDING: 'Payouts Pending',
        },
        TABS: {
            OVERVIEW: 'Overview',
            INVOICES: 'Invoices',
            PAYOUTS: 'Payouts',
            REPORTS: 'Reports',
        },
        ACTIONS: {
            EXPORT: 'Export Report',
            DATE_RANGE: 'Date Range',
            FILTER_ACTIVE: 'Filter Active',
        },
        INVOICE_ID: 'Invoice ID',
        CLIENT: 'Client',
        PSW: 'PSW',
        REVENUE: 'Revenue',
        PAYROLL: 'Payroll',
        PROFIT: 'Profit',
    },
} as const;
