export const opsServicesContent = {
    SERVICES: {
        TITLE: 'Services & Pricing',
        SUBTITLE: 'Manage the care packages and hourly rates offered to clients.',
        ADD_BTN: '+ Add New Service',
        TABLE: {
            NAME: 'Service Name',
            CATEGORY: 'Category',
            RATE: 'Hourly Rate',
            DESC: 'Description',
            ACTIONS: 'Actions',
            LOADING: 'Loading services...',
            EMPTY: 'No services configured.',
        },
        FORM: {
            TITLE_CREATE: 'Add New Service',
            TITLE_EDIT: 'Edit Service',
            NAME_LABEL: 'Service Name',
            RATE_LABEL: 'Hourly Rate ($)',
            CATEGORY_LABEL: 'Category',
            DESC_LABEL: 'Description',
            SAVE_BTN: 'Save Service',
            CANCEL_BTN: 'Cancel',
            DISCARD_TITLE: 'Discard Changes?',
            DISCARD_DESC: 'You have unsaved changes in this service. Are you sure you want to close?',
        },
        MESSAGES: {
            SUCCESS_CREATE: 'Service created successfully!',
            SUCCESS_UPDATE: 'Service updated successfully!',
            SUCCESS_DELETE: 'Service deleted successfully',
            ERROR_SAVE: 'Failed to save service',
            ERROR_DELETE: 'Failed to delete service',
            ERROR_LOAD: 'Failed to load services',
            CONFIRM_DELETE: 'Are you sure you want to delete this service?',
        },
        CATEGORIES: {
            SENIOR_CARE: 'Senior Care',
            FOOT_CARE: 'Foot Care',
            CONSULTING: 'Consulting',
            TRAINING: 'Training',
        }
    },
    INCIDENTS: {
        TITLE: 'Incident Reports',
        SUBTITLE: 'Document clinical or operational incidents for audit.',
        ADD_BTN: 'Report Incident',
        FORM: {
            TITLE: 'Report New Incident',
            TYPE_LABEL: 'Incident Type',
            SEVERITY_LABEL: 'Severity',
            DESC_LABEL: 'Description',
            SUBMIT_BTN: 'Submit Report',
            REPORTING: 'Reporting...',
            SUCCESS_MSG: 'Incident report submitted',
            ERROR_MSG: 'Submission failed',
        },
        RESOLVE: {
            BTN: 'Resolve',
            TITLE: 'Resolve Incident',
            NOTES_LABEL: 'Resolution Notes',
            NOTES_PLACEHOLDER: 'Describe the steps taken to resolve this incident...',
            RESOLVING_LOADING: 'Resolving...',
            DISCARD_TITLE: 'Discard Changes?',
            DISCARD_DESC: 'You have typed resolution notes. Are you sure you want to cancel?',
            SUCCESS: 'Incident resolved successfully',
            ERROR: 'Failed to resolve incident',
        },
        TABLE: {
            TYPE: 'Type',
            REPORTER: 'Reporter',
            STATUS: 'Status',
            DATE: 'Date',
            ACTIONS: 'Actions',
            LOADING: 'Loading incidents...',
        }
    },
} as const;
