export const opsFieldContent = {
    PSW_LIVE_VISIT: {
        TITLE: 'Live Visit Tracker',
        SUBTITLE: 'Real-time shift management and ADL reporting.',
        HEADER: {
            PATIENT: 'Active Client',
            START_TIME: 'Shift Start',
            ELAPSED: 'Time Elapsed',
            STATUS: 'Visit Status',
            IDLE: 'Caregiver Offline',
            IN_PROGRESS: 'Visit In-Progress',
            STAMP: 'Last Sync',
        },
        ACTIONS: {
            CLOCK_IN: 'Clock In',
            CLOCK_OUT: 'Clock Out',
            SUBMIT_ENTRY: 'Submit Care Entry',
            REPORT_INCIDENT: 'Report Incident',
        },
        CHECKOUT: {
            TITLE: 'Visit Completion',
            SUBTITLE: 'Final review and professional sign-off.',
            BUTTON: 'Finish & Checkout',
            CONFIRM: 'Are you sure you want to complete this visit?',
            GPS_LOCKED: 'Location Verified (GPS)',
            GPS_PULSE: 'Continuous Tracking Active',
            DURATION: 'Total Visit Duration',
        },
        CHECKIN: {
            TITLE: 'Visit Check-In',
            SUBTITLE: 'Authorized arrival and location verification.',
            LOADING: 'Loading visit context...',
            DESC: 'Please confirm your arrival at the client residence to begin clinical documentation.',
            BACK: 'Back to Schedule',
            BUTTON: 'Clock In Now',
            BTN_VERIFYING: 'Verifying Location...',
            BTN_VERIFIED: 'Verification Success',
            GPS_REQUIRED: 'GPS Location Required',
            GPS_TITLE: 'Authorized Arrival Distance',
            VISIT_DETAILS: {
                TITLE: 'Client & Visit Details',
                LOCATION: 'Visit Location',
                TIME_SLOT: 'Scheduled Time',
                SERVICE: 'Care Service',
            },
            GPS_IDLE: 'GPS Ready',
            GPS_VERIFYING: 'GPS Signal Search...',
            GPS_VERIFIED: (distance: number) => `GPS Verified: ${distance}m away`,
            GPS_ERROR: 'Location Verification Failed',
        },
        NAV: {
            HOME: 'Visit Home',
            VITALS: 'Vitals & Wellness',
            PROTOCOLS: 'Clinical Protocols',
            NURSING: 'Nursing Interventions',
            ADL: 'Care Tasks',
            NOTES: 'Clinical Notes',
            SUMMARY: 'Visit Summary',
            ACCOUNT: 'My Account',
        },
        CLINICAL: {
            TITLE: 'Clinical Protocol Hub',
            SUBTITLE: 'Authorized nursing and care guidelines.',
            VITALS: 'Vitals & Observation',
            NURSING: 'Medication & Nursing',
            PROTOCOLS: 'Clinical Guidelines',
            DIETARY: 'Dietary Monitoring',
            MOBILITY: 'Mobility & Physio',
            CONNECT_RN: 'Emergency RN Consultation',
            VITALS_HUB: 'Real-time Vitals Monitor',
        },
        MESSAGES: {
            SUCCESS: 'Action completed successfully',
            CLOCK_IN_SUCCESS: 'Clocked in successfully',
            CLOCK_OUT_SUCCESS: 'Clocked out successfully',
            ENTRY_SUCCESS: 'Visit entry submitted',
            DAILY_ENTRY_SUCCESS: 'Nursing entry documented successfully',
            NETWORK_ERROR: 'Network connection lost',
            DAILY_ENTRY_ERROR: 'Failed to submit clinical entry',
            CHECKOUT_ERROR: 'Failed to complete checkout',
            GEOLOCATION_NOT_SUPPORTED: 'Browser does not support geolocation',
            UNABLE_TO_RETRIEVE_LOCATION: 'Unable to retrieve GPS coordinates',
            LOAD_VISIT_NETWORK_ERROR: 'Failed to load visit details. Check connection.',
            LOAD_VISIT_ERROR: 'Failed to find visit context',
        }
    },
    PSW_MESSAGES: {
        TITLE: 'Caregiver Communications',
        SUBTITLE: 'Direct messaging with coordination and RN oversight.',
        RECIPIENTS: {
            OFFICE: 'Office Staff',
            RN: 'Supervising RN',
            FAMILY: 'Client Family',
        }
    },
    PSW_SCHEDULE: {
        TITLE: 'Shift Registry',
        SUBTITLE: 'Your upcoming and completed care visits.',
        TABS: {
            UPCOMING: 'Upcoming',
            COMPLETED: 'Completed',
            OFFERS: 'Open Offers',
        },
        ACTIONS: {
            ACCEPT: 'Accept Shift',
            DECLINE: 'Decline',
            DETAILS: 'View Details',
        },
        TABLE: {
            CLIENT: 'Client',
            TIME: 'Visit Time',
            DATETIME: 'Schedule Datetime',
            SERVICE: 'Care Service',
            LOCATION: 'Location',
            STATUS: 'Status',
            RATE: 'Pay Rate',
        },
        MESSAGES: {
            LOADING: 'Loading shift registry...',
            SUCCESS_ACCEPT: 'Shift accepted successfully!',
            SUCCESS_DECLINE: 'Shift declined',
            ERROR_ACTION: 'Failed to process shift action',
            EMPTY: 'No shifts found for this criteria.',
        }
    },
    PSW_HANDOVER: {
        TITLE: 'Shift Handover',
        SUBTITLE: 'Professional transfer of care responsibility.',
        LABEL_VISIT: 'Select Visit',
        LABEL_NOTES: 'Handover Notes',
        LABEL_SAFETY: 'Safety Concerns',
        LABEL_SUPPLIES: 'Critical Supplies Handover',
        PLACEHOLDER_NOTES: 'Summary of clinical status and ADL highlights...',
        SUCCESS_MSG: 'Handover documented successfully',
        ERROR_MSG: 'Failed to save handover',
    },
    PSW_PAYOUTS: {
        TITLE: 'Earnings & Payouts',
        SUBTITLE: 'Your payroll history and pending clinic settlements.',
        METRICS: {
            PENDING: 'Pending Approval',
            AVAILABLE: 'Available for Payout',
            TOTAL: 'Lifetime Earnings',
        },
        HISTORY_TITLE: 'Settlement History',
        TABLE: {
            DATE: 'Payout Date',
            AMOUNT: 'Amount',
            STATUS: 'Status',
            METHOD: 'Transfer Method',
        },
        ACTIONS: {
            WITHDRAW: 'Request Payout',
            HISTORY: 'Full History',
        },
        SUCCESS_REQUEST: 'Payout request submitted successfully',
        ERROR_REQUEST: 'Failed to submit payout request',
    },
    PSW_AVAILABILITY: {
        TITLE: 'Work Availability',
        SUBTITLE: 'Define your preferred clinical service hours.',
        SECTION_OVERRIDES: 'Availability Exceptions',
        ADD_OVERRIDE: 'Add Specific Date Override',
        SUCCESS_SYNC: 'Availability synced successfully',
        ERROR_SYNC: 'Failed to sync availability',
    },
    MANAGER_OPERATIONS: {
        TITLE: 'Regional Operations Hub',
        SUBTITLE: 'Cross-branch administrative and logistics triage.',
        TABS: {
            LOGISTICS: 'Logistics Overview',
            COMPLIANCE: 'Regional Compliance',
            TICKETS: 'Support Tickets',
        },
        ALERTS: {
            HIGH_RISK: 'High Risk Branch Alert',
            STAFFING_GAP: 'Regional Staffing Gap',
            COMPLIANCE_DROP: 'Compliance Variance Detected',
        },
        KPI: {
            LOGISTICS_EFFICIENCY: 'Logistics Efficiency',
            REVENUE: 'Regional Revenue Accrual',
            UTILIZATION: 'Regional Staffing Utilization',
            TURNOVER: 'Regional Turnover',
            COMPLIANCE: 'Regional Compliance',
            COMPLIANCE_RATE: 'Average Compliance Rate',
            AUDIT_PROGRESS: 'Regional Audit Progress',
        },
        GRID: {
            BRANCH: 'Branch',
            MANAGER: 'Branch Manager',
            HEALTH: 'Health Score',
            LAST_AUDIT: 'Last Audit',
        },
        ACTIONS: {
            AUDIT: 'Initiate Regional Audit',
            SYNC: 'Sync branch ledgers',
            GLOBAL_SYNC: 'Regional Satellite Sync',
            DOWNLOAD_REPORT: 'Download Operations Report',
        },
        MESSAGES: {
            AUDIT_START: 'Regional audit sequence initiated...',
            SYNC_SUCCESS: 'All branch data synchronized',
        }
    },
    COORDINATOR_WAITLIST: {
        TITLE: 'Waitlist Management',
        SUBTITLE: 'Prioritize and match clients awaiting care.',
        COLUMNS: {
            PRIORITY: 'Priority Rank',
            CLIENT: 'Client Name',
            STATUS: 'Waitlist Status',
            SINCE: 'Waiting Since',
            ENTRY_DATE: 'Date Added',
            URGENCY: 'Clinical Urgency',
            ACUITY: 'Clinical Acuity Score',
            PREFERENCE: 'Provider Preference',
        },
        ACTIONS: {
            MATCH: 'Execute Match',
            PRIORITIZE: 'Adjust Priority',
            BOOST_PRIORITY: 'Priority Elevation',
            ASSIGN_STAFF: 'Manual Caregiver Assignment',
            REMOVE: 'Remove from List',
        },
        MESSAGES: {
            SUCCESS_MATCH: 'Client matched successfully',
            ERROR_MATCH: 'Failed to find suitable match',
        }
    },
    COORDINATOR_SOS: {
        TITLE: 'Emergency Response Center',
        SUBTITLE: 'Real-time SOS monitoring and clinical triage.',
        ALERTS_TITLE: 'Active Clinical SOS Alerts',
        FORM: {
            RESOLUTION_LABEL: 'Resolution Summary',
            PLACEHOLDER_RESOLUTION: 'Describe clinical outcome, dispatch status...',
            INCIDENT_LOG: 'Emergency Incident Log',
            RESOLVE_BTN: 'Finalize Resolution',
        },
        TABLE: {
            TIME: 'Alert Time',
            PSW: 'Caregiver',
            CLIENT: 'Patient',
            LOCATION: 'Live GPS',
            STATUS: 'Alert Status',
        },
        ACTIONS: {
            ACKNOWLEDGE: 'Acknowledge SOS',
            DISPATCH: 'Dispatch Emergency Services',
            RESOLVE: 'Mark as Resolved',
        },
        MESSAGES: {
            SUCCESS_ACK: 'SOS alert acknowledged and escalated',
            ERROR_ACK: 'Failed to acknowledge SOS',
            LOCK_WARNING: 'Another coordinator is currently responding to this alert.',
            NO_ALERTS: 'No active clinical SOS alerts detected.',
        }
    },
    COORDINATOR_MAP: {
        TITLE: 'Live Logistics Map',
        SUBTITLE: 'Real-time spatial visualization of regional clinical operations.',
        LEGEND: {
            ACTIVE: 'Active Visit',
            IDLE: 'Idle/Travel',
            SOS: 'SOS Alert',
            CLIENT: 'Client Location',
        },
        ACTIONS: {
            REFRESH: 'Refresh Fleet Data',
            CENTER: 'Center on Region',
            FILTER: 'Filter Assets',
        }
    },
} as const;
