export const scrumMasterContent = {
    API_HUB: {
        TITLE: 'API Integrity Hub',
        SUBTITLE: 'Endpoint registry',
        TEST_BTN: 'Test Protocol',
        READY: 'Registry Ready',
        TESTING: '⌛ Analysis...',
    },
    MONITORING: {
        TITLE: 'System Health',
        SUBTITLE: 'Real-time platform vitals and operational telemetry.',
        API_CLUSTER: 'Worker API Cluster',
        UPTIME_DESC: 'Continuous operational uptime per role basis.',
        DB_TELEMETRY: 'Database Query Latency',
        LOGS_TITLE: 'Live System Logs',
        HEARTBEAT: 'System heartbeat pulse detected.',
    },
    ENV_AUDIT: {
        TITLE: 'Environment Audit',
        SUBTITLE: 'Infrastructure and environment variable verification.',
        SECURITY_NOTE: 'Sensitive values are masked for audit compliance.',
    },
    REGISTRY_CHECK: {
        TITLE: 'Registry Integrity',
        SUBTITLE: 'Structural compliance check across all registries.',
    },
    SCHEMA: { TITLE: 'Schema Audit' },
    BUILDS: { TITLE: 'Build Surveillance' },
    SCANS: { TITLE: 'Vulnerability Scans' },
    LOCALIZATION: {
        TITLE: 'Localization Audit',
        SUBTITLE: 'I18n coverage and registry shadowing report.',
    },
    PERFORMANCE: {
        TITLE: 'Node Performance',
        SUBTITLE: 'Real-time node and worker performance metrics.',
    },
    THEME_LAB: { TITLE: 'Theme Studio' },
    SECURITY_SCANS: {
        TITLE: 'Security Scans',
        SUBTITLE: 'Vulnerability and dependency lattice surveillance.',
    },
    BUILD_HEALTH: {
        TITLE: 'Build Health',
        SUBTITLE: 'Live CI/CD and production bundle status.',
    },
    MONITORING_STATS: { TITLE: 'Monitoring Stats' },
    DATABASE_SCHEMA: {
        TITLE: 'Database Schema',
        SUBTITLE: 'Prisma overview and data model audit.',
        MODEL_NAME: 'Model',
        CORE_FIELDS: 'Fields',
        RELATIONS: 'Rel',
        SYNC_STATUS: 'Sync',
        INSIGHT: 'Data isolation isolated at app level.',
    },
    INTEGRITY: {
        TITLE: 'System Integrity',
        TOTAL_ROUTES: 'Total Route Definitions',
        API_MAPPINGS: 'API Endpoint Mappings',
        TRANSLATION_OVERLAP: 'Translation Keys Overlap',
        BROKEN_LINKS: 'Broken Internal Links',
    },
    COMPONENTS: {
        TITLE: 'UI Comp',
        SUBTITLE: 'Design tokens',
        COMPONENT_NAME: 'Component',
        REFERENCE: 'Reference',
        STATUS: 'Active Status',
        LAYER: 'Architectural Layer',
    },
    PAGES: {
        TITLE: 'Pages',
        SUBTITLE: 'Fractal tiering and route validation.',
    },
    API_ENDPOINTS: {
        TITLE: 'APIs',
        SUBTITLE: 'Endpoint health and latency tracking.',
    },
    DASHBOARD: {
        TITLE: 'Scrum Master Home',
        SUBTITLE: 'Engineering oversight and platform integrity metrics.',
    },
    DEV_KB: {
        TITLE: 'Developer Knowledge Base',
        SUBTITLE: 'Documentation for technical architecture and engineering patterns.',
        SEARCH_PLACEHOLDER: 'Search architecture docs...',
    },
    ANALYTICS: {
        TITLE: 'System Health Telemetry',
        LATENCY: 'API Latency (v1)',
        ERRORS: 'Error Distribution',
        AVAILABILITY: 'System Availability',
        COMPLIANCE: 'Registry Compliance',
        X_AXIS: 'Time',
        Y_AXIS: 'ms',
    },
    ALERTS: {
        TITLE: 'Active System Alerts',
        CRITICAL: 'Critical Environment Failure',
        WARNING: 'Sync Latency High',
        INFO: 'Daily Compliance Job Pending',
        RESOLVE: 'Resolve',
    },
    ROADMAP: {
        TITLE: 'Product Roadmap & Enhancements',
        PHASE_1: 'Phase 14: Health Analytics',
        PHASE_2: 'Phase 15: AI-Driven Self-Healing',
        PHASE_3: 'Phase 16: Multi-Cloud Replication',
        STATUS_PLANNED: 'Planned',
        STATUS_IN_PROGRESS: 'In Progress',
        STATUS_COMPLETED: 'Completed',
    },
    COPILOT: {
        TITLE: 'Scrum Master AI Copilot',
        SUBTITLE: 'Predictive analytics and autonomous health management',
        SUGGESTION_1: 'Optimize API caching for /v1/admission',
        SUGGESTION_2: 'Unusual latency spike detected in US-EAST cluster',
        SUGGESTION_3: 'Schema drift detected in Earnings module',
    },
    GOVERNANCE: {
        TITLE: 'Live Governance',
        FOOTER: "Shadowing is strictly monitored. Ensure your local environment is configured for 'TECHNICAL_SUPPORT' mode before assuming identities.",
        TITLE_ALERTS: 'Security & Compliance Guardrails',
        DATA_ISOLATION: 'Tenant Data Isolation',
        ENCRYPTION: 'At-Rest Encryption',
        AUDIT_TRAIL: 'Immutable Audit Logs',
        STATUS_LOCKED: 'Secured',
    },
    SELF_HEALING: {
        TITLE: 'Self-Healing Engine',
        ACTION_RESTART: 'Auto-Restart Node',
        ACTION_CACHE: 'Cache Purge',
        ACTION_SYNC: 'Registry Re-Sync',
    },
    PROPOSAL_BOARD: {
        TITLE: 'Strategic Proposal Board',
        SUBTITLE: 'Community-driven feature requests and infrastructure improvements.',
        P1: 'Implement Advanced Caching Layer',
        P2: 'Multi-Region Database Failover',
        P3: 'Zero-Trust Security Model',
    },
    GLOBAL_NODES: {
        TITLE: 'Global Infrastructure Health',
        US_EAST: 'US-East Cluster',
        EU_WEST: 'EU-West Cluster',
        ASIA_PACIFIC: 'Asia-Pacific Cluster',
    },
    FLOW_DRILL: {
        TITLE: 'Role Flow Analysis',
        JOURNEY_MAP: 'Journey Steps',
    },
    ANOMALIES: {
        TITLE: 'Detected Anomalies',
        SEVERITY: 'Severity',
        COMPONENT: 'Component',
        OBSERVATION: 'Observation',
        TECHNICAL_SUGGESTION: 'Technical Suggestion',
    },
    ROLE_FLOWS: {
        TITLE: 'Flows',
        SUBTITLE: 'User journeys',
        SECURITY_ROLES: 'Security Roles',
        WORKFLOW_PATHWAY: 'Workflow pathway',
        STEPS: {
            ADMIN: ['Home Overlay', 'User Management', 'Global Schedule', 'Earnings Center', 'System Settings', 'Developer Audit Hub'] as const,
            SCRUM_MASTER: ['Technical Home', 'API Registry Audit', 'Blueprint Gap Analysis', 'Performance Sweep', 'Security Surveillance', 'Theme Customization'] as const,
            MANAGER: ['Operations Home', 'Shift Coordination', 'Clinical Reviews', 'Payroll Verification', 'Regional Analytics'] as const,
            MARKETING_MANAGER: ['Growth Pipeline', 'CRM Management', 'Lead Conversion', 'Campaign Performance'] as const,
            HR_MANAGER: ['Talent Pipeline', 'Recruitment Funnel', 'Onboarding Tracking', 'Compliance Audits'] as const,
            FINANCE_MANAGER: ['Revenue Intelligence', 'Expense Audits', 'Payroll Reconciliation', 'Tax Compliance'] as const,
            REGIONAL_MANAGER: ['Regional P&L', 'Branch Benchmarking', 'Operational Overhead', 'Growth Strategy'] as const,
            CLINICAL_MANAGER: ['Clinical Audit', 'Medication Safety', 'QA Compliance', 'Incident Oversight'] as const,
            COORDINATOR: ['Live Dispatch Map', 'SOS Queue', 'Coverage Alerts', 'Emergency Check-in'] as const,
            RECRUITING_MANAGER: ['Job Postings', 'Candidate Screening', 'Interview Roster', 'Offer Management'] as const,
            STAFF: ['Staff Hub', 'Lead Inquiries', 'Customer Roster', 'Incident Logging', 'Compliance Monitoring'] as const,
            RN: ['Clinical Home', 'Care Plan Manager', 'Daily Entry Audit', 'Supervision Hub'] as const,
            PSW: ['My Schedule', 'Open Market', 'Visit Check-in/out', 'Payout Requests', 'Compliance Ledger'] as const,
            CLIENT: ['Care Hub', 'New Request', 'Assigned Team', 'Digital Invoices', 'Feedback Gateway'] as const,
        }
    },
} as const;
