const TENANCY = {
    MANAGER: {
        DASHBOARD_KPI: '/v1/manager/dashboard/kpi',
        DASHBOARD_TODAY: '/v1/manager/dashboard/today',
        DASHBOARD_STATS: '/v1/manager/dashboard/stats',
        PERFORMANCE: '/v1/manager/performance/rankings',
        FINANCE: '/v1/manager/finance/pl',
        PAYROLL_AUDIT: '/v1/manager/finance/payroll-audit',
        BILLING_FINALIZE: '/v1/manager/finance/billing/finalize',
        TRAINING: '/v1/manager/training',
        SURVEYS: '/v1/manager/surveys',
        EVALUATIONS: '/v1/manager/evaluations',
        OPS_STATS: '/v1/manager/ops/stats',
        BRANCH_HEALTH: '/v1/manager/ops/branch-health',
        COMPLIANCE_SYNC: '/v1/manager/ops/compliance/sync',
        FEEDBACK_TRIAGE: (id: string) => `/v1/manager/ops/feedback/${id}/triage`,
        STAFF_ADD: '/v1/manager/staff/add',
        STAFF_EDIT: (id: string) => `/v1/manager/staff/${id}`,
        AUDIT_ATTENDANCE: '/v1/manager/audit/attendance',
    },
    CLIENT: {
        BOOKINGS: '/v1/client/bookings',
        BOOKING_REQUESTS: '/v1/client/bookings/requests',
        INVOICES: '/v1/client/invoices',
        SERVICES: '/v1/client/services',
        DASHBOARD_STATS: '/v1/client/dashboard/stats',
        CATALOG: '/v1/client/services/catalog',
        SUPPORT: '/v1/client/support/nursing-chat',
        CARE_TEAM: '/v1/client/team/roster',
        FEEDBACK_SUBMIT: '/v1/client/support/feedback',
        FAMILY_FEED: '/v1/client/engagement/feed',
        INVOICE_PAY: '/v1/client/engagement/pay-invoice',
        BOOKING_CANCEL: (id: string) => `/v1/client/bookings/${id}/cancel`,
    },
    PSW: {
        VISITS: '/v1/psw/schedule/visits',
        CHECK_IN: (id: string) => `/v1/psw/schedule/visits/${id}/check-in`,
        CHECK_OUT: (id: string) => `/v1/psw/schedule/visits/${id}/check-out`,
        PAYOUT_REQUEST: '/v1/psw/schedule/payouts/request',
        HANDOVER_SUBMIT: '/v1/psw/handover',
        AVAILABILITY_SYNC: '/v1/psw/availability/sync',
        WELLNESS_PULSE: '/v1/psw/wellness/pulse',
        PAYOUT_HISTORY: '/v1/psw/payouts/history',
        DAILY_ENTRY_SUBMIT: '/v1/psw/daily-entry',
        DASHBOARD_STATS: '/v1/psw/dashboard/stats',
        CREDENTIALS: '/v1/psw/credentials/vault',
        OFFERS: '/v1/psw/schedule/offers',
        OFFER_ACCEPT: (id: string) => `/v1/psw/schedule/offers/${id}/accept`,
        OFFER_DECLINE: (id: string) => `/v1/psw/schedule/offers/${id}/decline`,
        FEED: '/v1/psw/feed/social',
        INCIDENT_REPORT: '/v1/psw/incident/report',
    },
    RN: {
        DASHBOARD_STATS: '/v1/rn/dashboard/stats',
        CARE_PLANS: '/v1/rn/clinical/care-plans',
        CARE_PLAN_REVIEW: (id: string) => `/v1/rn/clinical/care-plans/${id}/review`,
        DAILY_AUDIT_LIST: '/v1/rn/clinical/audit/list',
        DAILY_AUDIT_SIGN_OFF: '/v1/rn/clinical/audit/sign-off',
        DAILY_REVIEW: (id: string) => `/v1/rn/daily-review/${id}/review`,
        SUPERVISION_OVERVIEW: (pswId: string) => `/v1/rn/clinical/supervision/psw/${pswId}/overview`,
        CLINICAL_ASSESS: '/v1/rn/clinical/assessments',
        RECON_SYNC: '/v1/rn/clinical/recon',
        RN_SUPERVISION: '/v1/rn/clinical/supervision',
        SUPERVISION_ROSTER: '/v1/rn/clinical/supervision/roster',
        CAREPLAN_VERIFY: (id: string) => `/v1/rn/clinical/care-plans/${id}/verify`,
    },
    STAFF: {
        CUSTOMERS: '/v1/staff/customers',
        TICKETS: '/v1/staff/tickets',
        DASHBOARD_STATS: '/v1/staff/dashboard/stats',
        TASKS: '/v1/staff/tasks/grid',
        MESSAGES: '/v1/staff/messages/hub',
        INCIDENT_SUBMIT: '/v1/staff/ops/incidents/submit',
        COMPLIANCE_SCAN: '/v1/staff/ops/compliance/scan',
        COORDINATOR: {
            COVERAGE_ALERTS: '/v1/manager/coordinator/coverage-alerts',
        },
    },
    COORDINATOR: {
        MATCH_OVERRIDE: '/v1/coordinator/match/override',
        WAITLIST_SYNC: '/v1/coordinator/waitlist/sync',
        SOS_ACK: '/v1/coordinator/incident/ack',
        SOS_INCIDENTS: '/v1/coordinator/incidents',
        SOS_DISPATCH: '/v1/coordinator/sos-dispatch',
        DASHBOARD_STATS: '/v1/coordinator/dashboard/stats',
        DISPATCH_MAP: '/v1/coordinator/dispatch-map',
        MATCHING_RUN: '/v1/coordinator/matching/run',
        MASTER_SCHEDULE: '/v1/coordinator/schedule/master',
        SHIFT_BROADCAST: '/v1/coordinator/shifts/broadcast',
        SHIFT_TRIAGE: '/v1/coordinator/shifts/triage',
        GPS_PING: (id: string) => `/v1/coordinator/tracking/${id}/ping`,
    },
} as const;

const PLATFORM = {
    ADMIN: {
        USERS: '/v1/admin/users',
        USERS_VERIFY: (id: string) => `/v1/admin/users/${id}/verify`,
        PSW_APPROVE: (id: string) => `/v1/admin/psw/approve/${id}`,
        STATS: '/v1/admin/stats',
        SERVICES: '/v1/admin/services',
        CAMPAIGNS: '/v1/admin/marketing/campaigns',
        LEADS: '/v1/admin/leads',
        LEADS_UPDATE: (id: string) => `/v1/admin/leads/${id}`,
        VISITS: '/v1/admin/visits',
        VISITS_ASSIGN: '/v1/admin/visits/assign',
        VISITS_UNASSIGNED: '/v1/admin/visits/unassigned',
        VISITS_UPDATE: (id: string) => `/v1/admin/visits/${id}`,
        INCIDENTS: '/v1/admin/incidents',
        CRISIS_MODE: '/v1/incidents/crisis-mode',
        TIMESHEETS: '/v1/admin/timesheets',
        INVOICES: '/v1/admin/invoices',
        CLIENTS: '/v1/admin/clients',
        SETTINGS_BUSINESS_MODEL: '/v1/admin/settings/business-model',
        SETTINGS_LOGO: '/v1/admin/settings/logo',
        SEARCH: '/v1/admin/search',
        REPORTS: '/v1/admin/reports/export',
        SETTINGS_COMMIT: '/v1/admin/settings/save',
        CONTENT_PUBLISH: '/v1/admin/content/publish',
        SEARCH_REINDEX: '/v1/admin/search/reindex',
        LEADS_CONVERT: (id: string) => `/v1/admin/leads/${id}/convert`,
        UI_OVERRIDE_COMMIT: '/v1/admin/registry/ui-override/commit',
        OPERATIONS: {
            REALTIME_CAPACITY: '/v1/admin/ops/capacity',
            REGION_MAPPING: '/v1/admin/ops/regions',
            SUPPLY_DEMAND: '/v1/admin/ops/supply-demand',
            LOGISTICS_HUB: '/v1/admin/ops/logistics',
            PREDICTIVE_ROUTOR: '/v1/admin/ops/predictive/dispatch',
            OPTIMIZE_LOGISTICS: '/v1/admin/ops/optimize',
        },
        RESELLER: {
            DASHBOARD: '/v1/admin/reseller/stats',
            FRANCHISES: '/v1/admin/reseller/franchises',
            PROVISION: '/v1/admin/reseller/provision',
            AGREEMENTS: '/v1/admin/reseller/agreements',
            SUSPEND: (id: string) => `/v1/admin/reseller/franchise/${id}/suspend`,
        },
        ERP: {
            INVENTORY: '/v1/admin/erp/inventory',
            SUPPLIERS: '/v1/admin/erp/suppliers',
            PURCHASE_ORDERS: '/v1/admin/erp/purchase-orders',
            STOCK_SYNC: '/v1/admin/erp/stock/sync',
        },
        TELEHEALTH: {
            DASHBOARD: '/v1/admin/telehealth/stats',
            SESSIONS: '/v1/admin/telehealth/sessions',
            CREATE_SESSION: '/v1/admin/telehealth/sessions/create',
            VITAL_SIGN_PUSH: '/v1/admin/telehealth/vitals/push',
        },
        RCM: {
            DASHBOARD: '/v1/admin/rcm/stats',
            CLAIMS: '/v1/admin/rcm/claims',
            SUBMIT_CLAIM: '/v1/admin/rcm/claims/submit',
            REVENUE_SYNC: '/v1/admin/rcm/revenue/sync',
        },
        PHARMACY: {
            DASHBOARD: '/v1/admin/pharmacy/stats',
            PRESCRIPTIONS: '/v1/admin/pharmacy/prescriptions',
            ORDER_DRUGS: '/v1/admin/pharmacy/orders',
            MAR_SYNC: '/v1/admin/pharmacy/mar/sync',
        },
        REGIONAL: {
            PL_EXPORT: '/v1/admin/regional/fin/pl-export',
            AUDIT_REQUEST: '/v1/admin/regional/governance/audit-req',
        },
        REPORTING: {
            TRADING_ACCOUNT: '/v1/admin/financial/reports/trading-account',
            PROFIT_LOSS: '/v1/admin/financial/reports/p-and-l',
            BALANCE_SHEET: '/v1/admin/financial/reports/balance-sheet',
            DAILY_SUMMARY: '/v1/admin/financial/reports/daily-summary',
            RECONCILIATION_SUMMARY: '/v1/admin/financial/reports/reconciliation-summary',
        }
    },
    SCRUM_MASTER: {
        DASHBOARD: '/v1/scrum-master/stats',
        API_ENDPOINTS: '/v1/scrum-master/endpoints',
        ENV_AUDIT: '/v1/scrum-master/env-audit',
        AUTO_FIX: '/v1/scrum-master/auto-fix',
        LOG_FLUSH: '/v1/scrum-master/forensics/flush',
        DB_RESEED: '/v1/scrum-master/governance/reseed',
        UNIVERSAL_SWEEP: '/v1/scrum-master/registry/sweep',
        SWEEP_START: '/v1/scrum-master/registry/sweep',
        RESPONSE_BOT_SCAN: '/v1/scrum-master/registry/sweep',
        SECURITY_SCAN: '/v1/scrum-master/security/scan',
        AUDITS_HISTORY: '/v1/scrum-master/audits',
        REGISTRY_HEALTH: '/v1/scrum-master/registry/health',
        REGISTRY_SYNC: '/v1/scrum-master/registry/sync',
        DEBUG_HASH: '/v1/debug/hash',
    },
    SYSTEM: {
        NOTIFICATIONS: '/v1/system/notifications',
        MARK_READ: (id: string) => `/v1/system/notifications/${id}/read`,
        PLATFORM_STATS: '/v1/system/platform/stats',
        CAPACITY: '/v1/system/ops/capacity',
        REGIONS: '/v1/system/ops/regions',
        LOGISTICS_HUB: '/v1/system/ops/logistics',
    },
    SUPERUSER: {
        TENANTS: '/v1/superuser/tenants',
        AUDIT_LOGS: '/v1/superuser/audit-logs',
        GOVERNANCE: '/v1/superuser/governance',
        PLATFORM_HEALTH: '/v1/superuser/health/summary',
        SLA_COMPLIANCE: '/v1/superuser/sla/compliance',
        POLICY_ENGINE: '/v1/superuser/policies/engine',
        RISK_SCAN: '/v1/superuser/risk-surveillance',
    },
    AI: {
        INSIGHTS: '/v1/ai/insights',
        PREDICTIVE: '/v1/ai/predictive',
        CHURN: '/v1/ai/churn',
        OPTIMIZATION: '/v1/ai/optimization',
        VISIT_SENTIMENT: '/v1/ai/visit-sentiment',
        AI_OPTIMIZE: '/v1/ai/optimize-flow',
        AI_SENTIMENT_SCAN: '/v1/ai/sentiment-scan',
        INSIGHTS_REFRESH: '/v1/ai/insights/refresh',
        AUTOPILOT_ENGAGE: '/v1/ai/autopilot/engage',
    },
    SECURITY: {
        THREATS: '/v1/security/threats',
        SESSIONS: '/v1/security/sessions',
        PERMISSIONS: '/v1/security/permissions',
        AUDIT_DETAIL: (id: string) => `/v1/security/audits/${id}`,
        CRYPTO_HEALTH: '/v1/security/crypto-health',
        THREAT_DETECTION: '/v1/security/threat-detection',
        PLATFORM_AUDIT_LOGS: '/v1/security/platform-audit',
    },
    INTEROP: {
        FHIR_EXPORT: (id: string) => `/v1/interop/fhir/export/${id}`,
        FHIR_IMPORT: '/v1/interop/fhir/import',
        DID_VERIFY: '/v1/interop/did/verify',
        HEALTH_ID_GENERATE: '/v1/interop/did/generate',
    },
} as const;

export const ApiRegistry = {
    AUTH: {
        LOGIN: '/v1/auth/login',
        REGISTER: '/v1/auth/register',
        FORGOT_PASSWORD: '/v1/auth/forgot-password',
        RESET_PASSWORD: '/v1/auth/reset-password',
        LOGOUT: '/v1/auth/logout',
        SWITCH_ROLE: '/v1/auth/switch-role',
        REFRESH: '/v1/auth/refresh',
        IMPERSONATE: '/v1/auth/impersonate',
    },
    USER: {
        PROFILE: '/v1/user/profile',
    },
    PLATFORM,
    ...PLATFORM,
    TENANCY,

    // Legacy mapping
    MANAGER: TENANCY.MANAGER,
    CLIENT: TENANCY.CLIENT,
    PSW: TENANCY.PSW,
    RN: TENANCY.RN,
    STAFF: TENANCY.STAFF,
    COORDINATOR: TENANCY.COORDINATOR,
    SYSTEM: PLATFORM.SYSTEM,

    PUBLIC: {
        LEADS: '/v1/public/leads',
        SERVICES: '/v1/public/services',
        BLOG: '/v1/public/blog',
    },
    SUPPORT: {
        CHAT_HISTORY: '/v1/support/chat',
        TICKETS: '/v1/support/tickets',
    }
} as const;
