export const ContentRegistry = {
    APP: {
        NAME: 'PrimeCare',
        TAGLINE: 'Compassionate Care, Professional Service',
    },
    AUTH: {
        LOGIN_TITLE: 'Sign in to your account',
        LOGIN_TITLE_CLIENT: 'Client Portal Login',
        LOGIN_TITLE_STAFF: 'Staff Portal Login',
        LOGIN_TITLE_PSW: 'Caregiver Portal Login',
        LOGIN_TITLE_RN: 'Registered Nurse Portal Login',
        BUTTON: 'Sign in',
        BUTTON_CLIENT: 'Sign In as Client',
        BUTTON_PSW: 'Sign In as Caregiver',
        BUTTON_RN: 'Sign In as RN',
        BUTTON_STAFF: 'Sign In as Staff',
        EMAIL_LABEL: 'Email address',
        PASSWORD_LABEL: 'Password',
        FORGOT_PASSWORD: 'Forgot password?',
        REGISTER_TITLE: 'Create your account',
        BUTTON_REGISTER: 'Sign up',
        SIGNUP_LINK: "Don't have an account? Sign up",
    },
    ADMIN_DASHBOARD: {
        STATS: {
            TOTAL_USERS: 'Total Users',
            NEW_INQUIRIES: 'New Inquiries',
            PENDING_VISITS: 'Pending Visits',
            TOTAL_VISITS: 'Total Care Visits',
        },
        TITLES: {
            WELCOME: 'Welcome back, Admin',
            SUBTITLE: "Here is what's happening today at PrimeCare.",
            QUICK_ACTIONS: 'Quick Actions',
            OPERATIONAL_STATUS: 'Operational Status',
            ANALYTICS: 'Performance Analytics',
        },
        ACTIONS: {
            VIEW_DETAILS: 'Click to view details →',
            CHECK_CERTS: 'Check certifications',
            VIEW_SCHEDULE: 'View Schedule',
            MANAGE_ASSIGNMENTS: 'Manage assignments',
            REVIEW_LEADS: 'Review Leads',
            RESPOND_INQUIRIES: 'Respond to inquiries',
            SYSTEM_CONFIG: 'System Config',
            APP_ADJUSTS: 'App adjustments',
            POST_SHIFT: '+ Post New Shift',
            POST_SHIFT_DESC: 'Direct or open posting',
            POST_SUCCESS: 'Shift posted successfully!',
        },
        STATUS: {
            API: 'Worker API Status',
            CLIENT_APP: 'Mobile Client App',
            PSW_APP: 'Mobile PSW App',
            HEALTHY: '● Healthy',
            ONLINE: (v: string) => `● v${v} Online`,
        }
    },
    CLIENT_DASHBOARD: {
        TITLE: 'My Care Hub',
        SUBTITLE: 'Welcome back to your family care portal.',
        BUTTON_REQUEST: 'Request New Care',
        MODAL_TITLE: 'Request New Care',
        MODAL_SUBTITLE: 'Please select your care type and preferred time.',
        MESSAGES: {
            LOADING: 'Loading Client Dashboard...',
        }
    },
    PSW_DASHBOARD: {
        TITLE: 'My Work Schedule',
        SUBTITLE: 'Stay updated on your upcoming assigned care visits.',
        BUTTON_FULL_SCHEDULE: 'View Full Schedule',
        SECTION_SHIFTS: 'Shift Schedule',
        NO_SHIFTS: 'You have no shifts scheduled at this time.',
        MESSAGES: {
            LOADING: 'Loading Provider Dashboard...',
        }
    },
    RN_DASHBOARD: {
        TITLE: 'Clinical Care Management',
        SUBTITLE: 'Supervise care plans, review daily entries, and manage clinical outcomes.',
        QUICK_ACTIONS: 'Clinical Oversight',
        STATS: {
            PENDING_CARE_PLANS: 'Care Plans to Review',
            DAILY_REVIEWS: 'Daily Entries to Verify',
            SUPERVISED_PSWS: 'PSWs Under Supervision',
        },
        TASKS: {
            TITLE: 'Pending Clinical Tasks',
            EMPTY: 'No pending clinical tasks.',
            RESOLVE_BTN: 'Resolve Task',
            PATIENT_LABEL: 'Patient: ',
        },
        MESSAGES: {
            LOADING: 'Loading Clinical Dashboard...',
        }
    },
    USERS: {
        TITLE: 'Users & Healthcare Workers',
        APPROVE_BTN: 'Approve',
        ROLE: 'Role',
        STATUS: 'Status',
        INVITE_BTN: 'Invite User',
        ADD_BTN: 'Add New User',
        INVITE_PROMPT: 'Enter email to invite:',
        INVITE_SUCCESS: (email: string) => `Invitation sent to ${email}`,
        VERIFY_BTN: 'Verify Certs',
        EDIT_BTN: 'Edit',
        ID_VERIFICATION: 'ID Verification',
        ACTIONS: 'Actions',
        VERIFIED: 'Verified',
        PENDING: 'Pending Review',
        CLEAR_FILTERS: 'Clear All',
        ACTIVE_FILTERS: 'Active Filters:',
        MESSAGES: {
            LOADING: 'Retrieving secure user registry...',
            EMPTY: 'No users found in the registry.',
            ERROR_VERIFY: 'Failed to approve worker',
            ERROR_LOAD: 'Failed to load user list',
            SUCCESS_VERIFY: 'User extracted and verified successfully',
        },
        MODAL: {
            INVITE_TITLE: 'Invite New User',
            DISCARD_TITLE: 'Discard Invite?',
            DISCARD_DESC: 'Are you sure you want to cancel this invitation?',
            DISCARD_BTN: 'Discard',
            STAY_BTN: 'Stay',
            SEND_BTN: 'Send Invite',
            SENDING: 'Sending...',
        },
        FORM: {
            TITLE_CREATE: 'Create New User',
            TITLE_EDIT: 'Edit User',
            SUBTITLE: 'Manage system access and profile details.',
            BTN_CREATE: 'Create User',
            BTN_UPDATE: 'Update User',
            BTN_CANCEL: 'Cancel',
            LOADING: 'Loading user data...',
            ERROR_LOAD: 'Failed to load user data',
            SUCCESS_CREATE: 'User created successfully',
            SUCCESS_UPDATE: 'User updated successfully',
            ERROR_ACTION: 'Action failed',
        }
    },
    INCIDENTS: {
        TITLE: 'Incident Reports',
        SUBTITLE: 'Document clinical or operational incidents for audit.',
        ADD_BTN: 'Report Incident',
        FORM: {
            TITLE: 'Report New Incident',
            TYPE_LABEL: 'Incident Type',
            SEVERITY_LABEL: 'Severity',
            DESC_LABEL: 'Description',
            SUBMIT_BTN: 'Submit Report',
            REPORTING: 'Reporting...',
            SUCCESS_MSG: 'Incident report submitted',
            ERROR_MSG: 'Submission failed',
        },
        RESOLVE: {
            BTN: 'Resolve',
            TITLE: 'Resolve Incident',
            NOTES_LABEL: 'Resolution Notes',
            NOTES_PLACEHOLDER: 'Describe the steps taken to resolve this incident...',
            RESOLVING_LOADING: 'Resolving...',
            DISCARD_TITLE: 'Discard Changes?',
            DISCARD_DESC: 'You have typed resolution notes. Are you sure you want to cancel?',
        },
        TABLE: {
            TYPE: 'Type',
            REPORTER: 'Reporter',
            STATUS: 'Status',
            DATE: 'Date',
            ACTIONS: 'Actions',
            LOADING: 'Loading incidents...',
        }
    },
    LEADS: {
        TITLE: 'Lead Inquiries',
        SUBTITLE: 'Track and manage potential client inquiries.',
        ADD_BTN: 'New Lead',
        SEARCH_PLACEHOLDER: 'Search leads...',
        ACTIONS: {
            EXPORT: 'Export CSV',
            REFRESH: 'Refresh',
            REFRESHING: 'Refreshing...',
            MARK_CONTACTED: 'Mark Contacted',
            CONVERT: 'Convert',
            CLOSE: 'Close',
        },
        FORM: {
            TITLE: 'New Lead Entry',
            SUBTITLE: 'Record an offline inquiry.',
            SOURCE_LABEL: 'Inquiry Source',
            NAME_LABEL: 'Lead Name',
            SUBMIT_BTN: 'Create Lead',
            SAVING: 'Saving...',
            SUCCESS_MSG: 'Lead created successfully',
            ERROR_MSG: 'Error creating lead',
            DISCARD_TITLE: 'Discard Lead?',
        },
        TABLE: {
            NAME: 'Name',
            CONTACT: 'Contact',
            INTEREST: 'Interest',
            STATUS: 'Status',
            DATE: 'Date',
            ACTIONS: 'Actions',
            NO_LEADS: 'No leads found matching your search.',
        },
        STATUS: {
            NEW: 'New',
            CONTACTED: 'Contacted',
            CONSULTATION: 'Consultation',
            CONVERTED: 'Converted',
            LOST: 'Lost',
        },
        MESSAGES: {
            LOADING: 'Loading leads repository...',
            EMPTY: 'No leads found.',
            ERROR: 'Failed to fetch leads',
            ERROR_UPDATE: 'Failed to update status',
        }
    },
    SCHEDULE: {
        TITLE: 'Visit Schedule',
        SUBTITLE: 'Coordinate care visits and assign PSWs to client requests.',
        ACTIONS: {
            CREATE: '+ Create Visit Request',
            ASSIGN: 'Assign Caregiver',
            CONFIRM_ASSIGN: 'Confirm Assignment',
            CANCEL_VISIT: 'Cancel Visit',
            CLOSE: 'Close',
            EDIT: 'Edit Details',
        },
        MODAL: {
            SELECT_PSW: 'Select Verified PSW',
            CHOOSE_WORKER: '-- Choose a worker --',
            CONFIRM_DELETE: 'Are you sure you want to cancel this visit?',
        },
        MESSAGES: {
            SUCCESS_ASSIGN: 'PSW assigned successfully!',
            SUCCESS_CANCEL: 'Visit cancelled',
            ERROR_ASSIGN: 'Assignment failed',
            ERROR_DELETE: 'Failed to delete visit',
            ERROR_UPDATE: 'Status update failed',
        }
    },
    SETTINGS: {
        TITLE: 'System Settings',
        SUBTITLE: 'Configure global parameters and administrative preferences.',
        NOTIFICATIONS: {
            TITLE: 'General Notifications',
            EMAIL_ALERTS: 'Email Alerts for New Leads',
            EMAIL_DESC: 'Notify administrators when a new inquiry is submitted.',
        },
        SCHEDULING: {
            TITLE: 'Booking & Scheduling',
            AUTO_ASSIGN: 'Automatic PSW Assignment',
            AUTO_DESC: 'Experimental: Match best worker automatically for nursing visits.',
            GRACE_PERIOD: 'Late Check-in Grace Period',
            GRACE_DESC: 'Minutes allowed after scheduled start before alert is triggered.',
        },
        ACTIONS: {
            RESET: 'Reset to Defaults',
            SAVE: 'Save Settings',
            SUCCESS_SAVE: 'Settings saved successfully!',
        }
    },
    ROLES: {
        ADMIN: 'Administrator',
        STAFF: 'Staff Member',
        PSW: 'Personal Support Worker',
        RN: 'Registered Nurse',
        CLIENT: 'Client',
        COORDINATOR: 'Scheduling Coordinator',
        FINANCE: 'Finance Manager',
        HR: 'HR Manager',
        COMPLIANCE: 'Compliance Officer',
        CRM: 'Client Relationship Manager',
        TRAINING: 'Training Manager',
    },
    MENU: {
        DASHBOARD: 'Dashboard',
        USERS: 'Users & PSWs',
        SCHEDULE: 'Schedule',
        INCIDENTS: 'Incidents',
        TIMESHEETS: 'Timesheets',
        LEADS: 'Lead Inquiries',
        SERVICES: 'Services',
        AUDITS: 'Call Audits',
        CONTENT: 'Content',
        REPORTS: 'Reports',
        SETTINGS: 'Settings',
        SUPPORT: 'Support',
        CLIENT_HUB: 'My Care Hub',
        CLIENT_BOOKINGS: 'My Bookings',
        CLIENT_BILLING: 'Billing',
        PROFILE: 'Account Profile',
        STAFF_HUB: 'Staff Hub',
        CUSTOMERS: 'Customer Mgmt',
        TICKETS: 'Tickets',
        WORK_SCHEDULE: 'Work Schedule',
        OPEN_SHIFTS: 'Open Shifts',
        MY_SHIFTS: 'My Shifts',
        MY_EARNINGS: 'My Earnings',
        MY_CREDENTIALS: 'My Credentials',
        HELP_DESK: 'Help Desk',
        CLINICAL_DASHBOARD: 'Clinical Dashboard',
        CLINIENT_ADMISSION: 'Clients admission',
        DAILY_ENTRY: 'Daily Entry',
        EVALUATIONS: 'Evaluations',
        SERVICE_REVIEW: 'Service Review',
        ONBOARDING: 'Onboarding',
        TRAINING: 'Training',
        COMPLIANCE: 'Compliance',
        INQUIRIES: 'Inquiries',
        SATISFACTION: 'Satisfaction',
        MODULES: 'Modules',
        SKILLS: 'Staff Skills',
        CARE_PLANS: 'Care Plans',
    },
    MANAGER_DASHBOARD: {
        TITLE: 'Manager Dashboard',
        SUBTITLE: 'Operational overview and rapid metrics',
        QUICK_ACTIONS: 'Quick Actions',
        ANALYTICS: 'Performance Analytics',
        KPI: {
            TODAY_SHIFTS: "Today's Shifts",
            ACTIVE_CLIENTS: 'Active Clients',
            STAFF_ON_DUTY: 'Staff On Duty',
            OPEN_INCIDENTS: 'Open Incidents',
        },
        ACTIONS: {
            DAILY_CARE: 'Daily Care Entry',
            STAFF_EVAL: 'Staff Evaluations',
            SERVICE_REVIEW: 'Service Reviews',
            LOG_INCIDENT: 'Log Incident',
            VIEW_CLIENTS: 'View Clients',
        },
        PERSPECTIVES: ['Operations', 'Clinical', 'Marketing', 'Recruiting', 'Finance'],
        MESSAGES: {
            LOADING: 'Loading Dashboard...',
        }
    },
    LAYOUT: {
        LOGOUT: 'Sign Out',
        PROFILE_TITLE: 'Account Profile',
        PERSPECTIVE: 'Perspective',
        IMPERSONATING: 'Impersonating profile',
        SWITCH_PERSPECTIVE: 'Choose Perspective',
        SEARCH_USERS: 'Search system users...',
        ONLINE_STATUS: 'STATUS: ONLINE',
        FULLSCREEN_ENTER: 'Enter Fullscreen',
        FULLSCREEN_EXIT: 'Exit Fullscreen',
        MOBILE_MENU: 'Toggle Menu',
        SEARCH_LABEL: 'Search Registry',
        LOGGED_IN_AS: 'Active Session: ',
    },
    ROLE_HELP: {
        TITLE: '💡 Umbrella Role System',
        ADMIN: {
            TITLE: 'Core Administration',
            LABEL: 'Administrator',
            INFO: 'Full system access. Manage global settings, billing architecture, and system roles.'
        },
        STAFF: {
            TITLE: 'Operations Umbrella',
            LABEL: 'Staff / HR / Finance',
            INFO: 'Manage day-to-day coordination: scheduling visits, payroll processing, and compliance monitoring.'
        },
        MANAGER: {
            TITLE: 'Management Umbrella',
            LABEL: 'Functional Managers',
            INFO: 'Strategic oversight: access to operational analytics, service audits, and department-level reporting.'
        },
        PROVIDER: {
            TITLE: 'Healthcare Workers',
            LABEL: 'Service Providers (PSW / RN)',
            INFO: 'Field operations: Direct care delivery, shift scheduling, and clinical documentation.'
        },
        CLIENT: {
            TITLE: 'Clients & Guardians',
            LABEL: 'Client / Family Profile',
            INFO: 'Service recipients: Manage family care requests, view assigned visits, and handle private billing.'
        },
        TIP_LABEL: 'Tip:',
        TIP_CONTENT: 'Users can possess multiple roles across umbrellas to aggregate permissions and access.'
    },
    MODALS: {
        CREATE_VISIT: {
            TITLE_CREATE: 'Create New Shift Request',
            TITLE_EDIT: 'Edit Shift Request',
            SUBMIT_CREATE: 'Create Shift',
            SUBMIT_SAVE: 'Save Changes',
            CANCEL: 'Cancel',
            PROCESSING: 'Processing...',
            SUCCESS_CREATE: 'Shift created successfully!',
            SUCCESS_UPDATE: 'Shift updated successfully!',
            ERROR_CREATE: 'Failed to create shift',
            ERROR_UPDATE: 'Failed to update shift',
        },
        CONFIRM_DELETE: {
            TITLE: 'Confirm Deletion',
            DESC: 'Are you sure you want to delete this item? This action cannot be undone.',
            CONFIRM: 'Delete',
            CANCEL: 'Cancel',
        }
    },
    EARNINGS: {
        TITLE: 'Earnings Center',
        SUBTITLE: 'Enterprise-grade financial oversight and payout management',
        STATS: {
            REVENUE: 'Total Revenue',
            PAYROLL: 'Total Payroll',
            PROFIT: 'Net Profit',
            PENDING: 'Payouts Pending',
        },
        TABS: {
            OVERVIEW: 'Overview',
            INVOICES: 'Invoices',
            PAYOUTS: 'Payouts',
            REPORTS: 'Reports',
        },
        ACTIONS: {
            EXPORT: 'Export Report',
            DATE_RANGE: 'Date Range',
            FILTER_ACTIVE: 'Filter Active',
        }
    },
    COMMON: {
        LOAD_MORE: 'Load More',
        RETRY: 'Retry',
        SEARCH_PLACEHOLDER: 'Search...',
        NO_RESULTS: 'No results found.',
        SAVE: 'Save',
        CLOSE: 'Close',
        BACK: 'Back',
        EDIT: 'Edit',
        DELETE: 'Delete',
        NETWORK_ERROR: 'Network error',
        PROCESSING: 'Processing...',
    }
} as const;
