name: governance_api
publish_to: 'none'
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.3

dependencies:
  postgres: ^3.5.9
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  analyzer: any
  path: any
  database_client:
    path: ../../packages/database_client
dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6
