export const RouteRegistry = {
    HOME: '/',
    SERVICES: '/services',
    SERVICE_FOOT_CARE: '/services/foot-care',
    SERVICE_EDUCATION: '/services/education',
    SERVICE_IT: '/services/it-support',
    SERVICE_SENIOR: '/services/senior-care',
    SERVICE_FACILITY_FOOT_CARE: '/services/facility-foot-care',
    SERVICE_STAFFING: '/services/staffing',
    SERVICE_CERTIFICATE: '/services/foot-care-certificate',
    SERVICE_PSW_TRAINING: '/services/psw-training',
    BLOG: '/blog',
    BLOG_DETAIL: '/blog/:id',
    CONTACT: '/contact',
    TERMS: '/terms',
    PRIVACY: '/privacy',
    CAREERS: '/careers',
    ABOUT: '/about',
    BOOKING: '/book-now',
    VOLUNTEER: '/volunteer',
    FRANCHISE: '/franchise',
    TESTIMONIALS: '/testimonials',
    LOGIN: '/login',
    LOGIN_STAFF: '/staff-login',
} as const;
