import os
import sys
import sqlite3
import json

# Add current folder to path to import governance_db
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
import governance_db

def generate():
    conn = governance_db.get_connection()
    cursor = conn.cursor()

    cursor.execute("""
    SELECT page_id, route, name, label, route_var, icon_var, section, role_allowed 
    FROM pages 
    WHERE label IS NOT NULL 
      AND (route_var IS NOT NULL OR route IS NOT NULL) 
      AND icon_var IS NOT NULL 
      AND role_allowed IS NOT NULL;
    """)
    rows = cursor.fetchall()

    role_menus = {}
    global_items = []

    for row in rows:
        label = row['label']
        route_var = row['route_var'] if row['route_var'] else f"'{row['route']}'"
        icon_var = row['icon_var']
        section = row['section'] if row['section'] else 'Main'
        page_id = row['page_id']
        roles = json.loads(row['role_allowed'])

        item = {
            'id': page_id,
            'label': label,
            'route_var': route_var,
            'icon_var': icon_var,
            'section': section,
        }

        if '*' in roles or 'all' in roles:
            global_items.append(item)
        else:
            for role in roles:
                if role not in role_menus:
                    role_menus[role] = []
                role_menus[role].append(item)

    # Inject global items into all roles
    for role in role_menus:
        role_menus[role].extend(global_items)

    rep = []
    rep.append('// Layer: 01_INFRASTRUCTURE')
    rep.append('// GENERATED CODE - DO NOT MODIFY BY HAND')
    rep.append('// This file is generated by .agents/governance/manifest_generator.py from SQLite DB')
    rep.append('// Source: .agents/governance/governance.db (pages table)')
    rep.append('')
    rep.append("import 'package:lucide_icons/lucide_icons.dart';")
    rep.append("import '../models/navigation_item.dart';")
    rep.append("import '../routes/groups/corporate_routes.dart';")
    rep.append("import '../routes/groups/franchise_routes.dart';")
    rep.append("import '../routes/groups/clinical_routes.dart';")
    rep.append("import '../routes/groups/client_routes.dart';")
    rep.append("import '../routes/groups/common_routes.dart';")
    rep.append('')
    rep.append('class NavigationRegistry {')
    rep.append('  static final Map<String, List<PrimeCareNavigationItem>> _roleMenus = {')

    for role, items in role_menus.items():
        rep.append(f"    '{role}': [")
        for item in items:
            section_key = item['section'].lower().replace(' ', '_')
            rep.append('      const PrimeCareNavigationItem(')
            rep.append(f"        label: 'navigation.items.{item['id']}',")
            rep.append(f"        icon: {item['icon_var']},")
            rep.append(f"        route: {item['route_var']},")
            rep.append(f"        section: 'navigation.sections.{section_key}',")
            rep.append('      ),')
        rep.append('    ],')

    rep.append('  };')
    rep.append('')
    rep.append("""
  static List<PrimeCareNavigationItem> getMenuForRole(String role) {
    // 1. Super Admin / Admin master directory fallback
    final checkRole = role.toLowerCase();
    if (checkRole == 'super admin' ||
        checkRole == 'admin' ||
        checkRole == 'it admin') {
      final Map<String, PrimeCareNavigationItem> allItems = {};
      _roleMenus.forEach((roleName, menuList) {
        for (final item in menuList) {
          if (!allItems.containsKey(item.route)) {
            allItems[item.route] = PrimeCareNavigationItem(
              label: item.label,
              icon: item.icon,
              route: item.route,
              section: item.section ?? 'Master Directory',
              activeIcon: item.activeIcon,
            );
          }
        }
      });
      return allItems.values.toList();
    }

    // 2. Try exact match first
    if (_roleMenus.containsKey(role)) {
      return _roleMenus[role]!;
    }

    // 3. Try case-insensitive exact match
    final upperRole = role.toUpperCase();
    for (var key in _roleMenus.keys) {
      if (key.toUpperCase() == upperRole) {
        return _roleMenus[key]!;
      }
    }

    // 4. Fallback to Title Case normalization
    final normalizedRole = role
        .split(' ')
        .map(
          (word) => word.isEmpty
              ? ''
              : '${word[0].toUpperCase()}${word.substring(1).toLowerCase()}',
        )
        .join(' ');

    return _roleMenus[normalizedRole] ?? _roleMenus['Admin'] ?? [];
  }
}""")

    out_file = 'packages/flutter_core/lib/config/navigation_registry.dart'
    os.makedirs(os.path.dirname(out_file), exist_ok=True)
    with open(out_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(rep))

    conn.close()
    print(f"[OK] Successfully generated navigation_registry.dart with {len(role_menus)} roles!")

if __name__ == "__main__":
    generate()
