export const MKT_LAYOUT = {
    header: {
        logo: "logo-link",
        linkFamily: "link-family-portal",
        linkStaff: "link-staff-hub",
        navHealthtech: "nav-healthtech",
        btnBook: "btn-book-assessment",
        btnMobile: "btn-mobile-menu",
        navInsights: "mobile-nav-insights",
        btnFullscreen: "btn-fullscreen",
        themeSelector: "theme-selector",
    },
    footer: {
        email: "lnk-footer-email",
        phone: "lnk-footer-phone",
        caregiverLogin: "footer-caregiver-login",
        familyLogin: "footer-family-login",
        staffLogin: "footer-staff-login",
        about: "lnk-footer-about",
        careers: "lnk-footer-careers",
        socialFb: "lnk-footer-fb",
        socialTw: "lnk-footer-tw",
        socialLi: "lnk-footer-li",
        socialIg: "lnk-footer-ig",
        socialYt: "lnk-footer-yt",
        privacy: "lnk-footer-privacy",
        terms: "lnk-footer-terms",
    },
    chat: {
        toggle: "btn-chat-widget-toggle",
        back: "btn-chat-back",
        close: "btn-chat-close",
        inpName: "chat-contact-name",
        inpPhone: "chat-contact-phone",
        inpEmail: "chat-contact-email",
        btnSubmit: "btn-chat-contact-submit",
        btnTextChat: "btn-chat-text",
        btnVoiceCall: "btn-chat-voice",
        lnkCall: "lnk-chat-call-direct",
        lnkWhatsapp: "lnk-chat-whatsapp",
        lnkEmail: "lnk-chat-email-direct",
        inpText: "chat-input-text",
        btnSend: "btn-chat-send",
        btnVoiceStart: "btn-chat-call-start",
        btnVoiceEnd: "btn-chat-call-end",
    }
};
