import 'package:flutter/material.dart';
import 'package:primecare_ui/primecare_ui.dart';
import 'package:primecare_ui/src/components/sdui_form_builder.dart';

class PswDataEntryPage extends StatelessWidget {
  const PswDataEntryPage({super.key});

  @override
  Widget build(BuildContext context) {
    final forms = <String>[
      'User',
      'Tenant',
      'Registry',
      'ApiKey',
      'AuditLog',
      'SystemEvent',
      'Lead',
      'FAQ',
      'UserDevice',
      'SystemPolicy',
      'ResponseBotAudit',
      'SystemTouchpoint',
      'RegistryEntry',
      'MessageThread',
      'Message',
      'PlatformRole',
      'RoleScreenAccess',
      'CrisisProtocol',
      'ProtocolResolution',
      'EcosystemStateOverride',
      'UserReputation',
      'EcosystemAutopilotConfig',
      'HospitalTarget',
      'ReferralPipeline',
      'SupplyForecastMetrics',
      'ClientProfile',
      'PswProfile',
      'Visit',
      'Service',
      'VisitCheckEvent',
      'VisitNote',
      'VisitChecklist',
      'Incident',
      'DailyEntry',
      'Booking',
      'PswAvailability',
      'PswDocument',
      'ShiftAssignment',
      'Timesheet',
      'TimesheetItem',
      'ShiftHandover',
      'AvailabilityOverride',
      'VisitMatch',
      'WaitlistEntry',
      'StaffTask',
      'StaffGroup',
      'StaffGroupMember',
      'BookingRequest',
      'FleetStatus',
      'CarePlan',
      'ClinicalRecord',
      'ClinicalAssessment',
      'MedicationRecon',
      'SupervisionLog',
      'HealthID',
      'FhirSyncLog',
      'VitalSign',
      'PatientAlert',
      'Medication',
      'Prescription',
      'MAR_Entry',
      'EVVRecord',
      'ServiceAuthorization',
      'ConsentForm',
      'DailyAuditSignOff',
      'WellnessPulse',
      'Invoice',
      'Payment',
      'InsuranceProvider',
      'Claim',
      'BillingCode',
      'Payout',
      'MileageLog',
      'ChartOfAccount',
      'FinancialTransaction',
      'JournalEntry',
      'FinancialReconciliation',
      'BankTransaction',
      'TransactionLedger',
      'BlogPost',
      'Feedback',
      'TrainingModule',
      'TrainingAssignment',
      'Survey',
      'SurveyResponse',
      'Region',
      'BranchCapacity',
      'BranchStat',
      'ComplianceRecord',
      'Franchise',
      'ResellerAgreement',
      'Supplier',
      'InventoryItem',
      'PurchaseOrder',
      'TelehealthSession',
      'MarketplaceListing',
      'TenantSLA',
      'AIRecommendation',
      'SentimentAnalysis',
      'SecurityThreat',
      'TechnicalAudit',
      'FamilyNotification',
      'CareFeedback',
      'Referral',
      'FamilyMember',
      'PerformanceReview',
      'WebhookEndpoint',
      'WebhookDelivery',
      'IoTEvent',
      'AppNotification',
      'GamificationProfile',
      'AIInference',
      'CommunicationLog',
      'DailyActivity',
      'PlatformScreen',
      'ScreenFunctionality',
      'PswShiftLog',
      'AdlCareLog',
      'PswVitalSign',
      'BehaviorNote',
      'NutritionRecord',
      'MobilityLog',
      'InfectionControlChecklist',
      'NarrativeProgressNote',
      'CarePlanFollowUp',
      'Clinic',
      'Patient',
      'FinancialRecord',
      'FamilyAppointment',
      'FamilyCarePlanTask',
      'FamilyClinicalMessage',
      'PatientIntake',
      'IntakeReferralMetric',
      'JobOpening',
      'JobCandidate',
      'InterviewEvent',
      'InvoiceRecord',
      'InsuranceClaim',
      'FinancialGoal',
      'FacilityNode',
      'StaffUtilization',
      'OpsIssueTicket',
      'IncidentReportNode',
      'AuditLogNode',
      'PatientSatisfactionNode',
      'SalesDealNode',
      'KeyAccountNode',
      'RepPerformanceNode',
      'MarketingCampaignNode',
      'LocalGrowthNode',
      'ContentAssetNode',
      'PatientAdmissionNode',
      'ClinicalShiftNode',
      'MedicalAuditNode',
      'SupportTicketNode',
      'PatientFeedbackNode',
      'SystemTelemetryNode',
      'CurriculumNode',
      'InstructorNode',
      'CertificationNode',
      'FranchiseRevenueNode',
      'ClinicPerformanceNode',
      'FranchiseBookingNode',
      'OutreachEventNode',
      'ParticipantMetricNode',
      'OutreachBudgetNode',
      'LocalNetworkNode',
      'LocalFinanceNode',
      'LocalActivityNode',
      'LocalMarketingAnalyticNode',
      'LocalCampaignNode',
      'LocalContentNode',
      'SupportAgentNode',
      'TicketVolumeNode',
      'ResolutionFeedbackNode',
      'ClientTrendNode',
      'ClientClinicNode',
      'ClientDemographicNode',
      'HealthNetRevenueNode',
      'HealthNetEfficiencyNode',
      'HealthNetNetworkNode',
      'SchedulerTrendNode',
      'SchedulerRosterNode',
      'SchedulerFacilityNode',
    ];

    return Scaffold(
      appBar: AppBar(
        title: const Text('PSW Database Entry Hub'),
        backgroundColor: Colors.blueAccent,
      ),
      body: ListView.separated(
        padding: const EdgeInsets.all(16),
        itemCount: forms.length,
        separatorBuilder: (_, __) => const SizedBox(height: 8),
        itemBuilder: (context, index) {
          final formId = forms[index];
          return ElevatedButton(
            style: ElevatedButton.styleFrom(
              padding: const EdgeInsets.symmetric(vertical: 20),
            ),
            onPressed: () {
              Navigator.of(context).push(
                MaterialPageRoute(
                  builder: (_) => Scaffold(
                    appBar: AppBar(title: Text('Edit $formId Data')),
                    body: PrimeCareDynamicFormBuilder(formId: formId),
                  ),
                ),
              );
            },
            child: Text('Data Entry: $formId'),
          );
        },
      ),
    );
  }
}
