name: provider_api
description: PrimeCare provider-api - Migrated to Full-Stack Dart.
version: 1.0.0
publish_to: 'none'
environment:
  sdk: '^3.11.3'
dependencies:
  server_core:
    path: ../../packages/server_core
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  database_client:
    path: ../../packages/database_client
dev_dependencies:
  lints: ^3.0.0
  test: any
