// Generated file. Do not edit directly. Edit theme_config.json in root.
import 'package:flutter/material.dart';

class AppThemePalette {
  final Brightness brightness;
  final Color primary;
  final Color primaryContainer;
  final Color primaryDark;
  final Color onPrimary;
  final Color secondary;
  final Color secondaryContainer;
  final Color secondaryDark;
  final Color onSecondary;
  final Color background;
  final Color surface;
  final Color textPrimary;
  final Color textSecondary;
  final Color textDisabled;
  final Color divider;
  final Color sidebarBackground;
  final Color topbarBackground;
  final String defaultLanguage;
  final List<String> supportedLanguages;

  const AppThemePalette({
    required this.brightness,
    required this.primary,
    required this.primaryContainer,
    required this.primaryDark,
    required this.onPrimary,
    required this.secondary,
    required this.secondaryContainer,
    required this.secondaryDark,
    required this.onSecondary,
    required this.background,
    required this.surface,
    required this.textPrimary,
    required this.textSecondary,
    required this.textDisabled,
    required this.divider,
    required this.sidebarBackground,
    required this.topbarBackground,
    required this.defaultLanguage,
    required this.supportedLanguages,
  });
}

class ThemeConfig {
  static const Map<String, AppThemePalette> _data = {
    'clinic': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF0D47A1),
      primaryContainer: Color(0xFF5472D3),
      primaryDark: Color(0xFF002171),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFB0BEC5),
      secondaryContainer: Color(0xFFE2F1F8),
      secondaryDark: Color(0xFF808E95),
      onSecondary: Color(0xFF111827),
      background: Color(0xFFF1F5F9),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF111827),
      textSecondary: Color(0xFF6B7280),
      textDisabled: Color(0xFF959CA9),
      divider: Color(0xFFD8D9DA),
      sidebarBackground: Color(0xFF0D47A1),
      topbarBackground: Color(0xFF0D47A1),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'corporate': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF1E3A8A),
      primaryContainer: Color(0xFFDBEAFE),
      primaryDark: Color(0xFF08254A),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF00B4A6),
      secondaryContainer: Color(0xFF33C7BB),
      secondaryDark: Color(0xFF00867B),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF6F8FA),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF0F3C6E),
      textSecondary: Color(0xFF4B5563),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFFE5E7EB),
      sidebarBackground: Color(0xFF1E3A8A),
      topbarBackground: Color(0xFF1E3A8A),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'auth': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF0F172A),
      primaryContainer: Color(0xFF1E293B),
      primaryDark: Color(0xFF0F1115),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1565C0),
      secondaryContainer: Color(0xFF3C83D6),
      secondaryDark: Color(0xFF0E4B90),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF6F7F8),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF1F232B),
      textSecondary: Color(0xFF4B5563),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFFE5E7EB),
      sidebarBackground: Color(0xFF0F172A),
      topbarBackground: Color(0xFF0F172A),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'governance': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF004AC6),
      primaryContainer: Color(0xFF363B44),
      primaryDark: Color(0xFF0F1115),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1565C0),
      secondaryContainer: Color(0xFF3C83D6),
      secondaryDark: Color(0xFF0E4B90),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF6F7F8),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF1F232B),
      textSecondary: Color(0xFF4B5563),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFFE5E7EB),
      sidebarBackground: Color(0xFF0F172A),
      topbarBackground: Color(0xFF0F172A),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'franchise': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF0D1B2A),
      primaryContainer: Color(0xFF363B44),
      primaryDark: Color(0xFF0F1115),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1565C0),
      secondaryContainer: Color(0xFF3C83D6),
      secondaryDark: Color(0xFF0E4B90),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF6F7F8),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF1F232B),
      textSecondary: Color(0xFF4B5563),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFFE5E7EB),
      sidebarBackground: Color(0xFF0F172A),
      topbarBackground: Color(0xFF0F172A),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'client': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF0EA5E9),
      primaryContainer: Color(0xFFE0F2FE),
      primaryDark: Color(0xFF0F1115),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1565C0),
      secondaryContainer: Color(0xFF3C83D6),
      secondaryDark: Color(0xFF0E4B90),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF6F7F8),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF1F232B),
      textSecondary: Color(0xFF4B5563),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFFE5E7EB),
      sidebarBackground: Color(0xFF0F172A),
      topbarBackground: Color(0xFF0F172A),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'business_development': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF2563EB),
      primaryContainer: Color(0xFF363B44),
      primaryDark: Color(0xFF0F1115),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1565C0),
      secondaryContainer: Color(0xFF3C83D6),
      secondaryDark: Color(0xFF0E4B90),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF6F7F8),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF1F232B),
      textSecondary: Color(0xFF4B5563),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFFE5E7EB),
      sidebarBackground: Color(0xFF0F172A),
      topbarBackground: Color(0xFF0F172A),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'marketing': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF2563EB),
      primaryContainer: Color(0xFF363B44),
      primaryDark: Color(0xFF0F1115),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1565C0),
      secondaryContainer: Color(0xFF3C83D6),
      secondaryDark: Color(0xFF0E4B90),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF6F7F8),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF1F232B),
      textSecondary: Color(0xFF4B5563),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFFE5E7EB),
      sidebarBackground: Color(0xFF0F172A),
      topbarBackground: Color(0xFF0F172A),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'support': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFFEA580C),
      primaryContainer: Color(0xFFFFFFEDD5),
      primaryDark: Color(0xFF0F1115),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1565C0),
      secondaryContainer: Color(0xFF3C83D6),
      secondaryDark: Color(0xFF0E4B90),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF6F7F8),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF1F232B),
      textSecondary: Color(0xFF4B5563),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFFE5E7EB),
      sidebarBackground: Color(0xFF0F172A),
      topbarBackground: Color(0xFF0F172A),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'enterprise_blueprint': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF2563EB),
      primaryContainer: Color(0xFF363B44),
      primaryDark: Color(0xFF0F1115),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1565C0),
      secondaryContainer: Color(0xFF3C83D6),
      secondaryDark: Color(0xFF0E4B90),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF6F7F8),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF1F232B),
      textSecondary: Color(0xFF4B5563),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFFE5E7EB),
      sidebarBackground: Color(0xFF0F172A),
      topbarBackground: Color(0xFF0F172A),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'default': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF1F232B),
      primaryContainer: Color(0xFF363B44),
      primaryDark: Color(0xFF0F1115),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1565C0),
      secondaryContainer: Color(0xFF3C83D6),
      secondaryDark: Color(0xFF0E4B90),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF6F7F8),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF1F232B),
      textSecondary: Color(0xFF4B5563),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFFE5E7EB),
      sidebarBackground: Color(0xFF1F232B),
      topbarBackground: Color(0xFF1F232B),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'defaultDark': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF2B2F38),
      primaryContainer: Color(0xFF414652),
      primaryDark: Color(0xFF16191E),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF3C83D6),
      secondaryContainer: Color(0xFF5A9AF0),
      secondaryDark: Color(0xFF1D5EB0),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFF0F1115),
      surface: Color(0xFF1A1D22),
      textPrimary: Color(0xFFE5E7EB),
      textSecondary: Color(0xFFA5ABB5),
      textDisabled: Color(0xFF6B7280),
      divider: Color(0xFF2D3139),
      sidebarBackground: Color(0xFF2B2F38),
      topbarBackground: Color(0xFF2B2F38),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'defaultNavbar': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF1F232B),
      primaryContainer: Color(0xFF363B44),
      primaryDark: Color(0xFF0F1115),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1565C0),
      secondaryContainer: Color(0xFF3C83D6),
      secondaryDark: Color(0xFF0E4B90),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFE5E7EB),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF1F232B),
      textSecondary: Color(0xFF4B5563),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFFE5E7EB),
      sidebarBackground: Color(0xFF1F232B),
      topbarBackground: Color(0xFF1F232B),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'legacyDefault': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF0A74DA),
      primaryContainer: Color(0xFF536D89),
      primaryDark: Color(0xFF00418A),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF00A4EF),
      secondaryContainer: Color(0xFF6BC9F7),
      secondaryDark: Color(0xFF0078D7),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFE8E8E8),
      surface: Color(0xFFF4F4F4),
      textPrimary: Color(0xFF212121),
      textSecondary: Color(0xFF5F6368),
      textDisabled: Color(0xFF969696),
      divider: Color(0x1F000000),
      sidebarBackground: Color(0xFF0A74DA),
      topbarBackground: Color(0xFF0A74DA),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'legacyDark': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF0A74DA),
      primaryContainer: Color(0xFF536D89),
      primaryDark: Color(0xFF00418A),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF00A4EF),
      secondaryContainer: Color(0xFF6BC9F7),
      secondaryDark: Color(0xFF0078D7),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFF121212),
      surface: Color(0xFF1E1E1E),
      textPrimary: Color(0xFFE0E0E0),
      textSecondary: Color(0xFFB0BEC5),
      textDisabled: Color(0xFF969696),
      divider: Color(0x1FFFFFFF),
      sidebarBackground: Color(0xFF0A74DA),
      topbarBackground: Color(0xFF0A74DA),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'navyTealPalette': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF0F3C6E),
      primaryContainer: Color(0xFF365E92),
      primaryDark: Color(0xFF08254A),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF00B4A6),
      secondaryContainer: Color(0xFF33C7BB),
      secondaryDark: Color(0xFF00867B),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF6F8FA),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF0F3C6E),
      textSecondary: Color(0xFF4B5563),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFFE5E7EB),
      sidebarBackground: Color(0xFF0F3C6E),
      topbarBackground: Color(0xFF0F3C6E),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'indigoAmberPalette': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF21255F),
      primaryContainer: Color(0xFF40448A),
      primaryDark: Color(0xFF15183C),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFFFB547),
      secondaryContainer: Color(0xFFFFC66D),
      secondaryDark: Color(0xFFD89330),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF7F8FC),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF21255F),
      textSecondary: Color(0xFF4B5563),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFFE5E7EB),
      sidebarBackground: Color(0xFF21255F),
      topbarBackground: Color(0xFF21255F),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'darkBlueSilver': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF0D47A1),
      primaryContainer: Color(0xFF5472D3),
      primaryDark: Color(0xFF002171),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFB0BEC5),
      secondaryContainer: Color(0xFFE2F1F8),
      secondaryDark: Color(0xFF808E95),
      onSecondary: Color(0xFF111827),
      background: Color(0xFFF1F5F9),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF111827),
      textSecondary: Color(0xFF6B7280),
      textDisabled: Color(0xFF959CA9),
      divider: Color(0xFFD8D9DA),
      sidebarBackground: Color(0xFF0D47A1),
      topbarBackground: Color(0xFF0D47A1),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'darkBlueSilverDark': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF0D47A1),
      primaryContainer: Color(0xFF5472D3),
      primaryDark: Color(0xFF002171),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFB0BEC5),
      secondaryContainer: Color(0xFFE2F1F8),
      secondaryDark: Color(0xFF808E95),
      onSecondary: Color(0xFF111827),
      background: Color(0xFF263238),
      surface: Color(0xFF2D3940),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFF94A3B8),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFF42474D),
      sidebarBackground: Color(0xFF0D47A1),
      topbarBackground: Color(0xFF0D47A1),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'slateCrimson': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF37474F),
      primaryContainer: Color(0xFF62727B),
      primaryDark: Color(0xFF102027),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFD32F2F),
      secondaryContainer: Color(0xFFFF6659),
      secondaryDark: Color(0xFF9A0007),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFE6E6E6),
      surface: Color(0xFFF2F2F2),
      textPrimary: Color(0xFF111827),
      textSecondary: Color(0xFF6B7280),
      textDisabled: Color(0xFF959CA9),
      divider: Color(0xFFD9D9D9),
      sidebarBackground: Color(0xFF37474F),
      topbarBackground: Color(0xFF37474F),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'slateCrimsonDark': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF37474F),
      primaryContainer: Color(0xFF62727B),
      primaryDark: Color(0xFF102027),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFD32F2F),
      secondaryContainer: Color(0xFFFF6659),
      secondaryDark: Color(0xFF9A0007),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFF212121),
      surface: Color(0xFF2E2E2E),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFF94A3B8),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFF3A3D40),
      sidebarBackground: Color(0xFF37474F),
      topbarBackground: Color(0xFF37474F),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'emeraldGold': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF00695C),
      primaryContainer: Color(0xFF439889),
      primaryDark: Color(0xFF003D33),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFFFD740),
      secondaryContainer: Color(0xFFFFFF74),
      secondaryDark: Color(0xFFC8A600),
      onSecondary: Color(0xFF111827),
      background: Color(0xFFDCF2F2),
      surface: Color(0xFFF2FDFA),
      textPrimary: Color(0xFF111827),
      textSecondary: Color(0xFF6B7280),
      textDisabled: Color(0xFF959CA9),
      divider: Color(0xFFB3C4C3),
      sidebarBackground: Color(0xFF00695C),
      topbarBackground: Color(0xFF00695C),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'emeraldGoldDark': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF00695C),
      primaryContainer: Color(0xFF439889),
      primaryDark: Color(0xFF003D33),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFFFD740),
      secondaryContainer: Color(0xFFFFFF74),
      secondaryDark: Color(0xFFC8A600),
      onSecondary: Color(0xFF111827),
      background: Color(0xFF004D40),
      surface: Color(0xFF00544A),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFF94A3B8),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFF2D6360),
      sidebarBackground: Color(0xFF00695C),
      topbarBackground: Color(0xFF00695C),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'indigoCoral': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF283593),
      primaryContainer: Color(0xFF5F5FC4),
      primaryDark: Color(0xFF001064),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFFF7043),
      secondaryContainer: Color(0xFFFFA270),
      secondaryDark: Color(0xFFC63F17),
      onSecondary: Color(0xFF111827),
      background: Color(0xFFEAEBFB),
      surface: Color(0xFFF6F7FD),
      textPrimary: Color(0xFF111827),
      textSecondary: Color(0xFF6B7280),
      textDisabled: Color(0xFF959CA9),
      divider: Color(0xFFDCDCF2),
      sidebarBackground: Color(0xFF283593),
      topbarBackground: Color(0xFF283593),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'indigoCoralDark': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF283593),
      primaryContainer: Color(0xFF5F5FC4),
      primaryDark: Color(0xFF001064),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFFF7043),
      secondaryContainer: Color(0xFFFFA270),
      secondaryDark: Color(0xFFC63F17),
      onSecondary: Color(0xFF111827),
      background: Color(0xFF1A237E),
      surface: Color(0xFF283593),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFF94A3B8),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFF4D557E),
      sidebarBackground: Color(0xFF283593),
      topbarBackground: Color(0xFF283593),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'charcoalTeal': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF094A43),
      primaryContainer: Color(0xFF28635A),
      primaryDark: Color(0xFF004A41),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF009688),
      secondaryContainer: Color(0xFF52C7B8),
      secondaryDark: Color(0xFF00675B),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFEDF6FA),
      surface: Color(0xFFF7FCFC),
      textPrimary: Color(0xFF111827),
      textSecondary: Color(0xFF6B7280),
      textDisabled: Color(0xFF959CA9),
      divider: Color(0xFFCEE5F0),
      sidebarBackground: Color(0xFF094A43),
      topbarBackground: Color(0xFF094A43),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'charcoalTealDark': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF455A64),
      primaryContainer: Color(0xFF718792),
      primaryDark: Color(0xFF1C313A),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF009688),
      secondaryContainer: Color(0xFF52C7B8),
      secondaryDark: Color(0xFF00675B),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFF000000),
      surface: Color(0xFF102027),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFF94A3B8),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFF2D383D),
      sidebarBackground: Color(0xFF455A64),
      topbarBackground: Color(0xFF455A64),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'skyBlueOrange': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF64B5F6),
      primaryContainer: Color(0xFF9BE7FF),
      primaryDark: Color(0xFF2286C3),
      onPrimary: Color(0xFF111827),
      secondary: Color(0xFFFAA528),
      secondaryContainer: Color(0xFFF6AD3F),
      secondaryDark: Color(0xFFCB8721),
      onSecondary: Color(0xFF111827),
      background: Color(0xFFF5F5F5),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF111827),
      textSecondary: Color(0xFF6B7280),
      textDisabled: Color(0xFF959CA9),
      divider: Color(0xFFE9E6E0),
      sidebarBackground: Color(0xFF64B5F6),
      topbarBackground: Color(0xFF64B5F6),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'skyBlueOrangeDark': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF64B5F6),
      primaryContainer: Color(0xFF9BE7FF),
      primaryDark: Color(0xFF2286C3),
      onPrimary: Color(0xFF111827),
      secondary: Color(0xFFFAA528),
      secondaryContainer: Color(0xFFF6AD3F),
      secondaryDark: Color(0xFFCB8721),
      onSecondary: Color(0xFF111827),
      background: Color(0xFF1A1A1A),
      surface: Color(0xFF333333),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFF94A3B8),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFF544949),
      sidebarBackground: Color(0xFF64B5F6),
      topbarBackground: Color(0xFF64B5F6),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'softGreenMaroon': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF81C784),
      primaryContainer: Color(0xFFB2F2B6),
      primaryDark: Color(0xFF519657),
      onPrimary: Color(0xFF111827),
      secondary: Color(0xFFD81B60),
      secondaryContainer: Color(0xFFFF5C8D),
      secondaryDark: Color(0xFFA00037),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF5F5F5),
      surface: Color(0xFFFAFCFA),
      textPrimary: Color(0xFF111827),
      textSecondary: Color(0xFF6B7280),
      textDisabled: Color(0xFF959CA9),
      divider: Color(0xFFDADEDA),
      sidebarBackground: Color(0xFF81C784),
      topbarBackground: Color(0xFF81C784),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'softGreenMaroonDark': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF81C784),
      primaryContainer: Color(0xFFB2F2B6),
      primaryDark: Color(0xFF519657),
      onPrimary: Color(0xFF111827),
      secondary: Color(0xFFD81B60),
      secondaryContainer: Color(0xFFFF5C8D),
      secondaryDark: Color(0xFFA00037),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFF1A1A1A),
      surface: Color(0xFF323332),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFF94A3B8),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFF505250),
      sidebarBackground: Color(0xFF81C784),
      topbarBackground: Color(0xFF81C784),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'coolGreyPink': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFFDDE6EB),
      primaryContainer: Color(0xFFFFFFFF),
      primaryDark: Color(0xFF9EA7AA),
      onPrimary: Color(0xFF111827),
      secondary: Color(0xFFF06292),
      secondaryContainer: Color(0xFFFF94C2),
      secondaryDark: Color(0xFFBA2D65),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF5F5F5),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF111827),
      textSecondary: Color(0xFF6B7280),
      textDisabled: Color(0xFF959CA9),
      divider: Color(0xFFE1E1E1),
      sidebarBackground: Color(0xFFDDE6EB),
      topbarBackground: Color(0xFFDDE6EB),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'coolGreyPinkDark': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFFDDE6EB),
      primaryContainer: Color(0xFFFFFFFF),
      primaryDark: Color(0xFF9EA7AA),
      onPrimary: Color(0xFF111827),
      secondary: Color(0xFFF06292),
      secondaryContainer: Color(0xFFFF94C2),
      secondaryDark: Color(0xFFBA2D65),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFF1A1A1A),
      surface: Color(0xFF292929),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFF94A3B8),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFF424242),
      sidebarBackground: Color(0xFFDDE6EB),
      topbarBackground: Color(0xFFDDE6EB),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'legacy': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF252F3E),
      primaryContainer: Color(0xFF92979F),
      primaryDark: Color(0xFF161D28),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF22D3EE),
      secondaryContainer: Color(0xFFBDF2FA),
      secondaryDark: Color(0xFF0CB7E2),
      onSecondary: Color(0xFF111827),
      background: Color(0xFFF6F7F9),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF111827),
      textSecondary: Color(0xFF6B7280),
      textDisabled: Color(0xFF959CA9),
      divider: Color(0xFFE2E8F0),
      sidebarBackground: Color(0xFF252F3E),
      topbarBackground: Color(0xFF252F3E),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'light1': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF006565),
      primaryContainer: Color(0xFFB3D1D1),
      primaryDark: Color(0xFF003737),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFFFBE2C),
      secondaryContainer: Color(0xFFFFECC0),
      secondaryDark: Color(0xFFFF9910),
      onSecondary: Color(0xFF111827),
      background: Color(0xFFF0F7F7),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF111827),
      textSecondary: Color(0xFF6B7280),
      textDisabled: Color(0xFF959CA9),
      divider: Color(0xFFE2E8F0),
      sidebarBackground: Color(0xFF006565),
      topbarBackground: Color(0xFF006565),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'light2': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF1B9E85),
      primaryContainer: Color(0xFFBBE2DA),
      primaryDark: Color(0xFF087055),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFFF6231),
      secondaryContainer: Color(0xFFFFD0C1),
      secondaryDark: Color(0xFFFF3413),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF2F8F1),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF111827),
      textSecondary: Color(0xFF6B7280),
      textDisabled: Color(0xFF959CA9),
      divider: Color(0xFFE2E8F0),
      sidebarBackground: Color(0xFF1B9E85),
      topbarBackground: Color(0xFF1B9E85),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'light3': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF6B2C57),
      primaryContainer: Color(0xFFD3C0CD),
      primaryDark: Color(0xFF3C102C),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF36336A),
      secondaryContainer: Color(0xFFC3C2D2),
      secondaryDark: Color(0xFF16143C),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFFAFAFE),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF111827),
      textSecondary: Color(0xFF6B7280),
      textDisabled: Color(0xFF959CA9),
      divider: Color(0xFFE2E8F0),
      sidebarBackground: Color(0xFF6B2C57),
      topbarBackground: Color(0xFF6B2C57),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'light4': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF404B57),
      primaryContainer: Color(0xFFC6C9CD),
      primaryDark: Color(0xFF1C232C),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF354968),
      secondaryContainer: Color(0xFFC2C8D2),
      secondaryDark: Color(0xFF16213A),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF5F4F6),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF111827),
      textSecondary: Color(0xFF6B7280),
      textDisabled: Color(0xFF959CA9),
      divider: Color(0xFFE2E8F0),
      sidebarBackground: Color(0xFF404B57),
      topbarBackground: Color(0xFF404B57),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'light5': AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF3A3A3A),
      primaryContainer: Color(0xFFC4C4C4),
      primaryDark: Color(0xFF181818),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFCBCAC3),
      secondaryContainer: Color(0xFFEFEFED),
      secondaryDark: Color(0xFFACABA1),
      onSecondary: Color(0xFF111827),
      background: Color(0xFFFAF8F2),
      surface: Color(0xFFEFEEE7),
      textPrimary: Color(0xFF111827),
      textSecondary: Color(0xFF6B7280),
      textDisabled: Color(0xFF959CA9),
      divider: Color(0xFFE2E8F0),
      sidebarBackground: Color(0xFF3A3A3A),
      topbarBackground: Color(0xFF3A3A3A),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'dark1': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF323338),
      primaryContainer: Color(0xFFC2C2C3),
      primaryDark: Color(0xFF131417),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF129B7F),
      secondaryContainer: Color(0xFFB8E1D9),
      secondaryDark: Color(0xFF056D4F),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFF1E1D1E),
      surface: Color(0xFF262526),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFF94A3B8),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0x1FF1F5F9),
      sidebarBackground: Color(0xFF323338),
      topbarBackground: Color(0xFF323338),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'dark2': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF4B4F5A),
      primaryContainer: Color(0xFFC9CACE),
      primaryDark: Color(0xFF23262E),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFE6DED5),
      secondaryContainer: Color(0xFFF8F5F2),
      secondaryDark: Color(0xFFD5C8BA),
      onSecondary: Color(0xFF111827),
      background: Color(0xFF2A2D35),
      surface: Color(0xFF31343E),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFF94A3B8),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0x1FF1F5F9),
      sidebarBackground: Color(0xFF4B4F5A),
      topbarBackground: Color(0xFF4B4F5A),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'dark3': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF354968),
      primaryContainer: Color(0xFFC2C8D2),
      primaryDark: Color(0xFF16213A),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFD55847),
      secondaryContainer: Color(0xFFF4CFCA),
      secondaryDark: Color(0xFFC03325),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFF1B2A3F),
      surface: Color(0xFF23354E),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFF94A3B8),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0x1FF1F5F9),
      sidebarBackground: Color(0xFF354968),
      topbarBackground: Color(0xFF354968),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'dark4': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF5A4E93),
      primaryContainer: Color(0xFFCECADF),
      primaryDark: Color(0xFF2E2564),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF00BC77),
      secondaryContainer: Color(0xFFB3EBD6),
      secondaryDark: Color(0xFF009747),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFF180F3D),
      surface: Color(0xFF22184B),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFF94A3B8),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0x1FF1F5F9),
      sidebarBackground: Color(0xFF5A4E93),
      topbarBackground: Color(0xFF5A4E93),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'dark5': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF56789D),
      primaryContainer: Color(0xFFCCD7E2),
      primaryDark: Color(0xFF2B486F),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF796CC4),
      secondaryContainer: Color(0xFFD7D3ED),
      secondaryDark: Color(0xFF493DA2),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFF232931),
      surface: Color(0xFF465261),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFF94A3B8),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0x1FF1F5F9),
      sidebarBackground: Color(0xFF56789D),
      topbarBackground: Color(0xFF56789D),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'dark6': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF252949),
      primaryContainer: Color(0xFFBEBFC8),
      primaryDark: Color(0xFF0D0F21),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF5079FC),
      secondaryContainer: Color(0xFFCBD7FE),
      secondaryDark: Color(0xFF2749FA),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFF202441),
      surface: Color(0xFF2D3159),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFF94A3B8),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0x1FF1F5F9),
      sidebarBackground: Color(0xFF252949),
      topbarBackground: Color(0xFF252949),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'dark7': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF204657),
      primaryContainer: Color(0xFFBCC8CD),
      primaryDark: Color(0xFF0B202C),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF00BD3E),
      secondaryContainer: Color(0xFFB3EBC5),
      secondaryDark: Color(0xFF00981B),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFF15171E),
      surface: Color(0xFF1C1E27),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFF94A3B8),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0x1FF1F5F9),
      sidebarBackground: Color(0xFF204657),
      topbarBackground: Color(0xFF204657),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
    'greyDark': AppThemePalette(
      brightness: Brightness.dark,
      primary: Color(0xFF1B2330),
      primaryContainer: Color(0xFF92979F),
      primaryDark: Color(0xFF161D28),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF22D3EE),
      secondaryContainer: Color(0xFFBDF2FA),
      secondaryDark: Color(0xFF0CB7E2),
      onSecondary: Color(0xFF111827),
      background: Color(0xFF263238),
      surface: Color(0xFF455A64),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFF94A3B8),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0x1FF1F5F9),
      sidebarBackground: Color(0xFF1B2330),
      topbarBackground: Color(0xFF1B2330),
      defaultLanguage: 'en',
      supportedLanguages: const ['en','fr','es'],
    ),
  };

  static AppThemePalette getAppPalette(String app) {
    return _data[app] ?? const AppThemePalette(
      brightness: Brightness.light,
      primary: Color(0xFF0F766E),
      primaryContainer: Color(0xFFCCFBF1),
      primaryDark: Color(0xFF115E59),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF0D9488),
      secondaryContainer: Color(0xFF2DD4BF),
      secondaryDark: Color(0xFF0F766E),
      onSecondary: Color(0xFFFFFFFF),
      background: Color(0xFFF0FDFA),
      surface: Color(0xFFFFFFFF),
      textPrimary: Color(0xFF111827),
      textSecondary: Color(0xFF4B5563),
      textDisabled: Color(0xFF9CA3AF),
      divider: Color(0xFFE5E7EB),
      sidebarBackground: Color(0xFF0F766E),
      topbarBackground: Color(0xFF0F766E),
      defaultLanguage: 'en',
      supportedLanguages: ['en', 'fr', 'es'],
    );
  }

  static Color getColor(String app, String key, Color fallback) {
    final palette = getAppPalette(app);
    switch (key) {
      case 'primary': return palette.primary;
      case 'primaryContainer': return palette.primaryContainer;
      case 'primaryDark': return palette.primaryDark;
      case 'onPrimary': return palette.onPrimary;
      case 'secondary': return palette.secondary;
      case 'secondaryContainer': return palette.secondaryContainer;
      case 'secondaryDark': return palette.secondaryDark;
      case 'onSecondary': return palette.onSecondary;
      case 'background': return palette.background;
      case 'surface': return palette.surface;
      case 'textPrimary': return palette.textPrimary;
      case 'textSecondary': return palette.textSecondary;
      case 'textDisabled': return palette.textDisabled;
      case 'divider': return palette.divider;
      case 'sidebarBackground': return palette.sidebarBackground;
      case 'topbarBackground': return palette.topbarBackground;
      default: return fallback;
    }
  }
}
