/**
 * Response Bot Route Definitions + Handlers (sweep logic)
 * Extracted from response-bot.routes.ts
 */
import { createRoute, z } from '@hono/zod-openapi';
import { ButtonRegistry, LinkRegistry, InteractionARegistry, InteractionRegistry } from 'prime-care-shared';

export const sweepRegistryRoute = createRoute({ summary: 'Platform Registry Sweep', description: 'Iterates through all platform registries to detect 404s or connectivity errors.', tags: ['Scrum Master'], method: 'post', path: '/sweep', request: { body: { content: { 'application/json': { schema: z.object({ publicUrlBase: z.string().optional() }) } } } }, responses: { 200: { content: { 'application/json': { schema: z.object({ status: z.string(), totalAudited: z.number(), errorsFound: z.number() }) } }, description: 'Registry sweep completed' } } });
export const updateTouchpointRoute = createRoute({ summary: 'Update System Touchpoint', tags: ['Scrum Master'], method: 'patch', path: '/touchpoints/{id}', request: { params: z.object({ id: z.string() }), body: { content: { 'application/json': { schema: z.object({ label: z.string().optional(), path: z.string().optional(), isOverridden: z.boolean().optional() }) } } } }, responses: { 200: { content: { 'application/json': { schema: z.any() } }, description: 'Touchpoint updated' } } });
export const listTouchpointsRoute = createRoute({ summary: 'List System Touchpoints', tags: ['Scrum Master'], method: 'get', path: '/touchpoints', responses: { 200: { content: { 'application/json': { schema: z.array(z.any()) } }, description: 'List of touchpoints' } } });
export const syncRegistriesRoute = createRoute({ summary: 'Synchronize Master Registries', tags: ['Scrum Master'], method: 'post', path: '/sync', request: { body: { content: { 'application/json': { schema: z.object({ entries: z.array(z.any()) }) } } } }, responses: { 200: { content: { 'application/json': { schema: z.object({ message: z.string() }) } }, description: 'Success' } } });

export async function handleSweepRegistry(c: any) {
    const prisma = c.get('prisma'); const tenantId = c.get('jwtPayload').tenantId; const { publicUrlBase } = c.req.valid('json');
    let totalAudited = 0; let errorsFound = 0;
    const checkPublic = async (path: string) => { if (!publicUrlBase) return { status: 'OK' as const }; try { const url = `${publicUrlBase.replace(/\/$/, '')}${path}`; const res = await fetch(url, { method: 'HEAD' }); if (res.status === 404) return { status: '404' as const, detail: 'Public 404' }; if (!res.ok) return { status: 'ERROR' as const, detail: `Public HTTP ${res.status}` }; return { status: 'OK' as const }; } catch (e) { return { status: 'ERROR' as const, detail: `Public Fetch Failed: ${e}` }; } };
    const upsertTouchpoint = async (data: { id: string; type: 'BUTTON' | 'LINK' | 'INTERACTION'; role: string; module: string; label: string; path: string; status: 'OK' | '404' | 'WARNING' | 'ERROR'; errorDetail?: string | null }) => {
        totalAudited++; if (data.status !== 'OK') errorsFound++;
        const existing = await prisma.systemTouchpoint.findUnique({ where: { touchpointId: data.id } });
        if (existing) { await prisma.systemTouchpoint.update({ where: { touchpointId: data.id }, update: { status: data.status, errorDetail: data.errorDetail, lastChecked: new Date(), label: existing.isOverridden ? undefined : data.label, path: existing.isOverridden ? undefined : data.path } }); }
        else { await prisma.systemTouchpoint.create({ data: { touchpointId: data.id, type: data.type, role: data.role, module: data.module, label: data.label, path: data.path, status: data.status, errorDetail: data.errorDetail, tenantId } }); }
    };
    for (const btn of ButtonRegistry) { let status: any = 'OK'; let errorDetail = null; if (btn.apiPath) { if (btn.apiPath.includes(':') || btn.apiPath.includes('undefined')) { status = 'WARNING'; errorDetail = 'Path contains placeholders.'; } else if (publicUrlBase) { const pc = await checkPublic(btn.apiPath); if (pc.status !== 'OK') { status = pc.status; errorDetail = pc.detail; } } } await upsertTouchpoint({ id: btn.id, type: 'BUTTON', role: btn.role, module: btn.module, label: btn.label, path: btn.apiPath || 'UI_ACTION', status, errorDetail }); }
    for (const link of LinkRegistry) { let status: any = 'OK'; let errorDetail = null; if (!link.path || link.path === '/shared/404') { status = '404'; errorDetail = 'Static link is broken.'; } else if (publicUrlBase) { const pc = await checkPublic(link.path); if (pc.status !== 'OK') { status = pc.status; errorDetail = pc.detail; } } await upsertTouchpoint({ id: link.id, type: 'LINK', role: link.role, module: link.module, label: link.label, path: link.path || '', status, errorDetail }); }
    for (const ia of InteractionARegistry) { let status: any = 'OK'; let errorDetail = null; const target = ia.target || 'UI_ACTION'; if (target !== 'UI_ACTION' && publicUrlBase) { const pc = await checkPublic(target); if (pc.status !== 'OK') { status = pc.status; errorDetail = pc.detail; } } await upsertTouchpoint({ id: ia.id, type: 'INTERACTION', role: ia.role, module: ia.module, label: ia.label, path: target, status, errorDetail }); }
    const crawlInteractions = async (obj: any, currentRole: string = 'unknown') => { for (const key in obj) { const val = obj[key]; if (val && typeof val === 'object') { if (val.id && val.label) { let status: any = 'OK'; let errorDetail = null; const path = val.apiEndpoint || val.route || 'UI_ACTION'; if (path !== 'UI_ACTION' && typeof path === 'string' && publicUrlBase) { const pc = await checkPublic(path); if (pc.status !== 'OK') { status = pc.status; errorDetail = pc.detail; } } await upsertTouchpoint({ id: val.id, type: 'INTERACTION', role: currentRole.toLowerCase(), module: val.module || 'UNKNOWN', label: val.label, path: typeof path === 'function' ? 'DYNAMIC_FUNC' : path, status, errorDetail }); } else { await crawlInteractions(val, isNaN(Number(key)) ? key : currentRole); } } } };
    await crawlInteractions(InteractionRegistry);
    return c.json({ status: 'success', totalAudited, errorsFound }, 200);
}
export async function handleUpdateTouchpoint(c: any) { const prisma = c.get('prisma'); const { id } = c.req.param(); const data = c.req.valid('json'); return c.json(await prisma.systemTouchpoint.update({ where: { id }, data: { label: data.label, path: data.path, isOverridden: data.isOverridden ?? true, overrideValue: data.label || data.path } }), 200); }
export async function handleListTouchpoints(c: any) { const prisma = c.get('prisma'); return c.json(await prisma.systemTouchpoint.findMany({ where: { tenantId: c.get('jwtPayload').tenantId }, orderBy: { lastChecked: 'desc' } }), 200); }
export async function handleSyncRegistries(c: any) { return c.json({ message: 'Registries synchronized successfully.' }, 200); }
