const TENANCY = {
    MANAGER: {
        DASHBOARD: '/tenancy/manager',
        MARKETING: '/tenancy/manager/marketing',
        OPERATIONS: '/tenancy/manager/operations',
        CLINICAL: '/tenancy/manager/clinical',
        REGIONAL_STATS: '/tenancy/manager/regional-stats',
        RECRUITING: '/tenancy/manager/recruiting',
        COMPLIANCE: '/tenancy/manager/compliance',
        TRAINING: '/tenancy/manager/training',
        DAILY_ENTRY: '/tenancy/manager/daily-entry',
        EVALUATIONS: '/tenancy/manager/evaluations',
        SERVICE_REVIEW: '/tenancy/manager/service-review',
        SURVEYS: '/tenancy/manager/surveys',
        PERFORMANCE: '/tenancy/manager/performance',
        FINANCE: '/tenancy/manager/finance',
        PAYROLL: '/tenancy/manager/payroll',
        TEAM: '/tenancy/manager/team',
        PORTFOLIO: '/tenancy/manager/portfolio',
    },
    STAFF: {
        DASHBOARD: '/tenancy/staff',
        CUSTOMERS: '/tenancy/staff/customers',
        TASKS: '/tenancy/staff/tasks',
        MESSAGES: '/tenancy/staff/messages',
        INCIDENTS: '/tenancy/staff/incidents',
        COMPLIANCE: '/tenancy/staff/compliance',
    },
    PSW: {
        DASHBOARD: '/tenancy/psw',
        SCHEDULE: '/tenancy/psw/schedule',
        OPEN_SHIFTS: '/tenancy/psw/open-shifts',
        OFFERS: '/tenancy/psw/offers',
        AVAILABILITY: '/tenancy/psw/availability',
        EARNINGS: '/tenancy/psw/earnings',
        PAYOUTS: '/tenancy/psw/payouts',
        EXPENSES: '/tenancy/psw/expenses',
        SHIFT_CONFIRMATION: '/tenancy/psw/shift-confirmation',
        CREDENTIALS: '/tenancy/psw/credentials',
        FEED: '/tenancy/psw/feed',
        LIVE_VISIT: '/tenancy/psw/live-visit',
        CHECK_IN: '/tenancy/psw/check-in/:id',
        HANDOVER: '/tenancy/psw/handover',
    },
    RN: {
        DASHBOARD: '/tenancy/rn',
        CARE_PLANS: '/tenancy/rn/care-plans',
        DAILY_AUDIT: '/tenancy/rn/entry-verify',
        SUPERVISION: '/tenancy/rn/supervision',
        SUPERVISION_DETAIL: (pswId: string) => `/tenancy/rn/supervision/psw/${pswId}`,
        ASSESSMENTS: '/tenancy/rn/assessments',
        RECONCILIATION: '/tenancy/rn/reconciliation',
    },
    COORDINATOR: {
        DASHBOARD: '/tenancy/coordinator',
        HUB: '/tenancy/coordinator/hub',
        MAP: '/tenancy/coordinator/dispatch-map',
        WAITLIST: '/tenancy/coordinator/waitlist',
        SOS: '/tenancy/coordinator/sos-center',
        SCHEDULE: '/tenancy/coordinator/schedule',
        SOS_HUB: '/coordinator/sos',
    },
    CLIENT: {
        DASHBOARD: '/tenancy/client',
        BOOKINGS: '/tenancy/client/bookings',
        BILLING: '/tenancy/client/billing',
        FEEDBACK: '/tenancy/client/feedback',
        REQUEST_BOOKING: '/tenancy/client/request-booking',
        SERVICES: '/tenancy/client/services',
        SUPPORT: '/tenancy/client/support',
        TEAM: '/tenancy/client/team',
        FEEDBACK_LOOP: '/tenancy/client/feedback-loop',
        FAMILY_HUB: '/tenancy/client/family-hub',
    },
    ALLIED: {
        DASHBOARD: '/tenancy/allied-health',
        TREATMENTS: '/tenancy/allied-health/treatments',
        SIGN_OFF: '/tenancy/allied-health/sign-off',
    },
    CARE_PLANS: '/care-plans',
} as const;

const PLATFORM = {
    ADMIN: {
        DASHBOARD: '/platform/admin',
        SUMMARY_DASHBOARD: '/platform/admin/summary-dashboard',
        CUSTOMERS: '/platform/admin/customers',
        USERS: '/platform/admin/users',
        USERS_NEW: '/platform/admin/users/new',
        USERS_EDIT: (id: string) => `/platform/admin/users/${id}/edit`,
        SCHEDULE: '/platform/admin/schedule',
        EARNINGS: '/platform/admin/earnings',
        INCIDENTS: '/platform/admin/incidents',
        INCIDENTS_NEW: '/platform/admin/incidents/new',
        INCIDENTS_EDIT: (id: string) => `/platform/admin/incidents/${id}/edit`,
        LEADS: '/platform/admin/leads',
        LEADS_NEW: '/platform/admin/leads/new',
        LEADS_EDIT: (id: string) => `/platform/admin/leads/${id}/edit`,
        LEADS_CONVERT: (id: string) => `/platform/admin/leads/${id}/convert`,
        INVOICES_NEW: '/platform/admin/invoices/new',
        INVOICES_EDIT: (id: string) => `/platform/admin/invoices/${id}/edit`,
        TIMESHEETS: '/platform/admin/timesheets',
        TIMESHEET_ADJUST: '/platform/admin/timesheets/adjust',
        REPORTS: '/platform/admin/reports',
        REPORT_EXPORT: '/platform/admin/reports/export',
        SEARCH: '/platform/admin/search',
        SERVICES: '/platform/admin/services',
        SETTINGS: '/platform/admin/settings',
        CONTENT: '/platform/admin/content',
        AUDITS: '/platform/admin/audits',
        ADMISSION: '/platform/admin/admission',
        ONBOARDING: '/platform/admin/onboarding',
        LOCATIONS: '/platform/admin/locations',
        SETUP_WIZARD: '/platform/admin/setup-wizard',
        WIZARD_HUB: '/platform/admin/wizard-hub',
        STAFF_ONBOARDING: '/platform/admin/wizards/staff-onboarding',
        CARE_PLAN_WIZARD: '/platform/admin/wizards/care-plan',
        REVENUE_WIZARD: '/platform/admin/wizards/revenue',
        BUSINESS_MODEL_WIZARD: '/platform/admin/wizards/business-strategy',
        BUSINESS_STATUS: '/platform/admin/business-status',
        KNOWLEDGE_BASE: '/platform/admin/knowledge-base',
        KNOWLEDGE_BASE_ARTICLE: (slug: string) => `/platform/admin/knowledge-base/${slug}`,
        AI_INSIGHTS: '/platform/admin/insights',
        CLINICAL_ASSISTANT: '/platform/admin/clinical-assistant',
        AUTOPILOT: '/platform/admin/automation/clinical-autopilot',
        INTEROP: '/platform/admin/interop',
        SOVEREIGN: '/platform/admin/sovereign',
        TEMPLATE_EDITOR: '/platform/admin/template-editor',
        ROLE_EDITOR: '/platform/admin/role-editor',
        PRIVATE_MARKETPLACE: '/platform/admin/private-marketplace',

        // New Intelligence & Security Layer
        AI: {
            DASHBOARD: '/platform/admin/ai',
            PREDICTIVE_ANALYTICS: '/platform/admin/ai/predictive',
            CHURN_RISK: '/platform/admin/ai/churn-risk',
            VISIT_OPTIMIZATION: '/platform/admin/ai/visit-optimization',
            SENTIMENT_ANALYSIS: '/platform/admin/ai/sentiment',
        },
        SECURITY: {
            DASHBOARD: '/platform/admin/security',
            PERMISSION_GRID: '/platform/admin/security/permissions',
            AUDIT_DETAIL: (id: string) => `/platform/admin/security/audits/${id}`,
            SESSION_MONITOR: '/platform/admin/security/sessions',
            THREAT_DETECTION: '/platform/admin/security/threats',
        },
        OPERATIONS: {
            REALTIME_CAPACITY: '/platform/admin/ops/capacity',
            REGION_MAPPING: '/platform/admin/ops/regions',
            SUPPLY_DEMAND: '/platform/admin/ops/supply-demand',
            LOGISTICS_HUB: '/platform/admin/ops/logistics',
        },
        ERP: {
            INVENTORY: '/platform/admin/erp/inventory',
            PROCUREMENT: '/platform/admin/erp/procurement',
        },
        TELEHEALTH: {
            CENTER: '/platform/admin/telehealth/center',
            ALERTS: '/platform/admin/telehealth/alerts',
        },
        RCM: {
            CLAIMS: '/platform/admin/rcm/claims',
            REVENUE: '/platform/admin/rcm/revenue',
        },
        PHARMACY: {
            HUB: '/platform/admin/pharmacy/hub',
            MAR: '/platform/admin/pharmacy/mar',
        }
    },
    SUPERUSER: {
        DASHBOARD: '/platform',
        TENANTS: '/platform/tenants',
        AUDIT_LOGS: '/platform/audit-logs',
        SLA: '/platform/sla',
        RISK_SURVEILLANCE: '/platform/risk-surveillance',
        GOVERNANCE_HUB: '/platform/governance',
        SYSTEM_POLICIES: '/platform/policies',
    },
    SCRUM_MASTER: {
        DASHBOARD: '/platform/scrum-master',
        API_ENDPOINTS: '/platform/scrum-master/api-endpoints',
        PAGES: '/platform/scrum-master/pages',
        COMPONENTS: '/platform/scrum-master/components',
        ROLE_FLOWS: '/platform/scrum-master/role-flows',
        MONITORING: '/platform/scrum-master/monitoring',
        ENV_AUDIT: '/platform/scrum-master/env-audit',
        REGISTRY_CHECK: '/platform/scrum-master/registry-check',
        DATABASE_SCHEMA: '/platform/scrum-master/database-schema',
        THEME_CENTER: '/platform/scrum-master/theme-center',
        // Consolidated from Admin
        DEVELOPER: '/platform/scrum-master/developer',
        DEV_KB: '/platform/scrum-master/dev-kb',
        // New Technical Orchestration
        PERFORMANCE: '/platform/scrum-master/performance',
        BUILD_HEALTH: '/platform/scrum-master/builds',
        SECURITY_SCANS: '/platform/scrum-master/security-scans',
        LOCALIZATION: '/platform/scrum-master/locales',
        INTERACTION_AUDIT: '/platform/scrum-master/interaction-audit',
        AUTO_FIX: '/platform/scrum-master/auto-fix',
        IMPERSONATE: '/platform/scrum-master/impersonate',
        RESPONSE_BOT: '/platform/scrum-master/response-bot',
    }
} as const;

const AUTH = {
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    BUSINESS_ONBOARD: '/onboard-business',
} as const;

const SHARED = {
    PROFILE: '/profile',
    MESSAGING: '/messaging',
    SUPPORT: '/support',
    SUPPORT_TICKETS_NEW: '/support/tickets/new',
    VISITS_DETAILS: (id: string) => `/visits/${id}`,
    VISITS_COMPLETE: (id: string) => `/visits/${id}/complete`,
    LEARN: '/learn',
    KNOWLEDGE_BASE: '/knowledge-base',
    KNOWLEDGE_BASE_ARTICLE: (slug: string) => `/knowledge-base/${slug}`,
    NOT_FOUND: '/shared/404',
    UNAUTHORIZED: '/shared/401',
    SERVER_ERROR: '/shared/500',
} as const;

export const RouteRegistry = {
    ...AUTH,
    ...SHARED,

    // Role-specific namespaces (Standard Access)
    ADMIN: PLATFORM.ADMIN,
    SUPERUSER: PLATFORM.SUPERUSER,
    MANAGER: TENANCY.MANAGER,
    STAFF: TENANCY.STAFF,
    PSW: TENANCY.PSW,
    RN: TENANCY.RN,
    CLIENT: TENANCY.CLIENT,
    COORDINATOR: TENANCY.COORDINATOR,
    ALLIED: TENANCY.ALLIED,
    CARE_PLANS: TENANCY.CARE_PLANS,
    SCRUM_MASTER: PLATFORM.SCRUM_MASTER,

    ROLE_DASHBOARDS: {
        admin: PLATFORM.ADMIN.DASHBOARD,
        reseller: PLATFORM.ADMIN.DASHBOARD,
        manager: TENANCY.MANAGER.DASHBOARD,
        marketing_manager: TENANCY.MANAGER.MARKETING,
        operations_manager: TENANCY.MANAGER.OPERATIONS,
        clinical_manager: TENANCY.MANAGER.CLINICAL,
        regional_manager: TENANCY.MANAGER.REGIONAL_STATS,
        recruiting_manager: TENANCY.MANAGER.RECRUITING,
        coordinator: TENANCY.COORDINATOR.DASHBOARD,
        crm: TENANCY.MANAGER.DASHBOARD,
        training: TENANCY.MANAGER.TRAINING,
        staff: TENANCY.STAFF.DASHBOARD,
        finance: TENANCY.STAFF.DASHBOARD,
        hr: TENANCY.STAFF.DASHBOARD,
        compliance: TENANCY.STAFF.DASHBOARD,
        rn: TENANCY.RN.DASHBOARD,
        psw: TENANCY.PSW.DASHBOARD,
        rmt: TENANCY.ALLIED.DASHBOARD,
        rpt: TENANCY.ALLIED.DASHBOARD,
        rch: TENANCY.ALLIED.DASHBOARD,
        client: TENANCY.CLIENT.DASHBOARD,
        super_admin: PLATFORM.SUPERUSER.DASHBOARD,
        scrum_master: PLATFORM.SCRUM_MASTER.DASHBOARD
    } as Record<string, string>,

    ROLE_EDITOR: PLATFORM.ADMIN.ROLE_EDITOR,
    LOCATIONS: PLATFORM.ADMIN.LOCATIONS,
    PRIVATE_MARKETPLACE: PLATFORM.ADMIN.PRIVATE_MARKETPLACE,
    TENANTS: PLATFORM.SUPERUSER.TENANTS,
} as const;
