export const RouteRegistry = {
    LOGIN: '/login',
    REGISTER: '/register',
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    USERS_NEW: '/admin/users/new',
    USERS_EDIT: (id: string) => `/admin/users/${id}/edit`,
    VISITS: '/admin/visits',

    EARNINGS: '/admin/earnings',
    SCHEDULE: '/admin/schedule',
    INCIDENTS: '/admin/incidents',
    TIMESHEETS: '/admin/timesheets',
    LEADS: '/admin/leads',
    SERVICES: '/admin/services',
    SETTINGS: '/admin/settings',
    CONTENT: '/admin/content',
    AUDITS: '/admin/audits',
    SUPPORT: '/admin/support',
    ADMISSION: '/admin/admission',
    ONBOARDING: '/admin/onboarding',

    ROLE_DASHBOARDS: {
        admin: '/admin/dashboard',
        manager: '/manager/dashboard',
        marketing_manager: '/manager/dashboard',
        operations_manager: '/manager/dashboard',
        clinical_manager: '/manager/dashboard',
        regional_manager: '/manager/dashboard',
        recruiting_manager: '/manager/dashboard',
        coordinator: '/manager/dashboard',
        crm: '/manager/dashboard',
        training: '/manager/dashboard',
        staff: '/staff/dashboard',
        finance: '/staff/dashboard',
        hr: '/staff/dashboard',
        compliance: '/staff/dashboard',
        rn: '/rn/dashboard',
        psw: '/psw/dashboard',
        rmt: '/psw/dashboard',
        rpt: '/psw/dashboard',
        rch: '/psw/dashboard',
        client: '/client/dashboard'
    } as Record<string, string>
} as const;
