// DYNAMIC ADAPTER RESOLVER
// Auto-generated by PrimeCare UI Architectural Normalize Pipeline

import 'package:primecare_adapters/src/business_development/franchise_sales_manager/adapters/franchise_sales_manager_dashboard_adapter.dart';
import 'package:primecare_adapters/src/business_development/partnership_manager/adapters/partnership_manager_dashboard_adapter.dart';
import 'package:primecare_adapters/src/business_development/regional_bdm_ontario/adapters/regional_manager_ontario_dashboard_adapter.dart';
import 'package:primecare_adapters/src/business_development/regional_bdm_usa/adapters/regional_manager_usa_dashboard_adapter.dart';
import 'package:primecare_adapters/src/business_development/territory_expansion_manager/adapters/territory_expansion_manager_dashboard_adapter.dart';
import 'package:primecare_adapters/src/client_family/client/adapters/client_dashboard_adapter.dart';
import 'package:primecare_adapters/src/client_family/family_member/adapters/family_dashboard_adapter.dart';
import 'package:primecare_adapters/src/client_family/guest/adapters/guest_dashboard_adapter.dart';
import 'package:primecare_adapters/src/clinical/clinic_manager/adapters/clinic_dashboard_adapter.dart';
import 'package:primecare_adapters/src/clinical/patient/adapters/patient_dashboard_adapter.dart';
import 'package:primecare_adapters/src/corporate/ceo/adapters/ceo_dashboard_adapter.dart';
import 'package:primecare_adapters/src/corporate/cfo/adapters/cfo_dashboard_adapter.dart';
import 'package:primecare_adapters/src/corporate/compliance_manager/adapters/compliance_manager_dashboard_adapter.dart';
import 'package:primecare_adapters/src/corporate/coo/adapters/coo_dashboard_adapter.dart';
import 'package:primecare_adapters/src/corporate/cto/adapters/cto_dashboard_adapter.dart';
import 'package:primecare_adapters/src/corporate/general_manager/adapters/general_manager_dashboard_adapter.dart';
import 'package:primecare_adapters/src/corporate/head_of_business_development/adapters/head_of_bus_dev_dashboard_adapter.dart';
import 'package:primecare_adapters/src/corporate/scrum_master/adapters/scrum_master_dashboard_adapter.dart';
import 'package:primecare_adapters/src/corporate/training_director/adapters/training_director_dashboard_adapter.dart';
import 'package:primecare_adapters/src/customer_support/customer_support/adapters/customer_support_dashboard_adapter.dart';
import 'package:primecare_adapters/src/customer_support/intake_coordinator/adapters/intake_dashboard_adapter.dart';
import 'package:primecare_adapters/src/customer_support/quality_assurance/adapters/qa_dashboard_adapter.dart';
import 'package:primecare_adapters/src/customer_support/support/adapters/support_dashboard_adapter.dart';
import 'package:primecare_adapters/src/customer_support/training_coordinator/adapters/training_coordinator_dashboard_adapter.dart';
import 'package:primecare_adapters/src/franchise/billing_admin/adapters/billing_admin_dashboard_adapter.dart';
import 'package:primecare_adapters/src/franchise/franchise_owner/adapters/franchise_owner_adapter.dart';
import 'package:primecare_adapters/src/franchise/hr_manager/adapters/hr_hiring_dashboard_adapter.dart';
import 'package:primecare_adapters/src/franchise/operations_manager/adapters/operations_manager_dashboard_adapter.dart';
import 'package:primecare_adapters/src/franchise/owner/adapters/owner_dashboard_adapter.dart';
import 'package:primecare_adapters/src/franchise/scheduler_coordinator/adapters/scheduler_dashboard_adapter.dart';
import 'package:primecare_adapters/src/marketing/community_outreach/adapters/community_outreach_dashboard_adapter.dart';
import 'package:primecare_adapters/src/marketing/head_of_marketing/adapters/head_of_marketing_dashboard_adapter.dart';
import 'package:primecare_adapters/src/marketing/local_marketing_manager/adapters/local_marketing_manager_dashboard_adapter.dart';
import 'package:primecare_adapters/src/marketing/territory_sales_manager/adapters/territory_sales_manager_dashboard_adapter.dart';
import 'package:primecare_ui/src/components/auth_split_layout_adapter.dart';
import 'package:primecare_ui/src/components/drag_assign_widget_adapter.dart';
import 'package:primecare_ui/src/components/eta_tracker_widget_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/approve_expense_reimbursement_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/approve_payroll_run_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/approve_real_estate_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/approve_system_access_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/audit_global_education_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/audit_override_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/audit_royalty_payment_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/audit_security_compliance_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/audit_system_logs_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/create_canned_response_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/create_custom_invoice_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/create_revenue_report_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/create_supply_order_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/log_inventory_spoilage_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/log_petty_cash_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/override_global_schedule_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/register_corporate_risk_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/review_care_plan_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/review_fleet_maintenance_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/review_legal_contract_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/review_monthly_expenses_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/review_vendor_contracts_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/role_permissions_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/schedule_facility_maintenance_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/submit_daily_census_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/admin/submit_healthcare_claim_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/base_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/clinical/assign_care_pod_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/clinical/audit_compliance_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/clinical/care_plan_evaluation_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/clinical/log_clinical_incident_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/clinical/log_infection_control_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/clinical/review_clinical_incident_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/clinical/review_medication_inventory_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/clinical/schedule_clinical_audit_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/clinical/submit_adl_checklist_form_adapter.dart';
import 'package:primecare_ui/src/components/forms/hr/approve_leave_request_form_adapter.dart';
import 'package:primecare_ui/src/components/greeting_header_widget_adapter.dart';
import 'package:primecare_ui/src/components/layouts/admin_layout_adapter.dart';
import 'package:primecare_ui/src/components/layouts/client_layout_adapter.dart';
import 'package:primecare_ui/src/components/layouts/master_layout_adapter.dart';
import 'package:primecare_ui/src/components/layouts/provider_layout_adapter.dart';
import 'package:primecare_ui/src/components/master_detail_layout_adapter.dart';
import 'package:primecare_ui/src/components/mood_slider_widget_adapter.dart';
import 'package:primecare_ui/src/components/slide_to_clock_in_widget_adapter.dart';
import 'package:primecare_ui/src/screens/auth/auth_layout_adapter.dart';
import 'package:primecare_ui/src/screens/auth/forgot_password_screen_adapter.dart';
import 'package:primecare_ui/src/screens/auth/login_screen_adapter.dart';
import 'package:primecare_ui/src/screens/auth/mfa_screen_adapter.dart';
import 'package:primecare_ui/src/screens/auth/signup_screen_adapter.dart';
import 'package:primecare_ui/src/screens/common/dynamic_role_dashboard_screen_adapter.dart';
import 'package:primecare_ui/src/screens/common/splash_screen_adapter.dart';
import 'package:primecare_ui/src/screens/common/subscription_upgrade_screen_adapter.dart';
import 'package:primecare_ui/src/theme/primecare_responsive_shell_adapter.dart';

/// Global Registry dynamically mapping screen routing IDs to their Hydration Adapters
final Map<String, dynamic> globalAdapterRegistry = {
  'territorySalesManagerDashboard':
      territorySalesManagerDashboardAdapterProvider,
  'localMarketingManagerDashboard':
      localMarketingManagerDashboardAdapterProvider,
  'headOfMarketingDashboard': headOfMarketingDashboardAdapterProvider,
  'communityOutreachDashboard': communityOutreachDashboardAdapterProvider,
  'schedulerDashboard': schedulerDashboardAdapterProvider,
  'ownerDashboard': ownerDashboardAdapterProvider,
  'operationsManagerDashboard': operationsManagerDashboardAdapterProvider,
  'hrHiringDashboard': hrHiringDashboardAdapterProvider,
  'franchiseOwner': franchiseOwnerAdapterProvider,
  'billingAdminDashboard': billingAdminDashboardAdapterProvider,
  'trainingCoordinatorDashboard': trainingCoordinatorDashboardAdapterProvider,
  'supportDashboard': supportDashboardAdapterProvider,
  'qaDashboard': qaDashboardAdapterProvider,
  'intakeDashboard': intakeDashboardAdapterProvider,
  'customerSupportDashboard': customerSupportDashboardAdapterProvider,
  'trainingDirectorDashboard': trainingDirectorDashboardAdapterProvider,
  'scrumMasterDashboard': scrumMasterDashboardAdapterProvider,
  'headOfBusDevDashboard': headOfBusDevDashboardAdapterProvider,
  'generalManagerDashboard': generalManagerDashboardAdapterProvider,
  'ctoDashboard': ctoDashboardAdapterProvider,
  'cooDashboard': cooDashboardAdapterProvider,
  'complianceManagerDashboard': complianceManagerDashboardAdapterProvider,
  'cfoDashboard': cfoDashboardAdapterProvider,
  'ceoDashboard': ceoDashboardAdapterProvider,
  'patientDashboard': patientDashboardAdapterProvider,
  'clinicDashboard': clinicDashboardAdapterProvider,
  'guestDashboard': guestDashboardAdapterProvider,
  'familyDashboard': familyDashboardAdapterProvider,
  'clientDashboard': clientDashboardAdapterProvider,
  'territoryExpansionManagerDashboard':
      territoryExpansionManagerDashboardAdapterProvider,
  'regionalManagerUSADashboard': regionalManagerUSADashboardAdapterProvider,
  'regionalManagerOntarioDashboard':
      regionalManagerOntarioDashboardAdapterProvider,
  'partnershipManagerDashboard': partnershipManagerDashboardAdapterProvider,
  'franchiseSalesManagerDashboard':
      franchiseSalesManagerDashboardAdapterProvider,
  'assignTrainingModuleForm': assignTrainingModuleFormAdapterProvider,
  'auditPayrollDiscrepancyForm': auditPayrollDiscrepancyFormAdapterProvider,
  'disciplineLogForm': disciplineLogFormAdapterProvider,
  'leaveRequestForm': leaveRequestFormAdapterProvider,
  'logEmployeeGrievanceForm': logEmployeeGrievanceFormAdapterProvider,
  'newEmployeeOnboardingForm': newEmployeeOnboardingFormAdapterProvider,
  'requestShiftAdjustmentForm': requestShiftAdjustmentFormAdapterProvider,
  'reviewOnboardingStatusForm': reviewOnboardingStatusFormAdapterProvider,
  'reviewPeerPerformanceForm': reviewPeerPerformanceFormAdapterProvider,
  'scheduleInterviewForm': scheduleInterviewFormAdapterProvider,
  'submitExitInterviewForm': submitExitInterviewFormAdapterProvider,
  'addFranchiseLeadForm': addFranchiseLeadFormAdapterProvider,
  'approveFranchiseDisclosureForm':
      approveFranchiseDisclosureFormAdapterProvider,
  'assignLeadForm': assignLeadFormAdapterProvider,
  'createAdPlacementForm': createAdPlacementFormAdapterProvider,
  'franchiseOnboardingChecklistForm':
      franchiseOnboardingChecklistFormAdapterProvider,
  'logFranchiseeVettingCallForm': logFranchiseeVettingCallFormAdapterProvider,
  'nurtureLocalizedLeadForm': nurtureLocalizedLeadFormAdapterProvider,
  'reviewLeadConversionForm': reviewLeadConversionFormAdapterProvider,
  'reviewMarketShareForm': reviewMarketShareFormAdapterProvider,
  'scheduleOpenHouseForm': scheduleOpenHouseFormAdapterProvider,
  'submitMarketingBudgetForm': submitMarketingBudgetFormAdapterProvider,
  'singleInputForm': singleInputFormAdapterProvider,
  'approveMedicationRefillForm': approveMedicationRefillFormAdapterProvider,
  'dailyVitalsCardForm': dailyVitalsCardFormAdapterProvider,
  'patientIntakeForm': patientIntakeFormAdapterProvider,
  'approveExpenseReimbursementForm':
      approveExpenseReimbursementFormAdapterProvider,
  'approveLeaveRequestForm': approveLeaveRequestFormAdapterProvider,
  'approvePayrollRunForm': approvePayrollRunFormAdapterProvider,
  'authSplitLayout': authSplitLayoutAdapterProvider,
  'dragAssignWidget': dragAssignWidgetAdapterProvider,
  'etaTrackerWidget': etaTrackerWidgetAdapterProvider,
  'greetingHeaderWidget': greetingHeaderWidgetAdapterProvider,
  'masterDetailLayout': masterDetailLayoutAdapterProvider,
  'moodSliderWidget': moodSliderWidgetAdapterProvider,
  'slideToClockInWidget': slideToClockInWidgetAdapterProvider,
  'primecareResponsiveShell': primecareResponsiveShellAdapterProvider,
  'authLayout': authLayoutAdapterProvider,
  'forgotPasswordScreen': forgotPasswordScreenAdapterProvider,
  'loginScreen': loginScreenAdapterProvider,
  'mfaScreen': mfaScreenAdapterProvider,
  'signupScreen': signupScreenAdapterProvider,
  'dynamicRoleDashboardScreen': dynamicRoleDashboardScreenAdapterProvider,
  'splashScreen': splashScreenAdapterProvider,
  'subscriptionUpgradeScreen': subscriptionUpgradeScreenAdapterProvider,
  'baseForm': baseFormAdapterProvider,
  'adminLayout': adminLayoutAdapterProvider,
  'clientLayout': clientLayoutAdapterProvider,
  'masterLayout': masterLayoutAdapterProvider,
  'providerLayout': providerLayoutAdapterProvider,
  'approveRealEstateForm': approveRealEstateFormAdapterProvider,
  'approveSystemAccessForm': approveSystemAccessFormAdapterProvider,
  'auditGlobalEducationForm': auditGlobalEducationFormAdapterProvider,
  'auditOverrideForm': auditOverrideFormAdapterProvider,
  'auditRoyaltyPaymentForm': auditRoyaltyPaymentFormAdapterProvider,
  'auditSecurityComplianceForm': auditSecurityComplianceFormAdapterProvider,
  'auditSystemLogsForm': auditSystemLogsFormAdapterProvider,
  'createCannedResponseForm': createCannedResponseFormAdapterProvider,
  'createCustomInvoiceForm': createCustomInvoiceFormAdapterProvider,
  'createRevenueReportForm': createRevenueReportFormAdapterProvider,
  'createSupplyOrderForm': createSupplyOrderFormAdapterProvider,
  'logInventorySpoilageForm': logInventorySpoilageFormAdapterProvider,
  'logPettyCashForm': logPettyCashFormAdapterProvider,
  'overrideGlobalScheduleForm': overrideGlobalScheduleFormAdapterProvider,
  'registerCorporateRiskForm': registerCorporateRiskFormAdapterProvider,
  'reviewCarePlanForm': reviewCarePlanFormAdapterProvider,
  'reviewFleetMaintenanceForm': reviewFleetMaintenanceFormAdapterProvider,
  'reviewLegalContractForm': reviewLegalContractFormAdapterProvider,
  'reviewMonthlyExpensesForm': reviewMonthlyExpensesFormAdapterProvider,
  'reviewVendorContractsForm': reviewVendorContractsFormAdapterProvider,
  'rolePermissionsForm': rolePermissionsFormAdapterProvider,
  'scheduleFacilityMaintenanceForm':
      scheduleFacilityMaintenanceFormAdapterProvider,
  'submitDailyCensusForm': submitDailyCensusFormAdapterProvider,
  'submitHealthcareClaimForm': submitHealthcareClaimFormAdapterProvider,
  'assignCarePodForm': assignCarePodFormAdapterProvider,
  'auditComplianceForm': auditComplianceFormAdapterProvider,
  'carePlanEvaluationForm': carePlanEvaluationFormAdapterProvider,
  'logClinicalIncidentForm': logClinicalIncidentFormAdapterProvider,
  'logInfectionControlForm': logInfectionControlFormAdapterProvider,
  'reviewClinicalIncidentForm': reviewClinicalIncidentFormAdapterProvider,
  'reviewMedicationInventoryForm': reviewMedicationInventoryFormAdapterProvider,
  'scheduleClinicalAuditForm': scheduleClinicalAuditFormAdapterProvider,
  'submitAdlChecklistForm': submitAdlChecklistFormAdapterProvider,
};

/// Resolver utility to dynamically fetch any ViewModel provider by string ref
dynamic resolveAdapterByName(String name) {
  return globalAdapterRegistry[name];
}
