"""Build documentation traceability from the finite checklist; never approve APIs."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUTS = ('docs/api/api-delivery-checklist.json', 'docs/api/workflow-contract-reviews.json')
SLOTS = ('request', 'response', 'validation', 'authentication', 'authorization',
         'permission', 'rateLimits', 'audit', 'errors', 'version', 'workflow',
         'persistence', 'idempotency', 'tests', 'clientBinding', 'examples')
CHAPTERS = ('README.md', 'system-requirements.md', 'architecture-data.md',
            'security-authorization.md', 'api-workflow-contracts.md',
            'runtime-operations.md', 'testing-release.md', 'implementation-plan.md',
            'identity-work-package.md', 'family-decision-register.md')


def build():
    checklist, reviews = [json.loads((ROOT / p).read_text()) for p in INPUTS]
    families = reviews['reviews']
    identities = [o['api'] for o in checklist['operations']]
    if len(identities) != len(set(identities)):
        raise ValueError('Finite checklist contains duplicate operations')
    if any(o['api'] != o['method'] + ' ' + o['route'] for o in checklist['operations']):
        raise ValueError('Operation method/path identity is inconsistent')
    memberships = {}
    for family in families:
        for operation in family['operations']:
            if operation['api'] not in identities:
                raise ValueError('Family references an unknown operation')
            memberships.setdefault(operation['api'], []).append(family['id'])
    unresolved = {o['api'] for o in checklist['operations'] if o['stage'] in
                  ('needs_contract_and_verification', 'blocked')}
    if unresolved != set(memberships):
        raise ValueError('Family decisions must cover exactly the unresolved operations')
    entries = []
    for operation in sorted(checklist['operations'], key=lambda o: o['api']):
        entries.append({
            'requirementId': 'API-' + hashlib.sha256(operation['api'].encode()).hexdigest()[:16],
            'api': operation['api'], 'method': operation['method'], 'path': operation['route'],
            'declarationIds': operation['declarationIds'], 'services': operation['services'],
            'area': operation['area'], 'baselineStage': operation['stage'],
            'familyIds': sorted(set(memberships.get(operation['api'], []))),
            'requiredContractSections': list(SLOTS),
            'unitEvidenceRecorded': operation['unitEvidenceRecorded'],
            'postgresEvidence': operation['postgresEvidence'],
            'productionEvidence': operation['productionEvidence'],
            'nextAction': operation['nextAction'],
            'authority': 'Not established by this documentation register',
            'completionCredits': 0,
        })
    summary = checklist['summary']
    data = {
        'generator': 'build-technical-operation-register.py',
        'purpose': 'Documentation traceability, not runtime permission, approval, or implementation',
        'sourceCommit': '3979ed1028c8b7dfdb9acca72b1ea53d4d034127',
        'inputs': {p: hashlib.sha256((ROOT / p).read_bytes()).hexdigest() for p in INPUTS},
        'uniqueOperations': len(entries), 'unresolvedOperations': len(unresolved),
        'families': len(families), 'baselineStages': summary['stages'],
        'completionCredits': 0, 'operations': entries,
        'familyDecisions': [{key: family[key] for key in
                            ('id', 'title', 'priority', 'operations', 'policyDecisions', 'evidencePaths')}
                           for family in families],
    }
    lines = ['# Operation and family decision register', '',
             'Generated by `scripts/build-technical-operation-register.py`. This is an implementation input, not API completion evidence.', '',
             f"The finite baseline contains {len(entries):,} unique method/path pairs. {len(unresolved):,} unresolved operations belong to {len(families)} reviewed families. Multiple family references never increase the operation count.", '',
             'Every exact operation, declaration ID, evidence stage, service, and required contract section is recorded in [operation-register.json](operation-register.json).', '',
             'For each family below, recover source contracts and grant provenance first. Business decisions remain open until their owner records an explicit decision. Do not derive write authority from read access, screen visibility, a role name, a generated DTO, or a similar URL.', '']
    for family in sorted(families, key=lambda f: (f['priority'], f['id'])):
        lines.extend([f"## {family['id']}: {family['title']}", '',
                      'Status: requires a defined workflow contract; implementation credit remains zero.', '',
                      '### Exact operation coverage', ''])
        for operation in family['operations']:
            lines.append(f"- `{operation['api']}` — declarations {', '.join(map(str, operation['declarationIds']))}; baseline `{operation['stage']}`.")
        lines.extend(['', '### Family-specific decisions', ''])
        for decision in family['policyDecisions']:
            lines.append('- ' + decision)
        lines.extend(['', '### Evidence to reconcile', ''])
        for path in family['evidencePaths']:
            lines.append('- `' + path + '`')
        lines.extend(['', '### Required implementation record', '',
                      'Supply all 16 contract sections: ' + ', '.join('`' + s + '`' for s in SLOTS) + '.', '',
                      'Record actor and subject identities, tenant/resource boundary, exact permitted action, projected fields, preconditions, validation, transaction and failure behavior. Bind each rule to a source or an explicit decision. Map deny, cross-tenant, ownership, replay, malformed-input, and persistence tests before activation.', ''])
    outputs = {'docs/technical/operation-register.json': json.dumps(data, indent=2, ensure_ascii=False) + '\n',
               'docs/technical/family-decision-register.md': '\n'.join(lines) + '\n'}
    book = ['# PrimeCare complete technical manual', '',
            'Generated from the source-controlled technical chapters. Observed behavior, requirements, proposals and open decisions remain distinct. This manual does not certify API completion or production readiness.', '']
    for number, chapter in enumerate(CHAPTERS, 1):
        relative = 'docs/technical/' + chapter
        content = outputs.get(relative)
        if content is None:
            content = (ROOT / relative).read_text()
        digest = hashlib.sha256(content.encode()).hexdigest()
        book.extend(['---', '', f'## Chapter {number}: {chapter}', '',
                     f'<!-- Source: {relative}; SHA256: {digest} -->', '', content.rstrip(), ''])
    outputs['docs/technical/PRIMECARE_TECHNICAL_MANUAL.md'] = '\n'.join(book) + '\n'
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    outputs = build()
    for relative, value in outputs.items():
        path = ROOT / relative
        if path.is_symlink() or any(parent.is_symlink() for parent in path.parents):
            raise ValueError('Refusing an unsafe documentation output path')
        if args.check:
            if not path.exists() or path.read_text() != value:
                raise ValueError('Stale technical operation register: ' + relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(value)
    register = json.loads(outputs['docs/technical/operation-register.json'])
    print(json.dumps({key: register[key] for key in
                      ('uniqueOperations', 'unresolvedOperations', 'families', 'completionCredits')}))


if __name__ == '__main__':
    main()
