import os
import sys
import sqlite3
import json
import subprocess
from datetime import datetime

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(PROJECT_ROOT, ".agents", "governance", "governance.db")

# ANSI colors
COLOR_RESET = "\033[0m"
COLOR_BOLD = "\033[1m"
COLOR_GREEN = "\033[92m"
COLOR_CYAN = "\033[96m"
COLOR_YELLOW = "\033[93m"
COLOR_RED = "\033[91m"
COLOR_BLUE = "\033[94m"

def main():
    print(f"\n{COLOR_BOLD}{COLOR_CYAN}==============================================================")
    print("PRIMECARE ENTERPRISE GOVERNANCE FUNCTIONS ORCHESTRATOR")
    print(f"=============================================================={COLOR_RESET}")

    if not os.path.exists(DB_PATH):
        print(f"{COLOR_RED}[ERROR] Database not found at {DB_PATH}{COLOR_RESET}")
        sys.exit(1)

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    # Query all functions that have not passed
    cursor.execute("""
        SELECT * FROM governance_functions 
        WHERE last_run_status != 'passed' OR last_run_status IS NULL;
    """)
    functions = cursor.fetchall()

    if not functions:
        print(f"{COLOR_GREEN}[CLEAN] All governance functions are already in 'passed' state!{COLOR_RESET}")
        conn.close()
        return

    print(f"Discovered {len(functions)} governance functions requiring execution.\n")

    for idx, func in enumerate(functions, 1):
        func_id = func['id']
        code = func['function_code']
        name = func['function_name']
        ftype = func['function_type']
        cmd = func['run_command']
        success_cond = func['success_condition_text']
        target_table = func['stores_result_in_table']

        print(f"{COLOR_BOLD}{COLOR_BLUE}--------------------------------------------------------------")
        print(f"EXECUTING FUNCTION {idx} OF {len(functions)}: {name} ({code})")
        print(f"Command: {cmd}")
        print(f"--------------------------------------------------------------{COLOR_RESET}")

        # 1. Initialize run record in agent_function_runs
        cursor.execute("""
            INSERT INTO agent_function_runs 
            (function_id, agent_name, run_status, command_run)
            VALUES (?, 'AntigravityGovernanceOrchestrator', 'started', ?);
        """, (func_id, cmd))
        run_id = cursor.lastrowid
        conn.commit()

        # 2. Run the subprocess
        print(f"  {COLOR_CYAN}-> Launching process...{COLOR_RESET}")
        start_time = datetime.now()
        
        try:
            # We run the command within the project root directory
            result = subprocess.run(
                cmd,
                shell=True,
                cwd=PROJECT_ROOT,
                capture_output=True,
                text=True,
                timeout=120 # 2-minute limit
            )
            
            completed_time = datetime.now()
            duration = (completed_time - start_time).total_seconds()
            
            stdout_log = result.stdout or ""
            stderr_log = result.stderr or ""
            exit_code = result.returncode

            print(f"  Process finished in {duration:.2f} seconds with exit code {exit_code}")

        except Exception as e:
            completed_time = datetime.now()
            stdout_log = ""
            stderr_log = str(e)
            exit_code = -1
            print(f"  {COLOR_RED}[ERROR] Process execution failed: {e}{COLOR_RESET}")

        # 3. Determine success state
        run_passed = (exit_code == 0)
        status_str = "passed" if run_passed else "failed"

        # 4. Parse output and populate kpi_results if successful
        proof_data = {"exit_code": exit_code}
        proof_log_name = f"reports/governance/proof_{code}.log"
        proof_log_full_path = os.path.join(PROJECT_ROOT, proof_log_name)

        # Write output log to a dedicated proof file
        os.makedirs(os.path.dirname(proof_log_full_path), exist_ok=True)
        with open(proof_log_full_path, "w", encoding="utf-8") as pf:
            pf.write(f"=== GOVERNANCE RUN LOG: {code} ===\n")
            pf.write(f"Timestamp: {datetime.now().isoformat()}\n")
            pf.write(f"Command: {cmd}\n")
            pf.write(f"Exit Code: {exit_code}\n\n")
            pf.write("--- STDOUT ---\n")
            pf.write(stdout_log)
            pf.write("\n\n--- STDERR ---\n")
            pf.write(stderr_log)

        if run_passed:
            # Read output files generated by our Javascript runners
            if code == "test_public_urls" and os.path.exists(os.path.join(PROJECT_ROOT, "public_urls_result.json")):
                try:
                    with open(os.path.join(PROJECT_ROOT, "public_urls_result.json"), "r") as r_f:
                        res_json = json.load(r_f)
                        proof_data = res_json
                        for item in res_json['results']:
                            cursor.execute("""
                                INSERT INTO kpi_results (app_id, function_id, kpi_code, kpi_name, kpi_value, kpi_status, proof_json, proof_log_path)
                                VALUES (1, ?, 'public_url_status', ?, ?, 'passed', ?, ?);
                            """, (func_id, f"Public Page Deployed: {item['url']}", f"{item['latency_ms']} ms", json.dumps(item), proof_log_name))
                except Exception as ex:
                    print(f"  {COLOR_RED}[WARN] Failed to parse public urls json: {ex}{COLOR_RESET}")

            elif code == "test_api_endpoints" and os.path.exists(os.path.join(PROJECT_ROOT, "api_endpoints_result.json")):
                try:
                    with open(os.path.join(PROJECT_ROOT, "api_endpoints_result.json"), "r") as r_f:
                        res_json = json.load(r_f)
                        proof_data = res_json
                        for item in res_json['results']:
                            cursor.execute("""
                                INSERT INTO kpi_results (app_id, function_id, kpi_code, kpi_name, kpi_value, kpi_status, proof_json, proof_log_path)
                                VALUES (1, ?, 'api_health', ?, ?, 'passed', ?, ?);
                            """, (func_id, f"Direct API Route: [{item['method']}] {item['path']}", f"{item['latency_ms']} ms", json.dumps(item), proof_log_name))
                except Exception as ex:
                    print(f"  {COLOR_RED}[WARN] Failed to parse api endpoints json: {ex}{COLOR_RESET}")

            elif code == "verify_screen_runtime" and os.path.exists(os.path.join(PROJECT_ROOT, "screens_verification_result.json")):
                try:
                    with open(os.path.join(PROJECT_ROOT, "screens_verification_result.json"), "r") as r_f:
                        res_json = json.load(r_f)
                        proof_data = res_json
                        cursor.execute("""
                            INSERT INTO kpi_results (app_id, function_id, kpi_code, kpi_name, kpi_value, kpi_status, proof_json, proof_log_path)
                            VALUES (1, ?, 'screen_runtime_success', 'Physical Screen Codebase Widget Scans', ?, 'passed', ?, ?);
                        """, (func_id, f"Scanned {res_json['total_screens_scanned']} screens", json.dumps(res_json), proof_log_name))
                except Exception as ex:
                    print(f"  {COLOR_RED}[WARN] Failed to parse screens verification json: {ex}{COLOR_RESET}")

            elif code == "update_screen_kpis" and os.path.exists(os.path.join(PROJECT_ROOT, "update_kpis_result.json")):
                try:
                    with open(os.path.join(PROJECT_ROOT, "update_kpis_result.json"), "r") as r_f:
                        res_json = json.load(r_f)
                        proof_data = res_json
                        cursor.execute("""
                            INSERT INTO kpi_results (app_id, function_id, kpi_code, kpi_name, kpi_value, kpi_status, proof_json, proof_log_path)
                            VALUES (1, ?, 'page_load_time', 'Performance Metrics SLA updates', ?, 'passed', ?, ?);
                        """, (func_id, f"Updated {res_json['screens_updated']} screens", json.dumps(res_json), proof_log_name))
                except Exception as ex:
                    print(f"  {COLOR_RED}[WARN] Failed to parse update kpis json: {ex}{COLOR_RESET}")

        # 5. Save detailed logging to agent_function_runs
        cursor.execute("""
            UPDATE agent_function_runs
            SET 
                run_status = ?,
                output_log = ?,
                error_log = ?,
                completed_at = CURRENT_TIMESTAMP
            WHERE id = ?;
        """, (status_str, stdout_log, stderr_log, run_id))

        # 6. Update governance_functions with execution outcome
        cursor.execute("""
            UPDATE governance_functions
            SET 
                last_run_status = ?,
                last_run_at = CURRENT_TIMESTAMP,
                last_error = ?,
                proof_log_path = ?,
                proof_json = ?
            WHERE id = ?;
        """, (status_str, stderr_log if not run_passed else None, proof_log_name, json.dumps(proof_data), func_id))

        # 7. If failed, create implementation_tasks row
        if not run_passed:
            print(f"  {COLOR_RED}[FAIL] Governance function failed to pass! Creating implementation task...{COLOR_RESET}")
            task_title = f"Remediate stored function failure: {name}"
            task_desc = f"Stored function {code} failed with exit code {exit_code}. Details logged to {proof_log_name}."
            cursor.execute("""
                INSERT INTO implementation_tasks (app_id, task_title, task_description, priority, task_type, status)
                VALUES (1, ?, ?, 'high', 'agent_fix', 'pending');
            """, (task_title, task_desc))

        conn.commit()
        print(f"  {COLOR_GREEN}[OK] Function finished execution state set to: {status_str.upper()}{COLOR_RESET}")

    conn.close()
    print(f"\n{COLOR_BOLD}{COLOR_GREEN}==============================================================")
    print("SUCCESS: Governance Functions Orchestration Sweep Complete!")
    print(f"=============================================================={COLOR_RESET}")

if __name__ == '__main__':
    main()
