import os
import sys

# Ensure unicode safe terminal output on Windows console
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

# Resolve absolute paths
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GIT_HOOKS_DIR = os.path.join(PROJECT_ROOT, ".git", "hooks")
HOOK_PATH = os.path.join(GIT_HOOKS_DIR, "pre-push")

# ANSI Color Codes
COLOR_RESET = "\033[0m"
COLOR_BOLD = "\033[1m"
COLOR_CRITICAL = "\033[91m"  # Red
COLOR_LOW = "\033[92m"       # Green
COLOR_CYAN = "\033[96m"      # Cyan

def install_hook():
    print(f"\n{COLOR_BOLD}{COLOR_CYAN}======================================================================")
    print("INSTALLING PRIMECARE COMPLIANCE PRE-PUSH GATEWAY")
    print(f"======================================================================{COLOR_RESET}")

    if not os.path.exists(GIT_HOOKS_DIR):
        print(f"{COLOR_CRITICAL}[ERROR] Git hooks directory not found at {GIT_HOOKS_DIR}. Ensure you are in a git repository.{COLOR_RESET}")
        sys.exit(1)

    hook_content = """#!/bin/sh
# PrimeCare Zero-Drift compliance Pre-Push Hook gateway
# Auto-generated by Compliance Operator

echo "Executing pre-push compliance checks..."
python scripts/run_governance_guardian.py
RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo ""
  echo "❌ [COMPLIANCE ERROR] Git push blocked by Zero-Drift Compliance Gateway."
  echo "Resolve the architectural drifts or lint warnings listed above."
  echo "To bypass in an emergency, use: git push --no-verify"
  exit 1
fi

echo "✅ [COMPLIANCE SUCCESS] Zero-drift validation passed. Commencing remote push."
exit 0
"""

    try:
        # Write pre-push file
        with open(HOOK_PATH, "w", newline="\n", encoding="utf-8") as f:
            f.write(hook_content)

        # Make executable on Unix/macOS systems (safe to call on Windows too)
        if os.name != 'nt':
            import stat
            st = os.stat(HOOK_PATH)
            os.chmod(HOOK_PATH, st.st_mode | stat.S_IEXEC)

        print(f"{COLOR_LOW}[SUCCESS] Git pre-push hook successfully written to: {HOOK_PATH}{COLOR_RESET}")
        print(f"Zero-Drift verification checks will now run automatically before every 'git push'!")
        print(f"{COLOR_CYAN}======================================================================{COLOR_RESET}")
    except Exception as e:
        print(f"{COLOR_CRITICAL}[ERROR] Failed to install pre-push hook: {e}{COLOR_RESET}")
        sys.exit(1)

if __name__ == "__main__":
    install_hook()
