"""Generate source-bound, nonexecutable workflow descriptors in fixed packages.

This utility emits code for reviewing undefined contracts, never API handlers,
DTOs, permissions, database writes, or gateway registrations.
"""
import argparse
import hashlib
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REQUEST_PATH = 'docs/api/contract-factory/code-requests.json'
PLACEMENT_PATH = 'docs/api/contract-factory/code-placement.json'
TARGETS = (
    'packages/domain/src/generated/unimplemented-workflow-contracts.ts',
    'packages/flutter_core/lib/src/generated/unimplemented_workflow_contracts.dart',
    'cloudflare/workers/contracts/unimplemented-workflows.json',
)
MARKER = 'Generated by primecare-bulk-codegen.py; NONEXECUTABLE CONTRACT REVIEW.'


def digest(text):
    return hashlib.sha256(text.encode()).hexdigest()


def serialize(value):
    return json.dumps(value, sort_keys=True, separators=(',', ':'), ensure_ascii=True) + '\n'


def factory():
    spec = importlib.util.spec_from_file_location('contract_factory', ROOT / 'scripts/primecare-contract-factory.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def expected_requests(checklist, manifest, validate_sources=None):
    module = factory()
    bundle = module.build(checklist, manifest, validate_sources=validate_sources)['bundle.json']
    inputs = dict(bundle['inputHashes'])
    inputs['factorySource'] = digest((ROOT / 'scripts/primecare-contract-factory.py').read_text())
    inputs['generatorSource'] = digest(Path(__file__).read_text())
    records = []
    for item in bundle['contracts']:
        records.append({
            'requestKind': 'generate-unimplemented-contract-code',
            'api': item['api'], 'method': item['method'], 'path': item['route'],
            'declarationIds': item['declarationIds'], 'family': item['familyKey'],
            'missingSlots': [slot for slot in module.SLOTS if item['slots'][slot]['value'] is None],
            'sourceReferenceId': item['reviewSourceReferenceId'],
            'outputTargets': list(TARGETS), 'noActivation': True,
            'readiness': False, 'implementationCredits': 0, 'retirementCredits': 0,
        })
    return {'version': 1, 'generatedBy': MARKER, 'noActivation': True,
            'readiness': False, 'implementationCredits': 0, 'retirementCredits': 0,
            'sourceInputs': inputs, 'sourceHashes': bundle['sourceHashes'],
            'outputTargetAllowlist': list(TARGETS),
            'uniqueOperations': len(records), 'requests': records}


def validate_requests(submitted, expected):
    # Serialized comparison also rejects bool/int substitutions (True == 1 in Python).
    if not isinstance(submitted, dict) or serialize(submitted) != serialize(expected):
        raise ValueError('Bulk requests must exactly match source-bound identities, coverage, missing slots, safety flags, and output allowlist')


def dart_literal(value):
    # JSON literals are Dart-compatible except interpolation: escape every dollar.
    return json.dumps(value, ensure_ascii=True).replace('$', r'\$')


def build(checklist, manifest, requests=None, validate_sources=None):
    expected = expected_requests(checklist, manifest, validate_sources)
    if requests is not None:
        validate_requests(requests, expected)
    descriptors = [{key: row[key] for key in
                    ('api', 'method', 'path', 'declarationIds', 'family', 'missingSlots', 'noActivation', 'readiness')}
                   for row in expected['requests']]
    ts = '// ' + MARKER + '\n'
    ts += '''export interface UnimplementedWorkflowContract {
  readonly api: string;
  readonly method: string;
  readonly path: string;
  readonly declarationIds: readonly number[];
  readonly family: string;
  readonly missingSlots: readonly string[];
  readonly noActivation: true;
  readonly readiness: false;
}
export const unimplementedWorkflowContracts: readonly UnimplementedWorkflowContract[] = Object.freeze([
'''
    for row in descriptors:
        scalar = {k: v for k, v in row.items() if k not in ('declarationIds', 'missingSlots')}
        ts += '  Object.freeze<UnimplementedWorkflowContract>({ ...(' + serialize(scalar).strip() + ' as const), declarationIds: Object.freeze(' + serialize(row['declarationIds']).strip() + '), missingSlots: Object.freeze(' + serialize(row['missingSlots']).strip() + ') }),\n'
    ts += ''']);
export class MissingWorkflowContractError extends Error {
  readonly api: string;
  readonly missingSlots: readonly string[];
  constructor(api: string, missingSlots: readonly string[]) {
    super(`Workflow ${api} is not executable. Missing defined contract sections: ${missingSlots.join(', ')}. Governance approval and authorization are required.`);
    this.name = 'MissingWorkflowContractError';
    this.api = api;
    this.missingSlots = missingSlots;
  }
}
/** Always fails closed; this registry cannot confer executable readiness. */
export function requireExecutableWorkflow(method: string, path: string): never {
  const api = `${method} ${path}`;
  const descriptor = unimplementedWorkflowContracts.find((item) => item.api === api);
  if (!descriptor) throw new Error(`Unknown workflow ${api}; no executable authority exists in this review registry.`);
  throw new MissingWorkflowContractError(api, descriptor.missingSlots);
}
'''
    dart = '// ' + MARKER + '\n'
    dart += '''class UnimplementedWorkflowContract {
  final String api;
  final String method;
  final String path;
  final List<int> declarationIds;
  final String family;
  final List<String> missingSlots;
  final bool noActivation = true;
  final bool readiness = false;
  const UnimplementedWorkflowContract({required this.api, required this.method,
    required this.path, required this.declarationIds, required this.family,
    required this.missingSlots});
}
const List<UnimplementedWorkflowContract> unimplementedWorkflowContracts = [
'''
    for row in descriptors:
        dart += '  UnimplementedWorkflowContract(' + ', '.join(key + ': ' + (('[' + ', '.join(dart_literal(v) for v in value) + ']') if isinstance(value, list) else dart_literal(value)) for key, value in row.items() if key not in ('noActivation', 'readiness')) + '),\n'
    dart += '''];
/// Always fails closed; descriptor existence never authorizes execution.
Never requireExecutableWorkflow(String method, String path) {
  final api = '$method $path';
  for (final descriptor in unimplementedWorkflowContracts) {
    if (descriptor.api == api) {
      throw UnsupportedError('Workflow $api is not executable. Missing defined contract sections: ${descriptor.missingSlots.join(', ')}. Governance approval and authorization are required.');
    }
  }
  throw UnsupportedError('Unknown workflow $api; no executable authority exists in this review registry.');
}
'''
    review = {'generatedBy': MARKER, 'version': 1, 'noActivation': True,
              'readiness': False, 'gatewayRegistration': False,
              'uniqueOperations': len(descriptors), 'descriptors': descriptors}
    artifacts = {REQUEST_PATH: serialize(expected), TARGETS[0]: ts,
                 TARGETS[1]: dart, TARGETS[2]: serialize(review)}
    placement = {'version': 1, 'generatedBy': MARKER, 'noActivation': True,
                 'readiness': False, 'uniqueOperations': len(descriptors),
                 'implementationCredits': 0, 'retirementCredits': 0,
                 'runtimeHandlersGenerated': 0,
                 'sourceInputs': expected['sourceInputs'],
                 'files': [{'path': path, 'sha256': digest(content)} for path, content in artifacts.items()]}
    artifacts[PLACEMENT_PATH] = serialize(placement)
    return artifacts


def preflight(root, artifacts):
    root = root.resolve()
    for name in artifacts:
        path = root / name
        if path.is_symlink() or not path.resolve().is_relative_to(root):
            raise ValueError('Unsafe generated output: ' + name)
        for ancestor in path.parents:
            if ancestor == root:
                break
            if ancestor.is_symlink() or (ancestor.exists() and not ancestor.is_dir()):
                raise ValueError('Unsafe generated output ancestor: ' + name)
        if path.exists():
            if not path.is_file() or MARKER not in path.read_text():
                raise ValueError('Refusing to overwrite unknown output: ' + name)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--requests', type=Path)
    args = parser.parse_args()
    checklist = json.loads((ROOT / 'docs/api/api-delivery-checklist.json').read_text())
    manifest = json.loads((ROOT / 'docs/api/workflow-contract-reviews.json').read_text())
    submitted = json.loads(args.requests.read_text()) if args.requests else None
    artifacts = build(checklist, manifest, submitted, ROOT)
    preflight(ROOT, artifacts)
    if args.check:
        for name, content in artifacts.items():
            path = ROOT / name
            if not path.is_file() or path.read_text() != content:
                raise SystemExit('Stale bulk code artifact: ' + name)
    else:
        for name, content in artifacts.items():
            path = ROOT / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    placement = json.loads(artifacts[PLACEMENT_PATH])
    print(json.dumps({key: placement[key] for key in ('uniqueOperations', 'noActivation', 'implementationCredits', 'runtimeHandlersGenerated')}, sort_keys=True))


if __name__ == '__main__':
    main()
