name: scripts
description: Utility scripts for PrimeCare Platform
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.6.0
  sqlite3: ^2.4.6
  yaml: ^3.1.3
dev_dependencies:
  path: any
