"""Record a truthful execution-status contract; declarations are not probes."""
import hashlib,json,sqlite3
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
route='/v1/governance/api-service-status'
query={'type':'object','additionalProperties':False,'properties':{'limit':{'type':'integer','minimum':1,'maximum':100,'default':25},'offset':{'type':'integer','minimum':0,'maximum':100000,'default':0},'search':{'type':'string','maxLength':200},'app':{'type':'string','maxLength':40},'role':{'type':'string','maxLength':80},'screen':{'type':'string','maxLength':200}}}
response={'type':'object','required':['data','pagination','source'],'properties':{'data':{'type':'array','items':{'type':'object','required':['service','gatewayBound','declaredOperations','verificationStates','contractGaps','unmappedServiceLabels','evidenceScope','productionVerified','postgresVerified'],'properties':{'service':{'type':'string'},'gatewayBound':{'type':'boolean'},'declaredOperations':{'type':'integer','minimum':0},'verificationStates':{'type':'object','additionalProperties':{'type':'integer','minimum':0}},'contractGaps':{'type':'object','additionalProperties':{'type':'integer','minimum':0}},'unmappedServiceLabels':{'type':'array','items':{'type':['string','null']}},'evidenceScope':{'const':'registered_operation_metadata'},'postgresVerified':{'const':False},'productionVerified':{'const':False}}}},'pagination':{'type':'object','additionalProperties':False,'required':['limit','offset','total','hasMore'],'properties':{'limit':{'type':'integer','minimum':1,'maximum':100},'offset':{'type':'integer','minimum':0,'maximum':100000},'total':{'type':'integer','minimum':0},'hasMore':{'type':'boolean'}}},'source':{'type':'object','required':['catalogVersion','evidenceType'],'properties':{'catalogVersion':{'type':'string'},'evidenceType':{'const':'registered_governance'}}}}}
with sqlite3.connect(ROOT/'.agents/governance/governance.db') as db:
 sid,app=db.execute("SELECT s.id,a.id FROM screens s JOIN apps a ON a.app_code='gv' WHERE s.screen_code='api_health_dashboard'").fetchone()
 db.execute("INSERT INTO api_endpoints(app_id,endpoint_code,route_path,http_method,service_name,auth_required,implementation_status,permission_key,request_schema,response_schema,rate_limit_key,uses_pagination) SELECT ?,'GOVERNANCE_API_SERVICE_STATUS',?,'GET','governance',1,'implemented','runtime_catalog_permissions.can_view_inventory',?,?,'workspace.source',1 WHERE NOT EXISTS(SELECT 1 FROM api_endpoints WHERE route_path=? AND http_method='GET')",(app,route,json.dumps(query),json.dumps(response),route))
 aid=db.execute("SELECT id FROM api_endpoints WHERE route_path=? AND http_method='GET'",(route,)).fetchone()[0]
 db.execute('INSERT OR IGNORE INTO screen_api_links(screen_id,api_id,purpose) VALUES(?,?,?)',(sid,aid,'Distinguish recorded fixture evidence, blocked contracts and verification gaps; not live probes'))
 db.execute("INSERT OR REPLACE INTO governance_api_batches VALUES(?,?,207,'runtime_catalog_permissions.can_view_inventory','implemented','pending')",('GET '+route,sid))
catalog_path=ROOT/'cloudflare/workers/src/governance-api-registry.json'
catalog=json.loads(catalog_path.read_text());catalog['bindings']=[b for b in catalog['bindings'] if b['path']!='/api-service-status']+[{'path':'/api-service-status','screen':'api_health_dashboard','gate':'inventory','purpose':'Read per-service recorded coverage, retaining unknown labels as unassigned'}]
catalog['version']=hashlib.sha256(json.dumps({k:v for k,v in catalog.items() if k!='version'},sort_keys=True).encode()).hexdigest()[:16]
catalog_path.write_text(json.dumps(catalog,separators=(',',':'))+'\n')
spec={'openapi':'3.1.0','info':{'title':'PrimeCare API Execution Status','version':'1.0.0'},'paths':{route:{'get':{'operationId':'governance_api_service_status','summary':'Read recorded operation coverage across 12 gateway services','description':'Existing inventory authority, active explicit bearer session and tenant match required. Recorded governance evidence only. Active/healthy declarations do not prove executable APIs. Unit-tested records do not imply PostgreSQL or production verification. Filters apply to operation records before aggregation; pagination applies to the 12 service groups plus an unassigned group. PRISMA and unknown labels remain unassigned. Zero declarations are not completion evidence. Service labels do not prove deployed routes.','security':[{'bearerAuth':[]}],'parameters':[{'in':'query','name':k,'schema':v} for k,v in query['properties'].items()],'responses':{'200':{'description':'Recorded API execution status','content':{'application/json':{'schema':response}}},**{str(n):{'description':d} for n,d in [(400,'Invalid query'),(401,'No active session'),(403,'Inventory authority or tenant mismatch'),(405,'Read only'),(429,'Source limit'),(503,'Backend unavailable')]}}}}},'components':{'securitySchemes':{'bearerAuth':{'type':'http','scheme':'bearer'}}}}
(ROOT/'docs/api/api-service-status-batch-207.openapi.json').write_text(json.dumps(spec,indent=2)+'\n')
print('Registered API execution status; no readiness or role grants inferred.')
