"""Batches 101–105: expose registered contract gaps under existing inventory authority."""
import hashlib,json,sqlite3
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
queries={'limit':{'type':'integer','minimum':1,'maximum':100,'default':25},'offset':{'type':'integer','minimum':0,'maximum':100000,'default':0},'search':{'type':'string','maxLength':200},'app':{'type':'string','maxLength':40},'role':{'type':'string','maxLength':80},'screen':{'type':'string','maxLength':200}}
query={'type':'object','additionalProperties':False,'properties':queries}
fields=['permission','requestSchema','responseSchema','screenLink']
strings={'type':'array','items':{'type':'string'}}
record={'type':'object','additionalProperties':False,'required':['id','api','method','route','service','declaredImplementation','verificationState','batch','recordedUnitStatus','missingContractFields','screens','apps','roles','postgresVerified','productionVerified'],'properties':{'id':{'type':'integer'},'api':{'type':'string'},'method':{'type':'string'},'route':{'type':'string'},'service':{'type':['string','null']},'declaredImplementation':{'type':['string','null']},'verificationState':{'enum':['blocked','unit_fixtures_recorded','verification_pending']},'batch':{'type':['integer','null']},'recordedUnitStatus':{'type':'string'},'missingContractFields':{'type':'array','items':{'enum':fields}},'screens':strings,'apps':strings,'roles':strings,'postgresVerified':{'const':False},'productionVerified':{'const':False}}}
summary={'type':'object','additionalProperties':False,'required':['verificationState','operations','contractGaps','postgresVerified','productionVerified'],'properties':{'verificationState':record['properties']['verificationState'],'operations':{'type':'integer','minimum':0},'contractGaps':{'type':'object','additionalProperties':False,'required':fields,'properties':{key:{'type':'integer','minimum':0} for key in fields}},'postgresVerified':{'const':False},'productionVerified':{'const':False}}}
pagination={'type':'object','additionalProperties':False,'required':['limit','offset','total','hasMore'],'properties':{'limit':{'type':'integer','minimum':1,'maximum':100},'offset':{'type':'integer','minimum':0,'maximum':100000},'total':{'type':'integer','minimum':0},'hasMore':{'type':'boolean'}}}
source={'type':'object','additionalProperties':False,'required':['catalogVersion','evidenceType'],'properties':{'catalogVersion':{'type':'string'},'evidenceType':{'const':'registered_governance'}}}
definitions=[(101,'api-verification-summary','Count registered operations by recorded verification state after scope filters.'),(102,'api-missing-permissions','List operations without a registered permission key.'),(103,'api-missing-request-schemas','List operations without a parseable JSON object request schema.'),(104,'api-missing-response-schemas','List operations without a parseable JSON object response schema.'),(105,'api-unlinked-screens','List operations without a registered screen association.')]
paths={}
with sqlite3.connect(ROOT/'.agents/governance/governance.db') as db:
 sid,app=db.execute("SELECT s.id,a.id FROM screens s JOIN apps a ON a.app_code='gv' WHERE s.screen_code='api_health_dashboard'").fetchone()
 for batch,name,purpose in definitions:
  route='/v1/governance/'+name;code='GOVERNANCE_'+name.upper().replace('-','_')
  response={'type':'object','additionalProperties':False,'required':['data','pagination','source'],'properties':{'data':{'type':'array','items':summary if batch==101 else record},'pagination':pagination,'source':source}}
  db.execute("INSERT INTO api_endpoints(app_id,endpoint_code,route_path,http_method,service_name,auth_required,implementation_status,permission_key,request_schema,response_schema,rate_limit_key,uses_pagination) SELECT ?,?,?,'GET','governance',1,'implemented','runtime_catalog_permissions.can_view_inventory',?,?,'workspace.source',1 WHERE NOT EXISTS(SELECT 1 FROM api_endpoints WHERE route_path=? AND http_method='GET')",(app,code,route,json.dumps(query),json.dumps(response),route))
  aid=db.execute("SELECT id FROM api_endpoints WHERE route_path=? AND http_method='GET'",(route,)).fetchone()[0]
  db.execute('INSERT OR IGNORE INTO screen_api_links(screen_id,api_id,purpose) VALUES(?,?,?)',(sid,aid,purpose))
  db.execute("INSERT OR REPLACE INTO governance_api_batches VALUES(?,?,?,'runtime_catalog_permissions.can_view_inventory','implemented','pending')",('GET '+route,sid,batch))
  paths[route]={'get':{'operationId':code.lower(),'summary':purpose,'description':'Existing inventory authority, active explicit bearer and matching non-null tenant required. Static registered governance metadata only; this does not read tenant business records or infer permissions from reporting hierarchy. Permission gaps mean an absent registered key; schema gaps mean a missing or non-object JSON declaration, not full schema validation. Screen gaps mean no registered association, not proof of a missing UI. Recorded unit-fixture status is not database or production verification. For verification summary, exact app/role/screen and case-insensitive search filters apply to operation rows before aggregation, then limit/offset page the verification-state groups. Gap lists apply the gap predicate before filters and paging. Empty filters return empty data. No writes, new grants or readiness promotion.','security':[{'bearerAuth':[]}],'parameters':[{'in':'query','name':key,'schema':value} for key,value in queries.items()],'responses':{'200':{'description':'Registered contract gaps or scoped recorded verification groups','content':{'application/json':{'schema':response}}},**{str(status):{'description':description} for status,description in [(400,'Invalid query/body'),(401,'No active bearer'),(403,'Missing inventory authority or tenant mismatch'),(405,'Read only'),(429,'Source limit'),(503,'Backend unavailable')]}}}}
path=ROOT/'cloudflare/workers/src/governance-api-registry.json'
catalog=json.loads(path.read_text());names={'/'+name for _,name,_ in definitions};catalog['bindings']=[b for b in catalog['bindings'] if b['path'] not in names]+[{'path':'/'+name,'screen':'api_health_dashboard','gate':'inventory','purpose':purpose} for _,name,purpose in definitions]
catalog['version']=hashlib.sha256(json.dumps({k:v for k,v in catalog.items() if k!='version'},sort_keys=True).encode()).hexdigest()[:16];path.write_text(json.dumps(catalog,separators=(',',':'))+'\n')
(ROOT/'docs/api/contract-gaps-batches-101-105.openapi.json').write_text(json.dumps({'openapi':'3.1.0','info':{'title':'PrimeCare Registered API Contract Gaps','version':'1.0.0'},'paths':paths,'components':{'securitySchemes':{'bearerAuth':{'type':'http','scheme':'bearer'}}}},indent=2)+'\n')
print('Registered contract-gap API batches 101–105; existing inventory authority only.')
