#!/usr/bin/env node
/**
 * scaffold-feature.mjs — PrimeCare Feature Scaffold CLI
 *
 * Auto-generates new feature files following platform conventions:
 *   - Page component (TSX)
 *   - API route handler (TS)
 *   - Test stub (test.ts)
 *   - Registry entry snippet
 *   - Route entry snippet
 *
 * Usage:
 *   node scripts/scaffold-feature.mjs --name ShiftSwap --role coordinator --type page
 *   node scripts/scaffold-feature.mjs --name PayStub --role psw --type page
 *   node scripts/scaffold-feature.mjs --name MedicationLog --role rn --type full
 *
 * Options:
 *   --name    Feature name in PascalCase (e.g., ShiftSwap)
 *   --role    Target role (admin, psw, rn, coordinator, manager, client, staff)
 *   --type    What to generate: page | api | test | full (default: full)
 *   --dry     Dry run — show what would be created without writing files
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');

// ── Parse CLI Args ───────────────────────────────────────────────────────────
const args = process.argv.slice(2);
function getArg(name) {
    const idx = args.indexOf(`--${name}`);
    return idx !== -1 && args[idx + 1] ? args[idx + 1] : null;
}
const isDryRun = args.includes('--dry');

const name = getArg('name');
const role = getArg('role') || 'admin';
const type = getArg('type') || 'full';

if (!name) {
    console.error('❌ Error: --name is required\n');
    console.log('Usage: node scripts/scaffold-feature.mjs --name ShiftSwap --role coordinator --type full');
    console.log('\nOptions:');
    console.log('  --name    Feature name in PascalCase (required)');
    console.log('  --role    Target role: admin|psw|rn|coordinator|manager|client|staff');
    console.log('  --type    page|api|test|full (default: full)');
    console.log('  --dry     Show what would be created without writing');
    process.exit(1);
}

// ── Naming Conventions ───────────────────────────────────────────────────────
const pascal = name; // e.g., ShiftSwap
const kebab = pascal.replace(/([A-Z])/g, '-$1').toLowerCase().replace(/^-/, ''); // shift-swap
const snake = kebab.replace(/-/g, '_'); // shift_swap
const upper = snake.toUpperCase(); // SHIFT_SWAP
const camel = pascal.charAt(0).toLowerCase() + pascal.slice(1); // shiftSwap

// Determine route group from role
const ROLE_ROUTE_MAP = {
    admin: 'platform/admin',
    super_admin: 'platform/admin',
    scrum_master: 'platform/scrum-master',
    manager: 'tenancy/manager',
    regional_manager: 'tenancy/manager',
    coordinator: 'tenancy/coordinator',
    psw: 'tenancy/psw',
    rn: 'tenancy/rn',
    client: 'tenancy/client',
    staff: 'tenancy/staff',
    finance_director: 'platform/admin',
};
const routeGroup = ROLE_ROUTE_MAP[role] || 'tenancy/staff';
const roleTitle = role.charAt(0).toUpperCase() + role.slice(1);

// ── File Paths ───────────────────────────────────────────────────────────────
const WEB = path.join(ROOT, 'apps/web-admin/src');
const API = path.join(ROOT, 'apps/worker-api/src');

const pagePath = path.join(WEB, `app/routes/${routeGroup}/pages/${kebab}`);
const apiPath = path.join(API, `tenancy/${kebab}`);
const testPath = path.join(WEB, `test/${pascal}.test.ts`);

// ── Templates ────────────────────────────────────────────────────────────────

const pageTemplate = `import React from 'react';
import { useRegistryQuery } from '@/shared/hooks/useRegistryQuery';
import PageContainer from '@/shared/components/layout/PageContainer';

/**
 * ${pascal} — ${roleTitle} Feature Page
 * Generated by scaffold-feature CLI
 */
const ${pascal}: React.FC = () => {
    const { data, isLoading, error } = useRegistryQuery('/v1/${role}/${kebab}');

    if (isLoading) return <PageContainer title="${pascal}"><div className="skeleton-pulse" /></PageContainer>;
    if (error) return <PageContainer title="${pascal}"><p className="text-error">Failed to load: {error.message}</p></PageContainer>;

    return (
        <PageContainer title="${pascal}" data-cy="${kebab}-page">
            <div className="card">
                <h2>${pascal}</h2>
                <pre>{JSON.stringify(data, null, 2)}</pre>
            </div>
        </PageContainer>
    );
};

export default ${pascal};
`;

const indexTemplate = `// Re-export from identity file
export { default } from './${pascal}';
`;

const apiHandlerTemplate = `import { Hono } from 'hono';
import { Bindings, Variables } from '../../bindings';
import { requirePermission } from '../../_shared/middleware/rbac';

const app = new Hono<{ Bindings: Bindings; Variables: Variables }>();

/**
 * ${pascal} API Routes
 * Generated by scaffold-feature CLI
 */

// GET /v1/${role}/${kebab}
app.get('/', requirePermission('view_home'), async (c) => {
    const prisma = c.get('prisma');
    const tenantId = c.get('tenantId');

    try {
        // NOTE: Replace with actual query
        return c.json({
            data: [],
            meta: { tenantId, feature: '${kebab}', generatedAt: new Date().toISOString() }
        });
    } catch (err: any) {
        return c.json({ error: err.message || 'Internal Error' }, 500);
    }
});

// POST /v1/${role}/${kebab}
app.post('/', requirePermission('manage_schedule'), async (c) => {
    const body = await c.req.json();

    try {
        // NOTE: Implement create logic
        return c.json({ data: { id: 'new', ...body }, message: '${pascal} created' }, 201);
    } catch (err: any) {
        return c.json({ error: err.message || 'Internal Error' }, 500);
    }
});

export default app;
`;

const testTemplate = `import { describe, it, expect } from 'vitest';

/**
 * ${pascal} Unit Tests
 * Generated by scaffold-feature CLI
 */
describe('${pascal}', () => {
    it('should be defined as a feature', () => {
        // NOTE: Import and test the feature
        expect(true).toBe(true);
    });

    it('should have correct naming convention', () => {
        const featureName = '${pascal}';
        expect(featureName).toMatch(/^[A-Z]/); // PascalCase
    });
});
`;

const registrySnippet = `
// ── Add to ButtonRegistry.ts LINK_ENTRIES: ──
{ id: 'lnk-${role}-${kebab}', label: '${pascal.replace(/([A-Z])/g, ' $1').trim()}', role: '${role}', module: 'OPERATIONS', type: 'link', action: 'UI_NAVIGATION', path: RouteRegistry.${upper}_PATH || '/${role}/${kebab}', description: '${pascal} feature for ${roleTitle} role.' },

// ── Add to RouteRegistry (web-admin registry): ──
${upper}: '/${role}/${kebab}',

// ── Add to PermissionRegistry (if new permission needed): ──
// In Permission type: | 'manage_${snake}'
// In ROLE_PERMISSIONS[${role}]: 'manage_${snake}'

// ── Add route to ${routeGroup} Routes file: ──
// const ${pascal} = lazy(() => import('./pages/${kebab}'));
// <Route path="${kebab}" element={<${pascal} />} />
`;

// ── File Generation ──────────────────────────────────────────────────────────
const filesToCreate = [];

if (type === 'page' || type === 'full') {
    filesToCreate.push({ path: path.join(pagePath, `${pascal}.tsx`), content: pageTemplate });
    filesToCreate.push({ path: path.join(pagePath, 'index.tsx'), content: indexTemplate });
}

if (type === 'api' || type === 'full') {
    filesToCreate.push({ path: path.join(apiPath, 'index.ts'), content: apiHandlerTemplate });
}

if (type === 'test' || type === 'full') {
    filesToCreate.push({ path: testPath, content: testTemplate });
}

// ── Output ───────────────────────────────────────────────────────────────────
console.log(`\n🏗️  PrimeCare Feature Scaffold`);
console.log(`   Name:  ${pascal}`);
console.log(`   Role:  ${role}`);
console.log(`   Type:  ${type}`);
console.log(`   Route: /${routeGroup}/pages/${kebab}`);
console.log('');

if (isDryRun) {
    console.log('📋 DRY RUN — Would create:');
    filesToCreate.forEach(f => console.log(`   📄 ${path.relative(ROOT, f.path)}`));
    console.log('\n📌 Registry snippets to add manually:');
    console.log(registrySnippet);
    process.exit(0);
}

let created = 0;
for (const file of filesToCreate) {
    const dir = path.dirname(file.path);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
    if (fs.existsSync(file.path)) {
        console.log(`   ⚠️  SKIP (exists): ${path.relative(ROOT, file.path)}`);
    } else {
        fs.writeFileSync(file.path, file.content, 'utf-8');
        console.log(`   ✅ Created: ${path.relative(ROOT, file.path)}`);
        created++;
    }
}

console.log(`\n✨ Scaffold complete — ${created} file(s) created`);
console.log('\n📌 Next: Add registry entries manually:');
console.log(registrySnippet);
