import { TENANCY } from './tenancy';
import { PLATFORM } from './platform';

export const ApiRegistry = {
    AUTH: {
        LOGIN: API_VARS.API_V1_AUTH_LOGIN,
        REGISTER: API_VARS.API_V1_AUTH_REGISTER,
        FORGOT_PASSWORD: API_VARS.API_V1_AUTH_FORGOT_PASSWORD,
        RESET_PASSWORD: API_VARS.API_V1_AUTH_RESET_PASSWORD,
        LOGOUT: API_VARS.API_V1_AUTH_LOGOUT,
        SWITCH_ROLE: API_VARS.API_V1_AUTH_SWITCH_ROLE,
        REFRESH: API_VARS.API_V1_AUTH_REFRESH,
        IMPERSONATE: API_VARS.API_V1_AUTH_IMPERSONATE,
    },
    USER: {
        PROFILE: API_VARS.API_V1_USER_PROFILE,
        MESSAGING_THREADS: API_VARS.API_V1_USER_MESSAGING_THREADS,
        MESSAGING_SEND: (threadId: string) => `/v1/user/messaging/threads/${threadId}/messages`,
        TRAINING_CATALOG: API_VARS.API_V1_USER_TRAINING_CATALOG,
        TRAINING_PROGRESS: API_VARS.API_V1_USER_TRAINING_MY_PROGRESS,
    },
    PLATFORM,
    ...PLATFORM,
    TENANCY,

    // Legacy mapping
    MANAGER: TENANCY.MANAGER,
    CLIENT: TENANCY.CLIENT,
    PSW: TENANCY.PSW,
    RN: TENANCY.RN,
    STAFF: TENANCY.STAFF,
    COORDINATOR: TENANCY.COORDINATOR,
    SYSTEM: PLATFORM.SYSTEM,

    PUBLIC: {
        LEADS: API_VARS.API_V1_PUBLIC_LEADS,
        SERVICES: API_VARS.API_V1_PUBLIC_SERVICES,
        BLOG: API_VARS.API_V1_PUBLIC_BLOG,
    },
    SUPPORT: {
        CHAT_HISTORY: API_VARS.API_V1_SUPPORT_CHAT,
        TICKETS: API_VARS.API_V1_SUPPORT_TICKETS,
    }
} as const;
export * from './api-vars';
