import { ADMIN_DOMAIN_EXTENSIONS } from './admin-extensions';

export const PLATFORM = {
    ADMIN: {
        USERS: '/v1/admin/users',
        USERS_VERIFY: (id: string) => `/v1/admin/users/${id}/verify`,
        PSW_APPROVE: (id: string) => `/v1/admin/psw/approve/${id}`,
        STATS: '/v1/admin/stats',
        SERVICES: '/v1/admin/services',
        CAMPAIGNS: '/v1/admin/marketing/campaigns',
        LEADS: '/v1/admin/leads',
        LEADS_UPDATE: (id: string) => `/v1/admin/leads/${id}`,
        VISITS: '/v1/admin/visits',
        VISITS_ASSIGN: '/v1/admin/visits/assign',
        VISITS_UNASSIGNED: '/v1/admin/visits/unassigned',
        VISITS_UPDATE: (id: string) => `/v1/admin/visits/${id}`,
        INCIDENTS: '/v1/admin/incidents',
        CRISIS_MODE: '/v1/incidents/crisis-mode',
        TIMESHEETS: '/v1/admin/timesheets',
        INVOICES: '/v1/admin/invoices',
        CLIENTS: '/v1/admin/clients',
        SETTINGS_BUSINESS_MODEL: '/v1/admin/settings/business-model',
        SETTINGS_LOGO: '/v1/admin/settings/logo',
        SEARCH: '/v1/admin/search',
        REPORTS: '/v1/admin/reports/export',
        SETTINGS_COMMIT: '/v1/admin/settings/save',
        CONTENT_PUBLISH: '/v1/admin/content/publish',
        SEARCH_REINDEX: '/v1/admin/search/reindex',
        LEADS_CONVERT: (id: string) => `/v1/admin/leads/${id}/convert`,
        UI_OVERRIDE_COMMIT: '/v1/admin/registry/ui-override/commit',
        OPERATIONS: {
            CENTER: '/v1/admin/ops/center',
            REALTIME_CAPACITY: '/v1/admin/ops/capacity',
            REGION_MAPPING: '/v1/admin/ops/regions',
            SUPPLY_DEMAND: '/v1/admin/ops/supply-demand',
            LOGISTICS_HUB: '/v1/admin/ops/logistics',
            PREDICTIVE_ROUTOR: '/v1/admin/ops/predictive/dispatch',
            OPTIMIZE_LOGISTICS: '/v1/admin/ops/optimize',
        },
        RESELLER: {
            DASHBOARD: '/v1/admin/reseller/stats',
            FRANCHISES: '/v1/admin/reseller/franchises',
            PROVISION: '/v1/admin/reseller/provision',
            AGREEMENTS: '/v1/admin/reseller/agreements',
            SUSPEND: (id: string) => `/v1/admin/reseller/franchise/${id}/suspend`,
        },
        ERP: {
            INVENTORY: '/v1/admin/erp/inventory',
            SUPPLIERS: '/v1/admin/erp/suppliers',
            PURCHASE_ORDERS: '/v1/admin/erp/purchase-orders',
            STOCK_SYNC: '/v1/admin/erp/stock/sync',
        },
        TELEHEALTH: {
            DASHBOARD: '/v1/admin/telehealth/stats',
            SESSIONS: '/v1/admin/telehealth/sessions',
            CREATE_SESSION: '/v1/admin/telehealth/sessions/create',
            VITAL_SIGN_PUSH: '/v1/admin/telehealth/vitals/push',
        },
        RCM: {
            DASHBOARD: '/v1/admin/rcm/stats',
            CLAIMS: '/v1/admin/rcm/claims',
            SUBMIT_CLAIM: '/v1/admin/rcm/claims/submit',
            REVENUE_SYNC: '/v1/admin/rcm/revenue/sync',
        },
        PHARMACY: {
            DASHBOARD: '/v1/admin/pharmacy/stats',
            PRESCRIPTIONS: '/v1/admin/pharmacy/prescriptions',
            ORDER_DRUGS: '/v1/admin/pharmacy/orders',
            MAR_SYNC: '/v1/admin/pharmacy/mar/sync',
            VERIFY_BARCODE: '/v1/admin/pharmacy/verify-barcode',
        },
        REGIONAL: {
            PL_EXPORT: '/v1/admin/regional/fin/pl-export',
            AUDIT_REQUEST: '/v1/admin/regional/governance/audit-req',
        },
        REPORTING: {
            TRADING_ACCOUNT: '/v1/admin/financial/reports/trading-account',
            PROFIT_LOSS: '/v1/admin/financial/reports/p-and-l',
            BALANCE_SHEET: '/v1/admin/financial/reports/balance-sheet',
            DAILY_SUMMARY: '/v1/admin/financial/reports/daily-summary',
            RECONCILIATION_SUMMARY: '/v1/admin/financial/reports/reconciliation-summary',
            RECONCILE: '/v1/admin/financial/reconcile',
            AUTO_RECONCILE: '/v1/admin/financial/reconcile/auto',
            FORECAST: '/v1/admin/financial/reports/forecast',
            TAX_FILING: '/v1/admin/financial/reports/tax-filing',
            TAX_REMITTANCE: '/v1/admin/financial/tax-remittance',
        },
        // Domain extensions imported from sub-file
        ...ADMIN_DOMAIN_EXTENSIONS,
    },
    SCRUM_MASTER: {
        DASHBOARD: '/v1/scrum-master/stats',
        API_ENDPOINTS: '/v1/scrum-master/endpoints',
        ENV_AUDIT: '/v1/scrum-master/env-audit',
        AUTO_FIX: '/v1/scrum-master/auto-fix',
        LOG_FLUSH: '/v1/scrum-master/forensics/flush',
        DB_RESEED: '/v1/scrum-master/governance/reseed',
        UNIVERSAL_SWEEP: '/v1/scrum-master/registry/sweep',
        SWEEP_START: '/v1/scrum-master/registry/sweep',
        RESPONSE_BOT_SCAN: '/v1/scrum-master/registry/sweep',
        SECURITY_SCAN: '/v1/scrum-master/security/scan',
        AUDITS_HISTORY: '/v1/scrum-master/audits',
        REGISTRY_HEALTH: '/v1/scrum-master/registry/health',
        REGISTRY_SYNC: '/v1/scrum-master/registry/sync',
        DEBUG_HASH: '/v1/debug/hash',
    },
    SYSTEM: {
        NOTIFICATIONS: '/v1/system/notifications',
        MARK_READ: (id: string) => `/v1/system/notifications/${id}/read`,
        PLATFORM_STATS: '/v1/system/platform/stats',
        CAPACITY: '/v1/system/ops/capacity',
        REGIONS: '/v1/system/ops/regions',
        LOGISTICS_HUB: '/v1/system/ops/logistics',
    },
    SUPERUSER: {
        TENANTS: '/v1/superuser/tenants',
        AUDIT_LOGS: '/v1/superuser/audit-logs',
        GOVERNANCE: '/v1/superuser/governance',
        PLATFORM_HEALTH: '/v1/superuser/health/summary',
        SLA_COMPLIANCE: '/v1/superuser/sla/compliance',
        POLICY_ENGINE: '/v1/superuser/policies/engine',
        RISK_SCAN: '/v1/superuser/risk-surveillance',
    },
    AI: {
        INSIGHTS: '/v1/ai/insights',
        PREDICTIVE: '/v1/ai/predictive',
        CHURN: '/v1/ai/churn',
        OPTIMIZATION: '/v1/ai/optimization',
        VISIT_SENTIMENT: '/v1/ai/visit-sentiment',
        AI_OPTIMIZE: '/v1/ai/optimize-flow',
        AI_SENTIMENT_SCAN: '/v1/ai/sentiment-scan',
        INSIGHTS_REFRESH: '/v1/ai/insights/refresh',
        AUTOPILOT_ENGAGE: '/v1/ai/autopilot/engage',
    },
    SECURITY: {
        THREATS: '/v1/security/threats',
        SESSIONS: '/v1/security/sessions',
        PERMISSIONS: '/v1/security/permissions',
        AUDIT_DETAIL: (id: string) => `/v1/security/audits/${id}`,
        CRYPTO_HEALTH: '/v1/security/crypto-health',
        THREAT_DETECTION: '/v1/security/threat-detection',
        PLATFORM_AUDIT_LOGS: '/v1/security/platform-audit',
    },
    INTEROP: {
        FHIR_EXPORT: (id: string) => `/v1/interop/fhir/export/${id}`,
        FHIR_IMPORT: '/v1/interop/fhir/import',
        DID_VERIFY: '/v1/interop/did/verify',
        HEALTH_ID_GENERATE: '/v1/interop/did/generate',
    },
} as const;