export const TENANCY = {
    MANAGER: {
        DASHBOARD_KPI: '/v1/manager/dashboard/kpi',
        DASHBOARD_TODAY: '/v1/manager/dashboard/today',
        DASHBOARD_STATS: '/v1/manager/dashboard/stats',
        PERFORMANCE: '/v1/manager/performance/rankings',
        FINANCE: '/v1/manager/finance/pl',
        PAYROLL_AUDIT: '/v1/manager/finance/payroll-audit',
        BILLING_FINALIZE: '/v1/manager/finance/billing/finalize',
        TRAINING: '/v1/manager/training',
        SURVEYS: '/v1/manager/surveys',
        EVALUATIONS: '/v1/manager/evaluations',
        OPS_STATS: '/v1/manager/ops/stats',
        BRANCH_HEALTH: '/v1/manager/ops/branch-health',
        COMPLIANCE_SYNC: '/v1/manager/ops/compliance/sync',
        FEEDBACK_TRIAGE: (id: string) => `/v1/manager/ops/feedback/${id}/triage`,
        STAFF_ADD: '/v1/manager/staff/add',
        STAFF_EDIT: (id: string) => `/v1/manager/staff/${id}`,
        AUDIT_ATTENDANCE: '/v1/manager/audit/attendance',
        REVIEWS: '/v1/manager/reviews',
        REVIEWS_KPI: (pswId: string) => `/v1/manager/reviews/kpi/${pswId}`,
        TRAINING_ASSIGN: '/v1/manager/training/assign',
        TRAINING_COMPLIANCE: '/v1/manager/training/compliance',
        TRAINING_MODULES: '/v1/manager/training/modules',
    },
    CLIENT: {
        BOOKINGS: '/v1/client/bookings',
        BOOKING_REQUESTS: '/v1/client/bookings/requests',
        INVOICES: '/v1/client/invoices',
        SERVICES: '/v1/client/services',
        DASHBOARD_STATS: '/v1/client/dashboard/stats',
        CATALOG: '/v1/client/services/catalog',
        SUPPORT: '/v1/client/support/nursing-chat',
        CARE_TEAM: '/v1/client/team/roster',
        FEEDBACK_SUBMIT: '/v1/client/support/feedback',
        ENGAGEMENT_FEED: '/v1/client/engagement/feed',
        INVOICE_PAY: '/v1/client/engagement/pay-invoice',
        BOOKING_CANCEL: (id: string) => `/v1/client/bookings/${id}/cancel`,
        FAMILY_MEMBERS: '/v1/client/family/members',
        FAMILY_FEED: (clientId: string) => `/v1/client/family/feed/${clientId}`,
        FAMILY_MESSAGE: '/v1/client/family/message',
        FAMILY_HUB_OVERVIEW: '/v1/client/family/hub-overview',
        // Round 3 Extensions
        BILLING_INVOICES: '/v1/client/billing/invoices',
        BILLING_INVOICE_DETAIL: (id: string) => `/v1/client/billing/invoices/${id}`,
        BILLING_STATEMENT: '/v1/client/billing/statement',
        FEEDBACK_SURVEYS: '/v1/client/feedback/surveys',
        FEEDBACK_NEW: '/v1/client/feedback',
        FEEDBACK_ANALYTICS: '/v1/client/feedback/analytics',
        BOOKING_REQUEST_NEW: '/v1/client/bookings/request',
        BOOKING_REQUEST_LIST: '/v1/client/bookings/requests',
        CARE_TEAM_VIEW: '/v1/client/team',
        MEDICAL_SUMMARY: '/v1/client/profile/medical-summary',
    },
    PSW: {
        VISITS: '/v1/psw/schedule/visits',
        CHECK_IN: (id: string) => `/v1/psw/schedule/visits/${id}/check-in`,
        CHECK_OUT: (id: string) => `/v1/psw/schedule/visits/${id}/check-out`,
        PAYOUT_REQUEST: '/v1/psw/schedule/payouts/request',
        HANDOVER_SUBMIT: '/v1/psw/handover',
        AVAILABILITY_SYNC: '/v1/psw/availability/sync',
        WELLNESS_PULSE: '/v1/psw/wellness/pulse',
        PAYOUT_HISTORY: '/v1/psw/payouts/history',
        DAILY_ENTRY_SUBMIT: '/v1/psw/daily-entry',
        DASHBOARD_STATS: '/v1/psw/dashboard/stats',
        CREDENTIALS: '/v1/psw/credentials/vault',
        OFFERS: '/v1/psw/schedule/offers',
        OFFER_ACCEPT: (id: string) => `/v1/psw/schedule/offers/${id}/accept`,
        OFFER_DECLINE: (id: string) => `/v1/psw/schedule/offers/${id}/decline`,
        FEED: '/v1/psw/feed/social',
        INCIDENT_REPORT: '/v1/psw/incident/report',
        MILEAGE: '/v1/psw/mileage',
        MILEAGE_CALCULATE: '/v1/psw/mileage/calculate',
        MILEAGE_SUMMARY: '/v1/psw/mileage/summary',
        FLEET_HEARTBEAT: '/v1/psw/fleet/heartbeat',
        TRAINING_ASSIGNED: '/v1/psw/training/assigned',
        TRAINING_COMPLETE: (id: string) => `/v1/psw/training/${id}/complete`,
        // Round 3 Extensions
        SOS_TRIGGER: '/v1/psw/sos/trigger',
    },
    RN: {
        DASHBOARD_STATS: '/v1/rn/dashboard/stats',
        CARE_PLANS: '/v1/rn/clinical/care-plans',
        CARE_PLAN_REVIEW: (id: string) => `/v1/rn/clinical/care-plans/${id}/review`,
        DAILY_AUDIT_LIST: '/v1/rn/clinical/audit/list',
        DAILY_AUDIT_SIGN_OFF: '/v1/rn/clinical/audit/sign-off',
        DAILY_REVIEW: (id: string) => `/v1/rn/daily-review/${id}/review`,
        SUPERVISION_OVERVIEW: (pswId: string) => `/v1/rn/clinical/supervision/psw/${pswId}/overview`,
        CLINICAL_ASSESS: '/v1/rn/clinical/assessments',
        RECON_SYNC: '/v1/rn/clinical/recon',
        RN_SUPERVISION: '/v1/rn/clinical/supervision',
        SUPERVISION_ROSTER: '/v1/rn/clinical/supervision/roster',
        CAREPLAN_VERIFY: (id: string) => `/v1/rn/clinical/care-plans/${id}/verify`,
        MAR_SCHEDULE: (clientId: string) => `/v1/rn/mar/schedule/${clientId}`,
        MAR_ADMINISTER: '/v1/rn/mar/administer',
        MAR_HISTORY: (clientId: string) => `/v1/rn/mar/history/${clientId}`,
        MAR_PRN: '/v1/rn/mar/prn',
        MAR_REVIEW: '/v1/rn/mar/review',
        WOUND_ASSESSMENTS: (clientId: string) => `/v1/rn/wound-care/assessments/${clientId}`,
        WOUND_ASSESSMENT_CREATE: '/v1/rn/wound-care/assessments',
        WOUND_PROGRESS: (clientId: string) => `/v1/rn/wound-care/progress/${clientId}`,
        CHRONIC_DASHBOARD: (clientId: string) => `/v1/rn/wound-care/chronic/${clientId}`,
        RAI_TEMPLATES: '/v1/rn/assessments/templates',
        RAI_SUBMIT: '/v1/rn/assessments',
        RAI_HISTORY: (clientId: string) => `/v1/rn/assessments/client/${clientId}`,
        RAI_CAPS: (assessmentId: string) => `/v1/rn/assessments/caps/${assessmentId}`,
    },
    STAFF: {
        CUSTOMERS: '/v1/staff/customers',
        TICKETS: '/v1/staff/tickets',
        DASHBOARD_STATS: '/v1/staff/dashboard/stats',
        TASKS: '/v1/staff/tasks/grid',
        MESSAGES: '/v1/staff/messages/hub',
        INCIDENT_SUBMIT: '/v1/staff/ops/incidents/submit',
        COMPLIANCE_SCAN: '/v1/staff/ops/compliance/scan',
        COORDINATOR: {
            COVERAGE_ALERTS: '/v1/manager/coordinator/coverage-alerts',
        },
    },
    COORDINATOR: {
        MATCH_OVERRIDE: '/v1/coordinator/match/override',
        WAITLIST_SYNC: '/v1/coordinator/waitlist/sync',
        SOS_ACK: '/v1/coordinator/incident/ack',
        SOS_INCIDENTS: '/v1/coordinator/incidents',
        SOS_DISPATCH: '/v1/coordinator/sos-dispatch',
        DASHBOARD_STATS: '/v1/coordinator/dashboard/stats',
        DISPATCH_MAP: '/v1/coordinator/dispatch-map',
        MATCHING_RUN: '/v1/coordinator/matching/run',
        MASTER_SCHEDULE: '/v1/coordinator/schedule/master',
        SHIFT_BROADCAST: '/v1/coordinator/shifts/broadcast',
        SHIFT_TRIAGE: '/v1/coordinator/shifts/triage',
        GPS_PING: (id: string) => `/v1/coordinator/tracking/${id}/ping`,
        FLEET_POSITIONS: '/v1/coordinator/fleet/positions',
        FLEET_ETA: (visitId: string) => `/v1/coordinator/fleet/eta/${visitId}`,
        SHIFT_SWAP_REQUESTS: '/v1/coordinator/shift-swap/requests',
        SHIFT_SWAP_APPROVE: (visitId: string) => `/v1/coordinator/shift-swap/requests/${visitId}/approve`,
        // Round 3 Extensions
        SOS_ACTIVE: '/v1/coordinator/sos/active',
        SOS_ACKNOWLEDGE: (id: string) => `/v1/coordinator/sos/${id}/acknowledge`,
        WAITLIST: '/v1/coordinator/waitlist',
        WAITLIST_PRIORITIZE: (id: string) => `/v1/coordinator/waitlist/${id}/prioritize`,
    },
} as const;