export const TENANCY_ROUTES = {
    MANAGER: {
        HOME: '/tenancy/manager',
        MARKETING: '/tenancy/manager/marketing',
        OPERATIONS: '/tenancy/manager/operations',
        CLINICAL: '/tenancy/manager/clinical',
        REGIONAL_STATS: '/tenancy/manager/regional-stats',
        RECRUITING: '/tenancy/manager/recruiting',
        COMPLIANCE: '/tenancy/manager/compliance',
        TRAINING: '/tenancy/manager/training',
        DAILY_ENTRY: '/tenancy/manager/daily-entry',
        EVALUATIONS: '/tenancy/manager/evaluations',
        SERVICE_REVIEW: '/tenancy/manager/service-review',
        SURVEYS: '/tenancy/manager/surveys',
        PERFORMANCE: '/tenancy/manager/performance',
        FINANCE: '/tenancy/manager/finance',
        PAYROLL: '/tenancy/manager/payroll',
        TEAM: '/tenancy/manager/team',
        PORTFOLIO: '/tenancy/manager/portfolio',
        REVIEWS: '/tenancy/manager/reviews',
        REVIEW_KPI: (pswId: string) => `/tenancy/manager/reviews/kpi/${pswId}`,
        // Premium features
        GAMIFICATION: '/tenancy/manager/gamification',
        IOT_MONITORING: '/tenancy/manager/iot-monitoring',
        DOCUMENT_SIGNING: '/tenancy/manager/document-signing',
        SMS_HUB: '/tenancy/manager/sms-hub',
        PERFORMANCE_REVIEWS: '/tenancy/manager/performance-reviews',
        TRAINING_ACADEMY: '/tenancy/manager/training-academy',
    },
    STAFF: {
        HOME: '/tenancy/staff',
        CUSTOMERS: '/tenancy/staff/customers',
        TASKS: '/tenancy/staff/tasks',
        MESSAGES: '/tenancy/staff/messages',
        INCIDENTS: '/tenancy/staff/incidents',
        COMPLIANCE: '/tenancy/staff/compliance',
        ALLIED_HEALTH: '/tenancy/staff/allied-health',
    },
    PSW: {
        HOME: '/tenancy/psw',
        SCHEDULE: '/tenancy/psw/schedule',
        OPEN_SHIFTS: '/tenancy/psw/open-shifts',
        OFFERS: '/tenancy/psw/offers',
        AVAILABILITY: '/tenancy/psw/availability',
        EARNINGS: '/tenancy/psw/earnings',
        PAYOUTS: '/tenancy/psw/payouts',
        EXPENSES: '/tenancy/psw/expenses',
        SHIFT_CONFIRMATION: '/tenancy/psw/shift-confirmation',
        CREDENTIALS: '/tenancy/psw/credentials',
        FEED: '/tenancy/psw/feed',
        LIVE_VISIT: '/tenancy/psw/live-visit',
        CHECK_IN: '/tenancy/psw/check-in/:id',
        HANDOVER: '/tenancy/psw/handover',
        MILEAGE: '/tenancy/psw/mileage',
        TRAINING: '/tenancy/psw/training',
        GUIDE: '/tenancy/psw/guide',
    },
    RN: {
        HOME: '/tenancy/rn',
        CARE_PLANS: '/tenancy/rn/care-plans',
        DAILY_AUDIT: '/tenancy/rn/entry-verify',
        SUPERVISION: '/tenancy/rn/supervision',
        SUPERVISION_DETAIL: (pswId: string) => `/tenancy/rn/supervision/psw/${pswId}`,
        ASSESSMENTS: '/tenancy/rn/assessments',
        RECONCILIATION: '/tenancy/rn/reconciliation',
        MAR: '/tenancy/rn/mar',
        MAR_CLIENT: (clientId: string) => `/tenancy/rn/mar/${clientId}`,
        WOUND_CARE: '/tenancy/rn/wound-care',
        WOUND_CARE_CLIENT: (clientId: string) => `/tenancy/rn/wound-care/${clientId}`,
        RAI_ASSESSMENTS: '/tenancy/rn/rai-assessments',
        RAI_ASSESSMENT_DETAIL: (id: string) => `/tenancy/rn/rai-assessments/${id}`,
        CHECK_IN: (id: string) => `/tenancy/rn/check-in/${id}`,
    },
    COORDINATOR: {
        HOME: '/tenancy/coordinator',
        HUB: '/tenancy/coordinator/hub',
        MAP: '/tenancy/coordinator/dispatch-map',
        WAITLIST: '/tenancy/coordinator/waitlist',
        SOS: '/tenancy/coordinator/sos-center',
        SCHEDULE: '/tenancy/coordinator/schedule',
        SOS_HUB: '/coordinator/sos',
        FLEET: '/tenancy/coordinator/fleet',
        SHIFT_SWAP: '/tenancy/coordinator/shift-swap',
    },
    CLIENT: {
        HOME: '/tenancy/client',
        BOOKINGS: '/tenancy/client/bookings',
        BILLING: '/tenancy/client/billing',
        FEEDBACK: '/tenancy/client/feedback',
        REQUEST_BOOKING: '/tenancy/client/request-booking',
        SERVICES: '/tenancy/client/services',
        SUPPORT: '/tenancy/client/support',
        TEAM: '/tenancy/client/team',
        FEEDBACK_LOOP: '/tenancy/client/feedback-loop',
        FAMILY_HUB: '/tenancy/client/family-hub',
        FAMILY_PORTAL: '/tenancy/client/family-portal',
        BOOKING_REQUEST_NEW: '/tenancy/client/request-booking',
        MEDICAL_SUMMARY: '/tenancy/client/medical-summary',
    },
    ALLIED: {
        HOME: '/tenancy/allied-health',
        TREATMENTS: '/tenancy/allied-health/treatments',
        SIGN_OFF: '/tenancy/allied-health/sign-off',
    },
    CARE_PLANS: '/care-plans',
} as const;
