import '../../primecare_adapters.dart';

/// Central provider that resolves the appropriate hydrated adapter for a given PrimeCareForm.
/// This allows the UI to simply request a form type and receive the bound data.
final primecareFormProvider = Provider.family<dynamic, PrimeCareForm>((
  ref,
  form,
) {
  // 1. Registry-Driven Lookup (High Fidelity Source of Truth)
  // We prioritize the Governance ScreenRegistry over the manual switch-case.
  final screen = ScreenRegistry.getScreenByForm(form);
  if (screen != null && screen.provider != null) {
    return screen.provider;
  }

  // 2. Legacy Switch-Case Fallback (Technical Debt Layer)
  // These categories represent specialized telemetry that hasn't yet migrated
  // to a 1:1 registry mapping but shares a common adapter.
  switch (form) {
    // 2.1 Specialized Infrastructure Monitoring
    case PrimeCareForm.infrastructureHealth:
    case PrimeCareForm.systemInfrastructure:
    case PrimeCareForm.itSecurityDashboard:
    case PrimeCareForm.apiMonitoring:
    case PrimeCareForm.systemStatus:
      return ref.watch(infrastructureMonitoringAdapterProvider(form));

    // 2.2 Specialized Operational Insights
    case PrimeCareForm.operationalInsights:
    case PrimeCareForm.strategicGrowth:
    case PrimeCareForm.revenueAnalysis:
    case PrimeCareForm.operationalEfficiency:
      return ref.watch(operationalInsightAdapterProvider(form));

    // 2.3 Catch-All / Modern Default Fallback
    // For any form not explicitly handled above, we use the generic adapter
    // which resolves based on the form's unique route string.
        case PrimeCareForm.addFranchiseLeadForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.adjustFontSize:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.adminDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.adminLayout:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.adminReconciliationDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.alignCenterIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.alignJustifyIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.alignLeftIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.alignRightIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.app:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.approveExpenseReimbursementForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.approveFranchiseDisclosureForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.approveLeaveRequestForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.approveMedicationRefillForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.approvePayrollRunForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.approveRealEstateForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.approveSystemAccessForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.arrowLeftIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.assignCarePodForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.assignLeadForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.assignTrainingModuleForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.auditComplianceForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.auditGlobalEducationForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.auditOverrideForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.auditPayrollDiscrepancyForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.auditRoyaltyPaymentForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.auditSecurityComplianceForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.auditSystemLogsForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.authContext:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.authLayout:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.authPagesMessageSection:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.authSplitLayout:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.authentication:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.authenticator:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.awsSignInTab:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.awsSignUpTab:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.banIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.baseForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.trainingDirectorCertificate:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.trainingHub:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.incidentReports:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.complianceAudit:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.clinicalIntelligence:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.financialSnapshot:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.billingLedger:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.messaging:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.userManagement:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.franchiseOperations:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.marketingCampaigns:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.salesPipeline:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.itSupport:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.marketExpansion:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.ebitdaAnalysis:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.cashOnHand:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.netMarginAnalysis:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.operationalBurn:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.taxOptimization:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.arAlert:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.capitalEfficiency:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.burnRateAnalysis:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.operationalVolume:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.uptimeMonitor:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.latencyAnalysis:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.errorRate:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.securityPosture:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.devOpsVelocity:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.staffingMatrix:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.protocolCompliance:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.incidentTrend:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.cashFlow:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.ledgerCommand:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.roiAnalysis:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.cacVolatility:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.businessOverview:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.financialPerformance:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.complianceStatus:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.appointment:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.carePlan:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.ticket:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.responseTime:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.satisfactionScore:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.slaBreachRisk:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.leadManagement:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.pendingVerification:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.recentAudit:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.featureIntake:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.platformMetrics:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.billingAdminDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.blockQuoteIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.boldIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.button:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.carePlanEvaluationForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.ceoDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.cfoDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.chevronDownIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.clientDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.clientLayout:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.clinicDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.clinicalDirectorDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.nurseDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.rnDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.rpnDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.rmtDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.physicianDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.pswDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.careGiverDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.therapistDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.socialWorkerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.familyMemberDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.receptionistDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.schedulerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.intakeCoordinatorDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.qualityAssuranceDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.qaDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.closeIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.code2Icon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.codeBlockIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.communityOutreachDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.complianceManagerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.configurator:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.cooDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.cornerDownLeftIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.createAdPlacementForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.createCannedResponseForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.createCustomInvoiceForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.createRevenueReportForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.createSupplyOrderForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.ctoDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.systemVerificationDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.systemHealthDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.courseArchitectTool:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.architecturalPlanningDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.customerSupportDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.dailyVitalsCardForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.dataTable:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.dataTableTopToolbar:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.demoContent:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.demoDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.demoFrame:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.demoLayoutFooterContent:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.demoSidebarContent:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.disciplineLogForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.documentationButton:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.dragAssignWidget:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.dropdownMenu:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.dynamicRoleDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.trainingDirectorDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.infectionControlDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.error401PageView:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.error404PageView:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.errorBoundary:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.etaTrackerWidget:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.exampleView:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.externalLinkIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.familyDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.familyMember:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.financeDirectorDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.firebaseAuthContext:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.firebaseSignInForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.firebaseSignInTab:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.firebaseSignUpForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.firebaseSignUpTab:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.footerLayout1:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.footerLayout2:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.footerLayout3:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.footerTheme:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.framedDemo:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.franchiseDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.franchiseOnboardingChecklistForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.franchiseOwnerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.franchiseReconciliationDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.franchiseRefundsDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.franchiseReportsDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.franchiseSalesManagerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.marketingManagerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fullScreenToggle:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseAuthContext:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseAuthorization:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseAwaitRender:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseCountdown:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseDialog:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseExample:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseHighlight:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseLayout:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseLayoutConfig:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseLayoutConfigs:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.systemDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseLayoutSettingsContext:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseLoading:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseNavBadge:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseNavHorizontalCollapse:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseNavHorizontalGroup:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseNavHorizontalItem:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseNavHorizontalLayout1:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseNavHorizontalLink:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseNavItem:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseNavVerticalCollapse:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseNavVerticalGroup:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseNavVerticalItem:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseNavVerticalItemBase:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseNavVerticalLayout1:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseNavVerticalLayout2:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseNavVerticalLink:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseNavVerticalTab:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseNavigation:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fusePageCarded:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fusePageCardedHeader:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fusePageCardedSidebar:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fusePageCardedSidebarContent:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fusePageSimple:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fusePageSimpleHeader:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fusePageSimpleSidebar:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fusePageSimpleSidebarContent:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseScrollbars:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseSearch:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseSettings:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseSettingsContext:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseSettingsViewerDialog:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseShortcuts:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseSidePanel:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseSplash:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseSuspense:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseSvgIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseTheme:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseThemeHooks:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.fuseThemeSelector:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.generalManagerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.goToDocBox:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.governanceComplianceDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.greetingHeaderWidget:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.guestDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.headOfBusDevDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.headOfMarketingDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.headingButton:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.headingDropdownMenu:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.headingFiveIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.headingFourIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.headingIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.headingOneIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.headingSixIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.headingThreeIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.headingTwoIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.highlightPopover:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.highlighterIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.hrHiringDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.hrDirectorDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.hrManagerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.cxDirectorDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.itAdminDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.governanceMonitorDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.hrManager:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.imagePlusIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.imageUploadButton:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.imageUploadNode:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.genericDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.indexForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.initializeFirebase:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.intakeCoordinator:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.intakeDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.italicIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.jwSignUpTab:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.jwtAuthContext:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.jwtSignInForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.jwtSignInTab:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.jwtSignUpForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.languageSwitcher:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.layout1:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.layout2:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.layout3:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.leaveRequestForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.leftSideLayout1:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.leftSideLayout2:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.leftSideLayout3:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.lightDarkModeToggle:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.link:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.linkIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.linkPopover:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.listButton:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.listDropdownMenu:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.listIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.listOrderedIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.listTodoIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.localMarketing:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.localMarketingManagerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.logClinicalIncidentForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.logEmployeeGrievanceForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.logFranchiseeVettingCallForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.logInfectionControlForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.logInventorySpoilageForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.logPettyCashForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.logo:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.mainProjectSelection:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.markButton:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.masterAppShell:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.masterDashboardPage:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.masterDetailLayout:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.masterLayout:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.mockApi:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.moodSliderWidget:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.moonStarIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarLayout2:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarLayout3:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarMobileLayout2:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarMobileLayout3:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarPinToggleButton:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarStyle1:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarStyle1Content:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarStyle2:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarStyle2Content:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarTheme:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarToggleButton:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarToggleFab:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarToggleFabLayout1:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarToggleFabLayout2:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarWrapperLayout1:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarWrapperLayout2:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarWrapperLayout3:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navigation:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navigationSearch:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navigationShortcuts:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.newEmployeeOnboardingForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.nodeButton:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.numberFormController:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.nurtureLocalizedLeadForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.operationsManagerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.overrideGlobalScheduleForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.ownerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.pageBreadcrumb:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.pageTitle:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.palettePreview:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.paletteSelector:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.partnershipManagerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.patientDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.patientIntakeForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.popover:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.poweredByLinks:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.primecareResponsiveShell:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.providerLayout:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.purchaseButton:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.qualityAssurance:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.quickPanel:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.quickPanelToggleButton:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.radioFormController:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.redo2Icon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.regionalBdmDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.regionalManagerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.regionalManagerOntarioDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.regionalManagerUsaDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.registerCorporateRiskForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.requestShiftAdjustmentForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.reviewCarePlanForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.reviewClinicalIncidentForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.reviewFleetMaintenanceForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.reviewLeadConversionForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.reviewLegalContractForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.reviewMarketShareForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.reviewMedicationInventoryForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.reviewMonthlyExpensesForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.reviewOnboardingStatusForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.reviewPeerPerformanceForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.reviewVendorContractsForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.rightSideLayout1:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.rightSideLayout2:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.rightSideLayout3:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.rolePermissionsForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.route:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.routesConfig:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.scheduleClinicalAuditForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.scheduleFacilityMaintenanceForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.scheduleInterviewForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.scheduleOpenHouseForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.schemePreview:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.sectionPreview:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.separator:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.settingsPanel:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.signInPageForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.signInPageTitle:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.signInPageView:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.signOutPageTitle:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.signOutPageView:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.signUpPageTitle:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.signUpPageView:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.simpleEditor:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.singleInputForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.slideToClockInWidget:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.spacer:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.strikeIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.submitAdlChecklistForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.submitDailyCensusForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.submitExitInterviewForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.submitHealthcareClaimForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.submitMarketingBudgetForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.subscriptIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.sunIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.superscriptIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.switchFormController:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.territoryExpansionDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.territorySalesDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.territoryExpansionManagerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.territorySales:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.territorySalesManagerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.textAlignButton:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.themePreview:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.themeToggle:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.themesPanel:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.titleReferenceLink:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.toolbar:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.toolbarLayout1:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.toolbarLayout2:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.toolbarLayout3:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.toolbarTheme:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.tooltip:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.trainingCoordinatorDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.trashIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.underlineIcon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.undo2Icon:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.undoRedoButton:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.useAuth:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.useAwsAuth:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.useFirebaseAuth:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.useFuseDialogContext:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.useFuseLayoutSettings:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.useFuseRouteParameter:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.useFuseSettings:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.useJwtAuth:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.useLocalStorage:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.useNavigate:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.useNavigationItems:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.usePathname:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.useUser:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.userMenu:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.verifyCertificateForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.withRouter:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.withUser:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.ceoEnterpriseOverview:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.ceoRevenueSummary:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.cooOperationsOverview:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.cfoFinancialOverview:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.ctoSystemHealth:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.certifications:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.onboardingWizard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.invoiceManagement:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.referralManagement:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.intakeAssessment:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.qualityMetrics:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.volunteerCoordinatorDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.scrumMasterDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.healthDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.securityDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.infrastructureGovernanceMonitor:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.infrastructureAndAdminSystemInfrastructureOverview:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.infrastructureAndAdminConfiguratorHub:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.infrastructureAndAdminAuxiliaryPlatformViewI:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.error401:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.error404:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.signIn:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.signOut:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.signUp:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.architecturalPlanning:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.courseArchitectDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.dynamicScreenDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.featuresExplorer:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.createUserForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.passwordResetForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.createShiftForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.demoLayoutFooter:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarV2:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.navbarV3:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.toolbarV1:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.toolbarV2:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.systemMetrics:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.businessDevelopmentRegionDomainRegionalView:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.supportIntakeCoordinatorDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.intakeCoordinatorReferrals:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.intakeCoordinatorAssessments:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.clinicalDirectorQualityMetrics:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.officesRolesPatientDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.officesRolesPartnershipManagerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.officesRolesOwnerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.officesRolesFranchiseOwnerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.officesRolesLocalMarketingManagerDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.chiropractorDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.physiotherapistDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.trainingDirectorCertificateDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.clinicalDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.clinicalDirectorLabels:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.clinicalLabels:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.shareholderIntelligenceDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.corporateGovernanceDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.financeLedger:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.enterpriseOverview:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.strategicKpis:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.financialOverview:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.operationsBoard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.franchiseOwnerFinancialSnapshot:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.hrHiringOnboarding:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.adminInvoices:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.adminSettings:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.architectureGovernance:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.logisticsHub:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.operationalStaffingDirector:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.operationalRegionalManager:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.complianceHub:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.verificationHub:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.regionDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.supportDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.liveDispatchMap:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.officesRolesSupportTeamDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.officesRolesCustomerSupportDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfAddFranchiseLeadForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfApproveExpenseReimbursementForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfApproveFranchiseDisclosureForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfApproveLeaveRequestForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfApproveMedicationRefillForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfApprovePayrollRunForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfApproveRealEstateForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfApproveSystemAccessForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfAssignCarePodForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfAssignLeadForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfAssignTrainingModuleForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfAuditComplianceForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfAuditGlobalEducationForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfAuditOverrideForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfAuditPayrollDiscrepancyForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfAuditRoyaltyPaymentForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfAuditSecurityComplianceForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfAuditSystemLogsForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfCarePlanEvaluationForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfCreateAdPlacementForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfCreateCannedResponseForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfCreateCustomInvoiceForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfCreateRevenueReportForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfCreateSupplyOrderForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfDailyVitalsCardForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfDisciplineLogForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfFranchiseOnboardingChecklistForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfLeaveRequestForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfLogClinicalIncidentForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfLogEmployeeGrievanceForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfLogFranchiseeVettingCallForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfLogInfectionControlForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfLogInventorySpoilageForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfLogPettyCashForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfNewEmployeeOnboardingForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfNurtureLocalizedLeadForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfOverrideGlobalScheduleForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfPatientIntakeForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfRegisterCorporateRiskForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfRequestShiftAdjustmentForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfReviewCarePlanForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfReviewClinicalIncidentForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfReviewFleetMaintenanceForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfReviewLeadConversionForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfReviewLegalContractForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfReviewMarketShareForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfReviewMedicationInventoryForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfReviewMonthlyExpensesForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfReviewOnboardingStatusForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfReviewPeerPerformanceForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfReviewVendorContractsForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfScheduleClinicalAuditForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfScheduleFacilityMaintenanceForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfScheduleInterviewForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfScheduleOpenHouseForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfSubmitAdlChecklistForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfSubmitDailyCensusForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfSubmitExitInterviewForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfSubmitHealthcareClaimForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfSubmitMarketingBudgetForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.wfVerifyCertificateForm:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.administrativeForms:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.clinicalForms:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.commonForms:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.crmForms:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.financialForms:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.hrForms:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.globalSettings:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.growthPipeline:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.regionPerformance:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.leadershipReports:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.revenueTracker:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.profitability:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.taxRemittance:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.branchOperations:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.schedulingHealth:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.incidentReviews:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.platformUsage:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.auditLogs:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.cases:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.policyManager:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.audits:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.riskRegister:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.curriculumHub:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.skillMatrix:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.branchComparison:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.intakePipeline:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.referrals:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.pendingAssessments:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.billingConsole:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.invoices:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.marketingHub:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.campaignAnalytics:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.shiftTracker:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.messages:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.familyHome:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.billing:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.messagingHub:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.documentVault:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.notificationCenter:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.shareholderDashboard:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.commonDashboardLabels:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.regionalManagerLabels:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.commandCenterLabels:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.ctoDashboardLabels:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.ceoDashboardLabels:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.cfoDashboardLabels:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.supportDashboardLabels:
      return genericDashboardAdapterProvider(form);
    case PrimeCareForm.marketingDashboardLabels:
      return genericDashboardAdapterProvider(form);
default:
      return ref.watch(genericDashboardAdapterProvider(form));
  }
});