default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "Runner")
    upload_to_testflight
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    build_app(scheme: "Runner")
    upload_to_app_store(
      force: true,
      submit_for_review: true,
      automatic_release: true
    )
  end
end
