import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'ast_patch_engine.dart';
import 'registry_integrity_service.dart';
import 'cross_subsystem_auditor.dart';
import '../models/governance_issue.dart';
import '../../core/governance/governance_provider.dart';

class RemediationResult {
  final int issuesDetected;
  final int issuesResolved;
  final List<String> resolutionLogs;

  RemediationResult({
    required this.issuesDetected,
    required this.issuesResolved,
    this.resolutionLogs = const [],
  });
}

class GovernanceRemediationEngine {
  final Ref ref;
  final ASTPatchEngine _patchEngine;
  final String projectRoot;

  GovernanceRemediationEngine(this.ref, {this.projectRoot = '.'})
    : _patchEngine = ASTPatchEngine(projectRoot);

  /// Performs a platform-wide scan and automated remediation of all registries.
  Future<RemediationResult> executeGlobalRemediation() async {
    final state = ref.read(governanceProvider);
    final allScreens = state.allScreens;

    int resolvedCount = 0;
    final logs = <String>[];

    // 1. Core Registry Integrity Scan
    final issues = RegistryIntegrityService.inspect(allScreens);
    logs.add('Core Scan: ${issues.length} issues detected.');

    for (final issue in issues) {
      bool success = false;

      switch (issue.message) {
        case String msg when msg.contains('does not match metadata ID'):
          success = await _fixIdMismatch(issue);
          break;
        case String msg when msg.contains('Duplicate route path detected'):
          success = await _fixDuplicateRoute(issue);
          break;
        case String msg when msg.contains('0 story points'):
          success = await _fixZeroWeight(issue);
          break;
      }

      if (success) {
        resolvedCount++;
        logs.add('[RESOLVED] ${issue.screenId}: ${issue.message}');
      }
    }

    // 2. Cross-Subsystem Parity Scan
    final crossSubsystemCount = await _remediateCrossSubsystemDrift(logs);
    resolvedCount += crossSubsystemCount;

    // Blueprint Drift Remediation disabled since feature is removed.

    return RemediationResult(
      issuesDetected: issues.length + crossSubsystemCount,
      issuesResolved: resolvedCount,
      resolutionLogs: logs,
    );
  }

  Future<bool> _fixIdMismatch(GovernanceIssue issue) async {
    return await _patchEngine.updateRegistryMetadata(
      issue.screenId,
      {'id': issue.screenId},
      registryPath:
          _getRegistryPathForScreen(issue.screenId) ??
          'apps/primecare_governance/lib/core/governance/screen_registry.dart',
    );
  }

  Future<bool> _fixDuplicateRoute(GovernanceIssue issue) async {
    final newRoute =
        '${issue.routePath}_alt_${issue.screenId.hashCode.toString().substring(0, 4)}';
    final registryPath = _getRegistryPathForScreen(issue.screenId);
    if (registryPath == null) return false;

    return await _patchEngine.updateRegistryMetadata(issue.screenId, {
      'routePath': newRoute,
    }, registryPath: registryPath);
  }

  Future<bool> _fixZeroWeight(GovernanceIssue issue) async {
    return await _patchEngine.updateScreenMetadata(
      issue.screenId,
      storyPoints: 1,
    );
  }



  Future<int> _remediateCrossSubsystemDrift(List<String> logs) async {
    int count = 0;
    final auditor = CrossSubsystemAuditor(projectRoot: projectRoot);
    final formIssues = await auditor.auditFormProviderParity();
    final screenIssues = await auditor.auditScreenRegistryParity();

    final subsystemIssues = [...formIssues, ...screenIssues];

    for (final issue in subsystemIssues) {
      if (issue.autoRemediable) {
        if (issue.metadata['type'] == 'missing_form_provider') {
          final formName = issue.metadata['form'] as String;
          final targetPath = issue.metadata['targetPath'] as String;

          final success = await _patchEngine.injectSwitchCase(
            'PrimeCareForm.$formName',
            'ref.watch(genericDashboardAdapterProvider(form))',
            filePath: targetPath,
            variableName: 'primecareFormProvider',
          );
          if (success) {
            count++;
            logs.add(
              '[RESOLVED] Cross-Subsystem: Fixed missing form provider for $formName',
            );
          }
        } else if (issue.metadata['type'] == 'missing_screen_registration') {
          final route = issue.metadata['route'] as String;
          final screenId = 'AUTOGEN_${DateTime.now().millisecondsSinceEpoch}';

          final success = await _patchEngine.injectScreenConstant(
            registryPath:
                'apps/primecare_governance/lib/core/governance/screen_registry.dart',
            className: 'ScreenRegistry',
            screenId: screenId,
            metadata: {
              'id': screenId,
              'title': "Autogenerated Screen for $route",
              'routePath': route,
              'featureName': "Autogenerated",
              'allowedRoles': ['Staff', 'Admin'],
              'lifecycleStatus': 'LifecycleStatus.backlog',
              'storyPoints': 1,
            },
          );
          if (success) {
            count++;
            logs.add(
              '[RESOLVED] Cross-Subsystem: Injected missing registry entry for $route',
            );
          }
        } else if (issue.metadata['type'] == 'structural_drift') {
          final screenId = issue.metadata['screenId'] as String;
          final missing = List<String>.from(issue.metadata['missing'] as List);

          final registryPath = _getRegistryPathForScreen(screenId);
          if (registryPath != null) {
            final success = await _patchEngine.updateRegistryMetadata(screenId, {
              'implementedComponents':
                  "[...implementedComponents, ${missing.map((c) => "'$c'").join(', ')}]",
            }, registryPath: registryPath);
            if (success) {
              count++;
              logs.add(
                '[RESOLVED] Cross-Subsystem: Fixed structural drift (added $missing) for $screenId',
              );
            }
          }
        }
      }
    }
    return count;
  }

  String? _getRegistryPathForScreen(String screenId) {
    if (screenId.contains('clinical')) {
      return 'apps/primecare_governance/lib/core/governance/registries/clinical_registry.dart';
    }
    if (screenId.contains('corporate') || screenId.contains('finance')) {
      return 'apps/primecare_governance/lib/core/governance/registries/corporate_registry.dart';
    }
    return 'apps/primecare_governance/lib/core/governance/registries/operational_registry.dart';
  }
}

final governanceRemediationEngineProvider = Provider(
  (ref) => GovernanceRemediationEngine(ref, projectRoot: '../../'),
);
