import 'package:flutter/material.dart';
import '../../../../components/page_template.dart';
import '../../../../components/clinical_glass.dart';

class CooStaffingEfficiencyScreen extends StatelessWidget {
  const CooStaffingEfficiencyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return PageTemplate(
      title: 'Staffing Efficiency',
      subtitle: 'Correlate clinical payroll models against revenue generated by physical plant.',
      kpiCards: const [
        KPIConfig(label: 'Revenue/Head', value: '\$14.2k', trend: '+2.1%', color: Colors.green),
        KPIConfig(label: 'OT Dependency', value: '11%', trend: 'Alert', color: Colors.orange),
        KPIConfig(label: 'Labor Cost', value: '62%', trend: 'of OpEx', color: Colors.blue),
      ],
      sections: [
        ClinicalGlass(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('Payroll vs Yield', style: Theme.of(context).textTheme.titleLarge),
              const SizedBox(height: 16),
              const Text('Scatter plot visualizing the relationship between staffing density and location profitability...'),
            ],
          ),
        ),
      ],
    );
  }
}
