import 'package:flutter/material.dart';
import '../../core/colors.dart';

import 'package:google_fonts/google_fonts.dart';
import 'package:primecare_ui/primecare_ui.dart';

/// Phase 75: General Manager Supply-Chain Forecast Screen
/// This powerful executive radar pulls data generated by the `predictive_forecaster.ts`
/// Cloudflare Cron job. It shows exactly where the company will fail next week
/// unless the automated pre-recruitment SMS solves the deficit.
class SupplyChainForecastScreen extends StatelessWidget {
  const SupplyChainForecastScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: PrimeCareColors.radarDark, // Deep radar dark
      appBar: AppBar(
        title: Text('SUPPLY CHAIN MATRIX', style: GoogleFonts.firaCode(fontWeight: FontWeight.bold, letterSpacing: 2)),
        backgroundColor: Colors.transparent,
        elevation: 0,
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Master KPI Heads-Up
            Row(
              children: [
                Expanded(child: _buildMetricCard('Predicted Demand (7 Days)', '400 Hrs', Colors.orangeAccent)),
                const SizedBox(width: 16),
                Expanded(child: _buildMetricCard('Latent Supply Available', '320 Hrs', Colors.blueAccent)),
                const SizedBox(width: 16),
                Expanded(child: _buildMetricCard('Global Risk Status', 'CRITICAL', Colors.redAccent)),
              ],
            ),
            const SizedBox(height: 32),
            
            Text('GEOGRAPHICAL DEFICIT RADAR', style: GoogleFonts.outfit(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold)),
            const SizedBox(height: 16),
            
            _buildDeficitRow('Etobicoke Sub-Franchise', 400, 320, isWarning: true),
            const SizedBox(height: 12),
            _buildDeficitRow('Downtown Sub-Franchise', 120, 200, isWarning: false),
            const SizedBox(height: 12),
            _buildDeficitRow('North York Sub-Franchise', 250, 250, isWarning: false),

            const SizedBox(height: 48),

            // AI Action Log
            Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: PrimeCareColors.slate800,
                borderRadius: BorderRadius.circular(16),
                border: Border.all(color: Colors.white10),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      const Icon(Icons.bolt, color: Colors.yellowAccent),
                      const SizedBox(width: 12),
                      Text('TELEMETRY ACTIONS LOG', style: GoogleFonts.firaCode(color: Colors.white, fontWeight: FontWeight.bold)),
                    ],
                  ),
                  const Divider(color: Colors.white24, height: 32),
                  _buildLogEntry('02:00 AM', 'Etobicoke Deficit detected. Demand = 400. Supply = 320.'),
                  _buildLogEntry('02:01 AM', 'Executing Pre-Recruitment sequence (TrustScore +15 Bounty).'),
                  _buildLogEntry('02:05 AM', 'SMS Lifeline dispatched to 14 latent Field Workers.'),
                  _buildLogEntry('02:40 AM', '2 Field Workers accepted. Deficit reduced to 56 Hours.'),
                ],
              ),
            )
          ],
        ),
      ),
    );
  }

  Widget _buildMetricCard(String title, String value, Color accentColor) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: PrimeCareColors.slate800,
        borderRadius: BorderRadius.circular(16),
        border: Border(bottom: BorderSide(color: accentColor, width: 4)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: GoogleFonts.inter(color: Colors.grey[400], fontSize: 13, fontWeight: FontWeight.w600)),
          const SizedBox(height: 8),
          Text(value, style: GoogleFonts.outfit(color: Colors.white, fontSize: 28, fontWeight: FontWeight.bold)),
        ],
      ),
    );
  }

  Widget _buildDeficitRow(String zone, int demand, int supply, {required bool isWarning}) {
    double fillRatio = (supply / demand).clamp(0.0, 1.0);
    int percent = (fillRatio * 100).toInt();

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: isWarning ? Colors.redAccent.withAlpha(20) : Colors.blueAccent.withAlpha(20),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: isWarning ? Colors.redAccent.withAlpha(50) : Colors.blueAccent.withAlpha(50)),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(zone, style: GoogleFonts.inter(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16)),
              const SizedBox(height: 4),
              Text(isWarning ? 'DEFICIT DETECTED' : 'SUPPLY OPTIMAL', style: GoogleFonts.firaCode(color: isWarning ? Colors.redAccent : Colors.blueAccent, fontSize: 12)),
            ],
          ),
          Row(
            children: [
              Text('$percent% Fill Rate', style: GoogleFonts.outfit(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold)),
              const SizedBox(width: 16),
              CircularProgressIndicator(value: fillRatio, backgroundColor: Colors.white24, color: isWarning ? Colors.redAccent : Colors.blueAccent),
            ],
          )
        ],
      ),
    );
  }

  Widget _buildLogEntry(String time, String message) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('[$time]', style: GoogleFonts.firaCode(color: Colors.grey[500], fontSize: 12)),
          const SizedBox(width: 12),
          Expanded(child: Text(message, style: GoogleFonts.inter(color: Colors.white, fontSize: 14))),
        ],
      ),
    );
  }
}
