// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by .agents/governance/manifest_generator.dart
// Source: .agents/governance/page_inventory.yaml

import 'package:lucide_icons/lucide_icons.dart';
import 'package:primecare_core/flutter_core.dart';

class NavigationRegistry {
  static final Map<String, List<PrimeCareNavigationItem>> _roleMenus = {
    'Admin': [
      const PrimeCareNavigationItem(
        label: 'System Dashboard',
        icon: LucideIcons.layoutDashboard,
        route: CorporateRoutes.ceoDashboard,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Compliance Hub',
        icon: LucideIcons.shieldCheck,
        route: CorporateRoutes.complianceManagerDashboard,
        section: 'Management',
      ),
      const PrimeCareNavigationItem(
        label: 'Global Settings',
        icon: LucideIcons.settings2,
        route: CommonRoutes.globalSettings,
        section: 'Management',
      ),
      const PrimeCareNavigationItem(
        label: 'User Management',
        icon: LucideIcons.users,
        route: CommonRoutes.userManagement,
        section: 'Management',
      ),
    ],
    'CEO': [
      const PrimeCareNavigationItem(
        label: 'System Dashboard',
        icon: LucideIcons.layoutDashboard,
        route: CorporateRoutes.ceoDashboard,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'User Management',
        icon: LucideIcons.users,
        route: CommonRoutes.userManagement,
        section: 'Management',
      ),
      const PrimeCareNavigationItem(
        label: 'Enterprise Overview',
        icon: LucideIcons.globe,
        route: CorporateRoutes.ceoEnterpriseOverview,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Strategic KPIs',
        icon: LucideIcons.barChart3,
        route: CorporateRoutes.ceoStrategicKpis,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Growth Pipeline',
        icon: LucideIcons.trendingUp,
        route: CorporateRoutes.ceoGrowthPipeline,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Region Performance',
        icon: LucideIcons.map,
        route: CorporateRoutes.ceoRegionPerformance,
        section: 'Strategic',
      ),
      const PrimeCareNavigationItem(
        label: 'Leadership Reports',
        icon: LucideIcons.fileText,
        route: CorporateRoutes.ceoLeadershipReports,
        section: 'Strategic',
      ),
    ],
    'Compliance Manager': [
      const PrimeCareNavigationItem(
        label: 'Compliance Hub',
        icon: LucideIcons.shieldCheck,
        route: CorporateRoutes.complianceManagerDashboard,
        section: 'Management',
      ),
      const PrimeCareNavigationItem(
        label: 'Cases',
        icon: LucideIcons.briefcase,
        route: CorporateRoutes.complianceManagerComplianceCases,
        section: 'Workflows',
      ),
      const PrimeCareNavigationItem(
        label: 'Policy Manager',
        icon: LucideIcons.bookOpen,
        route: CorporateRoutes.complianceManagerPolicies,
        section: 'Workflows',
      ),
      const PrimeCareNavigationItem(
        label: 'Audits',
        icon: LucideIcons.listChecks,
        route: CorporateRoutes.complianceManagerAudits,
        section: 'Workflows',
      ),
      const PrimeCareNavigationItem(
        label: 'Risk Register',
        icon: LucideIcons.flame,
        route: CorporateRoutes.complianceManagerRiskRegister,
        section: 'Workflows',
      ),
    ],
    'CFO': [
      const PrimeCareNavigationItem(
        label: 'CFO Dashboard',
        icon: LucideIcons.layoutDashboard,
        route: CorporateRoutes.cfoDashboard,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Financial Overview',
        icon: LucideIcons.wallet,
        route: CorporateRoutes.cfoFinancialOverview,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Revenue Tracker',
        icon: LucideIcons.dollarSign,
        route: CorporateRoutes.cfoRevenue,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Profitability',
        icon: LucideIcons.pieChart,
        route: CorporateRoutes.cfoProfitability,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Tax & Remittance',
        icon: LucideIcons.landmark,
        route: CorporateRoutes.cfoTaxAndRemittance,
        section: 'Main',
      ),
    ],
    'COO': [
      const PrimeCareNavigationItem(
        label: 'COO Dashboard',
        icon: LucideIcons.layoutDashboard,
        route: CorporateRoutes.cooDashboard,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Operations Board',
        icon: LucideIcons.activity,
        route: CorporateRoutes.cooOperationsOverview,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Branch Operations',
        icon: LucideIcons.gitMerge,
        route: CorporateRoutes.cooBranchOperations,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Scheduling Health',
        icon: LucideIcons.calendarCheck,
        route: CorporateRoutes.cooSchedulingHealth,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Incident Reviews',
        icon: LucideIcons.alertTriangle,
        route: CorporateRoutes.cooIssueEscalations,
        section: 'Main',
      ),
    ],
    'CTO': [
      const PrimeCareNavigationItem(
        label: 'CTO Dashboard',
        icon: LucideIcons.layoutDashboard,
        route: CorporateRoutes.ctoDashboard,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'System Health',
        icon: LucideIcons.hardDrive,
        route: CorporateRoutes.ctoSystemHealth,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Platform Usage',
        icon: LucideIcons.fingerprint,
        route: CorporateRoutes.ctoPlatformUsage,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'API Monitoring',
        icon: LucideIcons.cpu,
        route: CorporateRoutes.ctoApiMonitoring,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Audit Logs',
        icon: LucideIcons.scrollText,
        route: CorporateRoutes.ctoAuditLogs,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Verification Hub',
        icon: LucideIcons.database,
        route: CorporateRoutes.ctoVerificationHub,
        section: 'Main',
      ),
    ],
    'Corporate Developer': [
      const PrimeCareNavigationItem(
        label: 'System Health',
        icon: LucideIcons.hardDrive,
        route: CorporateRoutes.ctoSystemHealth,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Platform Usage',
        icon: LucideIcons.fingerprint,
        route: CorporateRoutes.ctoPlatformUsage,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'API Monitoring',
        icon: LucideIcons.cpu,
        route: CorporateRoutes.ctoApiMonitoring,
        section: 'Main',
      ),
    ],
    'Training Director': [
      const PrimeCareNavigationItem(
        label: 'Curriculum Hub',
        icon: LucideIcons.graduationCap,
        route: CorporateRoutes.trainingDirectorDashboard,
        section: 'Strategic',
      ),
      const PrimeCareNavigationItem(
        label: 'Skill Matrix',
        icon: LucideIcons.award,
        route: CorporateRoutes.trainingDirectorAnalytics,
        section: 'Workflows',
      ),
    ],
    'Regional Manager': [
      const PrimeCareNavigationItem(
        label: 'Region Dashboard',
        icon: LucideIcons.map,
        route: FranchiseRoutes.regionalManagerDashboard,
        section: 'Operations',
      ),
      const PrimeCareNavigationItem(
        label: 'Branch Comparison',
        icon: LucideIcons.split,
        route: FranchiseRoutes.regionalManagerBranchComparison,
        section: 'Operations',
      ),
    ],
    'Finance Director': [
      const PrimeCareNavigationItem(
        label: 'Ledger Command',
        icon: LucideIcons.landmark,
        route: CorporateRoutes.financeDirectorDashboard,
        section: 'Finance',
      ),
      const PrimeCareNavigationItem(
        label: 'Cash Flow',
        icon: LucideIcons.arrowDownUp,
        route: CorporateRoutes.financeDirectorCashFlow,
        section: 'Finance',
      ),
    ],
    'Intake Coordinator': [
      const PrimeCareNavigationItem(
        label: 'Intake Pipeline',
        icon: LucideIcons.userPlus,
        route: ClinicalRoutes.intakeCoordinatorDashboard,
        section: 'Clinical',
      ),
      const PrimeCareNavigationItem(
        label: 'Referrals',
        icon: LucideIcons.fileInput,
        route: ClinicalRoutes.intakeCoordinatorReferrals,
        section: 'Workflows',
      ),
      const PrimeCareNavigationItem(
        label: 'Pending assessments',
        icon: LucideIcons.clipboardList,
        route: ClinicalRoutes.intakeCoordinatorAssessments,
        section: 'Workflows',
      ),
    ],
    'Billing Admin': [
      const PrimeCareNavigationItem(
        label: 'Billing Console',
        icon: LucideIcons.receipt,
        route: FranchiseRoutes.billingAdminDashboard,
        section: 'Finance',
      ),
      const PrimeCareNavigationItem(
        label: 'Invoices',
        icon: LucideIcons.fileText,
        route: FranchiseRoutes.billingAdminInvoices,
        section: 'Finance',
      ),
    ],
    'Marketing Manager': [
      const PrimeCareNavigationItem(
        label: 'Marketing Hub',
        icon: LucideIcons.megaphone,
        route: FranchiseRoutes.marketingManagerDashboard,
        section: 'Growth',
      ),
      const PrimeCareNavigationItem(
        label: 'Campaign Analytics',
        icon: LucideIcons.lineChart,
        route: FranchiseRoutes.marketingManagerCampaigns,
        section: 'Growth',
      ),
    ],
    'Franchise Owner': [
      const PrimeCareNavigationItem(
        label: 'Business Overview',
        icon: LucideIcons.building2,
        route: FranchiseRoutes.franchiseOwnerDashboard,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Financial Performance',
        icon: LucideIcons.barChart,
        route: FranchiseRoutes.franchiseOwnerFinancialSnapshot,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Compliance Status',
        icon: LucideIcons.shieldCheck,
        route: FranchiseRoutes.franchiseOwnerCompliance,
        section: 'Main',
      ),
    ],
    'PSW': [
      const PrimeCareNavigationItem(
        label: 'Clinical Dashboard',
        icon: LucideIcons.stethoscope,
        route: CommonRoutes.clinicDashboard,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Shift Tracker',
        icon: LucideIcons.clock,
        route: CommonRoutes.clinicMyShifts,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Messages',
        icon: LucideIcons.messageSquare,
        route: CommonRoutes.messagingHub,
        section: 'Main',
      ),
    ],
    'Client': [
      const PrimeCareNavigationItem(
        label: 'Family Home',
        icon: LucideIcons.home,
        route: ClientRoutes.clientDashboard,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Care Plan',
        icon: LucideIcons.heartPulse,
        route: ClientRoutes.clientTreatmentHistory,
        section: 'Main',
      ),
      const PrimeCareNavigationItem(
        label: 'Billing',
        icon: LucideIcons.receipt,
        route: ClientRoutes.clientPayments,
        section: 'Main',
      ),
    ],
  };

  static List<PrimeCareNavigationItem> getMenuForRole(String role) {
    // 1. Super Admin / Admin master directory fallback
    final checkRole = role.toLowerCase();
    if (checkRole == 'super admin' ||
        checkRole == 'admin' ||
        checkRole == 'it admin') {
      final Map<String, PrimeCareNavigationItem> allItems = {};
      _roleMenus.forEach((roleName, menuList) {
        for (final item in menuList) {
          if (!allItems.containsKey(item.route)) {
            allItems[item.route] = PrimeCareNavigationItem(
              label: item.label,
              icon: item.icon,
              route: item.route,
              section: item.section ?? 'Master Directory',
              activeIcon: item.activeIcon,
            );
          }
        }
      });
      return allItems.values.toList();
    }

    // 2. Try exact match first
    if (_roleMenus.containsKey(role)) {
      return _roleMenus[role]!;
    }

    // 3. Try case-insensitive exact match
    final upperRole = role.toUpperCase();
    for (var key in _roleMenus.keys) {
      if (key.toUpperCase() == upperRole) {
        return _roleMenus[key]!;
      }
    }

    // 4. Fallback to Title Case normalization
    final normalizedRole = role
        .split(' ')
        .map(
          (word) => word.isEmpty
              ? ''
              : '${word[0].toUpperCase()}${word.substring(1).toLowerCase()}',
        )
        .join(' ');

    return _roleMenus[normalizedRole] ?? _roleMenus['Admin'] ?? [];
  }
}
