import 'package:flutter/material.dart';

class SidebarItemData {
  final String label;
  final IconData icon;
  final String path;

  const SidebarItemData({
    required this.label,
    required this.icon,
    this.path = '',
  });
}

class SidebarConfig {
  static final Map<String, List<SidebarItemData>> roleMenus = {
    'CEO': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Enterprise Overview', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Franchise Overview', icon: Icons.business_center_outlined),
      SidebarItemData(label: 'Region Performance', icon: Icons.description_outlined),
      SidebarItemData(label: 'Revenue Summary', icon: Icons.attach_money),
      SidebarItemData(label: 'Strategic KPIs', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Growth Pipeline', icon: Icons.business_center_outlined),
      SidebarItemData(label: 'Leadership Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Alerts & Risks', icon: Icons.notifications_outlined),
      SidebarItemData(label: 'Organization Map', icon: Icons.map_outlined),
      SidebarItemData(label: 'Approvals', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Messages', icon: Icons.chat_bubble_outline),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'COO': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Operations Overview', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Branch Operations', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Staffing Efficiency', icon: Icons.people_alt),
      SidebarItemData(label: 'Scheduling Health', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Service Delivery', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Issue Escalations', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Compliance View', icon: Icons.verified_user_outlined),
      SidebarItemData(label: 'Workflow Performance', icon: Icons.description_outlined),
      SidebarItemData(label: 'Branch Comparison', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'CFO': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Financial Overview', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Revenue', icon: Icons.attach_money),
      SidebarItemData(label: 'Expenses', icon: Icons.attach_money),
      SidebarItemData(label: 'Franchise Financials', icon: Icons.business_center_outlined),
      SidebarItemData(label: 'Payroll', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Accounts Receivable', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Accounts Payable', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Invoices', icon: Icons.attach_money),
      SidebarItemData(label: 'Profitability', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Tax & Remittance', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'CTO': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'System Health', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Platform Usage', icon: Icons.description_outlined),
      SidebarItemData(label: 'Feature Adoption', icon: Icons.circle_outlined),
      SidebarItemData(label: 'API Monitoring', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Integrations', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Audit Logs', icon: Icons.verified_user_outlined),
      SidebarItemData(label: 'Access Control', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Release Management', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Issue Tracking', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Infrastructure', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Compliance Manager': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Compliance Cases', icon: Icons.verified_user_outlined),
      SidebarItemData(label: 'Policies', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Audits', icon: Icons.verified_user_outlined),
      SidebarItemData(label: 'Incident Review', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Credential Tracking', icon: Icons.verified_user_outlined),
      SidebarItemData(label: 'Document Expiry', icon: Icons.description_outlined),
      SidebarItemData(label: 'Risk Register', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Corrective Actions', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Training Compliance', icon: Icons.verified_user_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Head of Business Development': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Lead Pipeline', icon: Icons.business_center_outlined),
      SidebarItemData(label: 'Franchise Pipeline', icon: Icons.business_center_outlined),
      SidebarItemData(label: 'Territory Map', icon: Icons.map_outlined),
      SidebarItemData(label: 'Partnerships', icon: Icons.handshake_outlined),
      SidebarItemData(label: 'Opportunities', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Sales Performance', icon: Icons.description_outlined),
      SidebarItemData(label: 'Expansion Forecast', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Head of Marketing': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Campaigns', icon: Icons.campaign_outlined),
      SidebarItemData(label: 'Leads', icon: Icons.business_center_outlined),
      SidebarItemData(label: 'Funnel Analytics', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Brand Assets', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Regional Campaigns', icon: Icons.map_outlined),
      SidebarItemData(label: 'Content Approval', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Performance Reports', icon: Icons.description_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Training Director': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Training Programs', icon: Icons.school_outlined),
      SidebarItemData(label: 'Staff Training Matrix', icon: Icons.people_alt),
      SidebarItemData(label: 'Compliance Training', icon: Icons.verified_user_outlined),
      SidebarItemData(label: 'Course Library', icon: Icons.school_outlined),
      SidebarItemData(label: 'Assessments', icon: Icons.medical_services_outlined),
      SidebarItemData(label: 'Certifications', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Trainer Assignments', icon: Icons.task_alt),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Regional BDM': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Leads', icon: Icons.business_center_outlined),
      SidebarItemData(label: 'Franchise Pipeline', icon: Icons.business_center_outlined),
      SidebarItemData(label: 'Territory Growth', icon: Icons.map_outlined),
      SidebarItemData(label: 'Meetings', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Deal Tracker', icon: Icons.business_center_outlined),
      SidebarItemData(label: 'Partners', icon: Icons.handshake_outlined),
      SidebarItemData(label: 'Competitor Notes', icon: Icons.medical_services_outlined),
      SidebarItemData(label: 'Tasks', icon: Icons.task_alt),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Franchise Sales Manager': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Leads', icon: Icons.business_center_outlined),
      SidebarItemData(label: 'Prospects', icon: Icons.business_center_outlined),
      SidebarItemData(label: 'Discovery Calls', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Proposals', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Sales Pipeline', icon: Icons.business_center_outlined),
      SidebarItemData(label: 'Contracts', icon: Icons.description_outlined),
      SidebarItemData(label: 'Follow-ups', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Partnership Manager': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Partners', icon: Icons.handshake_outlined),
      SidebarItemData(label: 'Outreach', icon: Icons.handshake_outlined),
      SidebarItemData(label: 'Active Deals', icon: Icons.business_center_outlined),
      SidebarItemData(label: 'Proposals', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Documents', icon: Icons.description_outlined),
      SidebarItemData(label: 'Renewals', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Territory Expansion Manager': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Territory Map', icon: Icons.map_outlined),
      SidebarItemData(label: 'Market Research', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Demographics', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Open Territories', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Expansion Plans', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Site Selection', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Forecast', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Franchise Owner': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Branch Overview', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Financial Snapshot', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Staff', icon: Icons.people_alt),
      SidebarItemData(label: 'Appointments', icon: Icons.calendar_today),
      SidebarItemData(label: 'Clients', icon: Icons.personal_injury),
      SidebarItemData(label: 'Compliance', icon: Icons.verified_user_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Hiring', icon: Icons.people_alt),
      SidebarItemData(label: 'Messages', icon: Icons.chat_bubble_outline),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Operations Manager': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Daily Operations', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Schedule', icon: Icons.calendar_today),
      SidebarItemData(label: 'Shifts', icon: Icons.calendar_today),
      SidebarItemData(label: 'Issues', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Service Quality', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Staff Coordination', icon: Icons.people_alt),
      SidebarItemData(label: 'Attendance', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Scheduler / Coordinator': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Appointment Calendar', icon: Icons.calendar_today),
      SidebarItemData(label: 'Shift Calendar', icon: Icons.calendar_today),
      SidebarItemData(label: 'Provider Availability', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Booking Requests', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Open Shifts', icon: Icons.calendar_today),
      SidebarItemData(label: 'Assignments', icon: Icons.task_alt),
      SidebarItemData(label: 'Conflicts', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Admin': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Invoices', icon: Icons.attach_money),
      SidebarItemData(label: 'Payments', icon: Icons.attach_money),
      SidebarItemData(label: 'Claims', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Reconciliation', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Outstanding Balances', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Refunds', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Documents', icon: Icons.description_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'HR / Hiring': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Applicants', icon: Icons.people_alt),
      SidebarItemData(label: 'Interviews', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Offers', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Onboarding', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Staff Documents', icon: Icons.description_outlined),
      SidebarItemData(label: 'Credentials', icon: Icons.verified_user_outlined),
      SidebarItemData(label: 'Training Status', icon: Icons.school_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'RN': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Today’s Schedule', icon: Icons.calendar_today),
      SidebarItemData(label: 'Assigned Clients', icon: Icons.personal_injury),
      SidebarItemData(label: 'Nursing Notes', icon: Icons.medical_services_outlined),
      SidebarItemData(label: 'Care Plans', icon: Icons.medical_services_outlined),
      SidebarItemData(label: 'Medication Notes', icon: Icons.medical_services_outlined),
      SidebarItemData(label: 'Vitals', icon: Icons.medical_services_outlined),
      SidebarItemData(label: 'Incident Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Progress Updates', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Client History', icon: Icons.personal_injury),
      SidebarItemData(label: 'Documents', icon: Icons.description_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'RPN': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Today’s Schedule', icon: Icons.calendar_today),
      SidebarItemData(label: 'Assigned Clients', icon: Icons.personal_injury),
      SidebarItemData(label: 'Nursing Notes', icon: Icons.medical_services_outlined),
      SidebarItemData(label: 'Care Updates', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Vitals', icon: Icons.medical_services_outlined),
      SidebarItemData(label: 'Medication Support', icon: Icons.help_outline),
      SidebarItemData(label: 'Client History', icon: Icons.personal_injury),
      SidebarItemData(label: 'Incident Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'RMT': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Today’s Schedule', icon: Icons.calendar_today),
      SidebarItemData(label: 'Clients', icon: Icons.personal_injury),
      SidebarItemData(label: 'Assessment', icon: Icons.medical_services_outlined),
      SidebarItemData(label: 'SOAP Notes', icon: Icons.medical_services_outlined),
      SidebarItemData(label: 'Treatment Plans', icon: Icons.medical_services_outlined),
      SidebarItemData(label: 'Homecare', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Session History', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Body Chart', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Intake Forms', icon: Icons.description_outlined),
      SidebarItemData(label: 'Invoices', icon: Icons.attach_money),
      SidebarItemData(label: 'Documents', icon: Icons.description_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'PSW': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Today’s Shifts', icon: Icons.calendar_today),
      SidebarItemData(label: 'Assigned Clients', icon: Icons.personal_injury),
      SidebarItemData(label: 'Care Tasks', icon: Icons.task_alt),
      SidebarItemData(label: 'ADL Tracking', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Daily Logs', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Check In / Out', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Client Updates', icon: Icons.personal_injury),
      SidebarItemData(label: 'Incident Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Completed Visits', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Documents', icon: Icons.description_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Customer Support': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Tickets', icon: Icons.help_outline),
      SidebarItemData(label: 'Chat', icon: Icons.chat_bubble_outline),
      SidebarItemData(label: 'Escalations', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Issue Categories', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Templates', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Intake Coordinator': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'New Intakes', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Intake Forms', icon: Icons.description_outlined),
      SidebarItemData(label: 'Eligibility', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Documents', icon: Icons.description_outlined),
      SidebarItemData(label: 'Scheduling', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Client Assignment', icon: Icons.task_alt),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Quality Assurance': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Audits', icon: Icons.verified_user_outlined),
      SidebarItemData(label: 'Reviews', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Complaints', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Corrective Actions', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Scorecards', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Compliance Checks', icon: Icons.verified_user_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Training Coordinator': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Training Schedule', icon: Icons.calendar_today),
      SidebarItemData(label: 'Courses', icon: Icons.school_outlined),
      SidebarItemData(label: 'Progress', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Workshops', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Attendance', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Materials', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Certifications', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Local Marketing Manager': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Campaigns', icon: Icons.campaign_outlined),
      SidebarItemData(label: 'Leads', icon: Icons.business_center_outlined),
      SidebarItemData(label: 'Content Calendar', icon: Icons.calendar_today),
      SidebarItemData(label: 'Events', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Budget', icon: Icons.attach_money),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Assets', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Community Outreach': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Programs', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Events', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Partnerships', icon: Icons.handshake_outlined),
      SidebarItemData(label: 'Volunteers', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Contacts', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Follow-ups', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Territory Sales Manager': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Leads', icon: Icons.business_center_outlined),
      SidebarItemData(label: 'Pipeline', icon: Icons.business_center_outlined),
      SidebarItemData(label: 'Field Activity', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Conversions', icon: Icons.campaign_outlined),
      SidebarItemData(label: 'Area Performance', icon: Icons.description_outlined),
      SidebarItemData(label: 'Competitors', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Reports', icon: Icons.analytics_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Client': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Book Appointment', icon: Icons.circle_outlined),
      SidebarItemData(label: 'My Appointments', icon: Icons.calendar_today),
      SidebarItemData(label: 'Care Team', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Treatment History', icon: Icons.medical_services_outlined),
      SidebarItemData(label: 'Documents', icon: Icons.description_outlined),
      SidebarItemData(label: 'Payments', icon: Icons.attach_money),
      SidebarItemData(label: 'Messages', icon: Icons.chat_bubble_outline),
      SidebarItemData(label: 'Profile', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
    'Family Member': [
      SidebarItemData(label: 'Dashboard', icon: Icons.dashboard),
      SidebarItemData(label: 'Loved One Schedule', icon: Icons.calendar_today),
      SidebarItemData(label: 'Care Updates', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Documents', icon: Icons.description_outlined),
      SidebarItemData(label: 'Billing', icon: Icons.attach_money),
      SidebarItemData(label: 'Messages', icon: Icons.chat_bubble_outline),
      SidebarItemData(label: 'Emergency Contacts', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Notifications', icon: Icons.notifications_outlined),
      SidebarItemData(label: 'Profile', icon: Icons.circle_outlined),
      SidebarItemData(label: 'Settings', icon: Icons.settings_outlined),
    ],
  };
  
  static List<SidebarItemData> getMenuForRole(String role) {
    if (role.isEmpty) return roleMenus['PSW'] ?? []; // Default fallback
    
    // Exact mapping check
    for (String key in roleMenus.keys) {
      if (role.toLowerCase().contains(key.toLowerCase())) {
        return roleMenus[key]!;
      }
    }
    
    // Fuzzy matching fallbacks based on tokens
    if (role.toLowerCase().contains('rn')) return roleMenus['RN']!;
    if (role.toLowerCase().contains('rmt')) return roleMenus['RMT']!;
    if (role.toLowerCase().contains('physio')) return roleMenus['Physio'] ?? roleMenus['RMT']!;
    
    return roleMenus['PSW']!; 
  }
}
