name: Deploy API - primecare-auth-api

on:
  push:
    branches: [main]
    paths:
      - 'services/auth_api/**'
      - 'packages/database_client/**'
      - '.github/workflows/deploy-api-auth.yml'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-api.yml
    with:
      service_dir: services/auth_api
      service_name: primecare-auth-api
      image_name: auth-api
    secrets: inherit
