name: Deploy API - primecare-provider-api

on:
  push:
    branches: [main]
    paths:
      - 'services/provider_api/**'
      - 'packages/database_client/**'
      - '.github/workflows/deploy-api-provider.yml'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-api.yml
    with:
      service_dir: services/provider_api
      service_name: primecare-provider-api
      image_name: provider-api
    secrets: inherit
