name: Deploy Web - primecare-business-development

on:
  push:
    branches: [main]
    paths:
      - 'apps/primecare_business_development/**'
      - 'packages/flutter_core/**'
      - 'packages/primecare_ui/**'
      - '.github/workflows/deploy-web-business-development.yml'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-web.yml
    with:
      app: primecare_business_development
      project: primecare-business-development
    secrets: inherit
